### ISSUE TITLE
Empty value in Scenario Outline

### ISSUE THREAD

**Issue by majemo01** [behave/behave#1002]
Scenario outline and scenario not accepting "" (empty strings) in the table or parameters. Instead of writing multiple step definition there is any way behave will accepting empty values?

Example:

![image](https://user-images.githubusercontent.com/97751058/154059550-fac5158c-0461-4bd6-a127-0b35497aa566.png)

**Comment by jenisys** [comment]
INSUFFICIENT INFORMATION:
Provide a concrete example what you mean.

**Comment by majemo01** [comment]
@jenisys  updated my question

**Comment by jenisys** [comment]
I have a look.
BUT: In general that should not be a problem (what you are trying to do).

NOTE on TERMINOLOGY:
You are trying to pass an EMPTY-STRING, not a NULL value.

**Comment by jenisys** [comment]
Just curious: 
* Why do you think, it is not working ?
* What syndrome do you experience ?

**Comment by majemo01** [comment]
> I have a look. BUT: In general that should not be a problem (what you are trying to do).
> 
> NOTE on TERMINOLOGY: You are trying to pass an EMPTY-STRING, not a NULL value.

Yes empty string in Scenario and NULL in Scenario Outline

Example:

![image](https://user-images.githubusercontent.com/97751058/154060704-e4fb0bf0-2591-4093-896f-743a6be3597b.png)

**Comment by majemo01** [comment]
> * syndrome

Getting an error as undefined step

![image](https://user-images.githubusercontent.com/97751058/154060968-73ffb6cb-2a12-4d75-8fe1-a56b7e7ff819.png)

**Comment by jenisys** [comment]
Did you:

* CASE 1: Run `behave` against for feature file (and steps) or 
* CASE 2: Did you use the IDE that uses `behave` ?

 I assume you have used CASE 2, but you should verify the problem with CASE 1.

QUESTIONS:
* What are you using as IDE / IDE Test Runner / Feature Development ? (it looks like Jetbrains PyCharm to me)

**Comment by jenisys** [comment]
Ok, I can replicate your problem w/ CASE 1.
Weird, completely unexpected to me.
I look into it.

**WORKAROUND FOR YOU** (for now):
Add another step for the `EMPTY-STRING` case.

```python
# -- FILE: features/steps/my_steps.py
# AS BEFORE (see above):
...

@step('Passing parameter ""')
def step_define_parameter_as_empty_string(context):
    print("EMPTY_STRING")
```

**Comment by jenisys** [comment]
To pass string-value(s) and empty-strings, you need to:

* define an own type for the step-parameter (that matches EMPTY-STRING, too)
* use another step-definition for the EMPTY-STRING case (as suggested above) if want to use a type-less step param

EXAMPLE:

```python
# -- FILE: features/steps/my_steps.py
from behave import register_type

@parse.with_pattern(r".*")
def parse_any_text(text):
    return text

@parse.with_pattern(r'[^"]*')
def parse_unquoted_or_empty_text(text):
    return text

register_type(AnyText=parse_any_text)
register_type(Unquoted=parse_unquoted_or_empty_text)

# -- VARIANT 1:
@step('Passing parameter "{param:AnyText}"')
def step_use_parameter(context, param):
    print(param)

# -- VARIANT 2 (ALTERNATIVE: either/or):
@step('Passing parameter "{param:Unquoted}"')
def step_use_parameter(context, param):
    print(param)
```

HINT:
If you want to use `AnyText`, you should put double-quotes around your param.
Otherwise, greedy regular-expression match more than you expect if similar step definitions with common prefix are used.
