### ISSUE TITLE
Capturing file descriptor writes like pytest

### ISSUE THREAD

**Issue by turbo1912** [behave/behave#1010]
Pytest has a capturing mode called `fd` defined as; "fd (file descriptor) level capturing (default): All writes going to the operating system file descriptors 1 and 2 will be captured." 

https://docs.pytest.org/en/6.2.x/capture.html#setting-capturing-methods-or-disabling-capturing

Is there an equivalent of this in behave? Looks like `fd` mode is more than just capturing `stdout`.

**Comment by jenisys** [comment]
SHORT ANSWER: Yes

`behave` captures stdout/stderr unless you disable it on command-line (or: config-file).
The captured output from stdout / stderr / logging is shown if a step in a Scenario fails.

**Comment by turbo1912** [comment]
I am sorry maybe I should have been more clear, pytest (and perhaps other testing frameworks) have 2 capture modes:

```
fd (file descriptor) level capturing (default): All writes going to the operating system file descriptors 1 and 2 will be captured.

sys level capturing: Only writes to Python files sys.stdout and sys.stderr will be captured. No capturing of writes to filedescriptors is performed.
``` 
(https://docs.pytest.org/en/6.2.x/capture.html#setting-capturing-methods-or-disabling-capturing)

I have played around with some examples and looks like behave's stdout/stderr capturing is equivalent to what is mentioned as `sys level capturing` not `fd (file descriptor) level capturing`. For example behave doesn't capture writes from a subprocess (or I wasn't able to make it work. )

**Comment by jenisys** [comment]
Mmh, subprocess capturing is not the responsibility ob `behave` and why should it be?!?

Make a simple, motivating example what you are trying to achieve.
