### ISSUE TITLE
[Feature]Support switch between Step Matcher Strategy in a Step Definition File

### ISSUE THREAD

**Issue by Joeylu-master** [behave/behave#1020]
As a user, I want to switch step matcher in a step definition file.  But on behave 1.2.7, can not support it.

```
# -- FILE: features/steps/step.py
from behave import given, when, then, use_step_matcher
from hamcrest import assert_that, equal_to

# ------------------------------------------------------------------------
# STEPS with Regular Expression Matcher ("re")
# ------------------------------------------------------------------------
# -- SELECT STEP MATCHER: Before using it in step definitions.
use_step_matcher("re")

@when(u'I meet with "(?P<person>Alice|Bob)"')
def step_when_I_meet(context, person):
    context.person = person

# ------------------------------------------------------------------------
# STEPS with Parse Matcher ("parse")
# ------------------------------------------------------------------------
use_step_matcher("parse")

@then(u'I have a lot of fun with "{person}"')
def step_then_I_have_fun_with(context, person):
    assert_that(person, equal_to(context.person))
```

**Comment by jenisys** [comment]
You are mistaken.
You can switch the matcher.

BUT: Behave uses the `parse` module which only supports the named parameter regex style (for placeholders).

**Comment by jenisys** [comment]
MISTAKEN:
Check the feature file above that works without any problems.

**Comment by Joeylu-master** [comment]
Sorry, I made a mistake caused by pycharm. The code does work, but pycharm fails to navigate from feature file to step implement file.
<img width="569" alt="image" src="https://user-images.githubusercontent.com/10229790/166892569-2a994c04-2549-40c7-8f49-a559f49eb4b6.png">
<img width="411" alt="image" src="https://user-images.githubusercontent.com/10229790/166892704-3b97ec67-44d7-4001-98e9-0dda506bd8e7.png">

So how to set it to navigate code as normal?

**Comment by janoskut** [comment]
You can't expect `behave` to provide IDE support for you and it's also not that easy because identifying "the step definition" depends on the matching.

I normally go with "find in files" in my IDE to locate a step definition.

**Comment by Joeylu-master** [comment]
Thank you for your quick response. I see.
