### ISSUE TITLE
Question: why is "/" not an allowed character in tag-names?

### ISSUE THREAD

**Issue by janoskut** [behave/behave#1021]
We are using the forward slash (`/`) character as a delimiter for tag names, to put some semantics in them.

Now we notice, that **only with Scenario Outlines** (not with Scenarios), the `/` character is eaten up by [`behave.model.Tag.make_name()`](https://github.com/behave/behave/blob/main/behave/model.py#L2119). Meaning that e.g. a tag `@abc/def` will be turned into `@abcdef` after parsing.

Is there a specific known reason for that? Would we have a chance with an upstream PR to add the `/`? At least running all `behave` tests of the repository after adding it doesn't break anything.

**Comment by jenisys** [comment]
Currently, tags are basically parsed as words.
This means „tags“ that contain whitespace are split-up into two tags.

A ScenarioOutline is basically a template.
Therefore, the `ScenarioOutlineBuilder`, that creates scenarios from the ScenarioOutline and rows of its example table(s), uses `Tag.make_name()` to enforce that certain conventions are met. The method describes the exact behavior:

* What characters are allowed (and preserved)
* What characters are translated
* What characters are disallowed (and removed)

One of the reason for this mechanism was self-protection when the ScenarioOutline template is rendered.
The other that it provides a mechanism to get a normalized tag from a string.

**QUESTION:** Is their a reason why you want to use `/` instead `.` ?

**Comment by janoskut** [comment]
> QUESTION: Is their a reason why you want to use / instead . ?

It's really not that we **need** to use /, but we started using it as a delimiter already in our tool, and now it would be a bit of a pain to change that. Still, not really a problem of `behave` I believe, but on our side - and we'll have to change to . or :.
