### ISSUE TITLE
Allow adding a criticality level to the steps

### ISSUE THREAD

**Issue by vishrantgupta** [behave/behave#1025]
Maybe a feature request.

Is it possible to specify the level in the step definition, for example:

```
Feature: The google.com is reachable and most of the features are working
    
    Background: The google.com is reachable
        Given The google.com search engine is working

    Scenario: Validate that most of the functionality is working
        Then Verify search is working
        @warning(fail=false)
        Then Verify the logo is visible
        Then Verify YouTube is reachable
```

In the above scenario, in case `Verify the logo is visible` step fails it should generate a warning instead of failing the entire scenario and should continue with the next step.

**Comment by jenisys** [comment]
You are trying to use some other „syntactic sugar“ where with tags where are not needed and tags are not possible.

* Steps are not a taggable statement in Gherkin
* You can easily achieve the same thing with a step or another step definition

EXAMPLE:

```Gherkin
…
Scenario:
  Then verify that search is working
  And verify that the logo is visible but do not fail   # OR: And complain if the logo is not visible
  And verify that YouTube is reachable
```

**Comment by vishrantgupta** [comment]
Thanks, @jenisys.

I am running the scenarios with `--no-capture` how would the implementation of `verify that the logo is visible but do not fail` would look like, how the warning message can be added in the report? Are you suggesting adding logging with warning message, in case that, `--no-capture` will only output to stdout/ stderr if the scenario failed?

**Comment by jenisys** [comment]
@vishrantgupta 
From my point of view, you have two possibilities (except using `—no-capture` which has its own problems):

* Use logging that is not captured. Then you can inspect the logfile afterwards.
* Use an exploratory testing approach where you inspect something and show the results (as additional info)

SEE ALSO:

* [features/exploratory_testing.with_table.feature](https://github.com/behave/behave/blob/main/features/exploratory_testing.with_table.feature)
