### ISSUE TITLE
How to use cfparse, I need help

### ISSUE THREAD

**Issue by Clared1** [behave/behave#1035]
I want to collect all the vars into a list

> tutorial.feature
```
Given nums 0 1 2 3 4 5 6 7
```

> step.py
```
def Number2(tmpint):
    return int(tmpint)


register_type(Number=Number2)


@Given("nums {lsit:Number?}")
def step_impl(context, lsit):
```

I run it, but I fail
```
ValueError: format spec 'Number?' not recognised
```

How to Solve this problem?

**Comment by bbatliner** [comment]
A couple things to get your example working:

1. Call `use_step_matcher("cfparse")` in your step implementation file before registering any steps. It is available from the core behave module: `from behave import use_step_matcher`.
2. The default list separator for cardinality fields is a comma. If you wish to change this, see the [example](https://jenisys.github.io/behave.example/datatype/cardinality_one_or_more.html?highlight=listsep) provided by jenisys. Your feature should read:
```
Given nums 0, 1, 2, 3, 4, 5, 6, 7
```
