### ISSUE TITLE
How to merge  behave  html reports  from the first and second run 

### ISSUE THREAD

**Issue by Igor-Mochalin** [behave/behave#1037]
Hi ,  I would like  to launch behave, re-run failed scenarios and provide cumulative html  report  ...  How to do that?
I have the following code 

```
behave -f html -o test-report.html
exitCode=$?
if [[ ${exitCode} -gt 0 ]]
then
    behave @rerun_failing.features -f html -o test-report-second-run.html
    exitCode=$?
fi
```
I would  like to merge  all  results from the first and  second  htmls ..  Also will be good to ignore first failed scenarios ...

**Comment by jenisys** [comment]
SOLUTION 1:
* You need to keep track of test runs data (as XML, JSON or ...)
* From the test runs data, you generate a consolidated HTML report
  ALTERNATIVE: You merge the data from multiple test runs and generate a report from that.

SOLUTION 2:
* You provide a script that merges multiple HTML reports from multiple test runs
