### ISSUE TITLE
set [--no-capture]  Invalid ！ why ? help 

### ISSUE THREAD

**Issue by xA11en** [behave/behave#1038]
i am from China. English just soso !

my feature file is :
```gherkin
# -- FILE: features/demo.feature
Feature: demo feature
    Scenario: 简单例子
      Given 安装了behave
      When 实现一个测试
      Then behave就可以用了
```

my step code is :

```python
# -- FILE: features/steps/my_steps.py
from behave import step

@step("安装了behave")
def step_impl(context):
    print("我安装了behave")
    
@step("实现一个测试")
def step_impl(context):
    print("我实现一个测试")

@step("behave就可以用了")
def step_impl(context):
    print("behave就可以用了")
```

then execute cmd :  `behave --no-capture`

except print info but no  print anything ,  [--no-capture]  Invalid!   and  modify my  step code is : 

```python
# -- FILE: features/steps/my_steps.py
from behave import step

@step("安装了behave")
def step_impl(context):
    print("我安装了behave")
    print("我安装了behave")
    
@step("实现一个测试")
def step_impl(context):
    print("我实现一个测试")
    print("我实现一个测试")

@step("behave就可以用了")
def step_impl(context):
    print("behave就可以用了")
    print("behave就可以用了")
```

add a line print , then  execute cmd : `behave --no-capture` , 

result：print info， [--no-capture]  effected   !

why ????????

**Comment by jenisys** [comment]
Sorry, I am not quite sure I understand your problem.

* I reformatted your description to make the file information more readable
* I added the file location of each file (as example) to avoid problems in the directory structure

I assume you are having a Unicode problem.
`behave` works best with `UTF-8` unicode locale.
Maybe your edit action of the steps file (and saving the file afterwards from the editor) corrected the Unicode problem.
