### ISSUE TITLE
Django integration with LiveServerTestCase: database isn't reset after each scenario / setUp method isn't called

### ISSUE THREAD

**Issue by RobertoMaurizzi** [behave/behave#1040]
A while ago I used your integration example almost as-is to convert old tests written for the mostly-abandoned `django-behave` to use 'pure' `behave` by itself and it mostly worked out of the box.

Recently I had to do the same again for another Django app and I noticed the database is NOT reset between different scenarios (as is was instead happening with `django-behave`). Searching a bit around the internet, especially on S.O. and in the sources of `behave-django`, I found some suggestions that, however, relied on calling test _instance_ methods like _pre_setup and _post_teardown that are defined in `class LiveServerTestCase` and its parent classes (especially `class TransactionTestCase`).

In your example code's `django_test_case` you define a `context.test_case` attribute as a reference to the LiveServerTestCase class, then proceed to call the class method `setupClass()`. I can't find in your code any place where you then actually instantiate the class in a `LiveServerTestCase`-type object, that would be needed to call the _pre and _post methods. Additionally, it looks that the test object's `setUp()` and `tearDown()` methods are never called.

I tried changing the code from:

```python
@fixture
def django_test_case(context):
    context.test_case = LiveServerTestCase
    context.test_case.setUpClass()
    yield
    context.test_case.tearDownClass()
    del context.test_case
```

to

```python

class BehaveLiveServerTestCase(LiveServerTestCase):
    def setUp(self, *args, **kwarg):
        super().setUp(*args, **kwarg)

        # import Django models here since it's after Django Apps initialization
        from rest_framework.authtoken.models import Token
        from my_app.models import Contact
        from health.models import HealthFacility

        # recreate objects that should be present for each scenario step
        self.ministry_of_health = HealthFacility(name="MoH")
        # ...


@fixture
def django_test_case(context):
    context.test_case = BehaveLiveServerTestCase()
    context.test_case._pre_setup()
    context.test_case.setUpClass()
    context.test_case.setUp()
    context.config.server_url = context.test_case.live_server_url
    yield
    context.test_case.tearDown()
    context.test_case.tearDownClass()
    context.test_case._post_teardown()
    del context.test_case
```

This actually worked, meaning the database is reset after each scenario and repopulated before the next one, and the tests I have pass again... but I do wonder if this is the right way (especially since it was mostly working before, too...).

Questions:
  1) Should the `test_case` attribute be an __instance__ of the test class, or a reference to it like in your docs?
  2) Is calling the test object's .setUp() (and eventually .tearDown()) method explicitly here correct? Meaning: they need to be called and I don't see your code ever doing that... but I might have missed something :-)

**Comment by bittner** [comment]
Thank you, Roberto, for reporting this issue! Important to know that the related documentation is starting to be outdated.

The "manual integration" in the [Django chapter](https://behave.readthedocs.io/en/latest/usecase_django.html) is based on a blog post of @plus500s, as mentioned at the bottom of the section, but was overhauled by @jenisys later, IIRC. I don't know what to suggest other than looking at / trying out Andrii's original approach, for comparison.

Personally, I find the integration code confusing. Especially the empty `yield` statement is just too much magic. The code is not self-explanatory, and neither a comment nor a paragraph in the docs explain the implementation details of the boilerplate.

If the ultimate goal is to integrate with Django but not need to use `python manage.py` maybe there's a better way. We might find a simplified boilerplate that leverages `behave-django`, or make `behave-django` work without the management command as an alternative.

**Comment by RobertoMaurizzi** [comment]
The decision to use behave directly was taken because we got a problem with django-behave getting abandoned and after taking a look at behave-django (that is still well maintained and we're still using for a couple of other projects) we found that (back then) it had troubles keeping up with new features in `manage.py test` like commands to not drop the db at the end and run tests in parallel, so I thought it'd be better to directly understand how behave would integrate with Django... it turned out my knowledge of how a Python Test class should be setup and how it works wasn't deep enough 😅 

I did end up reading both Andrey's original blog post (and another one I found [on JetBrain's site](https://www.jetbrains.com/pycharm/guide/tutorials/django-aws/bdd-behave/) where they work around the missing database reset by manually creating and deleting objects in their subclass' setUpClass and tearDownClass methods) but for the rest they're exactly the same, including the @fixture decorator that (I assume) transforms the function in a generator so yield can be called. Andrey's original example simply does the same things without using @fixture, directly in before_/after_scenario and yeah it's a bit more clear.

What put me on the right path was a S.O. post linked from [a comment in Andrey's blog](https://stackoverflow.com/a/41246811/153330): there the author assumes that you'll have your regular setUp and tearDown methods called from your LiveServerTestCase's subclass that do the setup of the required objects for all the steps/scenarios... and that to make TransactionTestCase happy you need to call _pre_setup and _post_teardown explicitly but in our case we never have the instance of the test class that supposedly will call them... and I thought that maybe someone forgot the () at the end of the class name when writing `context.test_case = LiveServerTestClass` since it's a quite common mistake.
The "best" part is, it DOES work anyway since setUpClass and the base class do run most of the required code to start the test server and set up the information to give back data about it.

Unfortunately right now I don't have the time to dig deep in behave's code to ensure that it does nothing with that 'test_case' attribute (so we really have to manage everything ourselves). and as I said my knowledge of how a TestCase class should work in general isn't good enough to state "yes, this is how it should have worked from the beginning"... 
That's definitely the impression I have 😅 but it's not based on information verified enough to make a PR, I think (but at least now if somebody else wonders why the database isn't reset after each step, they'll find this issue :-) )
