### ISSUE TITLE
Question : Any way we can make tags case-insensitive?

### ISSUE THREAD

**Issue by SKAUL05** [behave/behave#1042]
Are behave tags sensitive?

I tried running features having the same tags but different cases `@report and @Report`, but it seems like if we run the following command only tag matching case will run
`behave --tags=report`

Is there any way we can run both the tags thereby eliminating the case-sensitive behavior of tags

**Comment by jenisys** [comment]
Tags are case-sensitive (by intention).
Therefore, be precise and not lazy.
