### ISSUE TITLE
Question: Want to save exception of failed test scenarios into db using after_step hook.

### ISSUE THREAD

**Issue by sourabhsharma-cpi** [behave/behave#1043]
python: 3.7
behave 1.2.6
I am trying to get hold of exception & error_message when step_status == Status.failed in after_step(context, step).

error message was simple - step.error_message
but i am struggling to find how can i catch the exception in  a string variable - so that i can save that in DB.
when i do step.exc_traceback, i get : <traceback object at 0x12082b0a0>

PS: Sorry if this is a python issue rather than a behave issue - i am new to Python (had been into java for 10 years)

**Comment by bittner** [comment]
Take a look at the [related Python documentation](https://docs.python.org/3.7/library/traceback.html#traceback.print_tb). You might be able to print the traceback with an appropriate method, e.g.

```python
traceback.print_tb()
```

**Comment by bittner** [comment]
Please let us know if this suggestion helped. Thank you!
