### ISSUE TITLE
[Question]How set table value as empty string?

### ISSUE THREAD

**Issue by Joeylu-master** [behave/behave#1045]
When I use **Example** in **Scenario Outline**, how can I set empty string in table data? If I set empty data as below, the step thrown **Undefined** error.

```
> Examples:
      | Name | age | work | student |
      | aa   | 3   | test |         |
      | bb   | 3   |      | 1       |
      | cc   | 2   |      | 1       |
```

**Comment by jenisys** [comment]
DUPLICATED: 
See issue #1002

CORE PROBLEM:
The `parse` module does not match EMPTY-STRING (any more) if you only use a named parameter.

EXAMPLE: `@when('I meet "{name}"')`
* Matches `When I meet "Alice"`: `name = "Alice"`
* NO_MATCH with `When I meet ""`

SOLUTIONS:
* Use another step binding that matches the empty string (or a second step implementation) as suggested by the error output
* Use an explicit user-defined type for the placeholder
