### ISSUE TITLE
How to use --stage option

### ISSUE THREAD

**Issue by zhangzy231** [behave/behave#1046]
Use `--stag` on the command line to specify steps, environment.py doesn't work anymore

**Comment by jenisys** [comment]
The stage option allows to use different `environment.py` files and `steps/` directories for each stage. This requires that the environment-file and the steps-directory have a different unique name for each stage (by using the stage name as part of the filename / directory-name).

This allows you to share the same feature files for different teams (that may have different step implementation and execution context).

SEE ALSO:

* [features/runner.use_stage_implementations.feature](https://github.com/behave/behave/blob/main/features/runner.use_stage_implementations.feature)
* Docs: [Search for „stage“](https://behave.readthedocs.io/en/latest/new_and_noteworthy_v1.2.5.html?highlight=Stage#test-stages)
