### ISSUE TITLE
Asterisk * keyword (bullet point) results always in given step type

### ISSUE THREAD

**Issue by zettseb** [behave/behave#1047]
Asterisk keywords (bullet points) unfortunately are always transformed into the step type `given`.
According to my understanding of the [Gherkin reference](https://cucumber.io/docs/gherkin/reference/), I am expecting the same behavior as with `and` and `but` , i.e. adoption of the previous step's type.

**Expectation:**
`When my when` -> step type `when`
`And my step` -> step type `when`
`* my step` -> step type `when`

**Reality:**
`When my when` -> step type `when`
`And my step` -> step type `when`
`* my step` -> step type `given`

**Assumed root cause:**
Function `parse_step()` in `parser.py` loops through the available keywords, but the asterisk matches always already on the first step type being `given`.

**Comment by jenisys** [comment]
You should either use `Given / When / Then`  style or generic steps with asterisk.

NOTES:
* The current tip of the repository supports asterisk with any step type.
  By reading the code, in your example you should get what you expected.

**Comment by jenisys** [comment]
INTEGRATED INTO: behave v1.2.7.dev2

**Comment by NehaMittal3010** [comment]
Hi @jenisys,

Are you planning to release this behave v1.2.7.dev2 as a GA so that we can consume as these fixes are very much needed to us. Appreciate if you can let us know the tentative date of this release.

Regards,
Neha.

**Comment by zettseb** [comment]
Hi @jenisys,
following up on @NehaMittal3010's question:
Will this fix be part of the v1.2.7 release (once it is published?
Thanks and BR,
Sebastian

**Comment by jenisys** [comment]
@zettseb 
Yes, as my comment above explicitly states that is was integrated and for which version it was integrated.
