### ISSUE TITLE
Split features to multiple directories

### ISSUE THREAD

**Issue by ammuradyan** [behave/behave#1048]
Hello.

I have an separate "monolith" repository called autotests, which contains autotests for my services. I place them in one directory which is not so comfortable:
```
features/
    steps/...

    devops.website.common.feature
    devops.auth.common.feature
              
    frontend.website.signin.feature
    frontend.website.signup.feature
    frontend.website.payment.feature
    ...
              
    backend.cms.content.feature
    backend.billing.checkout.feature
    backend.auth.signin.feature
    ...
```

I would like to have next project structure:
```
features/
    backend/
        steps/...
    frontend/
         steps/...
    devops/
          steps/....
```

I have tried to split them that way and specify `path` in setup.cfg but it still does not find my features. Is there a beatiful way to do something similar? 

Thanks

**Comment by jenisys** [comment]
The feature directory structure is possible, but currently:

* You can only have one `features/steps/` directory
* Or you use your structure w/ 3 test runs, one for each subdirectory, like: `behave features/backend/`

**Comment by ammuradyan** [comment]
Yup, i did it that way. Thanks!
