### ISSUE TITLE
How to access error_message from a Step object in a hook?

### ISSUE THREAD

**Issue by r4ddek** [behave/behave#1050]
Hi everyone,

I'm trying to access the error messages from failing steps during runtime. I was trying to access them in the `after_step` hook, until I found this issue https://github.com/behave/behave/issues/468 that says the message will not be available before this hook is executed since the hook itself may also fail. 

My question is: is there any way to access step failure messages for a given scenario, say, in a `after_scenario()` hook? I tried looking around but could not find anything helpful in the docs or over the internet in general.

Thank you!

**Comment by jenisys** [comment]
The `after_scenario(ctx, scenario)` hook gets the current scenario handed to it and the scenario contains its steps.
Therefore, you should be able to retrieve the `step.error_message` from the failed step of this scenario.

BUT: Could you explain what you are trying to achieve ?
