### ISSUE TITLE
Feature print file and steps unformatted

### ISSUE THREAD

**Issue by xzyup** [behave/behave#1051]
I define a feature file like this

`Feature: Feature test

  Scenario: A simple test
    Given you are happy
    When someone says hi
    Then you smile`

When i run this feature, the print file looks ugly.
![image](https://user-images.githubusercontent.com/30389683/187215267-9d35483a-d14f-4ffa-b7bd-ca5fc9f8bfae.png)

I have done something like create some related resources and start backend services in before_all function. 
Does any relationship to this.
Can someone help to resolve the problem

**Comment by bittner** [comment]
Which OS do you use? Can you share relevant details of your configuration? Where do you run behave? (PyCharm, WSL, terminal)

It looks like you're on Windows and behave emits LF instead of CR/LF. We need to understand why this happens.

**Comment by xzyup** [comment]
hello, bittner,
my os is 
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"

i found i use the hook before all and use docker compose to start the services.
this is in before all

def start_function_app(context, service):
    compose.process(
        'exec',
        '-T',
        '-e=AZURE_SUBSCRIPTION_ID',
        service,
        '/workspace/start_service',
        # stdout=None if 'verbose' in os.environ else DEVNULL,
        # stderr=None if 'verbose' in os.environ else DEVNULL,
    )

this is the final method be called.
 def process(
    *args,
    prefix=service_prefix,
    env=None,
    stdout=subprocess.DEVNULL,
    stderr=subprocess.DEVNULL,
):
    return __subprocess(
        method=subprocess.Popen,
        stdout=stdout,
        stderr=stderr,
        args=args,
        prefix=prefix,
        env=env,
    )

**Comment by bittner** [comment]
I'm a bit confused. 

Where do you run this code? On Azure?  In a pipeline? Locally on your developer machine? Should it say `docker-compose` as a command in your code sample?

Please try to provide a complete, reproducible example.

**Comment by xzyup** [comment]
hi, bittner, thanks for notice.
I create a demo project for this issue.
https://github.com/xzyup/behave-feature-test

You can clone the codes and then do the following commands.
- . .env
- start
- feature.sh

then you can see the file print unformatted.
![image](https://user-images.githubusercontent.com/30389683/187378363-149e3994-3039-41ad-a45f-369b3542307d.png)

By the way, my os is Ubuntu as mentioned before.

**Comment by bittner** [comment]
Your setup is rather complex. You mix shell scripts calling shell scripts that execute Docker to run Behave.

Have you tried to reduce the complexity, e.g. run Behave using Tox, no shell scripts, not inside Docker? I wouldn't be surprised if the problem went away.
