### ISSUE TITLE
TagExpressions v2: AND concatenation is faulty

### ISSUE THREAD

**Issue by janoskut** [behave/behave#1054]
The `--tags-help` text clearly states:

> The `--tags` option can be specified several times, and this represents logical AND

However the concatenation is done quite poorly and yields incorrect statements:

Examples:
```sh
python -m behave --dry-run --tags="fish or fries" --tags="beer and water"
# yields: ( fish or ( ( fries and beer ) and water ) )
```
Which is clearly not what can be expected, no matter how we put it. The same happens for tags expressions set in the `behave.ini` or other config files.

To logically "AND" the expressions, it is not sufficient to just add the word "and", but the parts need to be enclosed into brackets: https://github.com/behave/behave/blob/main/behave/tag_expression/__init__.py#L51.

What do you think about changing the logic to this?

```diff
diff --git a/behave/tag_expression/__init__.py b/behave/tag_expression/__init__.py
index c68521e..a1ad83d 100644
--- a/behave/tag_expression/__init__.py
+++ b/behave/tag_expression/__init__.py
@@ -48,7 +48,7 @@ def parse_tag_expression_v2(tag_expression_text):
     if not isinstance(text, six.string_types):
         # -- ASSUME: List of strings
         assert isinstance(text, (list, tuple))
-        text = " and ".join(text)
+        text = " and ".join(f"({t})" for t in text)
 
     if "@" in text:
         # -- NORMALIZE: tag-expression text => Remove '@' tag decorators.
```

**Comment by jenisys** [comment]
Mmh:

* There are tag-expressions v1 that needed multiple tags options
* There are tag-expressions v2 where one `—tags` option is completely sufficient to form all logical conditions that were not available before
* There is currently a compatibility mode that allows you to use tag-expressions v1
* This compatibility mode will be removed in the future (and only one `—tags` option will be available then)

**Comment by janoskut** [comment]
@jenisys 

> There are tag-expressions v2 where one —tags option is completely sufficient to form all logical conditions that were not available before

I don't believe that it can be desirable to only _allow_ one single `--tags` option, also with v2. Consider the `beahve.ini` example that I gave above. Users may want to put fix `--tags` into `behave.ini`, while it should be still possible to add more using the `--tags` CLI option.

No matter how you put it - concatenation of any logic using `" and ".join(text)`, without making sure of bracketing, is just **wrong** and yields to incorrect logic. I strongly suggest to fix it, and keep considerations about v1 vs. v2 on a separate topic.

On that v1 vs. v2 topic - as I suggested above, I don't see a need or benefit in limiting `--tags` expressions to just one, for v2. It seems totally feasible to `AND`-concat multiple expressions, as it is implemented and documented today. Just today's implementation is faulty.

**Comment by jenisys** [comment]
Sorry, I disagree.
It is better to state which Boolean operators you want to use instead of relying on side-effects magic (better be explicit than implicit).

With tag-expressions v2 there is no need to support more than one command-line option.
Everything can be done with one tag-expression on the command-line.

The tag-expressions in the config-file is a faulty argument because what do you do if you need to override this tag-expression from the config-file on the command-line.

NOTES:
* You gave no `behave.ini` example above. Therefore, it is weird that you refer to it.
* The suggested fix for the internal tag is correct and will be fixed for the current implementation.
  But this functionality will change/be removed in the future.

**Comment by janoskut** [comment]
Hey @jenisys , sorry for the delay on this topic, I was on vacation plus moving homes.

> The suggested fix for the internal processing code is correct and will be fixed for the current implementation.

Acknowledgment that we have a bug here is actually all I wanted to hear. The future plans I don't need to get involved with, at least not in this issue.

> will be fixed for the current implementation

So should I open an PR for it, or is that already ongoing?

**Comment by jenisys** [comment]
INTEGRATED INTO: behave v1.2.7 (after v1.2.7.dev3 release tag)
