### ISSUE TITLE
[Question] How can I make my behave tests fail when there is a HOOK-ERROR

### ISSUE THREAD

**Issue by zadigus** [behave/behave#1055]
I have some behave tests that I am running like this:

```python
# run_tc.py

import os
import sys

from behave.configuration import Configuration
from behave.runner import Runner

here = os.path.dirname(os.path.abspath(__file__))

configuration = Configuration()
configuration.stdout_capture = False
configuration.stderr_capture = False
configuration.paths = [os.path.join(here, "features")]
success = Runner(configuration).run()
print(f"Test runner returned: {success}")
sys.exit(int(success))
```

Now, I have a fixture defined like this:

```python
@fixture
def trainer(context):
    base_uri = f"{os.environ['API_BASE_PATH']}/api"
    context.trainer = Trainer(base_uri)
    assert context.trainer.server_is_up()
    return context.trainer
```

which I apply in the `before_all` hook. If the server is not up, then I get the following error from behave:

```
HOOK-ERROR in before_all: AssertionError:

ABORTED: By user.
0 features passed, 1 failed, 0 skipped, 1 untested
0 scenarios passed, 0 failed, 0 skipped, 6 untested
0 steps passed, 0 failed, 0 skipped, 0 undefined, 16 untested
Took 0m0.000s
```

which is great, but then I get also the following feedback (due to my run script above): 

```
Test runner returned: True
```

which is bad. 

How should I rework my fixture so that I get

```
Test runner returned: False
```

?

**Comment by jenisys** [comment]
If the `Runner.run()` call returns `True`, it means that the test run has failed.
That is exactly the behavior that you experience.

**Comment by zadigus** [comment]
Ok. 

Is it possible to distinguish a failure in the hooks from a failing test? If the hook fails, then the runner returns `True`. If at least one step fails, then the runner also returns `True`. How can I make a difference between both types of failure?

**Comment by jenisys** [comment]
Failed is failed.
There is a reason why you put an `assert` statement into your fixture implementation (or raise an exception).
You want to know if something has failed independent from where the failure occurred.
For the details, look at the summary (or the output).
In addition, the runner has a `hook_failures` attribute that counts how many hooks have failed (if any).

**Comment by zadigus** [comment]
Ok, I'll see if I can do something with the `hook_failures` attribute. That could help me out. Thanks for your kind recommendations.
