### ISSUE TITLE
Scenario should inherit Rule tags

### ISSUE THREAD

**Issue by testgitdl** [behave/behave#1061]
Do you know when it will e possible to select the scenarios under a Rule based on rule tagging? Thank you!

**Comment by jenisys** [comment]
I assume that you mean that the effective tags of a scenario are inherited from the rule that contains it?

OOPS, I was not aware that this aspect was missing.
It will be corrected soon (or you want to supply a pull-request).

**Comment by jenisys** [comment]
INTEGRATED INTO: behave-1.2.7
