### ISSUE TITLE
Run multiple stages in a single line

### ISSUE THREAD

**Issue by biswajit-mandal** [behave/behave#1062]
I was trying to use multiple stages at a single line. My directory structure:

```
features/
  +-- foo_steps/               
  |   +-- foo.py
  +-- bar_steps/     
  |   +-- bar.py
  +-- foo_environment.py         
  +-- bar_environment.py 
  +-- *.feature

```
And I was trying to run using `behave --stage=foo --stage=bar`, but it looks like behave only looks for one directory level, not the other, I get the below output:

```
Feature: Test DB # features/foo.feature:1

  Scenario: Test XXXXX          # features/foo.feature:2
    Given DB is UP                    # None
    When POST TO DB             # None
    And Send HTTP request    # None
    Then Data gets stored in DB # None

Feature: Test XXXXXX # features/bar.feature:1

  Scenario: Test bar        # features/bar.feature:2
    Given bar is UP          # features/bar_steps/bar.py:18 0.000s
    When blah blah       # features/bar_steps/bar.py:23 5.003s
    Then then then # features/bar_steps/bar.py:29
```

Please let me know how to achieve this.
So, for foo, the step file is not being looked at, it shows as None

**Comment by jenisys** [comment]
And it will stay that way for now.

This is just an automation problem that can easily be solved by a script that runs both stages (or more stages), like:

```bash
# -- file:behave_run_all_stages.sh
behave --stage=foo $*
behave --stage=bar $*
```

HINT:
In addition, this can easily be done in CI build scripts.
