### ISSUE TITLE
The "rerun_failing.features" file is nowhere to find, for  failed cases.   

### ISSUE THREAD

**Issue by chunji08** [behave/behave#1066]
I have set up a jenkins job on ubuntu to routinely execute my behave test cases, and there are some failures happened occasionally. 

This is my execution  command in the job to execute my feature file:  
`docker-compose -f docker-compose.yml run -u 111:117 --rm -v ${WORKSPACE}/allure-reports:/allure-reports fext_extender behave -verbose -f allure_behave.formatter:AllureFormatter -f pretty -o /allure-reports -f rerun features/devices/inventory.feature
`

And here is the message in the job console output, as we could see there are some failed cases this time. 

![image](https://user-images.githubusercontent.com/11307533/197850699-ba0213a5-b4b2-4b52-9f9e-a7debe71792b.png)

But after execution, I don't see anywhere this "rerun_failing.features" file is being created ?  The behave is of version 1.2.6. 

Any comments ? 

Thanks, 

Jack

**Comment by jenisys** [comment]
You need to specify that you want to use the „rerun“ formatter and its output-file.

This can be done on the command-line, like: `behave -f rerun -o rerun.txt -f pretty …`
But it is normally done in the „behave.ini“ config-file. In this case, it will be automatically used and you do not need to specify it on the command-line.

SEE ALSO:
* [behave.ini]( https://github.com/behave/behave/blob/main/behave.ini#L15)  (section: `[behave]`, options: `format`, `outfiles`)

**Comment by chunji08** [comment]
I do have this set in the behave.ini file, but somehow, I don't see the rerun file generated. here is the structure of my code: 
.
├── allure-reports
├── behave.ini
├── docker-compose.yml
├── features
│      ├── devices
│      │   ├── inventory.feature

And the contents of my behave.ini file: 
```
# -- file:behave.ini
[behave]
format   = rerun
outfiles = /tmp/rerun_failing.features

```

Do u know if that "docker-compose -f docker-compose.yml" command matters ? 


Thanks for the help. 

Jack

**Comment by jenisys** [comment]
I assume the "/tmp" directory of your docker container is not mounted (to the host system).
Therefore, I assume that you loose the contents of this temporary directory used within the container, when the docker container run ends.

Try to change the location of the output-file to "build/rerun_failing.features" for example (or to a location that provides a persistent file system / is mounted).

NOTES:
* This should not be a problem with `docker-compose` but with `docker` 
  (and which file contents are persistent and which are not).
* You seem to use the "rerun" formatter in the config-file and on the command-line (see above). If this by intention, it is OK, but if not ...

**Comment by chunji08** [comment]
Hi Jenisys, 
Thanks for the help. I have just figured out what is going on here. 

In my initially running, 
a) I have such on my command-line execution:  
**docker-compose ...  fext_extender behave -verbose -f allure_behave.formatter:AllureFormatter -f pretty -o /allure-reports -f rerun ...**, 
b) and a behave.ini file at my root dir. 

During the run-time, it is these command options that taking into effect, while the "behave.ini" is just a dummy file. 

Now I have solved this issue by:  
1) have the "_-f reurn_" part removed from the execution command-line.  
2) have made the correct mount so that behave.ini is taking into effect during the run-time !  Thanks. 

for me, the left-out question is:  is it possible to have this options  
"_-f allure_behave.formatter:AllureFormatter -f pretty -o /allure-reports_" 
moved from command-line into the behave.ini file also ? 

Just you know, my allure report is generated from my jenkins job **Post-Build Action** part. It may be different  from the normal process. 

overall, my initial issue has been resolved.  Thanks for the help. 

Jack

**Comment by jenisys** [comment]
Yes, you can move these parts into the „behave.ini“ config-file.
The existing config-file in the repository does similar things.

EXAMPLE:
```ini
[behave]
default_format = pretty
format = rerun
    allure          # OR: allure_behave.formatter:AllureFormatter (instead of the ALIAS)
outflies = rerun.txt
    /allure-reports

[behave.formatters]
allure = allure_behave.formatter:AllureFormatter    # Used as ALIAS here and above.
```

HINTS:
* The output-path „/allure-reports“ under the root directory normally requires special permissions.
   Therefore, it may be OK to use in the container but may cause problems, if you use on the host.

SEE ALSO:
* [behave.ini](https://github.com/behave/behave/blob/main/behave.ini)
