### ISSUE TITLE
Feature Request: show datetime before every step 

### ISSUE THREAD

**Issue by shero-lim** [behave/behave#1076]
add datetime before the step log. like: **[2022-12-11 21:51:00] Given 关键词 behave**
![image](https://user-images.githubusercontent.com/38414433/206907584-7d234e36-366b-472c-a2f5-2ee3650f1169.png)

**Comment by jenisys** [comment]
Sorry, that is too noisy in my opinion and will hide the really important information.

BUT:
You can always  provide and use your own formatter class that does exactly what you want and desire.
