### ISSUE TITLE
Skip a .feature if background steps fail 

### ISSUE THREAD

**Issue by lu-maca** [behave/behave#1082]
Hi,

is there a way to skip all scenarios in a feature if some of the background steps fail?

```
Background:
    Given the test environment is set up
    
Scenario: first scenario
    When a    
    Then b

Scenario: second scenario
    When c
    Then d

Scenario: third scenario
    When e
    Then f
```
If background step fails, I would like to skip all the scenarios not already run; for example, if background runs correctly for `first scenario`, but fails for  `second scenario`, I would like to skip the second and the third, jumping to the next feature file.

Is it possible?

Thank you,
Luca

**Comment by jenisys** [comment]
Yes, that should be possible in principle (I think) by providing an `after_step()` or `after_scenario()` hook that implements the desired functionality:

* Determine which step has failed (in `after_scenario()` hook)
* Determine if the failed step is a background step of the scenario
* Select the remaining scenarios of this feature and skip them

But note that is just a **band aid** to your real problem:
The setup of your test environment (in your example above) does not work in a reliable way.

**Comment by lu-maca** [comment]
> But note that is just a **band aid** to your real problem: The setup of your test environment (in your example above) does not work in a reliable way.

Thanks for you answer, @jenisys. 

My background step is supposed to determine if the test environment is working in the correct way. The test environment shall be configured in a proper way, and if background step fails, it means that the configuration has been done uncorrectly.
