### ISSUE TITLE
scenario_outline_annotation_schema cannot be specified on command line

### ISSUE THREAD

**Issue by zettseb** [behave/behave#1086]
For reasons of flexibility we require the configuration parameter `scenario_outline_annotation_schema` to be specifiable on the command line as well, e.g.:

`behave my_file.feature scenario_outline_annotation_schema={examples.name}_{name}`

Currently the only supported method is via the `behave.ini` config file.

**Comment by jenisys** [comment]
Mmh, I really see no reason to have this as a command-line option.
Therefore, by intention it is currently only possible to override/specify it in the configuration-file.

Can you explain why you need it as command-line option?

NOTE:
Just because you can do it, is no real reason.

**Comment by jenisys** [comment]
A potential hack could be:

* Use `userdata` option: `behave -D behave.scenario_outline_annotation_schema=<VALUE> …` to pass the information on command-line
* In the `environment-file` before_all() hook: Reconfigure the value in the `config` object if this userdata key is used
* In the `environment-file` before_feature() hook: Rebuild all scenarios in a ScenarioOutline/Template by keeping the status `SKIPPED` or `UNTESTED`. This will recreate the scenarios for all ScenarioOutline(s)/Template(s) with the new annotation_schema value

**Comment by zettseb** [comment]
Thanks for your quick feedback!

The background to our request is that we have several different test run scenarios which require different configuration of behave.
We use a script to set up the behave command incl. arguments based on the input scenario. The only behave setting that we cannot pass using the command line string is `scenario_outline_annotation_schema`, so we have to create a `behave.ini` file for that single parameter in the script (which then lingers in the environment).

We were just wondering if there was some active decision-making behind why some parameters are available as CLI arguments and some are not. Also, after looking at the [User-Defined Formatters](https://behave.readthedocs.io/en/stable/formatters.html#user-defined-formatters) docu section, it seemed one can inject any configuration object property via the `-D behave.[...]` syntax. This would at least harmonize `behave.ini` and CLI approaches, but it does not apply in general.

Thanks also for the workaround hint, I actually already also thought about this idea and will use it in the meantime.

**Comment by zettseb** [comment]
> * In the `environment-file` before_feature() hook: Rebuild all scenarios in a ScenarioOutline/Template by keeping the status `SKIPPED` or `UNTESTED`. This will recreate the scenarios for all ScenarioOutline(s)/Template(s) with the new annotation_schema value

Could you elaborate on this last point a little more? How can we re-run the feature with the new `scenario_outline_annotation_schema` value?

**Comment by jenisys** [comment]
The `ScenarioOutline.scenarios` attribute contains the template instances, one Scenario for each Examples table row of the `ScenarioOutline` (or `ScenarioTemplate`). The value of this attribute uses a lazy-build mechanism. Therefore, it is normally only build once when it is first accessed (when you walk/iterate over the scenarios of a Feature). 

If you assign the `ScenarioOutline.scenario_outline_annotation_schema` in the hook of the environment-file, it is normally already to late. The Scenarios (as Template instances) are already built w/ the initial value of the `scenario_outline_annotation_schema` and not the new one. Therefore, you need to throw away the contents of each `ScenarioOutline.scenarios` attribute. This will trigger that the attribute is build again later-on (or you rebuild it then).

**Comment by jenisys** [comment]
I am slightly confused.
My initial suggestion how you can solve the problem is still valid.

If your scenarios are long-running and resource-intensive, what does it matter.
The scenarios are just instantiated twice before they are executed.

Otherwise, the `ScenarioOutline.scenario_outline_annotation_schema` has just the impact in the `Scenario.name` (or title). Therefore, you can recompute also this parameter only for each of the affected scenarios.
