### ISSUE TITLE
ImportError: cannot import name 'given' from 'behave'

### ISSUE THREAD

**Issue by mtrzas** [behave/behave#1095]
This error occurs when using **behave 1.2.7.dev2**

I got a python package(1) where actionwords for given, when and then are implemented inside a file /features/steps/actionwords.py

Inside another project(2) I want to import those actionwords inside a file /features/steps/example.py.

When running behave for project(2) I get the error message:

`ImportError: cannot import name 'given' from 'behave' (/home/mike/projects/test/kanzidemo2/venv/lib/python3.10/site-packages/behave/__init__.py)`

When I'm using behave 1.2.6 this error does not occur

**Comment by jenisys** [comment]
Mmh, the complete test suite of `behave` imports the step-decorators from the `behave` module.
They are working, usable and actively checked by the tests.

Therefore, the fault location is probably somewhere in your workspace / work-environment.
Sorry, but without more details, it is rather hard to help you (to find out what is causing your problem).

**Comment by jenisys** [comment]
PROCEDURE: To verify if problem exists or not

```sh
# -- USING: shell=bash
$ virtualenv -p python3.10 .venv
$ source .venv/bin/activate
$ python --version
Python 3.10.8

$ pip install git+https://github.com/behave/behave@v1.2.7.dev2
$ python explore_behave.py
behave import: OK

# -- USING: Main tip of the Git repository
$ pip install git+https://github.com/behave/behave
$ python explore_behave.py
behave import: OK
```

with Python script:

```python
#!/usr/bin/env python3
# -- FILE: explore_behave.py
from __future__ import absolute_import, print_function

try:
    from behave import given, when, then
    print("behave import: OK")
except ImportError:
    print("behave-import: NOT-OK")
    raise
```

**Comment by jenisys** [comment]
@realchandan 
* Which `type hinting`?

NOTES:
* `behave` cannot provide `type hints` because it has still support for Python 2.7.
* That does not mean that you cannot use `type hints` in your own source code (if you use Python3)
* Any good editor or IDE will show you the parameters that you need.
