### ISSUE TITLE
How to customize the title suffix of parameterized use cases？

### ISSUE THREAD

**Issue by Rexze001** [behave/behave#1096]
I used the “Scenario Outline” method to achieve parameterization. 
<img width="623" alt="image" src="https://user-images.githubusercontent.com/22924327/228597817-7cf69d9d-e08e-4168-ac2e-0c4dc5e27094.png">

And I noticed that in the “Run” window the title of the parameterized use case consists of the scenario title and a suffix “@1.1”. 
How can I replace this suffix with my customized content？ 

<img width="451" alt="image" src="https://user-images.githubusercontent.com/22924327/228595594-37db3ee3-b1c1-4764-9e3a-f098671547f4.png">

**Comment by jenisys** [comment]
Use the config-file parameter `scenario_outline_annotation_schema`.

SEE ALSO:
* behave docs: [scenario_outline_annotation_schema](https://behave.readthedocs.io/en/latest/new_and_noteworthy_v1.2.5.html?highlight=scenario_outline_annotation_schema#better-represent-example-row)

**Comment by Rexze001** [comment]
It worked! Thank you!
