### ISSUE TITLE
How to loop through a feature？

### ISSUE THREAD

**Issue by Rexze001** [behave/behave#1102]
Due to the special performance of the test, it is necessary to dynamically pass multiple parameters from the outside. I  used the -D parameter in the command line to pass parameters：
`behave --tags=@wss -D name=test,dev1,dev2 -s --no-capture --no-skipped -f allure -o reports/allure-result`

And I defined variable in environment.py to receive the parameter:
```
context.name = context.config.userdata.get("name", "dev")
context.name = context.name.split(',')
```

Now the context.name = ['test', 'dev1', 'dev2']. How do I run a feature 3 times based on this variable?

**Comment by jenisys** [comment]
BDD / Gherkin has no loop support.
Therefore, it is not well suited for what you are trying to achieve.

POSSIBLE SOLUTIONS:
* Use a build-script that has a `for-loop` to loop over your parameter values
* Use a ScenarioOutline/Template w/ an Examples table that contains table-rows for each parameter set
* HINT: The Feature file with the ScenarioOutline can be generated by using a text template engine.

**Comment by Rexze001** [comment]
@jenisys Thank you, jenisys. I have achieved this in another way. 
I wrote a pre_process.py file to receive these dynamic parameters and then generate different feature files according to these parameters. 
Then run with the following command line:
`python common/pre_process.py --name=test,dev1,dev2 && behave --tags=@wss -s --no-capture --no-skipped -f allure -o reports/allure-result`
