### ISSUE TITLE
Integrate diferent Directories with the same steps definition

### ISSUE THREAD

**Issue by jossmar95** [behave/behave#1109]
Hello, i'm currently looking of a way to use 2 different directories in my project which will contain different feature files, however, they have some common steps within it so I want to use the steps I already have created with my new directory file with the new feature file.

Is this for testing purposes using behave framework we want to make our framework more transversal and use it for all our different projects.

**Comment by jenisys** [comment]
Use a step-library.
Step-libraries are normally provided outside of `features/` directory(s) as Python packages (and must be in the Python search path).

SEE ALSO:
* [features/step.use_step_library.feature](https://github.com/behave/behave/blob/main/features/step.use_step_library.feature)

**Comment by jossmar95** [comment]
I have a step library already however is located inside my feature file, I was thinking in adding command line arguments with parse, that way it can detect what's the name of the directory I want to test and run, but I'm stuck in the re-usability of the steps the I already have, so basically instead of creating new steps for my new directory/project I want to re-utilize the current ones I have, that's where i', facing my roadblock I don't know what to use to re-utilize them and that my feature files recognize them.

**Comment by jossmar95** [comment]
Any help you can give me with this ?

**Comment by jenisys** [comment]
@jossmar95 
I already provided you with clean solution by using step-libraries.

For your solution to work to need manipulate/provide the Python search path:

* As `PYTHONPATH` environment variable before you run `behave`
* Adapt the Python search in `features/environment.py` by using `sys.path`

You may run into problems if the same python module name is used in multiple `step-directories`.
