### ISSUE TITLE
Feature Request: Configuration of  Feature, Environment & Steps paths

### ISSUE THREAD

**Issue by otyrrell** [behave/behave#1117]
As a Test Engineer
I want to individually specify paths for feature files, environment.py and step definitions
So that I can core behave functionality without being constrained by the imposed directory structure

**Comment by bittner** [comment]
Maybe you want to provide a few examples to make your point better understood? :thinking: 

_Given_ ... _when_ ... _then_ ... :smirk:

**Comment by bittner** [comment]
@jenisys I feel you explain this very point roughly once a week or so. Shouldn't we have a FAQ chapter in the documentation that we can simply point to instead?

Also, maybe the concept of "step libraries" is too abstract for developers coming to Behave for just hacking their test code with it. We might give that topic a more prominent place in the docs, explaining, e.g., how to go about creating a step library for yourself and why it's useful.

**Comment by otyrrell** [comment]
> MISCONCEPTIONS (and potential existing SOLUTIONS):
> 
> * The `*.feature` files do not need to be in the the same directory as the `environment.py` file.
>   They can also be in subdirectories below this base directory (if that helps you).
> * Use `step-libraries`. This allows to reuse the same steps in multiple `features/` directories by provide a simple `use_steplib_<NAME>.py` as glue code that imports your steps from the `step-library`.
> * The same approach should work for `environment.py` files, meaning you can import the functionality from another python package, the `environment-library`
> * Use `stages` if you need to provide multiple `environment.py` / `step-dirs` in the same `features/` directory tree
> * Steps in nested subdirectories under the `steps/` directory are supported by now (note: I personally do not use them and I think that is the wrong solution for the problem; I use `step-libraries` instead)
> 
> OTHERWISE:
> 
> * The current `test runner` has the limitation that it only supports one `environment.py` and one `steps/` directory at a time
> * A better `test runner` might discover where multiple steps directories, etc. are located and splits up the test-run into multiple sub-test-runs, one for each directory scope
> * An alternative to the better `test runner` is a build-script that supports to run `behave` multiple times, once per directory scope.
> 
> NOTES:
> 
> * The `test runner` is an extension point in `behave`. That means you can provide and use your own one (requires: `behave v1.2.7.dev3` approx).
> 
> SEE ALSO:
> 
> * [features/step.use_step_library.feature](https://github.com/behave/behave/blob/main/features/step.use_step_library.feature)
> * [features/runner.use_substep_dirs.feature](https://github.com/behave/behave/blob/main/features/runner.use_substep_dirs.feature)
> * [features/directory_layout.advanced.feature](https://github.com/behave/behave/blob/main/features/directory_layout.advanced.feature)
> * [features/runner.use_stage_implementations.feature](https://github.com/behave/behave/blob/main/features/runner.use_stage_implementations.feature)
> * [features/runner.use_runner_class.feature](https://github.com/behave/behave/blob/main/features/runner.use_runner_class.feature)

Thanks very much for the explanation, will take a bit of time to have a thorough read and explore of your answer and come back

**Comment by jenisys** [comment]
@bittner 
You are probably right.
In addition, we should probably change the documentation into a structure like the "4 Quadrants of Documentation" system.

SEE ALSO: 
* https://documentation.divio.com
