### ISSUE TITLE
Logging ignoring level set in setup_logging

### ISSUE THREAD

**Issue by j7an** [behave/behave#1120]
I have the following in my `before_all`

```python
def before_all(context):
  context.config.setup_logging(logging.WARNING)
```

and the following in my `after_scenario`

```python
@capture
def after_scenario(context, scenario):
    logging.debug('This is a debug log')
    logging.info('This is a log message')
    logging.warning('This is a log message')
    logging.error('This is a log message')
    logging.critical('This is a log message')
```

My setup is only logging at level of WARNING or above, but my test result output ignores the level set as see below:

```
Captured Logging:
INFO:root:This is a log message
WARNING:root:This is a log message
ERROR:root:This is a log message
CRITICAL:root:This is a log message
```

What am I doing wrong with my setup?

**Comment by jenisys** [comment]
@j7an 
I could verify that I observe the same (or similar) behavior like you.
I look into it.

**Comment by jenisys** [comment]
INTEGRATED INTO: behave v1.2.7 (v1.2.7.dev4)
HINT:
* Workaround is shown in [issue.features/issue1120.feature](https://github.com/behave/behave/blob/main/issue.features/issue1120.feature#L54) that doesn't need the fix in `behave`.
