### ISSUE TITLE
I need the app I am testing to read command line switches and options

### ISSUE THREAD

**Issue by FriesK1** [behave/behave#1121]
I am writing a library that will handle our configuration management.  Part of what I need to test is setting those options from the command line... its a standard part of input for this library and critical for a properly tested package.  So is there a mechanism to send command line switches not to behave, but to the package behave is testing?  This is a pretty critical piece of testing for most programs I write.

**Comment by bittner** [comment]
Can you describe the way you'd like to use Behave to test the CLI behavior of your application?

It really depends on that. Behave is just a test runner. How you implement your tests is a different story.

For example, you may want to take a look at [cli-test-helpers](https://cli-test-helpers.readthedocd.io/) for ready-to-use test setups if you're fine to run unit tests. You can use the ideas to test a CLI from there too, and use (nearly) the same test code in your step implementations, if you prefer to stick to Behave.

**Comment by jenisys** [comment]
@FriesK1 
* Have you looked at `behave4cmd0` and its step-library (bundled with `behave`) ?
* There are some similar `behave` step-libraries for command-process on https://pypi.org/ (AFAIK).
  HINT: Just search for `behave` .

**SEE ALSO:**
* Bundled `behave4cmd0`: https://github.com/behave/behave/blob/main/behave4cmd0/
  HINT: Look at `*_steps.py` Python modules for step-library functionality.
* `behave4cmd0` in own repo (WIP): https://github.com/behave/behave4cmd0
  NOTE: There may be some setup steps need to be able to use it (setup where the root-directory is).
