### ISSUE TITLE
BDD not using supplied base directory for test location

### ISSUE THREAD

**Issue by b0uks** [behave/behave#1123]
path variable from:  " print(sys.executable)"
paths ['/home/.../features/tests']

Behave output gets the correct path, but sometimes appends the default path and will only search one item in the list of supplied paths?

I encounter this issue when running in PyCharm (debugger or standard). I have gotten past it by rerunning until it does not append the default "tests/features" path

I am using a behave.ini file to specify the paths variable:
```python
[behave]
paths = /home/.../features/tests
``` 

Supplied path: "/home/.../tests/features", "/home/.../features"
Trying base directory: /home/.../tests/features
Trying base directory: /home/.../tests
Trying base directory: /home/.../
Trying base directory: /home

...
error:
behave.configuration.ConfigError: No steps directory in '/home/.../tests/features'

line 803, in run
    self.setup_paths()
line 746, in setup_paths
    raise ConfigError(message)

**Comment by b0uks** [comment]
using PyCharm "Params":
pipenv run behave -k -v -t @endpoints_crud_ab_1 ... -D htmllog=/tmp/logs/alpha_c2_cft_3.html
env variables: AWS_PROFILE=c2; LOG_LEVEL=INFO

from the terminal this appears to be the command run:

/home/.../bin/python3 /home/adamb/.pycharm_helpers/pydev/pydevd.py --multiprocess --qt-support=auto --client localhost --port 46279 --file /home/adamb/.pycharm_helpers/pycharm/behave_runner.py pipenv run behave -k -v -t @endpoints_crud_ab_1 -D ... -D workloadProfile=c2 -D ...  -D htmllog=/tmp/.../alpha_c2_cft_3.html

**Comment by jenisys** [comment]
That does not really help:

* In both cases you do not know what your current working directory ist
  (and normally you specify this in the PyCharm form)
* You need to describe your directory structure (as directory tree, where the feature-files and steps-directory is) and what you expect and what actually happens
