### ISSUE TITLE
Feature Request: Need before_background and after_background hooks

### ISSUE THREAD

**Issue by govindasharma1986** [behave/behave#1127]
Hey,

Behave version: 1.2.6

I created before_background and after_background hooks and added logging statements in them. 

file: enviroment.py
```py
before_background(context, background):
    log.info("before background called")

after_background(context, background):
    log.info("after background called")

before_scenario(context, scenario):
    log.info("before scenario called")

after_scenario(context, scenario):
    log.info("after scenario called")
```

In the log file, before and after scenario logs are seen but background logs aren't found. 

Do we have a before and after background hooks cause I could not find one in the [documentation](https://behave.readthedocs.io/en/latest/tutorial/#environmental-controls).

**Comment by govindasharma1986** [comment]
Now the reason why I need such a functionality is,

For every scenario we need to log few things to DB. Now sometimes as per project and use-case we need to open website twice. So we open once in Background and once in Scenario. Hence, I need to do some operations in starting and ending point of a test which is before_background and after_scenario.

**Comment by jenisys** [comment]
FYI:

* `Backgrounds` are newer execute. They just serve as Organisation group for steps that need to run before any Scenario steps are run.
* Therefore, sorry to say: There will be no `before_background`/`after_background` hooks

IN ADDITION:

* You can solve this problem in your own test-support code
* Or use the `behave context` object to store information that you have already done some things
* You just need to check if your code if you have already done something.

HINT:

* If you really need this functionality, you can provide it on your own by using `before_step()` hooks to detect if a step in a Scenario is the first non-background step (the rest is left as excercise).

**Comment by govindasharma1986** [comment]
So, I read the Scenario Model and I understand that behave simply collects the background steps and prepends it to scenario steps. (pls correct me if I am wrong anywhere)

This is also fine for me since there is no entry point called Background and all steps are executed after before_scenario hook. right?

Can u give a pseudocode to understand how to use before_step to detect if a step in a Scenario is the first background and non-background step?

Also any other model or class that I need to go through?

I have a 16 Aug deadline. So any kind of help would be appreciated.

**Comment by jenisys** [comment]
BACKGROUND INFO:

* `scenario.steps` are the normal Scenario steps
* `scenario.background_steps` property contains the list of related `Background.steps` (as copy)
* Each `Step` has a `FileLocation` info containing `filename` and `line` number
* First step in a Scenario in a Gherkin `*.feature` file is: `first_scenario_step = scenario.steps[0]` (if scenario has steps)

PREDICATE FUNCTIONS: 
```python
# -- SOLUTION IDEA 1:
def is_background_step_of_scenario_s1(scenario, step): 
    # -- HINT: Over simplistic implementation
    return step.line < scenario.steps[0].line

def is_first_scenario_step_s1(scenario, step): 
    # -- HINT: Over simplistic implementation
    return step.line == scenario.steps[0].line

# -- SOLUTION IDEA 2:
def is_background_step_of_scenario_s2(scenario, step): 
    # -- HINT: Over simplistic implementation
    return step in scenario.background_steps

def is_first_scenario_step_s2(scenario, step): 
    # -- HINT: Over simplistic implementation
    return step in scenario.steps and step == scenario.steps[0]
```

SOLUTION IDEAS:

* S1: Use `FileLocation.line` to detect where `real Scenario steps` begin in `before_step(ctx, step)` hook (hint: `ctx.scenario` provides access to current `Scenario`)
* S2: Use `step in scenario.background_steps` or `step in scenario.steps` to determine if a step is a background-step or a normal step

SEE ALSO:

* [behave docs: Appendix -- Context Attributes](https://behave.readthedocs.io/en/latest/context_attributes/)

**Comment by bittner** [comment]
I believe, the question is clarified sufficiently. Hence closing the issue.
