### ISSUE TITLE
How to disable the default cleanup after scenario?

### ISSUE THREAD

**Issue by g0dd4rd** [behave/behave#1138]
I need to have an application running between scenarios to simulate a normal use of an application.
Where in behave can I disable the default cleanup that is executed after each scenario?

**Comment by jenisys** [comment]
POSSIBLE SOLUTIONS:
* You inject context resources on all/feature/rule level. The cleanup for these context resources occurs then on all/feature/rule layer level.
* You perform resource management outside of `behave‘s Context` (basically in Python). You perform the cleanup when needed in `after_xxx()` hook or you use `context.add_cleanup(some_cleanup_func, …, layer=„feature“)`.
