### ISSUE TITLE
How to get Failed step/scenario logs in Environment file? 

### ISSUE THREAD

**Issue by jigisha9** [behave/behave#1139]
@alexmclarty @jesper @mbaltaks @caphrim007 @SEJeff 

How to get Failed step/scenario logs in Environment file? 

I want to print errors/logs/exception message that we get during run time to be printed in Environment.py. How do i get errors for failed tests accessible from environment.py file. 

Anybody tried? can you point me example? what inbuild function i can use to read errors for failed step/scenario

Thx. 
Jigisha

**Comment by jenisys** [comment]
@jigisha9 
First: `Issues` are reserved for bugs and enhancements. You are better served using the `Discussions` tab for asking questions instead of using `Issues`.

OTHERWISE:
* What you are trying to do is normally the responsibility of a `Formatter`
* Therefore: Why are you trying to do that ?
* Have you looked at the source code of `behave` ?

**Comment by jigisha9** [comment]
@jenisys sure for questions will use discussion board.

Between, can you point me where do i find list of functions/attributes for scenario and step? 

def after_step(context, step):

def after_scenario(context, scenario):

For example, 
   scenario_name = scenario.name
    scenario_status = scenario.status
    scenario_error = scenario.error_message ===> not return any value although scenario failed.

I need error message when scenario fails. which function to use? couldn't find anywhere.

**Comment by jenisys** [comment]
The normal procedure is (and that is not specific to `behave`):

* Read the docs
* Inspect the source code

SEE ALSO:
* `behave` API docs: [behave.model.Scenario class](https://behave.readthedocs.io/en/latest/api/#behave.model.Scenario)
* `behave` API docs: [behave.model.Step class](https://behave.readthedocs.io/en/latest/api/#behave.model.Step)

RELATED: Source code
* [behave.model.Scenario](https://github.com/behave/behave/blob/387d773ce30126873566287643dde75db6e64883/behave/model.py#L845) class description
* [behave.model.Step](https://github.com/behave/behave/blob/387d773ce30126873566287643dde75db6e64883/behave/model.py#L1644) class description
* [behave.model_core.BasicStatement](https://github.com/behave/behave/blob/387d773ce30126873566287643dde75db6e64883/behave/model_core.py#L268) class (used as base-class by: `Scenario`, `Step`, …)
