### ISSUE TITLE
Is it possible to include a prefix/ suffix to each scenario

### ISSUE THREAD

**Issue by vishrantgupta** [behave/behave#1143]
We are designing a workflow where we plan to run the BDD tests in a longevity setup.

What I am looking for is a way to include prefix or suffix in each scenario to distinguish scenario execution, is there something that is already supported by `behave`?

**Comment by jenisys** [comment]
Better use [Diskussions](https://github.com/behave/behave/discussions) instead of `issues` for asking questions.

* You should be able to adapt the `scenario.name` in the `before_scenario()` hook
* Formatters for a scenario are executed after the `before_scenario()` hook is executed.
