### ISSUE TITLE
Is there a way to render text just for context in the feature file?

### ISSUE THREAD

**Issue by patrickmead** [behave/behave#1145]
There are times when we want to provide context that isn't actionable but it should be visible to all. Consequently, given statements, background descriptions, and comments aren't the appropriate mechanisms for communicating this type of information. 

This information typically would be stored in a Word/Google document, Confluence, etc. I would like to include it in the feature file to keep the context close to the specifications. Obviously we don't want the feature files to be unreadable so we might provide summaries and links if there is a large amount of content. 

I was pretty familiar with tools like JBehave and Serenity years ago; I thought that Serenity had this capability. I haven't used them in years so I might not be remembering the feature sets correctly. I've since switched to python development thus my interest in behave. 

Thank you.

**Comment by jenisys** [comment]
I am still not quite sure what you are looking for.
But I assume you are looking for `descriptions`:

* A `description` is basically text between a `feature/rule/scenario` title and its body.
* A `description` can be  `0 .. N` lines of text (meaning: a `description` is optional)
* A `description` cannot start with a `keyword` in a description line.

EXAMPLE:
* [features/tags.active_tags.feature](https://github.com/behave/behave/blob/main/features/tags.active_tags.feature#L7) (note: In this example, a `dot` is used as `feature.description` line prefix)

SEE ALSO:
* [cucumber: Gherkin reference](https://docs.cucumber.io/docs/gherkin/reference/)
* [Gherkin: AST diagram](https://github.com/cucumber/gherkin/blob/main/docs/ast.png)

**Comment by patrickmead** [comment]
Thank you so much for the quick reply. description is exactly what I needed. 

I missed it originally but I certainly see description in the [documentation](https://behave.readthedocs.io/en/latest/api/?highlight=description#behave.model.Background.description) now.
