### ISSUE TITLE
Add "contains" dunder method for Row

### ISSUE THREAD

**Issue by hovi** [behave/behave#1146]
I found it quite confusing, that `behave.model.Row` implements `__getitem__` and therefore I can use `row["column"]`, but at the same time, `__contains__` dunder is not implemented, so `"column" in row` returns `False`.
It feels much more natural and shorter to do it that way rather than `"column" in row.headings` or `"column" in row.as_dict()` and overall the class is very dict-like (`.items()`, `.get()` and basically represents dictionary anyway).

Please consider adding it.

**Comment by bittner** [comment]
Do you want to try a pull request, so we can discuss and verify the feature hands-on?

**Comment by hovi** [comment]
Sure, I put it here #1149

**Comment by bittner** [comment]
Fixed via #1149 with 79a2e5c546253bc309e4084bbb75f87902bd37a0.
