### ISSUE TITLE
Failure when building with Sphinx 7.2 

### ISSUE THREAD

**Issue by s3v-** [behave/behave#1150]
Hi,
behave fails to build against Sphinx 7.2 as reported in Debian [1].

```
$ sphinx-build -b html behave-1.2.6/docs/ .
Running Sphinx v7.2.6
WARNING: html_static_path entry '_static' is placed inside outdir
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
building [mo]: targets for 0 po files that are out of date
writing output... 
building [html]: targets for 26 source files that are out of date
updating environment: [new config] 26 added, 0 changed, 0 removed
reading sources... [  8%] api
Exception occurred:
  File "/usr/lib/python3/dist-packages/sphinx/ext/extlinks.py", line 108, in role
    title = caption % part
            ~~~~~~~~^~~~~~
TypeError: not all arguments converted during string formatting
```
Kind Regards

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1042610

**Comment by bittner** [comment]
Have to tried building the docs [using Tox](https://github.com/behave/behave/blob/main/tox.ini#L39-L43)?

```
tox run -e docs
```

**Comment by s3v-** [comment]
> Have to tried building the docs [using Tox](https://github.com/behave/behave/blob/main/tox.ini#L39-L43)?
> 
> ```
> tox run -e docs
> ```

Not yet, but I don't expect failures with that.
I see a constraint has been introduced in https://github.com/behave/behave/commit/ddcaca4505aa767adc6266cd1500690beecacfd7  
``` diff
# BEHAVE: PYTHON PACKAGE REQUIREMENTS: For documentation generation
# ============================================================================
# REQUIRES: pip >= 8.0
+ # AVOID: shponx v4.4.0 and newer -- Problems w/ new link check suggestion warnings

- sphinx >= 1.6
+ sphinx >=1.6,<4.4
sphinx-autobuild
sphinx_bootstrap_theme >= 0.6.0
```
Root problem is that a single "%s" is mandatory (since Sphinx 6) whether the caption is a string in "extlinks" config value.  
[Related commit](https://github.com/sphinx-doc/sphinx/commit/7682353574e7c8b54330f2ce8f273a16816a6d02)

**Comment by jenisys** [comment]
`sphinx == 7.3.7` (latest release) is now supported in `behave`.

INTEGRATED-INTO: behave v1.2.7
