### ISSUE TITLE
[feature] Add support for the "Rule" keyword

### ISSUE THREAD

**Issue by harmin-parra** [behave/behave#1152]
The **Rule** keyword has recently been introduced in the Gherkin language.
https://cucumber.io/docs/gherkin/reference/#rule

It is often used in conjunction with the **Example** keyword.

Today, **behave** doesn't support this.
Features with the **Rule** keyword are skipped.
```
Feature: Calculator
  Rule:
  Addition should work
  Example: Add 2 and 1
  Given I have a calculator
  When I add "2" and "1"
  Then the calculator returns "3"
0 features passed, 0 failed, 1 skipped
0 scenarios passed, 0 failed, 0 skipped
0 steps passed, 0 failed, 0 skipped, 0 undefined
Took 0m0.000s
```
Is there any plan to add support for **Rule** and **Example** keywords?

**Comment by jenisys** [comment]
The `Rule` keyword is already supported.
You currently need to use the releases in the Github repo.

SEE ALSO:
* https://behave.readthedocs.io/en/latest/new_and_noteworthy_v1.2.7/
* https://github.com/behave/behave/tags
