### ISSUE TITLE
step status do not permit "executing"

### ISSUE THREAD

**Issue by Johnlon** [behave/behave#1155]
I have a use case where I want the final status of a step to remain as "executing" , and ideally for this to roll up appropriately to the scenario and feature.

However, if I trigger this state by doing _"step.set_status(Status.executing)"_ in a hook for instance then I get KeyError from a few places.

Was this limitation intentional? I hope not as I don't understand why behave would really need to be proscriptive on that point,  

The obstacles to this look accidental rather than deliberate......

1) **model.py** has a function _'compute_status'_ that has an assert that omits to include 'executing' in the list of valid values.
This kills the test dead.

If that's fixed then reporting needs a tweak to avoid KeyError and to make the report sensible... 

2) **summary.py** needs to include executing in the _status_order_ list and scenario_summary and step_summary.

Note: The absense of 'executing' in the feature_summary list doesn't cause a fault. But, I think this is because some missing roll-up logic to include rolling up 'executing' from the scenario to the feature.

3) Figure out the missing rollup logic from scenario to feature

So ...

1 and 2 are enough to remove the limitation.
3 is ideally needed because the feature level status ought to show "executing" just like the other levels.

**Comment by jenisys** [comment]
* First, you are fiddling with low-level details that should not be your concern.
* `Status.executing` means that a step is currently executed. Therefore, it is only a temporary state that marks the execution of the step.
* When the execution of the step is finished (successfully or failed), the `status` needs to reflect this fact.
* Therefore, `executing` should never occur in a `Summary` because it is not a final state.

**Comment by Johnlon** [comment]
Is there a reason to be proscriptive?
Skipped and other statuses work ok.
Seems a. Unnecessary restriction

**Comment by jenisys** [comment]
As already explained, `executing` is only used while a step is executed. Therefore, it can not be a final state.

Why do you want to make executing is a final state (when it is not one)?

**Comment by Johnlon** [comment]
I have a situation where I have async execution.

Like I say the only reason it doesn't work is cos of those few lines. Why
does the product need to be proscriptive on this point. What's the benefit
to the product?

**Comment by jenisys** [comment]
Sorry, async is not explanation.
A test run is finished or it is not.
A test run is either successful or has failed.
It is not a maybe successful or maybe failed (in the future).
When it is finished, it is finished (or aborted).
Therefore, no step remains in executing state.
