### ISSUE TITLE
Not able to access my Behave configuration values. 

### ISSUE THREAD

**Issue by Abdul-rehman-3620** [behave/behave#1163]
Hello everyone I am using a function to access value from the behave.ini but I am not able to access the value from behave. 

```
def get_value_from_ini(context, key):
    """This function returns the configuration value from behave.ini.

    Args:
        context (Context): The default object is available throughout the behave framework.
        key (Any): Key in the key-value pair from the behave.ini.

    Returns:
        Value (Enum): Value in the key-value pair from the behave.ini
    """

    return context.config.userdata.get(key)
```

**Comment by jenisys** [comment]
Your description lacks the information how you provide the data in the `behave.userdata` section in the config-file (and that your config-file is used at all).

SEE ALSO:
* [features/userdata.feature](https://github.com/behave/behave/blob/main/features/userdata.feature#L120)
