### ISSUE TITLE
Support 'AND' after 'BACKGROUND'

### ISSUE THREAD

**Issue by aneeshdurg** [behave/behave#1164]
Some gherkin tests in the wild have no prior step to an And, but do have a Background (for example, [openCypher's tck Match5.feature](https://github.com/opencypher/openCypher/blob/3983da2fc5dc0de99a7b2095cb69b67f2d51cd2c/tck/features/clauses/match/Match5.feature#L466)).

**Comment by jenisys** [comment]
IMPLEMENTED IN: pull #1097 (w/ some adaptions)
INTEGRATED INTO: behave v1.2.7.dev6
