### ISSUE TITLE
question: how to mark a step as failed in `after_step()`, or scenario as failed in `after_scenario()`?

### ISSUE THREAD

**Issue by panlinux** [behave/behave#1167]
I want to add a check after each step of my test suite to make sure there are no apparmor DENIED messages in the logs. So instead of adding such a check to all my steps, I thought about using `after_step()`, or even `after_scenario()`.

I found `Scenario.set_status()`, and looks like I can use that to set `Status.failed`, but for some reason the overall run was still considered a success:
```
1 feature passed, 1 failed, 47 skipped
0 scenarios passed, 5 failed, 896 skipped
22 steps passed, 0 failed, 16339 skipped, 0 undefined
Took 1m47.604s
.pkg: _exit> python /usr/lib/python3/dist-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
  behave: OK (171.67=setup[60.28]+cmd[111.39] seconds)
  ```

So now I'm looking at how I can mark a step as failed in `after_step()`, but all I can find is that the `Step.status` attribute is read-only, and there is no `Step.set_state()` call.

How can I mark a Step, or Scenario, as failed, in the corresponding `after_*()` call? Or is there another way?

**Comment by jenisys** [comment]
A hook fails if:
* an assert-statement fails during its execution, like: `assert False, „reason: …“‘ 
* an AssertionError(„…“) is raised
* an Exception is raised

Any of these options cause a hook to fail, same as while executing a step.
A step fails if its step-execution fails or any of its hooks fails.
A scenario fails, if any of its steps fails or any of its hooks fails.
