### ISSUE TITLE
TagExpression auto-detection is not working properly

### ISSUE THREAD

**Issue by Luca-morphy** [behave/behave#1170]
Hi

I'm using the last version, behave-1.2.7.dev5
Python 3.8.10

using tags options I noticed a weird behaviour
I will make an example with 2 possible tags equal to the feature names
```file-test_1, file-test_2```

```--tags="file-test_1"```
runs file-test_1 (correct)
```--tags="file*"```
runs file-test_1 and file-test_2 (correct)
```--tags="file-test*"```
runs nothing (incorrect)

the problem is related to ```-``` minus sign and ```*``` togheter.
but, if another relation is added the error is not present anymore

```--tags="file-test* or dummy_tags"```
runs file-test_1 and file-test_2 (correct)

I think that this error could be related to ```-``` which seems to be equal to ```~``` (also if it is not at the start of the tag), but is not clear to me how to correct this.
I wanted just to explain this issue to understand if I am using tags wrongly or could be corrected with future releases.

**Comment by jenisys** [comment]
Currently, `behave` supports:

* TagExpressions v2
* TagExpressions v1 (for backward compatibility)

The implemented algorithms tries to auto-detect if it should use TagExpressions v2 or TagExpressions v1. You seem to have stumbled over a corner case where TagExpressions v1 are selected (which do not support the wildcard matching as TagExpression v2). Note that should only happen if one term is used for the TagExpression.


WORKAROUND (until fixed): Use TagExpressions in strict mode (that only supports TagExpression v2)
```ini
# -- FILE: behave.ini
# ENSURE: Only TagExpression v2 is used (with auto-detection in strict mode)
[behave]
tag_expression_protocol = strict
```

SEE ALSO:
* [issue.features/issue1170.feature](https://github.com/behave/behave/blob/main/issue.features/issue1170.feature)

**Comment by jenisys** [comment]
INTEGRATED-AFTER: behave v1.2.7.dev5
