### ISSUE TITLE
PDF link in README.rst returns a 404 error 

### ISSUE THREAD

**Issue by Piyush-Bhor** [behave/behave#1175]
The pdf linked to this part of the [README](https://github.com/behave/behave/blob/7454670f4071fa3f75cbbc5b6263b4d3d6d39e35/README.rst?plain=1#L113) returns a 404 instead of the documentation. 
 
<img width="1680" alt="404 Error" src="https://github.com/behave/behave/assets/131725874/cc104a52-2466-40a6-8e64-818e47fa68a9">

**Comment by bittner** [comment]
Fixed via 81fac5ad8d4fbd37ba90e5847a1687c4de940d3a. Thanks for reporting! :+1:
