### ISSUE TITLE
Bad type-converter pattern: MatchWithError is turned into AmbiguousStep

### ISSUE THREAD

**Issue by omrischwarz** [behave/behave#1177]
Hi, all, I ran into this problem: 

On upgrading to Python 3.12 from 3.9 (because that's what my Mac does when I start using Homebrew), I started getting 
AmbiguousStep exceptions for steps that are not at all similar. Examples: 

`behave.step_registry.AmbiguousStep: @then('the Application report that the  part  id for WHATEVER  {string_id:d}') has already been defined in
  existing step @then('the Application reports that theBlah Blah  Status is {status:TypeBool}') 
`
(Apologies, but I  need to turn the code I used to run into this issue into something that doesn't leak info about my employer's ongoing product development work. )

The strings do not at all match. After tearing some of my hair out, I discovered that the step in add_step_definition that compares the two steps runs match() whiuch returns a MatchWithError object, and that the stored error is 

`NotImplementedError("Group names (e.g. (?P<name>) can cause failure, as they are not escaped properly: '\\Athe Application reports that theBlah Blah Status is (?P<status>(?i)True|(?i)False)\\Z'")}`

So, possible fixes: the code that translates `{status:TypeBool}` to ` (?P<status>(?i)True|(?i)False)\\Z'` needs to mark this string as a raw string, or use some other regex syntax. 

Or this code             elif existing.match(step_text):     # -- SIMPLISTIC
should be made less simplistic and turn MatchWithError to None. 

I don't know what's considered more Pythonic or better-behaved, so I figured I should ask here.

**Comment by jenisys** [comment]
Your problem seems to be related to using named-params in your regex-pattern for `TypeBool`. If I use your regex with named-param `status`, I get similar exception `NotImplementedError: Group names ...` with the test below.

Therefore, use the simple variant with unnamed-params/groups for your type-converter function (`parse_bool_good`) instead:

```python
from behave import register_type
import parse

@parse.with_pattern(r"true|false")
def parse_bool_good(text):
    text = text.strip()
    return text == "true"

register_type(TypeBool=parse_bool_good)
```

COMPLETE TEST:
```python
# -- FILE: test_issue1177.py
import parse
import pytest

def test_parse_expr():
    @parse.with_pattern(r"true|false")
    def parse_bool_good(text):
        text = text.strip()
        return text == "true"

    @parse.with_pattern(r"(?P<status>(?i)true|(?i)false)", regex_group_count=1)
    def parse_bool_bad(text):
        text = text.strip()
        return text == "true"

    parse_bool = parse_bool_bad  #< VARIATION-POINT: parse_bool_good
    parser = parse.Parser("Light is on: {answer:Bool}",
                          extra_types=dict(Bool=parse_bool))
    result = parser.parse("Light is on: true")
    assert result["answer"] == True
    result = parser.parse("Light is on: false")
    assert result["answer"] == False
    result = parser.parse("Light is on: __NO_MATCH__")
    assert result is None
```

**Comment by jenisys** [comment]
INTEGRATED AFTER: behave v1.2.7.dev5

NOTES:
`NotImplementedError` exception (from `parse` module) will now be raised when another step is added after the step that uses the BAD-TYPE-CONVERTER-PATTERN.
