### ISSUE TITLE
behave output with timestamp

### ISSUE THREAD

**Issue by cjabrantes** [behave/behave#1178]
Hi all,

we are running behave test in k8s, so while seen the logs from the pod works perfectly fine (right order) when  seen in Kibana the logs are out of order, something that makes the readability really hard.

To overcome this problem we would need to print a timestamp in each line, is that possible?

```
--logging-format
Specify custom format to print statements. Uses the same format as used by standard logging handlers. The default is “%(levelname)s:%(name)s:%(message)s”.
```

tried with:
`--logging-format "%(asctime)s- %(levelname)s:%(name)s:%(message)s"`

But seems to not make any effect, also tried with a few options of --format, but also no luck.

Any ideas?

Thanks,

**Comment by jenisys** [comment]
Stdout and logging is normally captured during test runs.
Both are normally only shown when a test (scenario) fails.
First, adapting the logging format is possible (there are tests that verify that).

You can try to use the following approaches:

* Use `behave --no-logcapture` or `behave --no-capture` (or both). If logging output appears, you should be able to verify that you can change the logging format.
* HINT: Logging/print in hooks is normally not captured.
* In the `before_all()` hook: Setup the logging system and then create a log record (to verify that the format/setup works).
* You can use logging filters to ensure that some log records are logged in any case (normally to a file).

SEE ALSO:
* [features/logging.setup_format.feature](https://github.com/behave/behave/blob/main/features/logging.setup_format.feature)
* [features/logging.setup_with_configfile.feature](https://github.com/behave/behave/blob/main/features/logging.setup_with_configfile.feature)
* [features/logging.no_capture.feature](https://github.com/behave/behave/blob/main/features/logging.no_capture.feature)
* [features/logcapture.feature](https://github.com/behave/behave/blob/main/features/logcapture.feature)
* [features/logcapture.filter.feature](https://github.com/behave/behave/blob/main/features/logcapture.filter.feature)

**Comment by jenisys** [comment]
NO REACTION: Question seems to be resolved/answered.
