### ISSUE TITLE
Support Background Steps with Placeholders for Scenario Outlines

### ISSUE THREAD

**Issue by hemendra0851** [behave/behave#1183]
Allow support for Background section to have access to the Scenario Outline's example section values.

It will help to reduce the common steps as usual but with an added benefit of having to not hard code parameters which can differ for each scenario.

**Comment by jenisys** [comment]
Mmh, I think what you want is actually the other way around:

* `ScenarioOutline` is the **template**.
* `ScenarioOutline` should apply the template mechanism to `Background` steps, too.

PROBLEM:

* That only works if you have only rather homogeneous `ScenarioOutlines` after a `Background`
* If the `ScenarioOutline` placeholders vary between `ScenarioOutlines`(s), it does not help
* If not only `ScenarioOutline`(s) but also `Scenario`(s) are used, this will not work

SUMMARY:

* Your proposal is an island solution for a problem that does not occur very often
* Your proposal has unsolvable problems

**Comment by jenisys** [comment]
INTEGRATED INTO: v1.2.7.dev6

* User must decide how useful that really is.

**Comment by lflfm** [comment]
We're just starting with behave and one of the first things we were missing was precisely this... any estimate as to when 1.2.7 will be released into pipy?
