### ISSUE TITLE
Behave release schedule 

### ISSUE THREAD

**Issue by Sullisters** [behave/behave#1187]
Good morning. I am wondering when behave 1.2.7.dev6 will be officially released. Thank you.

**Comment by jenisys** [comment]
This version will probably be released before end of July 2024.

**Comment by santiruizmazzo** [comment]
Hi, any updates on the release date?

**Comment by jenisys** [comment]
Next week. 
I currently plan to release it and plublish it to https://pypi.org .

**Comment by jenisys** [comment]
`behave v1.2.7.dev6` was published on pypi (as pre-release):

* https://pypi.org/project/behave/1.2.7.dev6/
