### ISSUE TITLE
Running Behave test with filestream instead of Feature File

### ISSUE THREAD

**Issue by av1roytman** [behave/behave#1190]
I am trying to run a behave test with a file stream instead of a feature file to have dynamic tests.

```py
from behave.__main__ import main as behave_main

def main():
    success = behave_main("tests/features")
    print(success)

if __name__ == '__main__':
    main()
```

Instead of passing in the file name, is there any way to edit the Configuration or any way to pass a stream with the contents of a feature file instead?

**Comment by jenisys** [comment]
Nope.

**Comment by av1roytman** [comment]
I want to incorporate the output of behave tests in a validation document that certain changes my code makes to aws services actually go through. So I want to run a lot of behave tests for a bunch of different services and right now I am dynamically generating feature files and placing them in the temp directory of an aws lambda, but wanted to see if I could just pass in the file contents without needing to save them to a file and then run behvave.

**Comment by jenisys** [comment]
Mmh, but that does not answer my real question:

* Why do you need trailing-withespace(s) in `step.text` line(s) ?

**Comment by jenisys** [comment]
The Gherkin parser supports only one Feature per (feature) file.

* That said the parser provides the necessary building blocks for doing what you want to do
* But you need your own test runner functionality because `behave` as cli-tool (and its test runner) are feature-file oriented.
