### ISSUE TITLE
Extension-Points for Formatters, Reporters

### ISSUE THREAD

**Issue by jenisys** [behave/behave#120]
The provision of own/external formatters or reporter needs to be improved.
There are various ways to address this:

  * Provide a plugin concept (solves: plugin loading and command-line option issues)
  * Provide class loading (which does not command-line option extension issues)
  * Provide and use setuptools registration hooks with behave
  * ...

**Comment by jenisys** [comment]
Formatter as a plugin is provided with the introduction of support for user-defined formatters (behave-1.2.5a1).

**Comment by bleargh45** [comment]
@jenisys ... while I see that you now support `--format=my.custom.format:MyFormatter` as a command line argument, I can't ever get this to work unless I copy my custom formatter **into** the same directory that the core Behave formatters get loaded from.

In the project I'm working on, we've got Python set up in a venv, _but_ we want to pull the custom formatter from the current directory.  I've tried various combinations of `PYTHONPATH=.` or `PYTHONPATH=$(pwd)`, but have not yet been able to get it to be able to load up my custom formatter.

I'm sure that whatever I'm missing is simple... anyone care to fill me on in what it is?

**Comment by jenisys** [comment]
@bleargh45 
The most common problem should be that your formatter cannot be imported. This can easily be checked by you in an interactive shell. By using the ``PYTHONPATH`` environment variable should be able to adapt it to your needs (as you tried it).

The requirements from a Formatter are:
* it must be possible to import the formatter module
* the custom formatter (class) must be derived from the ``behave.formatter.base.Formatter`` class

I have copied the original plain formatter into a custom module and was able to use it directly.

**QUESTIONS:** 
* Have you import related problems ?
* Or other problems when you use your formatter ?

See also: 
[features/formatter.user_defined.feature](https://github.com/behave/behave/blob/master/features/formatter.user_defined.feature)

**Comment by jaypatel512** [comment]
I am also running into a similar issue, when I am trying to reproduce the steps of https://github.com/behave/behave/blob/master/features/formatter.user_defined.feature#L21

It gives me this:

```
> behave -f behave_ext.formatter_one:SuperFormatter feature/paypal-payment.feature 
usage: behave [options] [ [DIR|FILE|FILE:LINE] ]+
behave: error: format=behave_ext.formatter_one:SuperFormatter is unknown
```

Tried adding .ini entry as shown here, but similar error.

**Comment by jaypatel512** [comment]
Never mind. Setting `PYTHONPATH=.` did the job.

**Comment by joshery420** [comment]
I'm trying to create a custom formatter, json.ptf, based on json.pretty and I have this issue as well. Right now it's just a copy of json.pretty with different class and file names and in a different directory. Unfortunately, setting PYTHONPATH isn't a valid solution in my case due to our project constraints. 

My verbose output looks like this:
```
Loading config defaults from "./behave.ini"
Using defaults:
 logging_format %(levelname)s:%(name)s:%(message)s
         format ['json.ptf']
          color False
   show_timings True
scenario_outline_annotation_schema {name} -- @{row.id} {examples.name}
       outfiles ['json.ptf.output']
 stderr_capture True
          stage None
       userdata {}
  steps_catalog False
        dry_run False
 stdout_capture True
    log_capture True
        summary True
more_formatters {'json.ptf': 'utilities.behave_ptf_formatter:PTFFormatter'}
   show_skipped True
  show_snippets True
 default_format pretty
  logging_level 20
          junit False
    show_source True

usage: behave [options] [ [DIR|FILE|FILE:LINE] ]+
behave: error: format=json.ptf is unknown
```
Tracing it through the Behave code it appears to be failing in load_module() at behave/importer.py::25, so it appears that it's definitely having trouble with the import for some reason.

However, when I run an interactive shell with Python it allows me to import just fine:
```
C:\Users\...\Documents\Git repos\my_repo>tools\Python27\python.exe
Python 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from utilities import behave_ptf_formatter
>>> behave_ptf_formatter
<module 'utilities.behave_ptf_formatter' from 'utilities\behave_ptf_formatter.py'>
>>>
```

Is there any other way to resolve this that you're aware of @jenisys?

**Comment by jenisys** [comment]
Import problems have normally 2 failure causes:

1. Python search path problem (PYTHONPATH, sys.path)
2. Module to Import has errors

The latter problem can be checked with pylint, for example. Note also that Python errors are sometimes only shown when you use the code and not when you import the module. 

There is also a Feature test for user-defined formatters. 

Ciao,
Jens Engel


Ciao,
Jens Engel
mailto:jens_engel@t-online.de

**Comment by joshery420** [comment]
Well I'll be.
I had a custom import in the formatter and that was failing to import properly.
Strange, since I thought working directory imports worked just fine, and the working directory at that time in the script is right, but oh well.

Resolved my problem by adding that directory path to sys.path programmatically in the formatter, which works for our edge case.

Thanks @jenisys!

**Comment by yucer** [comment]
Maybe is good to have a --reporter option also. Like [Mocha](http://bit.ly/1SQg2tG) 

By the way... the --junit can not be used with a custom reporter.  Once the --junit option is used, the --reporter value can be used as the junit reporter [here](http://bit.ly/1SQgqbu)

**Comment by jenisys** [comment]
Formatters are currently sufficient. You can easily convert a Formatter into Reporter. Therefore, you can already provided own "Reporters" as a Formatter.

**Comment by yucer** [comment]
So, there is an equivalent command line sentence to run the junit reporter with the **--format=my.custom.format:MyFormatter** ?

**Comment by jenisys** [comment]
That is not what I said. You need an generic Adapter class that adapts the Formatter Interface to the Reporter API (or vice versa). Therefore, this problem is easily solvable.

**Comment by jenisys** [comment]
**NOTE:** Currently only provided for user-defined formatters (for some time).

**HINT: COMMON USER MISTAKE**
``PYTHONPATH`` environment variable is not setup correctly to include the root-path for the new, user-defined formatter.

SEE ALSO:
* [features/formatter.user_defined.feature](https://github.com/behave/behave/blob/master/features/formatter.user_defined.feature)
