### ISSUE TITLE
 Async fixtures (redux)

### ISSUE THREAD

**Issue by rdpoor** [behave/behave#1211]
This is a follow-on from #832 

I have fixture code where both the setup and tear down are async functions.  I'm not sure how to create a fixture using this.  Consider this  pidgin code:
```python
class Console:
    def init(self. port, baud):
        ...

    async def start():
        print(f"Starting console port:{port} {baud}: baud...")
        ...

    async def stop():
        print("Shutting down console.")
        ...

@fixture
async def console(context, port, baud):        # can the fixture function itself be async?
    console = Console(port, baud)
    await console.start()
    context.add_cleanup(console.stop)          # cannot work - console.stop() is async
```
So:
* Can a fixture function itself be async?
* How do I specify the cleanup function if it is async?
* (Added) Where is `internal_cleanup_func ` even called?

**Comment by jenisys** [comment]
Async-functions (coroutines) are currently not supported as fixtures.

* Therefore, it you want to use the `Console` object to need to use the normal sync-to-async rendezvous functionality that is described in `asyncio`.
* For the `cleanup-function`, you probably best use a closure (as sync-function) that calls the coroutine(s) via sync-to-async mechanisms (reason: It will have access to the `console` object).

So if you need this functionality, provide a sane implementation that integrates into the existing infrastructure.

**Comment by rdpoor** [comment]
Thanks much.  I'm not yet familiar with the sync-to-asych mechanisms, but
will research.

In the meantime, I think I can emulate the functionality I need with
before_feature() and after_feature().

**Comment by rdpoor** [comment]
I read the response from @jenisys on a phone screen and didn't see the suggested code.  Just as well -- I subsequently came to understand the `asyncio.run(my_async_thunk)` idiom.  So that appears to be the way to go...

Closing this for now.  If a sane implementation suggests itself, I'll submit a PR.

**Comment by rdpoor** [comment]
Untested, but this feels like a cleaner pattern.  Assumes 
```
@fixture
def console(context, port, baud):
    console = Console(port, baud)

    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    try:
        loop.run_until_complete(console.start())
        yield
        loop.run_until_complete(console.stop())
    finally:
        loop.close()
```
If I understand correctly, if there are any coroutines inside the `yield`, they will be run in the fixture's event loop - that should pose no problem.  However, any async functions called outside of the fixture will be blocked until the fixture returns (i.e. asyncio reverts to the 'master' event loop).
