### ISSUE TITLE
How do I assure one event loop across all fixtures and @async_run_until_complete functions?

### ISSUE THREAD

**Issue by rdpoor** [behave/behave#1212]
### Context
I have a number of fixtures that require `asyncio await...` for setup.  At the same time, I have .step.py files that use the `@async_run_until_complete` decorator.  I don't know at runtime which fixture files get loaded.

### The question:
How do I create a single asyncio event loop that gets shared across all the fixtures and the .step functions?

#### Attempt `#1`:
I added this code to environment.py:

```python
def before_all(context):
    ....
    # Create an asyncio event loop for global use
    try:
       loop = asyncio.get_running_loop()  # use existing event loop
        logger.info(f'*** A using existing loop {loop}')
    except RuntimeError:
        loop = asyncio.new_event_loop()    # ... or create and use a new one
        asyncio.set_event_loop(loop)
        logger.info(f'*** A creating loop {context.event_loop}')
    ...
```

and for a .step function:

```python
@step(u'the this and that')
@async_run_until_complete
async def step_impl(context):
   await whatever()...
    ...
```
This fails with:

```
RuntimeError:  got Future <Future pending> attached to a different loop
```

#### attempt `#2`
Pass `@async_run_until_complete(loop=context.event_loop)` in step functions

I used the same startup code as in `attempt #1`, but modified the async_run_until_complete step function decorator:

```python
@step(u'the this and that')
@async_run_until_complete(loop=asyncio.get_running_loop())
async def step_impl(context):
   await whatever()...
    ...
```
This fails with:
```
RuntimeError: no running event loop
```

#### attempt `#3`
Save the newly created event loop in `context`"

I added this code to environment.py to save the event loop in `context.event_loop`:
```python
def before_all(context):
    ....
    # Create an asyncio event loop for global use
    try:
        context.event_loop = asyncio.get_running_loop()  # use existing event loop
        logger.info(f'*** A using existing loop {context.event_loop}')
    except RuntimeError:
        context.event_loop = asyncio.new_event_loop()    # ... or create and use a new one
        asyncio.set_event_loop(context.event_loop)
        logger.info(f'*** A creating loop {context.event_loop}')
    ...
```
and tried to access the event_loop via the context in the step functions:

```python
@step(u'the this and that')
@async_run_until_complete(loop=context.event_loop)
async def step_impl(context):
    ...
```

but of course that fails because `context` isn't available to the `async_run_until_completion` decorator.

**Comment by jenisys** [comment]
Calling `asyncio.get_running_loop()` outside the context of an async-function call (aka: coroutine) will always raise an `RuntimeError`. Therefore, trying this in the context of the `before_all()` hook or in the step-decorator is pointless (as described the `asyncio` documentation).

SOLUTION 0: Fixing your solution

* Specify attribute-name in the `Context` that contains the event-loop.

```python
@step(u'the this and that')
@async_run_until_complete(loop="event_loop")
async def step_impl(context):
    ...
```

SOLUTION 1: Provide an own asyncio event-loop

* Provide a function `example4me.get_event_loop()` in a Python module
* Optional: Set up the event loop in `before_all()` hook (if needed) in `features/environment.py`.
* Use it in the async-step decorator, like:

```python
# -- FILE: features/steps/async_steps_1.py

import asyncio
import example4me
from behave import step
from behave.api.async_step import async_run_until_complete

@step('I run an async step')
@async_run_until_complete(loop=example4me.get_event_loop())
async def step_run_async_step(ctx):
    await asyncio.sleep(0.1)
```

SOLUTION 2: Use an `AsyncContext` object (better solution)

```python
# -- FILE: features/environment.py
import example4me
from behave.api.async_step import use_or_create_async_context

def before_all(ctx):
    use_or_create_async_context(ctx)
    # OR: use_or_create_async_context(ctx, loop=example4me.get_event_loop())
```

```python
# -- FILE: features/steps/async_steps_2.py
import asyncio
from behave import step
from behave.api.async_step import async_run_until_complete

# -- HINT: Decorator uses AsyncContext object (and its event-loop) from the Context object.
@step('I run an async step')
@async_run_until_complete
async def step_run_async_step(ctx):
    await asyncio.sleep(0.1)
```

NOTE:

* Using the same async event-loop during the complete task-run may cause problems if tasks are not completed at the end of a scenario.
* BETTER: Ensure that all pending tasks are completed or cancelled at the end of a scenario (for example by using a fixture for that).
