### ISSUE TITLE
Doc Request: name a forum or best way to ask community for help

### ISSUE THREAD

**Issue by rdpoor** [behave/behave#1218]
As a developer, sometimes I need additional information not covered in the (excellent) documentation.

Therefore, I'd like to see an addendum to the [More Information about Behave](https://behave.readthedocs.io/en/stable/more_info.html#more-information-about-behave) section which names the preferred way to ask the community for help.

Is it in stackoverflow with a `behave-python` tag?  Etc...

**Comment by bittner** [comment]
There are a few badges at the top of the project README, which may interest you. I added Gitter years ago, but it's somewhat savaged. For what I know, GitHub discussions is @jenisys' preferred way of having community discussions.

We can add that to the docs via #1219, you may want to take a look if that's what you are after.
