### ISSUE TITLE
Behave is not loading settings from `

### ISSUE THREAD

**Issue by alexanderilyin** [behave/behave#1223]
I'm cleaning up top lever directory in repo and was trying to move Behave settings into `pyproject.toml`:

```diff
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -26,15 +26,6 @@ exclude = ".venv"
 extend-ignore = "E203"
 max-line-length = 120
 
+[tool.behave]
+tags = "~@wip"
+logging_level = "DEBUG"
+log_capture = true
+paths = ["features/"]
+
+[tool.behave.formatters]
+allure = "allure_behave.formatter:AllureFormatter"
```

For reasons yet unknown, settings were not read, which resulted in execution of `@wip` scenarios, which led to CI failures, regular INI configuration works as expected.

```ini
[behave]
tags = ~@wip
logging_level = DEBUG
log_capture = true
paths = features/

[behave.formatters]
allure = allure_behave.formatter:AllureFormatter
```

Behave version:

```
⬢ [Docker] ❯ poetry run behave --version
behave 1.2.6
```

**Comment by bittner** [comment]
The current stable version of Behave is quite old and doesn't support TOML yet. It's recommended that you install the latest development version ([1.2.7.dev6](https://pypi.org/project/behave/#history) at the time of this writing).
