### ISSUE TITLE
execute_step complains that steps must be unicode

### ISSUE THREAD

**Issue by floer32** [behave/behave#126]
When I try to run the following step:

``` plain
@given(u'I log in as a superuser')
def step_log_in_as_a_superuser(context):
    context.execute_steps("""
        given the following superusers exist
            | email         | password      |
            | admin@foo.bar | pass          |
        when I submit the following data
            | name          | value         |
            | username      | admin@foo.bar |
            | password      | pass          |
        then I see the word "Welcome"
    """)
```

I get the following error:

``` plain
Assertion Failed: Steps must be unicode.
```

Making the argument to `execute_step` a unicode string does the trick (`context.execute_steps(u"""foo""")`).

[The docs](http://pythonhosted.org/behave/api.html#calling-steps-from-other-steps) don't make this clear in the example provided.

**Comment by simi823** [comment]
Hi jenisys -- I saw the tutorial and was wondering how I can pass parameters to the sub-step. For example. I have this step definition:
@then(u'I search for the "{zipcode}" zip')
def step(context, zipcode):
    zip_input = context.browser.find_element_by_id('location')
    print zipcode
    zip_input.send_keys(zipcode)
    zip_input.send_keys(Keys.RETURN)
    url_path = "search/location-" + zipcode
    print url_path
    assert context.browser.find_element_by_css_selector('#inner-editor').text == zipcode
    assert url_path in context.browser.current_url

then I have another step definition that calls the one above, but I read a value from the csv file and call it like this:
context.execute_steps(u'''
                    then I search for the "{zipcode}" zip
                    ''').format(zipcode=zipcode)
zipcode is a value that was read from the csv file, so I want to pass it to the sub-step in {zipcode}, but it is passed as is, meaning as "{zipcode}" not the value. What have I missed?
