### ISSUE TITLE
JSONFormatter: Should use a slightly different output schema.

### ISSUE THREAD

**Issue by jenisys** [behave/behave#161]
RELATED TO: issue #60 

The following JSON output schema should be used to be compatible with _cucumber_.

```
USE-SCHEMA: 
[ { $feature1 }, ..., { $featureN } ]

INSTEAD OF CURRENT SCHEMA: 
{ "features": [ { $feature1 }, ..., { $featureN } ] }
```

IMPACT:
- behave.formatter.json
- behave.json_parser

RELATED:
- https://github.com/cucumber/gherkin/blob/master/features/json_formatter.feature
- https://github.com/cucumber/cucumber/blob/master/features/json_formatter.feature

**Comment by gittadesushil** [comment]
In case of error the .json file shows the error_message
"result": {
              "status": "failed",
              "duration": 0.001002311706543,
              "error_message": "Assertion Failed: the test case is failed"
            }

We want to show the success message inside result. How to capture message for success step?

**Comment by jenisys** [comment]
@gittadesushil 
What do you mean by "success message" ?
There is no "success message".
