### ISSUE TITLE
Using Behave with colored output under Windows in ansi-enabled console produces broken output

### ISSUE THREAD

**Issue by SchlauFuchs** [behave/behave#167]
### Environment:

Windows 7 64bit
Python 2.7.5 32bit and 64bit
Behave 1.2.2
Tried consoles:
- Cygwin bash
- ConEmu
- AnsiCon
### Scenario:

Under given environment run _behave_ with any features file producing output for passed,failed and missing steps once with **--color** option, once without. Compare output.
### Expected outcome:

both console outputs shows identical characters, just enhanced with colors when **--color** option is used
### Actual outcome:

**--color** output is missing many lines, some are duplicated, one time colored, other time plain console default color
The comment for missing stepcode is colored in both cases, where it shouldn't.
### Acceptance Criteria:

One or more of these:
- Fix it.
- If not a bug identify the color enabled console or python version not having this issue.

**Comment by mixxorz** [comment]
I know this issue has been open for almost two years, but the ansi colors effing out on Windows is really bugging me so I looked into it.

Here's a [line of code](https://github.com/behave/behave/blob/e5c74c540c62d8934d25ddcc434c5dfa15942978/behave/formatter/pretty.py#L150) that I found that might give clues as to why it's broken.

I've noticed that when I remove the +1 at the end of this line, the output magically fixes itself. Most of the time, anyway. I tested it on one of my projects and there's still one area where the output becomes overwritten. It happens on a feature with two scenarios.

I don't know why this is happening, but I wanted to show people where to look. It seems there's something wrong with how the step up lines are counted, but I can't be sure. I'll try to come up with a reproducible procedure soon, when I have more time. (I've already been poking the codebase for a few hours now lol.)

Cheers

**Comment by jenisys** [comment]
@mixxorz 
I will look at the suggested line, but on the first view I do not think how it should solve the problem.

The new ``coloarama`` version provides most of the functionality that is  needed for the pretty formatter (the older version did not support cursor-ups, etc.). In addition, it have a prototype that supports Windows coloring natively. Therefore, the problem should resolve itself in the near future.

**Comment by mixxorz** [comment]
Alright sweet! Thanks for all your hard work. :smiley: I'll be looking forward to that release then

**Comment by superlou** [comment]
Is this still an issue?

**Comment by jenisys** [comment]
Yes, but it is planned to fix it in the near future.

**Comment by superlou** [comment]
Is there a branch or PR we can help test?

**Comment by tobias-klein** [comment]
Any update on this since recently? I would also appreciate getting color support for windows!

**Comment by TAGC** [comment]
> Any update on this since recently? I would also appreciate getting color support for windows!

And my axe.

**Comment by jenisys** [comment]
@tobias-klein @TAGC 
Workaround was suggested above by @mixxorz (until feature is provided).
For example, use cygwin python with cywin shell.

**Comment by spyoungtech** [comment]
@mixxorz thanks for your comment. Making this change seems to fix the issue for me as well. Though, I haven't been able to reproduce the problem you described with the solution. My guess would be this happens when the line length and display width are particular values.

It appears changing this line was a proposed change as part of PR #115 -- which was resubmitted as PR #157 and has a different fix for the problem. Seems that could contain the the solution for the root problem.
