### ISSUE TITLE
multiple step directories under features/steps

### ISSUE THREAD

**Issue by schnupperboy** [behave/behave#169]
Is it possible to have multipe step directories under features/steps/ in order to improve the organization of code?

Like:
features/steps/stepdir_a
features/steps/stepdir_b

If yes, whats the best practice for achieving this?

**Comment by rsyring** [comment]
FWIW, I also like the directory structure proposed by @jenisys  and affirmed by @monkeez.

**Comment by frruit** [comment]
I tried the directory structure that @monkeez proposed and then i realized that behave didn't support it by default. Is it currently possible to teach behave to support this directory structure?

**Comment by davidharrigan** [comment]
+1 this would be helpful.

**Comment by jenisys** [comment]
@frruit Only when take care of that outside of ``behave``.
It is planned, but a "scope concept" (with own step registry and type registry per scope) which is needed to support this functionality in a clean way. Each step-directory exists in its own scope and can inherit parent-scopes (from its parent directories).

You write your own scoped runner as external script that performs a number of behave-subprocess calls, each subprocess call for a group of feature-arguments in same scope. This script can range from pretty dumb (statically configured scope-dirs) to more intelligent (discover where step-dirs=scope-dirs are).

**Comment by tejovanthn** [comment]
Hey, my feature structure is like this:
`DIRECTORY STRUCTURE:
+-- features/
     +-- steps/   (optional, common steps)
     +-- alice.features/
     |     +-- steps/   (specific steps for alice sub features, can use common steps)
     |     +-- *.feature
     |     +-- alice.environment.py
     +-- bob.features/
     |     +-- steps/
     |     +-- *.feature
     |     +-- bob.environment.py
     +-- *.feature`

When I run behave with `paths ['features/alice.features', 'features/bob.features']` it fails for shows `Not Implemented` for all `bob.features`, and vice versa if the order in paths is changed.

But when I run behave individually with a single path, it works perfectly.
Is there a way to do the same with the array type paths?

**Comment by jenisys** [comment]
@tejovanthn 
This question was already answered just before your question.

**Comment by hovi** [comment]
I am having same issue as @tejovanthn mentioned - when I run using one of either paths (or both of them), first one works fine, second one fails on missing steps. I don't use any common library and imports. In both features folders I have all steps required and as I mentioned if I run just that single path it works. What could be wrong? I am using behave-django to run everything, but don't think that related to this issue. My features structure:

```
./django.features
./django.features/environment.py
./django.features/registration.feature
./django.features/steps
./django.features/steps/registration.py
./django.features/steps/step_asserts.py
./django.features/subscription.feature
./selenium.features
./selenium.features/chant-submission.feature
./selenium.features/environment.py
./selenium.features/facebook-login.feature
./selenium.features/menu.feature
./selenium.features/speed.feature
./selenium.features/steps
./selenium.features/steps/chant-submission.py
./selenium.features/steps/selenium_basic.py
./selenium.features/steps/selenium_menu.py
./selenium.features/steps/selenium_speed.py
./selenium.features/steps/selenium_util.py
```

My behave.ini:
```
[behave]
junit = yes
junit_directory = reports/
paths=features/django.features
      features/selenium.features
```

**Comment by jenisys** [comment]
@hovi
The ``behave`` runner currently does not support "multiple scopes" (yet). The current solution is to split-up your work into two (or more) commands, one for "django.features/*" and the other for "selenium.features/*".  You normally use a build scripts that groups the args and perform the multiple behave calls (see [tasks/test.py](https://github.com/behave/behave/blob/master/tasks/test.py#L60) for example by using [invoke](http://docs.pyinvoke.org/en/latest/) as build system).

EXAMPLE:
```console
$ invoke test.behave --args='features/background.feature issue.features/issue0032.feature' 
.../python bin/behave -f progress  features/background.feature
features/background.feature  ........
1 feature passed, 0 failed, 0 skipped
8 scenarios passed, 0 failed, 0 skipped
36 steps passed, 0 failed, 0 skipped, 0 undefined
Took 0m1.430s
.../python bin/behave -f progress  issue.features/issue0032.feature
issue.features/issue0032.feature  .
1 feature passed, 0 failed, 0 skipped
1 scenario passed, 0 failed, 0 skipped
6 steps passed, 0 failed, 0 skipped, 0 undefined
Took 0m0.210s
```

**Comment by hovi** [comment]
Thanks for your reply.

So far best solution (and kinda similar to what you propose) I got is using stages + tags while having most of tests having tag of single (or sometimes both stages). So I run behave for each tag/stage pair. Only problem is, that I am using jenkins and test reporting so test results get overridden by last run so I see bunch of "skipped" tests in report, that were in fact ran in previous run. It is good enough for now, but can you think of way trough this?

**Comment by petrisorionel** [comment]
It is possible to have a structure like this, the steps from alice.features and bob.features will run if I run this command : "behave" or "behave --tags @"

`DIRECTORY STRUCTURE:
+-- features/
     +-- steps/   (optional, common steps)
        +-- alice.features/
         |     +-- steps/   (specific steps for alice sub features, can use common steps)
         |     +-- *.feature
        +-- bob.features/
             +-- steps/
             +-- *.feature
      +-- environment.py`

**Comment by hovi** [comment]
Don't think this solves my problem. I have multiple steps implementations already. My question was being able to execute all of them in one go. Meaning some features will be ran twice with both steps.

**Comment by xrg** [comment]
I'm afraid this is not pussible with current (1.2.6) implementation of `behave` . Reason is, all step definitions are loaded in a single, flat list. You cannot have two definitions of a wording and load either depending on the feature steps dir, some flag or anything.
I have long considered this limitation as a possible issue to tackle in 'behave-manners' or as a big patch to `behave` itself. Still, this would introduce some level of complexity (having to deal with "domains" of step definitions) that might confuse the average test developer.

**Comment by hovi** [comment]
Thanks for response. Yeah I understand what you mean, probably not worth doing. And not even sure if that's correct approach. Things should do one thing really well, without complications. Maybe I really should run 2 separate tests per each step group (or "platform") there should be way to generate clear different output for each of those. Now each output is as per all possible tests with tests from other "platform" being skipped.


My solution works in sense, that when there's problem I know about it and that's enough for my testing pipeline.

**Comment by xrg** [comment]
Back to this, I realize that there is more reason why behave should support multiple scopes (for step definitions). ...

**Comment by flyte** [comment]
> You cannot have two definitions of a wording and load either depending on the feature steps dir, some flag or anything.

That's what I came looking for actually. We currently have our tests running through the UI with selenium, but I'd like to implement ones which just use direct HTTP calls as well as/instead. I'd like to be able to keep the UI ones around and simply switch which step implementation is used based on a `@browser` tag or something. I'd make them both entirely separate, but there are a lot of steps which act on the database which I'd need to share between the two.

**Comment by jenisys** [comment]
@flyte 
Uses the stage concept and/or step-libraries.

SEE ALSO:
* [features/runner.use_stage_implementations.feature](https://github.com/behave/behave/blob/master/features/runner.use_stage_implementations.feature)
* [features/step.use_step_library.feature](https://github.com/behave/behave/blob/master/features/step.use_step_library.feature)

**Comment by StevenAFan** [comment]
> @hovi The `behave` runner currently does not support "multiple scopes" (yet). The current solution is to split-up your work into two (or more) commands, one for "django.features/_" and the other for "selenium.features/_". You normally use a build scripts that groups the args and perform the multiple behave calls (see [tasks/test.py](https://github.com/behave/behave/blob/master/tasks/test.py#L60) for example by using [invoke](http://docs.pyinvoke.org/en/latest/) as build system).
> 
> EXAMPLE:
> 
> ```
> $ invoke test.behave --args='features/background.feature issue.features/issue0032.feature' 
> .../python bin/behave -f progress  features/background.feature
> features/background.feature  ........
> 1 feature passed, 0 failed, 0 skipped
> 8 scenarios passed, 0 failed, 0 skipped
> 36 steps passed, 0 failed, 0 skipped, 0 undefined
> Took 0m1.430s
> .../python bin/behave -f progress  issue.features/issue0032.feature
> issue.features/issue0032.feature  .
> 1 feature passed, 0 failed, 0 skipped
> 1 scenario passed, 0 failed, 0 skipped
> 6 steps passed, 0 failed, 0 skipped, 0 undefined
> Took 0m0.210s
> ```

Is there any progress on "multiple scopes" for the behave runner/is it still planned?

**Comment by jenisys** [comment]
@StevenAFan @hovi
Yes, supporting test runs with multiple directories (as multiple scopes) is definitely planned for the future. Currently, running behave-tests from multiple co-located directories is a minor nuisance. The `behave` internal test discovery and test runner organisation must be reworked to support such a functionality.

But it can be solved by using a build-script that figures this out. The mentioned `invoke` task above is one example how to solve this (but it can be improved) until `behave` supports this functionality.

**Comment by StevenAFan** [comment]
@jenisys
Okay great, thank you for the update and guidance

**Comment by Marc-93** [comment]
Hi @jenisys, do you know if this functionality will be implemented? (multiple scopes without using invoke) and how we can track if the response is yes?

Thank you :D

**Comment by donihalim** [comment]
> It is possible to have a structure like this, the steps from alice.features and bob.features will run if I run this command : "behave" or "behave --tags @"
> 
> ```
> DIRECTORY STRUCTURE:
> +-- features/
>      +-- steps/   (optional, common steps)
>         +-- alice.features/
>          |     +-- steps/   (specific steps for alice sub features, can use common steps)
>          |     +-- *.feature
>         +-- bob.features/
>              +-- steps/
>              +-- *.feature
>       +-- environment.py
> ```

I was able to run all features inside `feature/steps/*` with project structure like this, but sadly now I cannot make it work again. Behave keep complaining about not implemented steps.

Here's my project structure:
`.
├── config
│   ├── config.json
│   └── config_reader.py
├── features
│   ├── environment.py
│   └── steps
│       └── dashboard
│           ├── login_dashboard.feature
│           └── steps
│               └── login_dashboard_steps.py
├── helpers
│   ├── driver_manager.py
│   └── selenium_manager.py
├── pages
│   ├── dashboard
│   │   ├── __pycache__
│   │   │   ├── dashboard_login_page.cpython-311.pyc
│   │   │   └── dashboard_main_page.cpython-311.pyc
│   │   ├── dashboard_login_page.py
│   │   └── dashboard_main_page.py
│   └── locators.py
└── requirements.txt`

failed with:
`@login
Feature: Login # features/steps/dashboard/login_dashboard.feature:2

  Scenario: Login with valid credentials          # features/steps/dashboard/login_dashboard.feature:4
    When Admin login with their valid credentials # None
Status.failed
    Then Admin should see dashboard main page     # None


Failing scenarios:
  features/steps/dashboard/login_dashboard.feature:4  Login with valid credentials

0 features passed, 1 failed, 0 skipped
0 scenarios passed, 1 failed, 0 skipped
0 steps passed, 0 failed, 0 skipped, 2 undefined
Took 0m0.000s

You can implement step definitions for undefined steps with these snippets:

@when(u'Admin login with their valid credentials')
def step_impl(context):
    raise NotImplementedError(u'STEP: When Admin login with their valid credentials')


@then(u'Admin should see dashboard main page')
def step_impl(context):
    raise NotImplementedError(u'STEP: Then Admin should see dashboard main page')`

**Comment by dron4ik86** [comment]
I've been working on a Behave project with a specific structure where step definitions are organized in subdirectories under the steps folder. To streamline the process of importing these step definitions, I wrote a Python script that automatically imports all .py files from these subdirectories. I believe this feature could be beneficial to be included in Behave.
```
Project folder/
│
├── features/
│   ├── api_1/
│   └── api_2/
│
├── lib/
│   ├── api_1/
│   └── api_2/
│
└── steps/
    ├── api_1_steps/
    │   └── api_1.py
    ├── api_2_steps/
    │   └── api_2.py
    └── __init__.py
```
My Solution:
```
# __init__.py
import glob
import os
import importlib.util


def import_steps_modules(directory):
    """
    Import all Python modules found in the specified directory's subdirectories.
    """
    for path in glob.glob(directory + '/*/*.py', recursive=True):
        name = os.path.splitext(os.path.basename(path))[0]
        if name != '__init__':
            spec = importlib.util.spec_from_file_location(name, path)
            module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(module)


import_steps_modules(os.path.dirname(__file__))
```
This script is placed in the __init__.py file inside the steps folder. It successfully imports all step definitions from the subdirectories, allowing for a more organized project structure.
I propose that Behave could include a feature to automatically import step definitions from subdirectories. This would allow users to organize their step definitions more effectively, especially in large projects.

**Comment by bittner** [comment]
@donihalim Your directory structure seems unnecessarily nested. Can't you keep your feature files and step implementation modules separate? See the [Behave docs](https://behave.readthedocs.io/en/latest/gherkin/) for configuration hints.

@dron4ik86 Why is the current implementation (default layout, otherwise configure as explained in the docs) not good enough? Isn't explicit better than implicit? – Can you elaborate on your thought process?

**Comment by dron4ik86** [comment]
@bittner 
 As your project grows, especially when testing numerous APIs with multiple endpoints, the number of step definition files can increase significantly. Manually adding each new step file to __init__.py can become tedious and error-prone. An automated import process scales better and reduces the risk of human error.

With many APIs, organizing step definitions into subfolders not only makes the project structure clearer but also aligns the test code organization closely with the API structure. This makes it easier for developers and testers to locate relevant tests and understand the project layout.
Suppose you have an API with the following endpoints:
User
```
GET /api/v1/users/collection/ids
GET /api/v1/users/{ids}
POST /api/v1/users/{ids}
```
Devices
```
GET /api/v1/devices/{id}/user
etc
```
You can organize your step definitions in a way that mirrors this API structure. Here's how the directory structure of your steps folder might look:
Project folder/
│
├── features/
│   ├── api_1/
│   │   └── [feature files for users]
│   ├── api_2/
│   │   └── [feature files for devices]
│
├── lib/
│   ├── users/
│   └── devices/
│
└── steps/
    ├── users_steps/
    │   └── users_steps.py
    ├── devices_steps/
    │   └── devices_steps.py
    └── __init__.py
    
The folder structure closely mirrors the API's structure, making it intuitive for developers and testers to find the step definitions related to a specific part of the API.

Testers can easily focus on a specific area of the API by navigating to the corresponding folder. This is particularly useful when working on large APIs with many endpoints.

New endpoints can be added without cluttering a single directory. For example, if a new Users API section is introduced, you can simply add a users subfolder with its respective step definition files.

Different teams or team members can work on different API sections without much overlap, reducing merge conflicts and improving parallel development.

It's easier to maintain and update tests since changes to a specific part of the API only affect a specific, easily identifiable subset of your test files.

**Comment by bittner** [comment]
That totally makes sense.

@dron4ik86 Would you want to take a look at the current implementation (I think this is the [loop in the runner class](https://github.com/behave/behave/blob/main/behave/runner.py#L852-L891)) and try to make the necessary adaptions to make the file collection behave like you need it?

We could then discuss the specific changes.

**Comment by bittner** [comment]
> is this fix deployed into the main branch?

I'm not 100% sure I understand the question.

You should branch off the `main` branch and prepare a PR to merge back into that branch again, yes!

Does that answer your question?

**Comment by dron4ik86** [comment]
@bittner, I'm currently attempting to run the Behave project locally. 
After installing all necessary packages, I encountered an error when trying to execute the `behave` command. The error is as follows:
`ImportError: cannot import name 'print_active_tags' from 'behave.tag_matcher'`
Could you please provide some documentation or guidance on how to correctly install and set up the project for local development? I want to ensure that I can effectively test and contribute to the project. Thank you!

**Comment by bittner** [comment]
> Could you please provide some documentation or guidance on how to correctly install and set up the project for local development?

It should be sufficient to use Tox, e.g.

```console
python -m pip install tox
python -m tox
```

For everything else please see the [Contributing chapter](https://behave.readthedocs.io/en/latest/contributing/) in the docs.

**Comment by dron4ik86** [comment]
> > Could you please provide some documentation or guidance on how to correctly install and set up the project for local development?
> 
> It should be sufficient to use Tox, e.g.
> 
> ```
> python -m pip install tox
> python -m tox
> ```
> 
> For everything else please see the [Contributing chapter](https://behave.readthedocs.io/en/latest/contributing/) in the docs.

Hi @bittner, 

I've made some changes to the `load_step_definitions` function. Unfortunately, I'm encountering issues when trying to create a pull request (`remote: Permission to behave/behave.git denied to dron4ik86.`) for these changes:

```
def load_step_definitions(self, extra_step_paths=None):
    if extra_step_paths is None:
        extra_step_paths = []

    steps_dir = os.path.join(self.base_dir, self.config.steps_dir)
    for root, dirs, files in os.walk(steps_dir):
        for file in files:
            if file.endswith('.py') and not file.startswith('__init__'):
                step_file = os.path.join(root, file)
                if os.path.isfile(step_file):  # Ensure it's a file
                    load_step_modules([root])  # Load from the directory
```

This change has been tested in my local environment and it works well for me.

**Comment by bittner** [comment]
> I'm encountering issues when trying to create a pr

You cannot push to a branch in the @behave GitHub organization when you're not an organization member. That's normal. – Please, push your changes on your personal fork of the behave project, then open the PR.

For more information see the [GitHub docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).

**Comment by dron4ik86** [comment]
Hi @bittner, please take a look
https://github.com/behave/behave/pull/1151

**Comment by digiDevemon** [comment]
I just wanted to check how this issue is going. I'm interested in the possibility of running Behave steps in separate folders. I've found several opinions from the past few years:

https://github.com/behave/behave/pull/600
https://github.com/behave/behave/pull/170

**Comment by dron4ik86** [comment]
> I just wanted to check how this issue is going. I'm interested in the possibility of running Behave steps in separate folders. I've found several opinions from the past few years:
> 
> #600 #170

https://github.com/behave/behave/pull/1210
