### ISSUE TITLE
Feature Request: Add flag to not print skipped features/scenarios

### ISSUE THREAD

**Issue by mitgr81** [behave/behave#192]
It would be quite nice to have the option of not printing the scenario steps if the scenario doesn't match the inclusion/exclusion criteria.

For instance:  I have a feature file that has 3 scenarios and I'm only running the first one by tag.  The output of the skipped scenarios 2 and 3 cover up any useful output in the scenario I do care about.

-w works pretty closely to this, though (at least in my experience) it doesn't colorize the output, and requires the @wip tag that a user may not want to put on the test they're running.

**Comment by lekhachandra** [comment]
hi, 
Im using behave 1.2.6. When running a particular scenario from  a feature file and when using --no-skipped option i see the skipped count in feature, scenario and steps. The option --no-skipped is not working.
