### ISSUE TITLE
Hooks processing should be more exception safe

### ISSUE THREAD

**Issue by jenisys** [behave/behave#197]
Currently it is up to the user in "environment.py" to ensure that no exceptions occur (by catching all). It would be better that hook errors (exceptions) would be caught and reported.

**Comment by jenisys** [comment]
INTEGRATED INTO: behave-1.2.6.dev0

**Comment by mec07** [comment]
This feature would be really good to have. Is there any chance that there will be a 1.2.6 release any time soon? Thanks. :)
