### ISSUE TITLE
integration with pdb

### ISSUE THREAD

**Issue by phamdt** [behave/behave#203]
it would be great if during a scenario and once an error occurs, behave allows you to drop into pdb for debugging. or it'd be just as good if behave could do this itself without pdb.

**Comment by AlexandreDecan** [comment]
The provided trick does not seem to work anymore. 
The execution is interrupted, but no interaction with pdb or ipdb can be done.

**Comment by masuka** [comment]
@AlexandreDecan 

You should use --no-capture run option with this solution, otherwise all ipdb stdout is captured by behave.

**Comment by AlexandreDecan** [comment]
Indeed, thank you!

**Comment by wren** [comment]
Is there a way to disable stdout capture in the `after_step` function? Some of my tests check the output, so they don't work with `--no-capture`.

**Comment by jenisys** [comment]
@wren 
I would try `ctx._runner.stop_capture()` .
