### ISSUE TITLE
Add ability to close (reset) Configuration() and Runner() in Behave API

### ISSUE THREAD

**Issue by ghost** [behave/behave#209]
Feature Request: I would like to see the ability to flush the Configuration and Runner objects so that using the Behave API in a loop doesn't cause old configs to interfere with new configs.

The issue I am facing is that when using the Behave API and looping through different tests which have the same step definition, the Confiugration() and Runner() object remain in memory so old steps are retained and conflict with new steps (ie; fill in first name on this page and that page).

The reason I am approaching it this way is that I am trying to leverage Fabric so that other QA members have an easy interface to execute their desired tests (or all which adds all of the test paths to the Fabric env variable).

Here is the loop that we are using (minus some config settings):

```
for test in env.tests:
    cfg = Configuration()
    ... cfg, etc.
    r = Runner(cfg)
    r.run()
```

Ideally at the end I could call something like cfg.close() or r.close() to close the respective behave classes and allow Configuration() or Runner(cfg) to be clean.

**Comment by jenisys** [comment]
CLOSE IT: Functionality is already provided in behave-1.2.6.dev0
``reset_runtime()`` function was provided.

**Comment by berndhahnebach** [comment]
I can not find reset_runtime() function in behave module. As I run into this propblem. How do I run this manually?
