### ISSUE TITLE
Add a way to add command line options to behave

### ISSUE THREAD

**Issue by mbhinder** [behave/behave#227]
Currently, I have a wrapper script to add command line options to behave and then call **main** as shown on http://stackoverflow.com/questions/22528535/passing-command-line-argument-to-python-behave Having an inbuilt way to support this would be nice.

**Comment by tomekwszelaki** [comment]
I understand this feature will not be available until the next version of behave? (I have version 1.2.4 and behave doesn't recognize the "--define" argument).

**Comment by jenisys** [comment]
@tomekwszelaki 
Correct (planned within January 2015, probably towards the end). 
If you need it now, you can install the GitHub repo or fork it ...

**Comment by tomekwszelaki** [comment]
ok, got it. Thanks :+1:
