### ISSUE TITLE
Provide output in HTML form

### ISSUE THREAD

**Issue by jeamland** [behave/behave#25]
This would be useful in CI environments.

**Comment by ShantanuMujumdar** [comment]
Thanks all for your efforts! By chance is the html report generation for behave working? I really need it.

**Comment by inrix-yi-gu** [comment]
+1

**Comment by gerosalesc** [comment]
+1

**Comment by Lucas-C** [comment]
Great idea, and awesome work so far !
Please go on :)

**Comment by andreybehalf** [comment]
Hi guys! 
I've written a little package which can help some of you guys ( It did helped me).
This package formats the behave json to cucumber json. Then you can use the new generated cucumber json to use any plugins available for cucumber to generate prettier reports. (I've used it with Cucumber-JVM Reporter - [https://wiki.jenkins-ci.org/display/JENKINS/Cucumber+Reports+Plugin](url))

The package can be found here: [https://github.com/behalfinc/b2c/](url)

Hope this will help to some of you, good luck!

**Comment by Lucas-C** [comment]
Interesting ! I wrote something similar: https://gist.github.com/Lucas-C/2ba14f253186e8df079219a3038e7d94
But ideally it should be included in behave

**Comment by andreybehalf** [comment]
True! I think it is really a good time for them to implement it, there is so many python user's and BDD getting so popular lately due to automation teams development around the globe.

**Comment by kaskelotti** [comment]
Hmmm... We have a JSON formatted output already, couldn't that be used to geneate HTML report by some templating?

**Comment by andreybehalf** [comment]
@kaskelotti Check this mate: https://www.npmjs.com/package/cucumber-html-report

**Comment by kaskelotti** [comment]
@andreybehalf thanks. If I understood correctly, using the tool requires one to first convert the behave json report to a cucumber one. Why not simply create mustache templates for behave directly?

**Comment by andreybehalf** [comment]
@kaskelotti True. Developing such thing requires much more work than just reformatting json files, but maybe some JS ninja can take up the glove and develop such script. 
Anyway as it said in previous comments, behave developers/contributors should consider implementing it as part of the library --format options.

**Comment by sseliverstov** [comment]
Guys, we just released beta version of allure behave formatter. It is already can build report over behave self-tests (v1.2.5). Welcome to taste it https://pypi.python.org/pypi/allure-behave/

**Comment by andreybehalf** [comment]
@sseliverstov Man that is really really cool, I actually managed to generate a report using your formatter and it worked perfectly. 
I do missing one thing and you might help me with that - context params - is there a way to pass the context params of a behave scenario to the allure report?

For an example - I have a test that verifies customer can login to my site - what I want is the info of the customer will be presented in the allure report. 
(In cucumber report I would use stdout to print this params and had access to them inside the exception window.)
Thanks!

**Comment by sseliverstov** [comment]
Now it is possible, just make attachment in hook. Also you can attach your data form any step. Enjoy;)

**Comment by eliezercazares** [comment]
Wow, this has been hanging around for years.

**Comment by ScarletMcLearn** [comment]
Still no update

**Comment by vishwas-tomar-telus** [comment]
Any update on this please..

**Comment by bittner** [comment]
Sorry for the long wait! The HTML formatter is now available under the @behave-contrib umbrella at https://github.com/behave-contrib/behave-html-formatter.

1. Install it using pip, e.g.
   ```console
   python3 -m pip install behave-html-formatter
   ```
2. Configure the formatter integration as described in the README, e.g.
   ```ini
   [behave.formatters]
   html = behave_html_formatter:HTMLFormatter
   ```
3. Use the `-f`/`--format` option with `behave`, e.g.
   ```console
   behave -f help
   behave -f html
   behave -f html -o behave-report.html
   ```

**Comment by swatantra15081986** [comment]
@bittner : can we add logs and steps in this report as well ?

**Comment by bittner** [comment]
Certainly! Please head over to [behave-contrib/behave-html-formatter](https://github.com/behave-contrib/behave-html-formatter) and open a PR with the changes you find useful. Or open an issue if you want to start slow.

**Comment by swatantrasrivastava** [comment]
I want to add logs and steps which is showing in CLI in the report, as these displays in Extent report.

**Comment by swatantra15081986** [comment]
Hi @bittner 
Can we attach  screenshots of failure cases in behave-html-formatter report ?

**Comment by bittner** [comment]
> Can we attach screenshots of failure cases in behave-html-formatter report ?

Have you tried?

The formatter can handle [videos](https://github.com/behave-contrib/behave-html-formatter/blob/master/behave_html_formatter/html.py#L469-L489), [images](https://github.com/behave-contrib/behave-html-formatter/blob/master/behave_html_formatter/html.py#L491-L505), [text](https://github.com/behave-contrib/behave-html-formatter/blob/master/behave_html_formatter/html.py#L507-L520) and [links](https://github.com/behave-contrib/behave-html-formatter/blob/master/behave_html_formatter/html.py#L522-L538) as embedded objects.

Please verify yourself whether the feature works for you as expected. If not, [go to the repository](https://github.com/behave-contrib/behave-html-formatter) and open an issue or submit a PR to improve the formatter implementation.

**Comment by swatantra15081986** [comment]
> @bittner : can we add logs and steps in this report as well ?



> Sorry for the long wait! The HTML formatter is now available under the @behave-contrib umbrella at https://github.com/behave-contrib/behave-html-formatter.
> 
>     1. Install it using pip, e.g.
>        ```
>        python3 -m pip install behave-html-formatter
>        ```
> 
>     2. Configure the formatter integration as described in the README, e.g.
>        ```ini
>        [behave.formatters]
>        html = behave_html_formatter:HTMLFormatter
>        ```
> 
>     3. Use the `-f`/`--format` option with `behave`, e.g.
>        ```
>        behave -f help
>        behave -f html
>        behave -f html -o behave-report.html
>        ```

Just like as, can we use html allure report formatter here as well and find attachment so that share to team ?

**Comment by bittner** [comment]
@swatantra15081986 Please try it out whether it does what you want. We don't maintain [allure-behave](https://pypi.org/project/allure-behave/). You have to open issues on their issue tracker to clarify questions and report bugs. They also have a Gitter chat.

**Comment by swatantra15081986** [comment]
@bittner : how can I go to there issue tracker ? 
Anyway thanks for your solution which you provided regarding save behave html formatter.At least we can share report to team

**Comment by bittner** [comment]
> how can I go to there issue tracker ?

https://github.com/behave-contrib/behave-html-formatter/issues

**Comment by vishwas-tomar-telus** [comment]
@bittner Is there any way to attach screenshot to failures ? If yes, please asssit

**Comment by swatantra15081986** [comment]
Also please assist how can we display the steps in each scenario in behave
html report, if possible .

Thanks

**Comment by bittner** [comment]
@vishwas-tomar-telus @swatantra15081986 Listen, maybe there is a misunderstanding.

This is a free software project. And this is an issue tracker. Not a personal support forum. Sorry if I'm rude but maybe it helps to explain. As in all free software projects, you're invited to:

1. Search the documentation for the topics you need help with. (Guess what, we have extensive documentation; the [table of contents](https://behave.readthedocs.io/en/latest/#contents) covers a lot of popular topics.)
2. Search the issue tracker, make sure this question hasn't been asked and answered before.
3. Search the Internet. (You'll likely get a StackOverflow answer or a blog post on your topic.)

## 7 seconds

I invested 7 seconds to open up the docs, searched and [found](https://behave.readthedocs.io/en/latest/tutorial.html#debug-on-error-in-case-of-step-failures) what you asked for. If you switch to the "latest" version (via the footer) you can also find content on yet unreleased features, such as the [context.attach](https://behave.readthedocs.io/en/latest/formatters.html#embedding-data-e-g-screenshots-in-reports) method on the `json` formatter.

I will now stop to explain the [behave-html-formatter](https://github.com/behave-contrib/behave-html-formatter) addon. You're obviously not trying hard enough. It has all been explained, I'm afraid.

**Comment by swatantra15081986** [comment]
@vishwas-tomar-telus :
Hi Viashwas,
Did you find the solution regarding :  -

- How to add steps in behave html formatter report near scenario
- How to add screenshot of Fail case in html formatter.
Please help. I am new in automation and code and learnt behave framework with python by Udemy.
