### ISSUE TITLE
Multiple contexts for the same steps and step implementation

### ISSUE THREAD

**Issue by mlopes** [behave/behave#279]
Hi, 

I would like to know if it's possible to run the same steps and implementation with different contexts (I.E. for example using different environment.py files to initialise different objects that behave in similar way, so that the steps can be ran against each of these different implementations)?

If this is not implemented, would this be something you'd be interested to have a pull request against?

Cheers,
Marco Lopes

/cc @nnevala

**Comment by mlopes** [comment]
Actually maybe a better solution seems to be something similar to contexts in Behat:

http://docs.behat.org/en/latest/guides/5.suites.html#suite-contexts

**Comment by jenisys** [comment]
**SOLUTION 1: Use multiple feature directories**
Currently, you would put your steps into a step library.
This makes it easy to reuse the steps in multiple feature directories.

**SOLUTION 2: Use userdata to setup your environment/context** (different flavors in multiple test runs)
Use "userdata" to configure your context to your needs in the "environment.py" file
(normally in the before_all() hook).

**SEE ALSO:**
  * [step.use_step_library.feature](https://github.com/behave/behave/blob/master/features/step.use_step_library.feature)
  * [userdata.feature](https://github.com/behave/behave/blob/master/features/userdata.feature)

**Comment by mlopes** [comment]
Solutions 2 looks like it should do it :)
Solution 1 does not really apply to this specific user case. 

Thanks for the help :)
