### ISSUE TITLE
using behave with saucelabs selenium for multiple browsers testing not with UnitTest

### ISSUE THREAD

**Issue by simi823** [behave/behave#284]
I have behave setup and running remotely on saucelabs with a single call to remote webdriver, but I have not been able to run something for multiple browsers. I have seen the examples of using unitTest, but I don't want to create unit tests because I have everything set up with behave .feature and steps in .py files. Is there a way to use a list like this, for example:
PLATFORMS = [
    {
        "platform": "Windows 8.1",
        "browserName": "Internet Explorer",
        "version": "11",
        "deviceName": None,
        "name": "TestMultiple for Autos on Windows 8.1 IE",
    },
    {
        "platform": "OS X 10.10",
        "browserName": "chrome",
        "version": "37",
        "deviceName": None,
        "name": "TestMultiple for Autos on OSX Chrome",
    },
    {
        "platform": "OS X 10.9",
        "browserName": "iPhone",
        "version": "7.1",
        "deviceName": None,
        "name": "TestMultiple for Autos on iPhone 7.1",
    },
    {
        "platform": "Linux",
        "browserName": "Android",
        "version": "4.4",
        "deviceName": "Google Nexus 7 HD Emulator",
        "name": "TestMultiple for Autos on Android Nexus Chrome",
    },
]

That will pass in the desired capabilities for each platform to the remote webdriver:
        sauce_url = "http://%s:%s@ondemand.saucelabs.com:80/wd/hub"
        context.browser = webdriver.Remote(
            desired_capabilities=desired_capabilities,
            command_executor=sauce_url % (USERNAME, ACCESS_KEY)
        )

The issue is that with each one that is open, it fails because it is not closed. It opens all of them when I create a loop, and then runs the feature tests in the last browser, failing the others.

**Comment by jenisys** [comment]
**POINT 1**: Accessing the data (and its details)
behave-1.2.5a1 (on Github repository) has the **userdata** feature. Look at "New and Noteworthy" in the docs directory or look at "features/userdata.feature".
NOTE: In older versions, you could also load the data in the "before_all()" hook in "environment.py".

**POINT 2**: Iterating over all your "test variants" (browsers and platform matrix in your data) 
This is normally a build-script problem (make, fabric, …).
You can also do it in behave by using "behave4cmd0" and a two stage approach:
* You have one feature (or feature directory tree) for one test variant
* You have a "macro feature" file (or several ones)

```!gherkin
# -- FILE: macro.features/run_all_test_variants.feature
Feature: Run tests for all test variants
   Scenario Outline: Run tests for test variant: <platform>-<browser>
      Given I use the current directory as working directory
      When I run "behave -D platform='<platform>' -D browser='<browser>' features/"
      Then it should pass
      
      Examples:
         | platform    | browser |
         | Windows 8.1 | InternetExplorer |
         | OSX 10.10   | Chrome |
```

Note that test problems are simpler to diagnose when you use the build-script approach. For behave, you will to rely on a log file for each test run (test variant).

SEE ALSO:
  * [behave/more.features/formatter.json.validate_output.feature](https://github.com/behave/behave/blob/master/more.features/formatter.json.validate_output.feature)

**Comment by simi823** [comment]
Hi jenisys -- These may be good solutions, thank you. I have behave 1.2.4, so I would need to implement point 2, however, I don't know about the macro feature you mention. Do I just create a feature that will run the variants? Where does the -D option get defined? I understanding how to create the scenario outline, and have a few other options to include the the Examples table, but I don't understand how behave will create this? Should I just use the step definitions you suggest listed in behave4cmd0?

**Comment by jenisys** [comment]
The referenced feature file above ("behave/more.features/formatter.json.validate_output.feature") implements the same concept as described in POINT 2. With behave-1.2.4 you don't have user data (therefore no -D option). Therefore, you must use environment variables (or something similar) to transport the variant information to your ``before_all()`` hook when behave is called.

```gherkin
# -- FILE: macro.features/run_all_test_variants2.feature
Feature:
  Scenario Outline:
     Given I use the current directory as working directory
     And I set the environment variable "TEST_PLATFORM" to "<platform>"
     And I set the environment variable "TEST_BROWSER" to "<browser>"
      When I run "behave features/"
      Then it should pass

      Examples:
         | platform    | browser |
         | Windows 8.1 | InternetExplorer |
         | OSX 10.10   | Chrome |     
```

NOTE:
Probably the simplest way is to run the following command line in a shell:

```sh
# -- WORKSPACE = Checked out behave repository
# REQUIRES: jsonschema >= 1.3.0
# SEE ALSO: bin/jsonschema_validate.py
behave more.features/formatter.json.validate_output.feature
# behave runs the Scenario (Outline) which starts a new behave subprocess to run the specific test variant (as specified by the Scenario). 
```

**Comment by simi823** [comment]
Thank you again jenisys -- As I am a newbie with all of this, I hope you don't mind if I ask for more clarification. I will review all the files you suggest and see if I can figure it out. So I will create a more.features directory where I will have the run_all_test_variants2.feature file. I will still create the step definitions for this feature file in steps directory? I have to pip install jsonschema (the version you list). What is the formatter.jscon.validate_output.feature? Do I create that as well? I have to also pip install behave4cmd0? I get the idea, but I am still unclear on how all of this works together.

**Comment by jenisys** [comment]
Currently, ``behave4cmd0`` is bundled with ``behave``. Therefore, clone the git repository or use a source distribution (sdist) of behave, Copy the "behave4cmd0" subdirectory tree to your project and ensure that it is in your Python search path (environment variable ``PYTHONPATH``before python start or manipulate ``sys.path`` in Python).
