### ISSUE TITLE
Behave fails when Handling Large data sets

### ISSUE THREAD

**Issue by tomatobrown** [behave/behave#285]
If I have a test case that has 500,000 rows of data Behave will return:

Exception MemoryError:
Traceback (most recent call last):
  File "C:\Python27\Scripts\behave-script.py", line 9, in <module>
    load_entry_point('behave==1.2.5a1', 'console_scripts', 'behave')()
  File "build\bdist.win32\egg\behave\__main__.py", line 111, in main
  File "build\bdist.win32\egg\behave\runner.py", line 678, in run
  File "build\bdist.win32\egg\behave\runner.py", line 699, in run_with_paths
  File "build\bdist.win32\egg\behave\runner.py", line 503, in run_model
  File "build\bdist.win32\egg\behave\reporter\summary.py", line 58, in feature
  File "build\bdist.win32\egg\behave\model.py", line 395, in duration
  File "build\bdist.win32\egg\behave\model.py", line 1164, in duration
  File "build\bdist.win32\egg\behave\model.py", line 1138, in scenarios
MemoryError

I'm assuming that this is because behind the scenes Behave is putting this whole table into 1 giant table rather than just adding it to some data object on each Scenerio.  It would be nice if there was a solution to this problem

**Comment by jenisys** [comment]
Well, what should I say. It is always possible to use up all memory. That you can do with behave: so what. You probably need to change your "domain language" in your steps. Using 500000 rows in a behave table is not sane, IMHO. Move the complexity into your step implementation and not into behave. This should scale better.

NOTE:
Currently, I see no way (in behave) how to solve this problem (and I actually don't see a need for it).
A feature file is completely parsed and converted into a feature model (object). This happens for all feature files. A step as Model object can only be executed when all its parts are available. The (complete) Table object is one such part.

You are the domain expert. You know your testing domain the best.
And nobody forces you to use behave's Table object to pull all your rows in it.
Read the data from a file with a step implementation or …

**Comment by jenisys** [comment]
Mmh, I looked over your traceback again. There is something fishy.
Your problem occurs when the summary information is collected (during duration computation) and the end of the test run. In a ScenarioOutline, it tries to build its scenarios from examples. This should have been done during running the Feature/ScenarioOutline.

Try something out, replace the following line and run the test again:
```python
# -- FILE: behave/model.py:1164  (in ScenarioOutline.duration())
   # -- ORIG: for scenario in self.scenarios:
   for scenario in self._scenarios:
```
Have you a ScenarioOutline that is disabled during the test run (via tags, etc.), with this large table ?

**Comment by tomatobrown** [comment]
I believe that I did have another Scenerio with a large table disable when getting the error above.  I made the changes that you requested and changed the files names of any features with large amounts  of data so that behave will ignore them.  Ends up that about 350 rows run for me then I get the following error...

Traceback (most recent call last):
  File "C:\Python27\Scripts\behave-script.py", line 9, in <module>
    load_entry_point('behave==1.2.5a1', 'console_scripts', 'behave')()
  File "build\bdist.win32\egg\behave\__main__.py", line 125, in main
  File "C:\Python27\lib\encodings\__init__.py", line 100, in search_function
    level=0)
MemoryError

I think I'm just going to end up using pandas or something inside of a step

**Comment by tomatobrown** [comment]
So...I made the changes and am running the test on the 20,000 row, but I think that this probably isn't the right approach anyway.  I think that we can close this issue.  I brought it up more as a question and I wonder if it would be better to have some sort of forum or place were we can share approaches on handling things.  In the meantime this issue can be closed I think.  Thanks

**Comment by jenisys** [comment]
[PROJECT_INFO.rst](https://github.com/behave/behave/blob/master/PROJECT_INFO.rst) mentions the link to the Google news group. Maybe that is a better place for discussions.

**Comment by jenisys** [comment]
Note that I modified the ScenarioOutline class to avoid building the Scenarios from its (ScenarioOutline) template if that is not needed (integrated into behave-1.2.5a1).
