### ISSUE TITLE
Behave 1.2.5 doesn't start on python 2.x

### ISSUE THREAD

**Issue by tomekwszelaki** [behave/behave#287]
My python version is 2.7.6 and I have upgraded behave to 1.2.5 today. On behave 1.2.4 everything ran correctly, but after upgrading I started getting two errors. First is a syntax error on print statements (as if behave didn't recognize python 2.x syntax) 
```
Exception SyntaxError: invalid syntax (environment.py, line 9)
Traceback (most recent call last):
  File "c:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\Python27\Scripts\behave.exe\__main__.py", line 9, in <module>
  File "c:\Python27\lib\site-packages\behave\__main__.py", line 109, in main
    failed = runner.run()
  File "c:\Python27\lib\site-packages\behave\runner.py", line 672, in run
    return self.run_with_paths()
  File "c:\Python27\lib\site-packages\behave\runner.py", line 677, in run_with_p
aths
    self.load_hooks()
  File "c:\Python27\lib\site-packages\behave\runner.py", line 631, in load_hooks

    exec_file(hooks_path, self.hooks)
  File "c:\Python27\lib\site-packages\behave\runner.py", line 303, in exec_file
    code = compile(f.read(), filename2, 'exec')
  File "features\environment.py", line 9
    print "before feature:", feature.name
                          ^
SyntaxError: invalid syntax
```

After commenting prints - I get it to run only to get the following:  `ImportError: cannot import name range`

Here's the full stacktrace:
```
Exception ImportError: cannot import name range
Traceback (most recent call last):
  File "c:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\Python27\Scripts\behave.exe\__main__.py", line 9, in <module>
  File "c:\Python27\lib\site-packages\behave\__main__.py", line 109, in main
    failed = runner.run()
  File "c:\Python27\lib\site-packages\behave\runner.py", line 672, in run
    return self.run_with_paths()
  File "c:\Python27\lib\site-packages\behave\runner.py", line 692, in run_with_p
aths
    self.formatters = make_formatters(self.config, stream_openers)
  File "c:\Python27\lib\site-packages\behave\formatter\_registry.py", line 131,
in make_formatters
    formatter_class = select_formatter_class(name)
  File "c:\Python27\lib\site-packages\behave\formatter\_registry.py", line 92, i
n select_formatter_class
    return _formatter_registry[formatter_name]
  File "c:\Python27\lib\site-packages\behave\importer.py", line 92, in __getitem
__
    value = value.__get__()
  File "c:\Python27\lib\site-packages\behave\importer.py", line 53, in __get__
    module = load_module(self.module_name)
  File "c:\Python27\lib\site-packages\behave\importer.py", line 26, in load_modu
le
    return importlib.import_module(module_name)
  File "c:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\Python27\lib\site-packages\behave\formatter\pretty.py", line 10, in <
module>
    from six.moves import range
ImportError: cannot import name range
```

**Comment by jgarcows** [comment]
I also encountered this problem and it is a test breaker.  Currently we are forcing version 1.2.4, but it would obviously be better to be able to use the latest.

**Comment by jenisys** [comment]
Problem 1 is a syntax error in your own "feature/environment.py". Python2.7 expects ```print(…)``` instead of ```print …```.

Problem 2 looks like either an older version of six is installed or may be none at all.
I am using Python 2.7 (but seldom on Windows) with six 1.8.0 (and six 1.9.0 in various virtual environments). Try to update six or reinstall six. 

See also the Travis test builds that verify that behave installs fine, runs its tests without problems with the supported Python versions.

**Comment by jgarcows** [comment]
Problem 1 is not a syntax error.  In Python 2.7, print is a statement and not a function and `print ...` is perfectly valid.  Even the input/output documentation shows print being used in this way: https://docs.python.org/2/tutorial/inputoutput.html

**Comment by jenisys** [comment]
Yeah, but behave uses internally "from __future__ import print_function" to achieve cross-version compatibility. For example, ``behave.runner`` module uses this idiom. This module loads the steps and the environment file. Probably, therefore these files may be affected.

**Comment by jenisys** [comment]
By the way, I just installed behave-1.2.5 (again) in a clean environment. Then I downloaded the sdist from PyPI to run the tests. Everything runs fine (as expected; on MACOSX, Linux=Travis).

But normally don't use print statements (or function calls) in my environment or steps files (except when I intend to do that).

**Comment by jgarcows** [comment]
Shouldn't behave be able to keep 3.0 compatibility without using `from __future__ import print_funciton` since in 2.7, even without that import, `print(...)` is valid syntax.  The import just forces that syntax, which can break environment or steps files that use the other syntax in 2.7.

**Comment by jenisys** [comment]
This currently just an assumption (and was not the intention).

**Comment by jenisys** [comment]
I verified that the print_function usage is injected into the environment file and steps.

QUICKFIX: Apply to your code base
```python
pip install modernize
python-modernize --fix=libmodernize.fixes.fix_print my_directory/          # Shows only changes
python-modernize --fix=libmodernize.fixes.fix_print --write my_directory/  # Applies changes
```

**Comment by jenisys** [comment]
Probably-mistaken marker relates to the "six" problem.
Print function problem is split-up and moved to #288 (as it is understood now).

**Comment by tomekwszelaki** [comment]
I'm using windows, let me set up a clean env and try again. I'll let you know if it works there.

**Comment by tomekwszelaki** [comment]
Ok, after a few hours of installing and removing python I think I got to the bottom of it. The problem is the requests library (unfortunatelly I have to use a very old version of requests - 0.13.6 - because the rest of the components use that version). When I try to import requests in a steps.py file or a library included in that steps.py file depends on the requests module I get the "ImportError: cannot import name range". I'll try investigating more to see exactly what causes this error.

**Comment by tomatobrown** [comment]
I have behave 1.2.5 running with requests without any issues, id recommend updating your version of requests

**Comment by tomekwszelaki** [comment]
Yup, I checked with the latest version of requests (2.5.1) and it works fine. But like I said I have to use the same version the rest of the components use so to be able to update requests I'd have to refactor all components that depend on it....
