### ISSUE TITLE
Documentation does not specify help channels

### ISSUE THREAD

**Issue by thedrow** [behave/behave#289]
behave has no IRC channel (or a Gitter channel), no mailing list and the documentation does not specify where to get help.

**Comment by jenisys** [comment]
SEE: [PROJECT_INFO.rst](https://github.com/behave/behave/blob/master/PROJECT_INFO.rst)

It contains all the necessary information.
A google group is set up, but not very actively used up to now.

**Comment by jenisys** [comment]
Gitter channel created.
See README.rst

**Comment by thedrow** [comment]
Thanks :)
