### ISSUE TITLE
behave-1.2.5 wheel package from pypi has problems with namespace packages

### ISSUE THREAD

**Issue by mp-pbn** [behave/behave#294]
In a project which uses two namespace packages, where one namespace package imports something
from the other namespace package the behave 1.2.5 wheel package from pypi has problems if the first
module is imported within the behave step implementation.

Using the sdist package from pypi works. It is unclear to me what the underlying problem is, especially as the sdist package works. Perhaps a problem on how the wheel package was build?

I created a repo demonstrating the issue: https://github.com/mp-pbn/behave-1.2.5-wheel-error

In there is a script named ./reproducer.sh, which accepts a commandline parameter 'wheel' or 'sdist,
creates a virtualenv and installs the two namespace packages, one with pip -e for installing it in developer mode. Only the wheel behave version shows an error and fails with an ImportError!

**Comment by jenisys** [comment]
I will looked into it (quick look, more probably next weekend). But on the first description, it looks more a wheel problem, not a behave problem. The "behave wheel" was build with "python setup.py bdist_wheel".

Note that I get the same problem independent with the ZIP package and the wheel package:

```sh
$ behave demo/features/
File "/.../.env/lib/python2.7/site-packages/behave/runner.py", line 304, in exec_file
    exec(code, globals, locals)
  File "demo/features/steps/steps.py", line 1, in <module>
    from ns.bar.demo import hello
  File "build/bdist.macosx-10.6-intel/egg/ns/bar/demo.py", line 1, in <module>
ImportError: No module named xyz.other
```

I also get this error when I install "ipython" in the virtual environment and try to import "from ns.bar.demo import hello" within "ipython" (completely independent of ``behave``). Therefore, I currently do not believe that this is a behave issue. It looks to me more like a python namespace problem (or related to eggs, …).

**Comment by jenisys** [comment]
Probably related to: [pip install --editable and pip install clash for namespace packages](https://github.com/pypa/pip/issues/3) 
(pypa/pip issue #3)

**Comment by jenisys** [comment]
But note that I also have the import problem from above when I install the 2nd package normally with pip.

**Comment by mp-pbn** [comment]
If I install the second package normally (without -e), the import works as expected, both with the wheel and sdist package.

```python
t430s:~/src/ax/behave-1.2.5-wheel-error (master)$ source .env/bin/activate
(.env)pbnt430s:~/src/ax/behave-1.2.5-wheel-error (master)$ python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ns.bar.demo
>>> dir(ns)
['__doc__', '__name__', '__path__', 'bar', 'xyz']
```

Nevertheless, I agree with your reasoning that this is related to https://github.com/pypa/pip/issues/3 
and not caused by behave.
