### ISSUE TITLE
Support running background job once per feature

### ISSUE THREAD

**Issue by domenkozar** [behave/behave#295]
So currently I have implemented a tag for the Feature that runs a set of steps once per Feature (as a fixture setup).

Previously I was using `Background`, but that runs the steps for each Scenario.

Not sure how to really implement this, maybe add `Setup` which is the same as `Background`, but it's ran before Feature, not each Scenario?

**Comment by iElectric** [comment]
https://github.com/behave/behave/pull/281 does make the implementation a bit easier, but it's still not simple.

**Comment by JMVM** [comment]
One solution could be include a new specific class in model.py based on Background -but different one in order to maintain the current Background behavior- and forcing one execution per feature in the same model.py. 

So since Background is added for each scenario, for example, the execution could be forced easily adding that new class only for the first scenario.

Note that for adding that new class, it would be necessary to modify formatter, etc.

**Comment by jenisys** [comment]
Use scenarios with tags ``@setup`` to achieve the same effect. This works especially when you use "file locations". The Scenario with tag ``@setup`` is automatically executed in a feature if a file location is provided.

**Comment by esciara** [comment]
Great stuff! Could not find this documented anywhere... Would it be worth doing so? Any more details we should know about?

**Comment by mbarakaja** [comment]
@jenisys, The problem that I see using **`@setup`** with file location is that the scenario's steps run in another context, making impossible to share data with the next scenario context. Which differs of the Background behavior that appends steps into a scenario in the same context.

I think that a functionality to skip the background in a scenario is desired.

**Comment by jenisys** [comment]
@mbarakaja 
Then provide a pull-request with a clean implementation and I will consider it.

**Comment by aidan** [comment]
Hi, I've updated #281 and I think this sort of hook should do what @domenkozar is after?
```
def before_background(context, background):
    if context.done_setup:
        background.skip()
        return
   do_setup(context)
   context.done_setup = True  
```
