### ISSUE TITLE
Don't skip failed steps

### ISSUE THREAD

**Issue by jonblack** [behave/behave#299]
When a step fails the test for the given feature stops. I propose adding an option to continue processing the remaining steps in the feature, regardless of the failure.

I have a feature with many steps. If the test fails on the first step, I fix the problem and run it again, then I noticed that the next step has failed. This becomes a problem when the feature takes a while to run. It'd be nice to have the option to see all failures in the first pass.

**Comment by jenisys** [comment]
I will not add the suggested functionality to behave. I know that the desired functionality is sometimes nice or needed, but in most cases the correlated failures (after the first one) may cause more confusion than really help you.

**BUT:**
I may add the required small functionality (if something is required), to allow you as a behave user to adapt behave test project in such a way that it has your functionality.

See the [delayed-assert](http://pythontesting.net/strategy/delayed-assert/) article where something similar is done in a Python unit test framework. You should be able to do something similar in the ``after_scenario()`` hook.

There may be some problems ahead, it you try to change the "passed" status of already run steps of the current scenario. The selected formatters have already seen the status of the step...

Think about what you need and then we discuss it. 
A working prototype may be helpful to check if all things are considered.

**Comment by jenisys** [comment]
INTEGRATED INTO: behave-1.2.6.dev0
Basic functionality was provided.

See: [features/runner.continue_after_failed_step.feature](https://github.com/behave/behave/blob/master/features/runner.continue_after_failed_step.feature)

**Comment by lsiden** [comment]
I just installed behave from the master branch and tried inserting the line

    @runner.continue_after_failed_step

immediately before a scenario with a failing step, 
but it still skips subsequent steps.

For the record,
    
    $ behave --version
    behave 1.2.6.dev0

Am I missing something?

**Comment by subbro** [comment]
Hi,
I have one issue. Say i have 5 steps and 3rd step fails, I see that the next two steps are marked as Passed in first run and if it fails again at 3rd step then the next steps are skipped in 2nd run.
I have the autoretry logic in before_scenario() to run twice

**Comment by jenisys** [comment]
So you have one or more flaky test(s).
You are welcome. Fix it and continue.

**Comment by subbro** [comment]
> So you have one or more flaky test(s).
> You are welcome. Fix it and continue.

I think they are fine, i see this issue while I have a retry logic
