### ISSUE TITLE
UnicodeDecodeError when read steps.py

### ISSUE THREAD

**Issue by sanjiely** [behave/behave#300]
Hi,
   Python3, behave 1.2.5.
   My system is running on Chinese GBK character set. But you know we make our files as utf-8 format generally, and so do I. I set my step file api1_steps.py as utf-8, and entered some Chinese characters in.
    Run "behave", but I got UnicodeDecodeError, just like this:
  File "D:\workspace\env_110\lib\site-packages\behave\runner.py", line 304, in e
xec_file
    code = compile(f.read(), filename2, 'exec')
UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 510: illegal
multibyte sequence

I change the code in runner.py in behave, from:
with open(filename) as f:
to:
with open(filename, encoding='utf-8') as f:

Then "behave" works normally.

Maybe we need support a configuration item about file format from behave.ini, or have a smart way to open files with different character sets.

Thanks.
Yong

**Comment by jenisys** [comment]
Thanks for the analysis. I fix it in the next few days and think about the encoding option that you suggested.

**Comment by PyDeq** [comment]
I hit this too... I don't get the error since the byte in my step file can be decoded by accident. But my ```locale.getpreferredencoding()``` (```'cp1250'```) (which is used by the ```open``` function) does not match the encoding of the file (```'utf-8'```) so the decoded character is different which results in ```behave``` being not able to find a correct step implementation:

```
You can implement step definitions for undefined steps with these snippets:

@given(u'I enter the address �http://127.0.0.1:8080/� into a browser')
def step_impl(context):
    raise NotImplementedError(u'STEP: Given I enter the address �http://127.0.0.1:8080/� into a browser')
```

The ```, encoding='utf-8'``` fix works in my case too. But ```, 'rb'``` works too and I think it's even better because you don't need to implement an encoding option then.

**Comment by sanjiely** [comment]
Yes, I agree with PyDeq: an option 'rb' for open file is enough.
Thanks.

**Comment by kangxu** [comment]
Behave 1.2.5 and python 2.x
Edit feature files with ‘utf-8’  format and entered some Chinese characters in feature file like:
......
  then I click the link 北京
.....
And in steps.py, parse steps and invoke WebDriver.find_element_by_link_text api like:

@step(u'I click the link "{text}"')
def click_element_by_link(context, text):
    element = context.web.driver.find_element_by_link_text(text)
    ......

Run "behave" , I got UnicodeDecodeError. But in Python interactive interpreter, invoke api like
WebDriver.find_element_by_link_text("北京"), it works normally. It seems that there're some problem about encode/decode in behave. Any thought ?

**Comment by sanjiely** [comment]
@kangxu
After I applied 'rb' option as above, my Behave of Python3 worked well on Chinese characters.
Since you are working on python2.x, you have to take some time on these errors like "UnicodeDecodeError". And I don't want to recall my experience on resolving the encoding issues on Python2 any more.
^_^

You know, on Python3 even we could use like this:
北京=1
print(北京)

Just FYI. This is one of my feature file (filled with Chinese characters) and working well on Python3:


# -- FILE: features/acceptance_create_cs.feature

Feature: CS新建接警单

Background: 初始化工作
    Given 初始化数据库
      And 接警员登录指挥中心客户端


Scenario Outline: CS客户端新建不同警情级别的接警单
"""CS客户端创建新接警单
"""
    Given 准备不同警情级别的接警单，警情级别:<警情级别>
     When 创建接警单    
     Then 创建接警单应该成功
      And 接警单应该推送给接警席

	Examples:
    | 警情级别    |    备注                   |
    |     1    |   一般警情            |
    |     2    |   紧急警情            |
    |     3    |   危急警情            |
    
    
    
    
Scenario: CS客户端新建接警单
"""CS客户端创建新接警单，使用指定的参数
"""
    Given 准备指定参数的接警单
    |name     |value         |
    |BJNR     | 研究院发生了持刀抢劫，请速度处理|
    |YHSFZ    |330600199909100010|
     When 创建接警单
     Then 创建接警单应该成功
      And 接警单应该推送给接警席

**Comment by jenisys** [comment]
Should be fixed, related to fix for #361.

**Comment by jenisys** [comment]
INTEGRATED INTO: behave-1.2.6.dev0

**Comment by ypochien** [comment]
Thanks for your support.
