### ISSUE TITLE
Support escaped-pipe in Gherkin table cell value

### ISSUE THREAD

**Issue by madazone** [behave/behave#302]
I have a pipe included in a table cell value. I tried to use backslash but it doesnt' work.

|value1|value2\|test|value3|

but I got the following parserror Exception

**Comment by jenisys** [comment]
This case is currently not supported by the parser. Therefore, try to avoid it (if that is possible for you). I will look into it.

**Comment by madazone** [comment]
Thanks for the reply. 

For now, I cannot avoid it. So, all help is welcome!

**Comment by jenisys** [comment]
The problem is mentioned in various places. 
The Gherkin project has an example for it: [escaped_pipes.feature](https://github.com/cucumber/gherkin/blob/master/features/escaped_pipes.feature)
But in the newer Gherkin3 project, I have seen no tests for it (Gherkin grammar ends with TableRow as token).

**Comment by tshead2** [comment]
+1 for escaped pipes.

**Comment by oblalex** [comment]
+1.

Was happy to see this _can_ be done in [an answer at stackoverflow](http://stackoverflow.com/a/12960857/1159558), but got disappointed this is not supported by _behave_.

**Comment by connorsml** [comment]
I need this now, so here is my attempt at it. It works for me:

https://github.com/behave/behave/pull/360

**Comment by jenisys** [comment]
INTEGRATED INTO: behave-1.2.6.dev0

**Comment by donato** [comment]
👍 
Love this, any idea when next tagged release will be out?

**Comment by jenisys** [comment]
@donato 
Soon.

**Comment by donato** [comment]
Awesome, let me know if you need help testing/releasing anything specific.
