### ISSUE TITLE
Can't find step definitions

### ISSUE THREAD

**Issue by kitanata** [behave/behave#311]
Hello:

Sometimes I'm finding that with multiple step files that Behave cannot pick up step definitions. Even if I copy and paste a stub of the step definition into the step file it will pick up some step definitions but not others. If I take that same step definition and place it into a different section of the same file, or into a different step file then behave is able to detect it. It appears to be really intermittent and random.

I am running behave 1.2.5 with Python 3.4.2

**Comment by jenisys** [comment]
Provide an example. 
Are you sure that your step files are valid and can be imported ?
Another issue may be that your step definitions are overlaying regular expressions, meaning: the first matching regular expression is used. But it general, behave complains if step definitions are ambiguous.

Use for example the following line to verify that all steps are found:
```console
$ behave --dry-run -f steps features/
GIVEN STEP DEFINITIONS[39]:
  Given I setup the current values for active tags with                    # features/steps/behave_active_tags_steps.py:35
  Given the behave context has a parameter "{param_name}"                  # features/steps/behave_context_steps.py:37
  Given the behave context does not have a parameter "{param_name}"        # features/steps/behave_context_steps.py:41
  Given the behave context contains                                        # features/steps/behave_context_steps.py:65
  Given a behave model with                                                # features/steps/behave_model_tag_logic_steps.py:55
  ...
```

**Comment by kitanata** [comment]
@jenisys 

I am absolutely positive the step definitions are there and can be imported. I am copying and pasting the stub (generated by missing step definitions) into a step file that already has "found" step definitions that are used within the feature file.

If I run 'behave --dry-run -f steps features' as above it find steps within the step file, but not the newly added step. The output stub of the missing step is the same as the one in the file. 

If you would like I can add you to a private repo on a branch where the error is occurring for you to investigate further. I am pretty sure that this is a heisenbug and highly intermittent. I normally would provide you with a small project that this is occurring, but the issue appears randomly.

**Comment by kitanata** [comment]
@jenisys I've added you to our private repo where this is occuring.

The line in question is here:

https://github.com/kitanata/collidr/blob/behave-heisenbug/server/features/steps/invites.py#L53

You are welcome to checkout/clone the project. If you cd to the server directory then run the following: `virtualenv -p python3 env'` and `source env/bin/activate` and `pip install -r requirements.txt` then run behave you will see the bug in action.

**Comment by kitanata** [comment]
I'm stepping through the behave source code. And I've noticed something interesting within runner.py where the step file is loaded.

runner.py(304)exec_file()
-> exec(code, globals, locals)
...
(Pdb) globals['step_when_user_requests_number_of_invites'] //a "missing" step definition (different branch)
<sure.AssertionBuilder object at 0x1079b4ac8>

@gabrielfalcao's sure library is stepping on the step definition somehow. That function is fully implemented. I do not know why sure is interfering here.

**Comment by kitanata** [comment]
Ok so. I've confirmed that once sure is removed as the assertion library of choice and we just use normal asserts that everything is fine and behave has no trouble finding the step definitions. 

**It is pretty clear that [sure](https://github.com/gabrielfalcao/sure) DOES NOT play nicely with behave.**
