### ISSUE TITLE
can't write summary to file

### ISSUE THREAD

**Issue by alisener** [behave/behave#312]
if you set the config item outfiles to a file, summary is still written to stdout not the file. 

SummaryReporter has a hard coded "stdout"  as output stream

class SummaryReporter(Reporter):
    show_failed_scenarios = True
    output_stream_name = "stdout"

**Comment by jenisys** [comment]
Output filename option is for formatters and not reporters.
But you can pipe the output into your desired output file ;-)

```console
behave features > xxx
```

will write the summary (and the formatter output) into an the file "xxx".

**Comment by alisener** [comment]
Even that doesn't work, since it is reopening the hard-coded sdtout with a streamopener.

**Comment by jenisys** [comment]
Well, it works for me. Otherwise I would have not suggested it.

What platform are you using (Windows, Linux, MACOSX, …) ?

**Comment by alisener** [comment]
well, after I updated the 1.2.5, it works for me too.

I was hoping to mail the results.log file via email in the after_all() hook, but i guess I have to write a script that sends the email after it finishes the whole run.

**Comment by jenisys** [comment]
@alisener 
A cheap solution would be to keep track of processed features in ``before_feature()`` or ``after_feature()`` hook and feed to your own Summary-Reporter object in the ``after_all()`` hook.

As alternative you could also select SummaryReporter object from the ``context.config.reporters`` list. Then you have direct access to its information. Note that depending on the configuration, a SummaryReporter object may not be always available.
