### ISSUE TITLE
--no-logcapture  --no-capture parameters do not work when using --format pretty

### ISSUE THREAD

**Issue by madazone** [behave/behave#313]
For instance when you used the pretty format with --no-logcapture, the log is still captured.

**Comment by jenisys** [comment]
**Why do you think that disabling the capture mechanism does not work ?**

**BACKGROUND:**
Capture mechanism works that way that behave captures the output/log-records, but only shows them when the scenario fails (as compressed information what might have caused the failing test).
If you disable the capture and write (or log) to stdout, etc. the results show up immediately and in all cases even when the tests pass.

Log-capture and output-capture are independent of the formatter that is used.

**SEE ALSO:**
* [features/logging.no_capture.feature](https://github.com/behave/behave/blob/master/features/logging.no_capture.feature)
* features/capture_*.feature
* features/logcapture.*.feature
