### ISSUE TITLE
Don't skip future steps after failed test

### ISSUE THREAD

**Issue by Puciek** [behave/behave#314]
It would be extremely helpful to be able to continue running tests even if one step fails.
We are running quite a few tests that already use the power of Scenario outline, and in those steps we look at various data fetched for given example data. As it is if any of the fields within one example doesn't fetch test then the other fields are not even checked. Which is annoying, because in our case steps check for independent parts of an object (they are not related nor depend on each other).
While this usually could be solved by breaking down and moving each step into separate test, this is just not suitable in this case, as fetching all this data is done at the same time (we can't change that) so this would make the tests a lot more expensive and time-consuming to run.

**Comment by jenisys** [comment]
See issue #299 .

The problematic was already discussed there.
It is currently not planned to add such a feature in behave for the reasons that are described in issue above.


* Try to use the **delayed-assert** functionality.
* Rewrite your steps to use one "check-step" with a table that contains all the checks
  (tables can be annotated, columns added or cell values can be replaced => "features/explorative_testing.with_table.feature").

NOTES:
If you use **delayed-assert** approach, check that all / most formatters are behaving "normally".

**Comment by jenisys** [comment]
INTEGRATED INTO: behave-1.2.6.dev0

**Comment by Renegade85** [comment]
Do I understand it right, that this feature applies to a complete scenario?

Is it possible to select just a single step?

Given voltage is at "nominal"
And communication is "running"
When I set voltage to "undervoltage"
Then the system state shall be "fault"
And the error flag shall be "0xXXXX"

In case of communication channel failure, I would like to skip the complete scenario (which is default behavior). But in case of Then/And, I would like to continue in case of failure.

Is this possible with this feature or I need to find a different hack? :-)

Thanks
