### ISSUE TITLE
Update comparison with other tools web page (Lettuce has support for tags)

### ISSUE THREAD

**Issue by ramiabughazaleh** [behave/behave#317]
Hi.

Thank you for behave.

I noticed that the web page https://pythonhosted.org/behave/comparison.html is outdated.
The latest version of Lettuce (v0.2.20) has support for tags.

```cmd
> pip install lettuce
> lettuce -h
```
One of the command line options:
```
-t TAGS, --tag=TAGS   Tells lettuce to run the specified tags only; can be
                        used multiple times to define more tags(prefixing tags
                        with "-" will exclude them and prefixing with "~" will
                        match approximate words)
```

Thank you.

**Comment by jenisys** [comment]
Thanks, I will update the information accordingly.

**Comment by ramiabughazaleh** [comment]
Maybe another thing to note is that the latest version of Lettuce (v0.2.20) does not yet support Python 3.4.
See the open issue here: https://github.com/gabrielfalcao/lettuce/issues/476

Thank you.

**Comment by jenisys** [comment]
INTEGRATED INTO: behave-1.2.6.dev0
