### ISSUE TITLE
it doesn't work for logging without the argument "configfile" to config.setup_logging 

### ISSUE THREAD

**Issue by sanjiely** [behave/behave#318]
Python3, behave 1.2.5.
I can't initialize my logging system by the following code:
def before_all(context):  
    context.config.setup_logging(level=logging.DEBUG,
                    format='%(asctime)s %(filename)s[line:%(lineno)d] %(levelname)s %(message)s',
                    datefmt='%a, %d %b %Y %H:%M:%S',
                    filename='d:/testt.log',
                    filemode='a')

The code as below is working:
def before_all(context):
    context.config.setup_logging(configfile='features/logging.ini')

The root cause is the call to basicConfig in setup_logging will never work really. Because all valid code  in the function basicConfi are under the statement "if len(root.handlers) == 0:", but the root logger has handlers in it already.

**Comment by jenisys** [comment]
I will look into it.
But the reason for this normally that the logging subsystem was already set up or used (which triggers basicConfig() calls in some cases).

**Comment by sanjiely** [comment]
Update:
It's not a bug.
Because the default configuration item "log_capture" has already initialized the logging subsystem, the basicConfig of logging is not working any more.
If I set  "log_capture" as "no", then I could set up the logging subsystem by:
def before_all(context):
         context.config.setup_logging(level=logging.DEBUG,
              format='%(asctime)s %(filename)s[line:%(lineno)d] %(levelname)s %(message)s',
              datefmt='%a, %d %b %Y %H:%M:%S',
              filename='d:/testt.log',
              filemode='a')

Sorry for bothering.

Another question (Document issue):
The value of boolean type should list on this document page: http://pythonhosted.org/behave/behave.html
For example, the readers will confuse which value (true or false) each line stands for like below:
log_capture – boolean
Don’t capture logging. Logging configuration will be left intact.
log_capture – boolean
Capture logging. All logging during a step will be captured and displayed in the event of a failure. This is the default behaviour. This switch is used to override a configuration file setting.

**Comment by jenisys** [comment]
@sanjiely 
The documentation for the command-line options and configuration-file are automatically generated. It refers to the configuration param (dest) and I agree that the output can be improved. The first entry describes the case for ``--log-capture`` (stores true) and the second for ``--no-log-capture`` (stores false).

**Comment by vit1251** [comment]
@jenisys you write wrong "--no-log-capture" is unrecognized argument.

**Comment by jenisys** [comment]
@vit1251 Sorry, I misspelled it. It should be:
```shell
behave --no-logcapture features/
```
Thanks, I correct it in the thread above.
