### ISSUE TITLE
behave 1.2.5: installing via pip with wheel in python 2.6 does not install all libraries

### ISSUE THREAD

**Issue by jearls** [behave/behave#319]
As seen in the following transcript, when using `pip` to install behave in Python 2.6 on CentOS 5.5, not all the prerequisite libraries get installed - specifically, `argparse` and `importlib` are missing even to get a version output.

    $ sudo -H python26 get-pip.py
    …
    $ sudo -H pip install behave
    …
    Successfully installed behave-1.2.5 enum34-1.0.4 ordereddict-1.1 parse-1.6.6 parse-type-0.3.4 six-1.9.0
    $ behave --version
    …
    ImportError: No module named argparse
    $ sudo -H pip install argparse
    …
    Successfully installed argparse-1.3.0
    $ behave --version
    …
    ImportError: No module named importlib
    $ sudo -H pip install importlib
    …
    Successfully installed importlib-1.0.3
    $ behave --version
    behave 1.2.5

**Comment by jenisys** [comment]
I assume that is a problem with pip support for Python2.6 and not behave.
behave specifies this requirement and installs it (as expected).
This can be easily verified when you use "easy_install" or use "python setup.py" for behave.

* Are you sure that the pip script that you use really uses python2.6? 
  (there exist problems when multiple python versions are installed)
* Which pip version are you using ?

```sh
$ pip --version
pip 6.x.y from /.../lib/python2.6/site-packages/pip-6.x.y-py2.6.egg
```

**Comment by darkfoxprime** [comment]
$ which pip
    /usr/bin/pip
    $ head -1 `which pip`
    #!/usr/bin/python26
    $ pip --version
    pip 6.1.1 from /usr/lib/python2.6/site-packages (python 2.6)
    $ /usr/bin/python26 -V
    Python 2.6.5

**Comment by darkfoxprime** [comment]
It looks like `pypi`'s database for behave does not include the `argparse` and `importlib` requirements:

    $ pip show behave | grep Requires
    Requires: parse, parse-type, six

And the snippet from https://pypi.python.org/pypi/behave :

> Requires Distributions
> > six
> > parse-type (>=0.3.4)
> > parse (>=1.6.3)

**Comment by jenisys** [comment]
Yeah, sure. If you deduce this information with Python2.7 that is correct. 
You forgot the Location info that indicates which Python version was used.

```sh
$ pip show behave
Location: /.../.venv_py26/lib/python2.6/site-packages/behave-1.2.5-py2.6.egg
Requires: parse, parse-type, six, argparse, importlib, ordereddict
```
and with Python 2.7:

```sh
$ pip show behave
Location: /.../python2.7/site-packages
Requires: parse, parse-type, six
```

**Comment by darkfoxprime** [comment]
$ pip show behave | sed -e 's;^;    ;'
    ---
    Metadata-Version: 2.0
    Name: behave
    Version: 1.2.5
    Summary: behave is behaviour-driven development, Python style
    Home-page: http://github.com/behave/behave
    Author: Benno Rice, Richard Jones and Jens Engel
    Author-email: behave-users@googlegroups.com
    License: BSD
    Location: /usr/lib/python2.6/site-packages
    Requires: parse, parse-type, six

**Comment by jenisys** [comment]
Ok, but you are showing me the results of your, potential corrupted pip database.
Setup a virtual environment with virtualenv and install behave there.
Or use ``pip uninstall behave`` (sometimes 2x is needed) and retry to install it. 
In addition, use "easy_install" to install it and checks if the results differ.

Which pip and setuptools versions are you using ?

**Comment by darkfoxprime** [comment]
I reported the pip version earlier -

    $ pip --version
    pip 6.1.1 from /usr/lib/python2.6/site-packages (python 2.6)

The setuptools is whatever version pip installed:

    $ pip show setuptools | sed -e 's;^;    ;'
    ---
    Metadata-Version: 2.0
    Name: setuptools
    Version: 15.2
    Summary: Easily download, build, install, upgrade, and uninstall Python packages
    Home-page: https://bitbucket.org/pypa/setuptools
    Author: Python Packaging Authority
    Author-email: distutils-sig@python.org
    License: PSF or ZPL
    Location: /usr/lib/python2.6/site-packages
    Requires:

I've never used virtualenv, so I can't show it there.  I will go ahead and remove python 2.6 entirely and re-install everything.

**Comment by darkfoxprime** [comment]
Okay, I completely removed the `python26` rpms, everything in `/usr/lib*/python2.6/site-packages`, and the `.cache/pip` directory.  I then re-installed `python26`, ran the `get-pip.py` script again (using `python26`), then installed behave:

    # python26 get-pip.py
      Downloading pip-6.1.1-py2.py3-none-any.whl (1.1MB)

        0% |*                               | 4.1kB 23.8MB/s eta 0:00:01
    ...
        100% |********************************| 1.1MB 283kB/s
    Collecting setuptools
      Downloading setuptools-15.2-py2.py3-none-any.whl (501kB)

        0% |*                               | 4.1kB 24.5MB/s eta 0:00:01
    ...
        100% |********************************| 503kB 671kB/s
    Installing collected packages: pip, setuptools
    Successfully installed pip-6.1.1 setuptools-15.2

    # pip install behave
    Collecting behave
      Downloading behave-1.2.5-py2.py3-none-any.whl (109kB)

        3% |**                              | 4.1kB 23.8MB/s eta 0:00:01
    ...
        100% |********************************| 110kB 1.5MB/s
    Collecting parse>=1.6.3 (from behave)
      Downloading parse-1.6.6-py2-none-any.whl
    Collecting parse-type>=0.3.4 (from behave)
      Downloading parse_type-0.3.4.tar.gz (62kB)

        6% |**                              | 4.1kB 31.5MB/s eta 0:00:01
    ...
        100% |********************************| 65kB 2.0MB/s
    Collecting six (from behave)
      Downloading six-1.9.0-py2.py3-none-any.whl
    Collecting enum34 (from parse-type>=0.3.4->behave)
      Downloading enum34-1.0.4.tar.gz
    Collecting ordereddict (from enum34->parse-type>=0.3.4->behave)
      Downloading ordereddict-1.1.tar.gz
    Installing collected packages: parse, six, ordereddict, enum34, parse-type, behave
      Running setup.py install for ordereddict
      Running setup.py install for enum34
      Running setup.py install for parse-type
    Successfully installed behave-1.2.5 enum34-1.0.4 ordereddict-1.1 parse-1.6.6 parse-type-0.3.4 six-1.9.0
    # pip show behave | sed -e 's;^;    ;'
    ---
    Metadata-Version: 2.0
    Name: behave
    Version: 1.2.5
    Summary: behave is behaviour-driven development, Python style
    Home-page: http://github.com/behave/behave
    Author: Benno Rice, Richard Jones and Jens Engel
    Author-email: behave-users@googlegroups.com
    License: BSD
    Location: /usr/lib/python2.6/site-packages
    Requires: parse, parse-type, six

**Comment by jenisys** [comment]
Mmh, I think I have an idea. Try "pip install --no-use-wheel -U behave".

The behave-*.whl was built using Python2.7. Therefore, it only stores the requirements that are needed for Python2.7 (and not the requirements that are needed for other Python versions).

You cannot add requirements to packages that are part of the standard library. Pip will complain when you do that. Therefore, the setup-logic includes these packages only when use the Python2.6 interpreter.

RESUMEE:
As long as you are using Python2.6, do not use the wheel.

**Comment by darkfoxprime** [comment]
I discovered this a bit ago as well.  If this is the case, the installation procedure in the documentation should be updated to reflect that.

Thanks,
- Johnson

**Comment by jenisys** [comment]
The ``wheel`` package supports to store this python-version specific requirements in its metadata (similar like the functionality for requirement-files in the newer pip versions). Therefore, there is a solution to this.

**Comment by jenisys** [comment]
INTEGRATED INTO: behave-1.2.6.dev0
