### ISSUE TITLE
Exception stack trace should contain the full path to source code files that raised the exception

### ISSUE THREAD

**Issue by ramiabughazaleh** [behave/behave#322]
Behave 1.2.5
Windows 7 x64 SP1

If I have a feature file and steps file, but there is a syntax error in the steps file for example, the stack trace does not contain the full path of the steps file.

If the output did have the full path of the file, it allows the PyCharm IDE, for example, to convert it into a hyperlink so that when it is clicked, the file will automatically open in the editor with the cursor at the specific line where the exception was raised.

```
Feature: Feature name # tests.feature:1
  Feature description
  Scenario: Scenario1          # tests.feature:6
    Given test name # steps\steps.py:6
      Traceback (most recent call last):
        File "C:\Python27\lib\site-packages\behave\model.py", line 1456, in run
          match.run(runner.context)
        File "C:\Python27\lib\site-packages\behave\model.py", line 1903, in run
          self.func(context, *args, **kwargs)
        File "steps\steps.py", line 8, in step_impl
          sytax_error
      NameError: global name 'sytax_error' is not defined



Failing scenarios:
  tests.feature:6  Scenario1

0 features passed, 1 failed, 0 skipped
0 scenarios passed, 1 failed, 0 skipped
0 steps passed, 1 failed, 0 skipped, 0 undefined
Took 0m0.000s
[Finished in 0.2s with exit code 1]
```

In this case, I expected:
```
File "steps\steps.py", line 8, in step_impl
```
to actually read:
```
File "C:\test\steps\steps.py", line 8, in step_impl
```
For example.

Thank you.

**Comment by mixxorz** [comment]
I don't understand. That's normal Python behavior.

![screenshot 2015-06-25 13 47 26](https://cloud.githubusercontent.com/assets/3102758/8348045/d0ca1936-1b40-11e5-8708-0dc15ef94a72.png)

**Comment by ramiabughazaleh** [comment]
Running on Windows 7 SP1 x64 and Python 2 and 3:
```
Traceback (most recent call last):
  File "C:\Users\rami.abughazaleh\Documents\testing.py", line 2, in <module>
    raise Exception('test')
Exception: test
```

**Comment by jenisys** [comment]
Sorry, this is not a behave issue, this is a tool-problem issue.
Reformatting the traceback of Python to make a tool happy is BAD (IMHO).
AFAIK, the PyCharm IDE has fixed this problem. Hyperlinking stack traces in PyCharm 5 works at least.
