### ISSUE TITLE
include pattern matches directory names

### ISSUE THREAD

**Issue by rakslice** [behave/behave#329]
After wondering for a while why my some of my continuous integration projects' behave test runs were running every test despite being launched with a `-i` include pattern, I finally noticed that the absolute path of the files contained that pattern.

That is very confusing. If it was at least noted in the help (https://pythonhosted.org/behave/behave.html#command-line-arguments) that pattern is matched against the absolute filename, it would be a good clue for future problem solvers. =)

**Comment by jenisys** [comment]
Why do you think that ?
The file-selection functionality is applied to the (feature) filenames that you provide on command-line.
If you provide absolute filenames ...
