### ISSUE TITLE
Custom Data to Formatters

### ISSUE THREAD

**Issue by jaypatel512** [behave/behave#332]
Any idea how could I add some custom data to formatters ? For e.g. for each steps, I need to add a "counter" value, that could help me reference some external Id. How can I pass that ? Btw, context object is not shared across the formatters.

**Comment by jaypatel512** [comment]
The sequence of execution I am able to get :

1. before_step(context, step)
2. step_impl(context,..) // no step object
3. formatters result(result) // step object but no context object
4. after_step(context, step) // has both, but its too late for me to exchange result from context to step.

Am I missing something here ? Or currently there would be no way to implement something like this ?

**Comment by jenisys** [comment]
I am not sure that I understand what you are trying to accomplish !?!

**Comment by jaypatel512** [comment]
Btw, I was able to find a workaround for this. However, it feels that this issue could be generalized to something like this:

- My goal is, I wish to write a lot of behave scripts that makes REST calls to my server. For each rest call made, we return a `debug_id` that could be used to track that rest call internally.
- Many steps may have called REST server multiple times, thus resulting to multiple debug_ids.
- Once each feature/scenario/step completes its feature, I wish to collect all the `debug_id`s generated by any number of rest call done per step, and log it inside JSONFormatter, to be printed as a part of "result" object inside each step.

to accomplish something like this, where a user would want to add some additional custom result information to JSON output, there is currently no obvious way to do that. It would be amazing if there could be a more streamlined way to somehow inject custom data to "result" object of each step, that could be retrieved by formatters and stored/printed/echoed accordingly.

Let me know if this helps.

**Comment by jenisys** [comment]
The first two points are basically storing the "debug_id" in the context. Then step implementations can reuse it from there (and the ``before_all()`` or ``before_feature()`` hook could initialize it in the context (if necessary).

The third point is something else. You want output annotation data in a custom formatter (and it has nothing to do with the result). There is currently no way for that. You can only write this data to a file or to stdout/stderr in one of the environment hooks (and avoid to capture the output for stdout/stderr).

**Comment by jaypatel512** [comment]
Thats exactly what I did for first 2 steps.

I was able to implement this with overriding JSONFormatter's `step`, `feature` and `eof` methods. However, I am not sure if there was a reason behind not having `eos` (end of scenario) method to be override. That would have helped me a lot.

**Comment by aisbaa** [comment]
Hello, I need additional information from step inside formatter as well. Are there any plans to add such functionality?
