### ISSUE TITLE
Some step implementations not detected when special characters are used 

### ISSUE THREAD

**Issue by yucer** [behave/behave#333]
I have this feature file in German language (*teilen.feature*):

``` cucumber
# language: de
Funktionalität: Nehmen
  Szenario: Küchen
    Angenommen Es gibt vier Teile
      Wenn Ich nehme ein Stück
      Dann Es gibt drei Teile
```
when i run *behave* i get this result:

``` bash
Funktionalität: Nehmen # teilen.feature:2

  Szenario: Küchen                # teilen.feature:3
    Angenommen Es gibt vier Teile # None
    Wenn Ich nehme ein Stück      # None
    Dann Es gibt drei Teile       # None


Failing scenarios:
  teilen.feature:3  Küchen

0 features passed, 1 failed, 0 skipped
0 scenarios passed, 1 failed, 0 skipped
0 steps passed, 0 failed, 0 skipped, 3 undefined
Took 0m0.000s

You can implement step definitions for undefined steps with these snippets:

@given(u'Es gibt vier Teile')
def step_impl(context):
    raise NotImplementedError(u'STEP: Given Es gibt vier Teile')

@when(u'Ich nehme ein Stück')
def step_impl(context):
    raise NotImplementedError(u'STEP: When Ich nehme ein Stück')

@then(u'Es gibt drei Teile')
def step_impl(context):
    raise NotImplementedError(u'STEP: Then Es gibt drei Teile')
```
Then I copy and paste the steps definition to a python file on the steps folder. All of them are recognized except the one with the word *Stück*. I think is by the special character: ü

This characters are also needed in German Language support: äöüß 

Later i discovered that i forgot to include this at the beginning of my python file:
```python
# -*- coding: utf-8 -*-
```

Maybe is a good idea to include that line in the snippet code generation (or a comment in the documentation).

**Comment by jenisys** [comment]
Mmh, that is standard python (supported by various editors and IDEs). 
Using UTF-8 is in general a good idea, especially when Umlaute are involved.

**Comment by yucer** [comment]
Anyway I reported that here just for reference. Maybe another one has the same problem.

You can mark it as solved.
