### ISSUE TITLE
Feature files in other language are failing when --lang is specified

### ISSUE THREAD

**Issue by yucer** [behave/behave#334]
Given this structure:

```
features
├── english.feature
├── german.feature
└── steps
    ├── english.py
    └── german.py
```

With this files:

```cucumber
# file:features/english.feature
# language: en
Feature: Using English Language

    Scenario: Run a simple test with German Keywords
        Given we have behave installed
         When we implement a test
         Then behave will test it for us!
```

```cucumber
# file:features/german.feature
# language: de
Funktionalität: Using Languages other than English (tutorial12)

    Szenario: Run a simple test completely in German
        Angenommen wir haben "behave" installiert
        Wenn wir einen Test implementieren
        Dann wird "behave" ihn für uns testen!
```

```python
# file:features/steps/english.py
# language: en
# ----------------------------------------------------------------------------
# STEPS:
# ----------------------------------------------------------------------------
from behave import given, when, then

@given('we have behave installed')
def step_impl(context):
    pass

@when('we implement a test')
def step_impl(context):
    assert True is not False

@then('behave will test it for us!')
def step_impl(context):
    assert context.failed is False
```

```python
# file:features/steps/german.py
# -*- coding: UTF-8 -*-
# language: de
# ----------------------------------------------------------------------------
# STEPS:
# ----------------------------------------------------------------------------
from behave import given, when, then

@given('wir haben "behave" installiert')
def step_impl(context):
    context.execute_steps(u"Angenommen we have behave installed")

@when('wir einen Test implementieren')
def step_impl(context):
    context.execute_steps(u"Wenn we implement a test")

@then(u'wird "behave" ihn für uns testen!')
def step_impl(context):
    context.execute_steps(u'Dann behave will test it for us!')
```

Every file has its language specification. When i try to run just the tests in german i get an error:

```bash
$ behave --lang=de
ParseError: Failed to parse "/home/yucer/src/dev/behave/features/german.feature": 
Parser failure in state init, at line 3: 'Feature: Using English Language'
REASON: No feature found.
``` 

Why it tries to interpret the english tests like if they were written in german? They are properly marked  with `# language: en` so they may be skipped.

**Comment by jenisys** [comment]
I am not sure if the showed the correct output because the problem should occur with "english.feature".
Note that when you use ``behave --lang=de …``, you override the language markers in the feature files. Therefore, the language marker is not evaluated during parsing.

In addition, the language comments in the step files are comments only (behave ignores them).
And it is also not a good idea to mix languages in one feature directory (IMHO).

**Comment by yucer** [comment]
Sorry I was confused. The current definition of the `--lang` Command-Line Argument is:
```
--lang
    Use keywords for a language other than English.
```
I though that it was: 
```
--lang
    Test the features for a language other than English.
```
The problem is that almost all the Command-Line Arguments have semantics related to control the execution (like the `tags` ones). I though that the `# language` mark was for the feature file interpretation (as it is associated to the definition of each feature file) and the `--lang` command line was for selecting the language I wanted to run. 

I thing that I need to define a tag for each language in order to achieve that. But I see that somehow redundant (because I am using already the `#language` mark). Can we make somehow that the `#language de` mark implicitly tag the feature with a *@lang_de* tag or something like that ? That would allow us to execute the test just for a language (even when another language steps are defined)

Think about an scenario where some people write tests in English and other people translates them. Feature files in both languages can coexists but we should be able to select one of them in the execution.

**Comment by mixxorz** [comment]
Cucumber implements what you just mentioned:

>A # language: header on the first line of a feature file tells Cucumber what spoken language to use – for example # language: fr for French. If you omit this header, Cucumber will default to English (en).

[Relevant docs](https://github.com/cucumber/cucumber/wiki/Spoken-languages)

**Comment by jenisys** [comment]
@yucer 
You can use tags for selecting features for a specific language as you suggested.
I would still use different directories for different languages or a filename convention, like:
  
  features/de.*.feature   # Features in German language
  features/en.*.feature   # Features in English language, etc.

**Comment by jenisys** [comment]
@mixxorz 
Behave has the same functionality as cucumber (AFAIK).
But I will make a small change in the near future. The ``--lang`` option will then define the default language to use (by selecting parser keywords). This means if a language comment is used at the begin of a feature file it has higher priority than the default language.

**Comment by berndhahnebach** [comment]
👍
