### ISSUE TITLE
"TypeError: not all arguments converted during string formatting" on failing assertion

### ISSUE THREAD

**Issue by kowalcj0** [behave/behave#337]
I recently updated behave from v1.2.3 to v1.2.5
So far I was happily using a custom file and console logger that I've configured in `environment.py` (probably attaching it to the context object is not the best way to do it, but it worked flawlessly).

The problem is that one of the steps with a simple assertion generates a `TypeError: not all arguments converted during string formatting` and stops the further feature execution (which looks like behave crashed)
The weirdest thing is that I'm getting this error only in 2 feature files among many that use the same step and it happens only when the assertion fails. 

This issue looks somewhat similar to the one found in Nose: https://github.com/nose-devs/nose/issues/561

Here's the step definition:

```
@then(u'the status code should be "{status_code}"')
def step_impl(context, status_code):
    assert int(status_code) == context.response.status_code, (
            u"Expected: {} but got: {}".format(status_code,
                context.response.status_code))
```

Issue persists even if I remove the custom error message!  

*- context.response is a standard [requests](http://docs.python-requests.org/en/latest/) response

The funny thing is that when I change the logging_level in .behaverc to INFO or remove it, then I don't see this error, but then my log file is empty.
I also tried to disable the log capturing in .behaverc:
```
log_capture=False
stderr_capture=False
stdout_capture=False
```

But that didn't help as well.

Here's the full stack trace:

```
Exception TypeError: not all arguments converted during string formatting
Traceback (most recent call last):
  File "/home/jk/.virtualenvs/behave/bin/behave", line 11, in <module>
    sys.exit(main())
  File "/home/jk/.virtualenvs/behave/local/lib/python2.7/site-packages/behave/__main__.py", line 109, in main
    failed = runner.run()
  File "/home/jk/.virtualenvs/behave/local/lib/python2.7/site-packages/behave/runner.py", line 672, in run
    return self.run_with_paths()
  File "/home/jk/.virtualenvs/behave/local/lib/python2.7/site-packages/behave/runner.py", line 693, in run_with_paths
    return self.run_model()
  File "/home/jk/.virtualenvs/behave/local/lib/python2.7/site-packages/behave/runner.py", line 483, in run_model
    failed = feature.run(self)
  File "/home/jk/.virtualenvs/behave/local/lib/python2.7/site-packages/behave/model.py", line 523, in run
    failed = scenario.run(runner)
  File "/home/jk/.virtualenvs/behave/local/lib/python2.7/site-packages/behave/model.py", line 1255, in run
    failed = scenario.run(runner)
  File "/home/jk/.virtualenvs/behave/local/lib/python2.7/site-packages/behave/model.py", line 882, in run
    if not step.run(runner):
  File "/home/jk/.virtualenvs/behave/local/lib/python2.7/site-packages/behave/model.py", line 1499, in run
    output = runner.log_capture.getvalue()
  File "/home/jk/.virtualenvs/behave/local/lib/python2.7/site-packages/behave/log_capture.py", line 99, in getvalue
    return '\n'.join(self.formatter.format(r) for r in self.buffer)
  File "/home/jk/.virtualenvs/behave/local/lib/python2.7/site-packages/behave/log_capture.py", line 99, in <genexpr>
    return '\n'.join(self.formatter.format(r) for r in self.buffer)
  File "/usr/lib/python2.7/logging/__init__.py", line 464, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
```

here's the logger configuration in `environment.py` :
```
def before_all(context):
    # ..... 
    log_file = './reports/behave.log'
    context.log = logging.getLogger("behave")
    fmt='%(asctime)s-%(filename)s[line:%(lineno)d]-%(name)s-%(levelname)s: %(message)s'
    formatter = logging.Formatter(fmt=fmt)
    fh = logging.handlers.RotatingFileHandler(log_file, mode='a',
                                              maxBytes=900000,
                                              backupCount=0,
                                              encoding=None,
                                              delay=0)
    fh.setLevel(logging.DEBUG)
    fh.setFormatter(formatter)
    context.log.addHandler(fh)
```

and `.behaverc`
```
[behave]
junit=True
junit_directory=./reports/
verbose=True
logging_level=DEBUG
```

**Comment by jenisys** [comment]
It is in general a good idea to use ``context.config.setup_logging()`` because you often overlook side issues. For example, in your case you have disable the logging_level command-line option.
In your case, it would the logging configuration in a configfile and use it with ``setup_logging()``.

The core issue seems to be that log capture uses another format (less or more params) than you configured for yourself. Logcapture uses ``config.logging_format`` and specified your logging format around it. So when a test fails, log capture kicks in and everything blows up.

**Comment by kowalcj0** [comment]
thank you for your response @jenisys 

I've replaced my custom configuration with `context.config.setup_logging()` and I removed `logging_level=DEBUG` from `.behaverc` so it looks like: 
```
[behave]
junit=True
junit_directory=./reports/
verbose=True
```

I tried such config:
```
    fmt='%(asctime)s-%(filename)s[line:%(lineno)d]-%(name)s-%(levelname)s: %(message)s'
    context.config.setup_logging(level=logging.DEBUG,
                                 filename='behave.log',
                                 filemode='a',
                                 format=fmt
                                 )
```

but when I run my tests `behave -k --tags=some.tag.name`, then no debug logs are displayed nor `behave.log` file is created. 
When I check the logging level within the steps implementation file: 
```
import logging
...
import ipdb; ipdb.set_trace()

ipdb> logging.getLogger().level
30
```
It should be `10` not `30`. See [logging levels](https://docs.python.org/2/library/logging.html#logging-levels)

When I run behave with ` --logging-level=DEBUG` then debug msgs are displayed (but with wrong, I mean the default not the custom formatting) in the terminal but `behave.log` is still not created and the same error is displayed `TypeError: not all arguments converted during string formatting`

```
DEBUG:root:Expected: 201 but got: 500
Exception TypeError: not all arguments converted during string formatting
Traceback (most recent call last):
  File "/home/jk/.virtualenvs/behave/bin/behave", line 11, in <module>
    sys.exit(main())
  File "/home/jk/.virtualenvs/behave/local/lib/python2.7/site-packages/behave/__main__.py", line 109, in main
    failed = runner.run()
  File "/home/jk/.virtualenvs/behave/local/lib/python2.7/site-packages/behave/runner.py", line 672, in run
    return self.run_with_paths()
  File "/home/jk/.virtualenvs/behave/local/lib/python2.7/site-packages/behave/runner.py", line 693, in run_with_paths
    return self.run_model()
  File "/home/jk/.virtualenvs/behave/local/lib/python2.7/site-packages/behave/runner.py", line 483, in run_model
    failed = feature.run(self)
  File "/home/jk/.virtualenvs/behave/local/lib/python2.7/site-packages/behave/model.py", line 523, in run
    failed = scenario.run(runner)
  File "/home/jk/.virtualenvs/behave/local/lib/python2.7/site-packages/behave/model.py", line 1255, in run
    failed = scenario.run(runner)
  File "/home/jk/.virtualenvs/behave/local/lib/python2.7/site-packages/behave/model.py", line 882, in run
    if not step.run(runner):
  File "/home/jk/.virtualenvs/behave/local/lib/python2.7/site-packages/behave/model.py", line 1499, in run
    output = runner.log_capture.getvalue()
  File "/home/jk/.virtualenvs/behave/local/lib/python2.7/site-packages/behave/log_capture.py", line 99, in getvalue
    return '\n'.join(self.formatter.format(r) for r in self.buffer)
  File "/home/jk/.virtualenvs/behave/local/lib/python2.7/site-packages/behave/log_capture.py", line 99, in <genexpr>
    return '\n'.join(self.formatter.format(r) for r in self.buffer)
  File "/usr/lib/python2.7/logging/__init__.py", line 464, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
```

What is even funnier is that even when I remove the custom format:
```
    context.config.setup_logging(level=logging.DEBUG,
                                 filename='behave.log',
                                 filemode='a'
                                 )
```

the same error is displayed as above.

But the worst of all is that when I remove `context.config.setup_logging()` from the `before_all` the same issue persists!!!!

An excerpt from my steps implementation file:
```
#....other imports
import logging

#... other step definitions

@then(u'the status code should be "{status_code}"')
def step_impl(context, status_code):
    assert int(status_code) == context.response.status_code, (
            u"Expected: {} but got: {}".format(status_code, context.response.status_code))
````


My set-up consists of:
Linux Mint 17(.1 and .2) and Os X Mountain Lion
Python 2.7.6 (same on all 3 machines)
packages in my virtualenv:
```
PyGreSQL==4.1.1
argparse==1.2.1
behave==1.2.5
enum34==1.0.4
ipdb==0.8
ipython==3.2.0
parse==1.6.6
parse-type==0.3.4
py==1.4.30
pytest==2.7.2
requests==2.7.0
six==1.9.0
stripe==1.23.0
wsgiref==0.1.2
```

**Comment by kowalcj0** [comment]
I stripped out most of the code from our repository and I've created a tiny repo with the basic setup similar to the one as described above: [logging-issue repo](https://github.com/kowalcj0/logging-issue)

Unfortunately I can't reproduce the `TypeError: not all arguments converted during string formatting` issue but I can reproduce the other problem, which is not creating the log file and not using the desired logging format.

Run it:
`behave --logging-level=DEBUG`

**Comment by jenisys** [comment]
I looked again over your stack trace and the implementation in the logging module.
The problem should be a faulty log message with too many args or too few args, like:

```python
logger.debug("Hello %s" % (name, age)) 
```

I would disable behave's logcapture. This will cause the log to fail directly where the problem occurs instead of later on. The stack trace should tell you where the emitter of the faulty log record is.

Otherwise, the easiest way to track that down would be to patch the logging module (``LogRecord.getMessage()``) where the message is computed with ``msg = msg % self.args``. Put a try/catch-block around it and output the "msg" and "args" in case of an exception. With this info you should be able to identify the location where it happens.

**Comment by jenisys** [comment]
Actually, the problematic line should look like:

```python
logger.debug("Hello %s", name, age) 
```

The example from above would fail immediately.

**Comment by kowalcj0** [comment]
Thank you for the hist @jenisys I found the troublemaker:

`logging.debug("1st line: {}\n"`
`                        "2nd line{}"`**,** <-----------------------here's the troublemaker
`                        "4th line:{}".format(first, second, third))`


But the other problem persists. The log file is still not generated. Dunno why's that?

the logging config looks about right:
```
    context.config.setup_logging(level=logging.DEBUG,
                                 filename='behave.log',
                                 filemode='a'
                                 )
```

**Comment by kowalcj0** [comment]
OK, stopped using the `context.config.setup_logging()` and switched back to the regular way of configuring the logger:

```
    # configure logger
    rootLogger = logging.getLogger()

    logFile = "./reports/behave.log"
    fmt='%(asctime)s-%(filename)s[line:%(lineno)d]-%(name)s-%(levelname)s: %(message)s'
    logFormatter = logging.Formatter(fmt)

    fileHandler = logging.FileHandler(logFile)
    fileHandler.setLevel(logging.DEBUG)
    fileHandler.setFormatter(logFormatter)
    rootLogger.addHandler(fileHandler)

    consoleHandler = logging.StreamHandler()
    consoleHandler.setFormatter(logFormatter)
    consoleHandler.setLevel(logging.INFO)
    rootLogger.addHandler(consoleHandler)
```

Thank you for your help @jenisys 

Let's close this ticket.
