### ISSUE TITLE
Add tags for environment url and browser choices to run from cmd line

### ISSUE THREAD

**Issue by jessingrass** [behave/behave#341]
I have added tags to the configuration.py file (class ConfigError(Exception): options to include 
-b, --browser and --env. Please find the code below: (some is pseudo code as it is different for every user). I have used this code to run tests from command line against production applications. Are there plans to add this functionality? If not, may I issue a PR? Please advise. I love Behave and it has been a very helpful tool for me over the past few years.

 (('-b', '--browser'),
     dict(action='store', dest='browser',
          default='firefox',
          help='Which browser to use for test.'))

and

    (('--env',),
     dict(action='store', dest='environment',
          default='dev',
          help='Which url to use for test.')),

**Comment by jenisys** [comment]
Why didn't you use the "userdata" functionality ?!?
It provides the common solution to provide user-specific configuration data for your test context.

```console
behave -D browser=firefox …
```

**Comment by jessingrass** [comment]
I will look into this functionality! Thanks for this information.

**Comment by jessingrass** [comment]
"Other advanced use cases:

support configuration profiles via cmdline ”... -D PROFILE=xxx ...” (uses profile-specific configuration file or profile-specific config section)
provide test stage specific configuration data"

This information is in the docs, but is there anywhere it is expanded to show how to create the profile-specific config file or section? I have not done this before so any info, links, guides, etc. would be helpful. If there is a better forum for me to be posting this, please let me know. Thanks

**Comment by mixxorz** [comment]
[Link in the docs.](https://pythonhosted.org/behave/new_and_noteworthy_v1.2.5.html#index-7)

**Comment by jenisys** [comment]
As stated by @mixxorz above.
You basically use a user data variable to load another user data section (named the PROFILE).
The example in the documentation from above shows it, but uses the variable "configfile" instead of "PROFILE". 

Note that if you want to use the user data defaults ("behave.ini"), you should use lowercase letters ("profile" instead of "PROFILE") because Python's configfile parser is case-insensitive. There is an issue and pull-request pending related to that.

**Comment by jessingrass** [comment]
@mixxorz @jenisys Thank you so much for your help. As stated earlier, I love Behave and am thankful for the helpful information and guide.
