### ISSUE TITLE
Calling tags from feature files

### ISSUE THREAD

**Issue by omacchioni** [behave/behave#347]
It's already possible to call steps from steps (execute_steps).

In my environment I'd like to be able to call tags from feature files, ie something like:

```
    @common_steps
    Scenario: Common Steps
        [... do something... ]

    @test1
    Scenario: Test1
        [... do something ... ]
        And I call tag @common_steps

    @test2
    Senario: Test 2
        [... do something ...]
        And I call tag @common_steps
```

... unless there is a way to do this. I didn't find anything in the documentation :(

**Comment by mixxorz** [comment]
I don't think this is the best way to do BDD. Your feature files shouldn't have implementation detail.

Can you tell us what you're trying to accomplish? We might be able to point you in the right direction.

**Comment by jenisys** [comment]
From your example above, you want a step that is executed as "macro" (of other steps). 
Just provide a step implementation that uses ``context.execute_steps(text)`` (common_steps in your case).

**Comment by omacchioni** [comment]
In this case we're not actually using behave for BDD - we're using (or abusing) it to populate our OpenERP/Odoo instance with new information, specifically new products. As this task is quite complex and is already done in the scope of BDD, we decided to use the same behave scripts to add new products on the production instance when requested by business. 

So the ```[... do something ...]``` for @test1 in my example will actually add some products, and the @common_steps is some other tasks we always need to perform after adding new products, regardless of the products added.

It's of course possible to use a step implementation in Python, but if I'm not mistaken this would imply that I rewrite @common_steps in Python... which would technically be doable of course but not in the spirit of Behave I think.

**Comment by mixxorz** [comment]
You could do

```gherkin
# Feature file

    Scenario: Common Steps
        Given some common state

    @test1
    Scenario: Test1
        [... do something ... ]
        Given some common state

    @test2
    Senario: Test 2
        [... do something ...]
        Given some common state

```

```python
# step implementations

@given(u'some comon state'):
def common_state(context):
    # do common things

```

If you wanted to, you could also register the step using `@step()` instead of `@given()` so that you can call it in whatever context (Given, When or Then).

**Comment by omacchioni** [comment]
Yes, I could define my steps in Python... that's a possible workaround.
