### ISSUE TITLE
Behave requires a .feature file in the working directory even when specifying a location

### ISSUE THREAD

**Issue by crccheck** [behave/behave#348]
My use case is I don't want to mix code with my feature files to avoid confusing non-technical readers.

Background: I have a `./steps/` folder with some definitions, if I run `behave` I get:
```
$ behave --version
behave 1.2.5
$ pwd
/Users/crccheck/behave_hello_world
$ behave /Users/crccheck/behave_hello_world/my_features
ConfigError: No feature files in "/Users/crccheck/behave_hello_world"
```

But if I do `touch dummy.feature` and re-run the above, it works as expected and goes over the features at `/Users/crccheck/my_features` and ignores my empty `dummy.feature`.

**Comment by crccheck** [comment]
I think this is intended, but if I point it to some feature files outside, it loses the ability to find the steps directory

**Comment by jenisys** [comment]
Actually the other way around works better. You can provide a "step library" outside the feature directory. In your feature directory(s) with its step directory you only import the the steps from the "step library" (which must be in the python search path => PYTHONPATH environment variable if necessary).

**Comment by crccheck** [comment]
I'm trying to do this "other way around" approach and no matter how I change my path/pythonpath, I get `ConfigError: No steps directory in "/Users/crc/my_features"`. I've been looking over #81 too. To reiterate, there seems to be a way to run tests where the /features directory is beneath the /steps directory, except you need a dummy `.feature` file next to the /steps directory. The idea is to keep  Python code outside the /features directory so business folks reviewing the /features directory don't get distracted by code.

**Comment by mixxorz** [comment]
Maybe the [`paths`](https://pythonhosted.org/behave/behave.html#configuration-files) option might help you out.

You can point one to the real features directory where your feature files are, then another on a features directory where you only put steps in.
