### ISSUE TITLE
Improper handling of escape characters in double-quoted named fields

### ISSUE THREAD

**Issue by mcandre** [behave/behave#350]
Behave is incorrectly interpreting my escape characters as a series of literals, in my double-quoted command field.

Feature:

    When I run the command "python/bin/network/kafka_request_executor.py -t requests_twitter -g integration-test -c \"{\"iter_timeout\": 5}\" -l INFO"

Step:

```
@when('I run the command "{command}"')
def i_run_the_command(context, command):
    print('Command: ' + pformat(command))
```

Expected:

    Command: python/bin/network/kafka_request_executor.py -t requests_twitter -g integration-test -c "{"iter_timeout": 5}" -l INFO

Observed:

    Command: python/bin/network/kafka_request_executor.py -t requests_twitter -g integration-test -c \\"{\\"iter_timeout\\": 5}\\" -l INFO

Mitigation:

If I use single quotes instead of double quotes in the template string and feature definition, the escaped characters are parsed correctly.

E.g.:

Feature:

    When I run the command 'python/bin/network/kafka_request_executor.py -t requests_twitter -g integration-test -c "{\"iter_timeout\": 5}" -l INFO'

Step:

```
@when('I run the command \'{command}\'')
def i_run_the_command(context, command):
    print('Command: ' + pformat(command))
```

System:

* behave 1.2.5
* Python 3.3
* Mac OS X 10.10

**Comment by jenisys** [comment]
If you have problems with quoting, add your own step implementation (and use it), for example with backticks:

```python
# -- FILE: features/steps/my_command_steps.py
from behave import when
from behave4cmd0.command_steps import step_i_run_command

@when(u'I run `{command}`')
def step_i_run_command_backticked(context, command):
    step_i_run_command(command)
```

NOTE: You are having a regular expression matching problem.
