### ISSUE TITLE
A pain to debian package (for both python2,3) because scripts in bin folder have hard-coded shebangs

### ISSUE THREAD

**Issue by robvdl** [behave/behave#353]
Scripts should be defined in the setup.py in the entry_points section, e.g. an example would be:

    entry_points={
        'console_scripts': [
            'behave = behave.scripts.cli:main'
        ],
    }

this goes in the setup.py, an argument of the setup() function.

this would have made things a lot easier to debian package for multiple Python versions, right now, I have to edit every script in the bin folder and replace the shebangs with python3 ones before packaging for Python 3, I shouldn't have to do this.

**Comment by robvdl** [comment]
I noticed it already has a console script defined for behave in the setup.py, so why then is it also in the bin folder? this makes no sense, unless this is legacy stuff left behind.

**Comment by jenisys** [comment]
The "bin/behave" scripts ensures that the current workspace is used (and not the installed version of behave).

**Comment by alesage** [comment]
Curious if this debian package came into existence?

**Comment by robvdl** [comment]
It's a long time ago now but I think we did sort of manage in the end, but couldn't quite create the correct Debian packaging config so that it would build both python-behave and python3-behave packages from the same source package.  I think we could only get it to build python3-behave but I can't really remember the details why because our funding got cut for writing BDD tests.

Sadly it looks like python3-behave STILL hasn't made it into Ubuntu 16.04, and that is 2 years later, which is a bit sad, but somehow doesn't surprise me because of the "state" of Python 3 packages in Debian/Ubuntu.

**Comment by alesage** [comment]
Thanks for this info!
