### ISSUE TITLE
Can't see the output of ipdd==0.8.1 when used with behave==1.2.5

### ISSUE THREAD

**Issue by kowalcj0** [behave/behave#355]
Hi All,

After upgrading ipdb to v0.8.1 and behave to v1.2.5, ipdb stopped working properly.
Basically when execution stops at the breakpoint, and you issue any of the ipdb commands then you won't see the output of that command. 
Here's an example repo that you can use to reproduce the issue: https://github.com/kowalcj0/behaveipdb

btw. I wasn't able to tell whether it's an issue with ipdb or behave so I've reported it on both projects' github repos.

**Comment by jenisys** [comment]
Use ``behave --no-capture`` and everything is fine.
Per default the step execution is captured. Therefore, you see no stdout (it is internally captured).
But this is not a new feature. The same should happen with older versions of behave (but I have not tested that).

**Comment by kowalcj0** [comment]
hmmm it works in that example project, but it doesn't work in my work project. Maybe custom logger messes up with the setup. Will investigate this. Thank you @jenisys for the hint!

**Comment by jenisys** [comment]
Assumed to be resolved (and user issue).
