### ISSUE TITLE
API docs are self-contradictory on step implementation decorator imports

### ISSUE THREAD

**Issue by tomxtobin** [behave/behave#356]
The API docs state:

> All step implementations **must** start with the import line:
>
> `from behave import *`

They then go on to state:

> *You don't need to import the decorators:* they're automatically available to your step implmentation modules as global variables.

From what I can tell, it *looks* like the second case is correct (i.e., `behave` works fine without the import line).

(And aside, "implmentation" is a typo in the docs.) :-)

**Comment by jenisys** [comment]
You should use "from behave import *" or "from behave import given, when, then, step" (or whatever you need) in step implementation files. The advantage by doing this is that you can apply "pylint" (or other static code analyzers) to step implementation files and verify that the step implementation file(s) is/or syntactically correct.

If you not import the basic behave API, behave injects the common step decorators symbols for you during the step import (as fallback or convenience).

**Comment by tomxtobin** [comment]
Thanks for the explanation.

I just noticed the issue was closed. (A bit late, I know!) I'd love to see the documentation updated to clarify your point. Should I open a new issue there?

Also, the typo I mentioned still exists. (Same question — new issue?) :-)
