### ISSUE TITLE
detecting lang from step definition code

### ISSUE THREAD

**Issue by yucer** [behave/behave#357]
I am interested in forwarding some info from the parser context to the application that i am testing.
Specifically the language of the feature being executed.

I was thinking in checking that in the before_feature method but I can't find the lang there.

Any tip?

**Comment by tomekwszelaki** [comment]
what are you trying to achieve? maybe this will help? https://pythonhosted.org/behave/gherkin.html#languages-other-than-english

**Comment by jenisys** [comment]
The language information is currently not part of the model (or Feature object). It is currently only available in the parser (or the default language in the config object).

Could you explain why you need this information ?

**Comment by yucer** [comment]
The application I am testing is internationalized. I am testing the middle-Tier via its API. When I query the database I need to specify the language so the API  can give me the translated values from the database. 

Given that the language is parsed at the beginning of the feature file by Behave, I was thinking to modify the *before_feature* method  to notify the app that the active language has changed.

**Comment by tomekwszelaki** [comment]
Do you need the feature file itself to be written in a different language or do you just need to specify the language as a string parameter (e.g. `language="Spanish"`) or does the database query have to be written in a different language? 

From what you've written I assume you do something like (in case of SQL): `SELECT * FROM user_data WHERE language="Spanish"` - is that correct? If not, could you write an example feature/steps so that we fully understand what's the problem?

**Comment by yucer** [comment]
You're right. The SQL queries use that language info in order to return the values that fit the user interface.

This is part of my de.features/environment.py file:

```python
from my_tools.lang import set_client_lang

def before_feature(ctx, feature):
    lang="de_DE"        # I need feature.lang to set the right lang
    set_client_lang(ctx, lang)
```

As the file represent features and the language is parsed from the head of the file I think there the feature objects should include the lang property used to parse it.

Although I have one feature folder fore each language, my `de.features/environment.py` file is a proxy to my `environment.py`. 

Actually my code works, but this is the unique reason that I have currently to specify a different `environment.py` file for each language.

**Comment by tomekwszelaki** [comment]
OK, I think we're mixing two concepts here.
1. Parsing of the .feature files - behave parses .feature files in english by default (so the Given, When, Then steps have to be written in English). There is a way of changing that default language to your chosen one so that you can write the steps in that language (for Spanish: `Given` becomes `Dado`, `When` becomes `Cuando` and `Then` becomes `Entonces`)
2. Being able to re-run your test suite for different languages - you write your .feature files in English, but you obtain responses in different languages depending on the input you specify

I believe what you need is point 2. right? 

Assuming you need point 2. and taking into account that you specify language on the `before_feature` hook (meaning on a per feature basis) how about using command line params to specify the language you want to use? This way you can easily run it locally (`behave /path/to/teatures -D lang=de_DE`) and it integrates very well with CI as well.

**Comment by yucer** [comment]
@tomekwszelaki Actually what I am asking is closer to point 2.

I have successfully achieved a multilingual configuration following the advice of @jenisys in https://github.com/behave/behave/issues/334 :

> I would still use different directories for different languages or a filename convention, like:
>
> features/de..feature # Features in German language
> features/en..feature # Features in English language, etc.

More precisely:

```shell
features/
├── de.features
│   ├── environment.py
│   ├── steps
│   └── ...
├── en.features
│   ├── environment.py
│   ├── steps
│   └── ...
└── environment.py
```
I was forced to include `environment.py` modules on every feature folder (it is mandatory, isn't it?). But as the code its the same I just import the functions from the more external one. 

Then I specify path to the correct features folder when running behave:
```shell
$ behave features/de.features
```
or:
```shell
$ behave features/en.features
```

I was not specifying the `--lang` parameter because I use the `# language` and the two folders. As long as I can see there are two approaches to specify the language needed to interpret the test:

1) *In the feature definitions*. 
This is suitable for having just one feature folder. The interpretation of the tests is allways the same because  the info needed to interpret them lies in the feature files.  
```shell
$ behave features/de.features
```
2) *At the moment of running the tests*.
This is suitable for having just one feature folder.
```shell
$ behave --lang=de_DE
```
here we have to decide if specify or not the language in the feature files. If we do it then we have conflicting information for the English tests when we run the German tests. This was the case solved in https://github.com/behave/behave/issues/334 and it was solved prioritizing information specified in the feature file (`#language`). 

I have decide use the first variant and avoid to use the command line parameter. As a matter of fact the semantic can be confusing. You can not force you to interpret in German a letter that is written in English, the letter itself should have that info in an implicit or explicit way. 

I think that if the parser can read the feature language that should be added accessible feature object. 

Anyway, in the case that I use `--lang` parameter at command line. How can I get that value in this scope ?:

```python
from my_tools.lang import set_client_lang
def before_feature(ctx, feature):
    lang=....                 # How can i get the --lang cmdline param value here ? 
    set_client_lang(ctx, lang)
```

Thank you very much.

**Comment by tomekwszelaki** [comment]
AFAIK you can't. The `--lang` parameter is for the parser only and is used to interpret the `.feature` files themselves (before you get to the actual execution of the test). The only way (that I know of) of getting a command-line param into the test execution phase is the use of the command-line parameters defined with the `-D` switch.

running: `behave features/de.features -Dlanguage=de_DE` will allow you to get the language like this:

```
from my_tools.lang import set_client_lang
def before_feature(ctx, feature):
    lang=ctx.config.userdata["language"]  # How can i get the --lang cmdline param value here ? 
    set_client_lang(ctx, lang)
```

**Comment by jenisys** [comment]
INTEGRATED INTO: behave-1.2.6.dev0

@yucer 
I added a language attribute to the Feature class. This allows you to detect the language of the current feature by using the context parameter.

```python
# -- FILE: features/environment.py
from __future__ import print_function

def before_feature(context, feature):
    # SAME: context.feature == feature (current_feature)
    print("USING: language=%s" % context.feature.language)
```

**Comment by yucer** [comment]
@jenisys 
Thank you very much.

**Comment by berndhahnebach** [comment]
> INTEGRATED INTO: behave-1.2.6.dev0
> 
> @yucer I added a language attribute to the Feature class. This allows you to detect the language of the current feature by using the context parameter.
> 
> ```python
> # -- FILE: features/environment.py
> from __future__ import print_function
> 
> def before_feature(context, feature):
>     # SAME: context.feature == feature (current_feature)
>     print("USING: language=%s" % context.feature.language)
> ```

very very useful 👍
