### ISSUE TITLE
json formatter does not produce tags compliant with the Cucumber JSON format

### ISSUE THREAD

**Issue by vmahe35** [behave/behave#358]
Hello,

I have done some testing with Behave 1.2.5 and the following Jenkins plugin : https://wiki.jenkins-ci.org/display/JENKINS/Cucumber+Test+Result+Plugin 
I am launching Behave with this shell command :
`behave --format=json.pretty --outfile=target/cucumber.json <my-features-folder>`

It works fine with the Jenkins plugin (which means that the JSON output is not so far from being compliant with Cucumber format) as long as you don't put any tag in your feature files.

This is because Cucumber expects the following tag format :
```
"tags": [
          {
            "name": "@mytag1",
            "line": 4
          },
          {
            "name": "@mytag2",
            "line": 4
          }
        ],
```
whereas the JSON formatter generates the following tag format :+1: 
```
"tags": ["mytag1","mytag2]
```

Would it be possible to either develop a new "cucumber" formatter or to fix this issue in the current json formatter ?

Thanks

**Comment by jenisys** [comment]
DUPLICATES issue #267 

Is this the only difference ?

BACKGROUND INFO;
Behave has a JSON Schema file. Therefore, its JSON format is specified and can be checked.
Cucumber has no JSON schema or no clear specification (AFAIK).
