### ISSUE TITLE
Behave won't find step definition files when in a sub-directory of the "steps" directory

### ISSUE THREAD

**Issue by jonathanicetek** [behave/behave#363]
Hi all,

Having a problem when trying to run my features files. 

Problem is that I want to have separate directories within my "steps" directory to better organize the step definitions. But apparently when Behave reaches "steps" it looks directly in and no further down into sub-directories because it successfully runs when I move tutorial.feature out of its sub-directory. Anyone have a solution to configure behave to search down sub-directories in "steps" to find step definition files? Thanks!

Here is an example file structure of my code:

project/

project/features
project/features/tutorial.feature

project/steps
project/steps/test
project/steps/test/tutorial.py   # the step definition that won't be located

**Comment by jenisys** [comment]
Subdirectories in the steps directory are currently not supported.
If your code grows such complex that your need subdirectories, put them in a python package and import the relevant steps in some code in your steps directory (step-library approach). This also allows you to test your complex code.

**Comment by BineshSubramanian** [comment]
Just curious about the import - Can you please provide with a working example. My folder structure is :
Project root/ foo
Project root/ foo/ mycode.py
Project root/ tests
Project root/ test/features
Project root/ test/features/steps
Project root/ test/features/steps/ mystep.py

I want to call a function written in mycode.py from mtstep.py

**Comment by jenisys** [comment]
ASSUMPTIONS:
* `foo` is a Python package: Add `root/foo/__init__.py`
* Current working directory: `CWD=root` (best as absolute path)
* Environment variable is set: `export PYTHONPATH=.:$CWD` (assumption: UNIX bash/sh shell; Windows has other path-separator)

```python
# — FILE: test/features/steps/mystep.py
import foo.mycode
…
```

```bash
$ pwd
…/root
$ echo $CWD
…/root

$ behave test/features/
…
```

NOTE: That is Python basics.

**Comment by BineshSubramanian** [comment]
Thanks for your response. The solution doesn't work (maybe a behave issue not a python one) though I solved the problem.

My import statement - from mycode import classname
and run the behave from terminal keeping foo as pwd - foo % behave
