### ISSUE TITLE
behave with re as the step matcher can't match any step

### ISSUE THREAD

**Issue by abgalphabet** [behave/behave#364]
i have defined this step definition 
```
from behave import *
import parse

use_step_matcher('re')

@given('A list of natural numbers of "(?P<numbers>(\d+\s*,?\s*)+)"')
def step_impl(context, numbers):
    context.list = numbers
```

and trying match this step during run
```
  Given A list of natural numbers of 1, 1, 2, 3, 5, 8
```

I got 
```
Test undefined
Please define test
```
anyone can adivse?

**Comment by hipyhop** [comment]
You step does not have quotes around the number list, whereas your step implementation expects the number list to be in double quotes.

**Comment by phunter00** [comment]
[Regex Buddy and Regex Magic] (http://www.regexbuddy.com) - best $70 you will ever spend. Well, maybe not, but they make working with the regular expressions very, very easy.

**Comment by abgalphabet** [comment]
@hipyhop yes the quote cause the problem, i thought regex has to been wrapped with double quote.

it works now with the step (remove double quote):
```
@given('A list of natural numbers of (?P<numbers>(?:\d+\s*,?\s*)+)')
```

**Comment by jenisys** [comment]
Usage problem should be resolved by now.

SEE ALSO:
  * http://jenisys.github.io/behave.example/step_matcher/re_matcher.html
  * https://github.com/jenisys/behave.example
