### ISSUE TITLE
Obey file coding when reading step definitions in Python3

### ISSUE THREAD

**Issue by throwable-one** [behave/behave#371]
Behave uses ``open`` to read step definitions. In Py3K this function accepts charset, but if no charset provided, it uses ``locale.getpreferredencoding``, and this functuion returns one-byte charset on Windows (1251 in Russia, 1252 in Europe etc, depends on Language and Regional settions). So, you simply can't use utf8 in error messages in step definitions!

I believe it should work like this:
* read first line
* if it has charset / encoding, then provide it as argument.

**Comment by jenisys** [comment]
The current assumption is UTF-8.
This will be changed in the next future by importing steps in binary mode. If this is the case, Python takes care of discovering the Unicode file encoding. There several duplicated issues related to this point.

**Comment by jenisys** [comment]
See fixes related to #361.
