### ISSUE TITLE
Better document multiple paths

### ISSUE THREAD

**Issue by dfee** [behave/behave#372]
https://github.com/behave/behave/commit/236c79d0e7f97a636695a9b87c6a8ef06f3dc720

This demonstrates that the correct way for specifying paths is:
[behave]
paths = my/path1
             my/path2

This fails, and is unexpected.
[behave]
paths =
    my/path1
    my/path2

**Comment by jenisys** [comment]
This is standard behavior of the ConfigParser/configparser module.

SEE:
https://docs.python.org/2/library/configparser.html (Example: long parameter)
