### ISSUE TITLE
Tagging Examples: under Scenario Outline

### ISSUE THREAD

**Issue by dillharr** [behave/behave#374]
I have been trying to find any information on whether I can tag multiple Examples: under a Scenario Outline. When I try to do this I get a parse error, which is making me think it's not allowed. If anyone could let me know if this is true or not, I would be very grateful. In case I was clear below is an example of what I want to do

Feature: I can do something
       Scenario Outline: sending out packets of <size> bytes
               Given we create packet of "<size>" bytes
               When we send the packet
               Then the receiver should send the packet back to us

               @light
               Examples: Packet Sizes
                               | size            |

               @medium
               Examples: Packet Sizes
                               | size            |

**Comment by jenisys** [comment]
Currently, you cannot use tags for examples in a scenario outline (yet). I am aware that this is supported for example by cucumber.

**Comment by dillharr** [comment]
Ok thank you for letting me know. I'll go ahead and close the issue. Do you know if it might be added to Behave in the future? Thanks again for your help.

**Comment by jenisys** [comment]
I need to look into it, but it is a useful enhancement.
If you need it, try to provide a pull-request.
