### ISSUE TITLE
Placing @capture decorator on before_step or after_step functions masks logging in steps files.

### ISSUE THREAD

**Issue by logavanc** [behave/behave#376]
It appears that any logging in the ```environment.py``` file's ```before_step()``` or ```after_step()``` functions is captured without the use of the ```@capture``` decorator.  Additionally, if the ```@capture``` decorator *is* placed onto the ```*_step()``` functions, any logging which is done in the steps files is not captured, and I get weird behavior of the logging in the ```*_step()``` functions.

My entire setup (feature files, environment.py file, etc.) is below if it helps...

```ini
# behave.ini
[behave]
logging_format = %(asctime)s:%(levelname)s:%(name)s:%(filename)s:%(lineno)s:%(funcName)s():%(message)s
show_snippets=false
verbose=true
```

```gherkin
# feature/test.feature
Feature: Test logging.

  Scenario: Still testing logging.
    Given I am Logan
    When I say go
    Then stuff happens!
```

```python
# feature/environment.py
from behave.log_capture import capture
import logging


log = logging.getLogger(__name__)


@capture
def before_all(context):
    """
    :type context: behave.runner.Context
    """
    log.info('YELLING!!!')


# Uncomment line below to see bad behavior.
# @capture
def before_step(context, step):
    log.info('This is before step {}'.format(step))
```

```python
# feature/steps/test.py
import logging
from behave import *
from other import wrapper


log = logging.getLogger(__name__)
use_step_matcher("re")


@given("I am Logan")
def step_impl(context):
    """
    :type context: behave.runner.Context
    """
    log.info('I think, therefore... I am.')
    pass


@when("I say go")
def step_impl(context):
    """
    :type context: behave.runner.Context
    """
    log.info('I heard him say it!!!')
    pass


@then("stuff happens!")
def step_impl(context):
    """
    :type context: behave.runner.Context
    """
    log.info('Oh noes!')
    raise AssertionError('Oh the humanity!')
```

**Comment by jenisys** [comment]
* stdout, logging capture depends on command-line args or configuration file settings. Therefore, you can adapt the default values if you do not like them
* ``@capture`` should not be used in ``before_all()``. That is the one place where the user can setup the logging subsystem in a sane way. And the logging subsystem behaves rather badly or in unexpected ways when you try to set it up multiple times.
