### ISSUE TITLE
Is it possible to run in a scenario outline only one line of Examples?

### ISSUE THREAD

**Issue by iariasleon** [behave/behave#377]
A tag executes a scenario or scenario outline (all its lines in Examples table), but a I would like to execute only one line of Examples in a scenario outline.

I would like somethng in execution similar to -t my_tag@3*. Is It possible?

**Comment by jenisys** [comment]
A ScenarioOutline is more or less a template (or blueprint) for generating Scenarios, one for each example row. Therefore, you can provide a tag schema for your ScenarioOutline and behave will generate the corresponding tags for you (one for each row).

As an alternative, you may also use the name selection mechanism for Scenario names to select your Scenario (examples row) of interest.

SEE ALSO:
  * [behave docs: New and Noteworthy: Tags may contain placeholders](http://pythonhosted.org/behave/new_and_noteworthy_v1.2.5.html#tags-may-contain-placeholders)

**Comment by iariasleon** [comment]
Thanks...LGTM
