### ISSUE TITLE
Does exist some way to use reg Exp (pattern) in tags ?

### ISSUE THREAD

**Issue by iariasleon** [behave/behave#378]
Example: 
 
I have three tags:
```
my_case_positive
my_case_negative
my_case_forbidden
```
I would like somethng in execution similar to `-t my_case*`. Is It possible?

**Comment by jenisys** [comment]
Sorry, no. This is currently not supported in ``behave``.
But you can provide your own implementation of such a mechanism by injecting the necessary tag selection logic in your "environment.py" file. You will use the following 2 functionalities:

* userdata, ala: ``behave -D tag_selector="my_case*" ... ``
* scenario skip logic in ``before_scenario()`` hook

SEE ALSO:
* [behave docs: New and Noteworthy: Userdata](http://pythonhosted.org/behave/new_and_noteworthy_v1.2.5.html#userdata)
* [behave docs: New and Noteworthy: Exclude Feature/Scenario at Runtime](http://pythonhosted.org/behave/new_and_noteworthy_v1.2.5.html#exclude-feature-scenario-at-runtime)
