### ISSUE TITLE
Is it possible to re run one feature file several times programmatically?

### ISSUE THREAD

**Issue by RockBomber** [behave/behave#381]
Is it possible to re run one feature file several times programmatically?

I have variety of datasets for a feature file. And I need run a feature file for each dataset.

**Comment by jenisys** [comment]
I do not know your exact needs. Therefore, I can only give you the generic answer:
  1. **USE BEHAVE USERDATA WITH BUILD-SCRIPT:** Use userdata concept to select which dataset should be used for a behave test run, like ``behave -D DATASET_ID=1 ... features``. Use a build-script to iterate over the all datasets.
  2. **BUILD-SCRIPT GENERATES FEATURES:** Generate N features files from a feature-template, one for each dataset. Then run them all with behave (or run them one by one).
  3. **BEHAVE SCENARIO-OUTLINES:** Use ScenarioOutlines (if that is suitable for you). A ScenarioOutline provides basically a parametrized template for a Scenario and generates N Scenarios from it.
  4. **BEHAVE-AS-BUILD-SCRIPT:** You can use a behave feature (as build script) to execute behave in one of its steps (example: [issue.features/issue0075.feature](https://github.com/behave/behave/blob/master/issue.features/issue0075.feature)). You will probably use a ScenarioOutline to iterate over the datasets and use user data (combination of solution 1 and 3).

**SEE ALSO:**
* [Userdata concept](http://pythonhosted.org/behave/new_and_noteworthy_v1.2.5.html#userdata)

**NOTE:**
Regarding solution 2: There are many template engines out there, for example [Jinja](https://pypi.python.org/pypi/Jinja2/).

**Comment by RockBomber** [comment]
Thanks for your answer!
