### ISSUE TITLE
before_scenario called too late

### ISSUE THREAD

**Issue by BRevzin** [behave/behave#385]
In `Scenario.run()`, the `before_scenario` hook is called *after* the formatters start formatting the scenario:

        if run_scenario or runner.config.show_skipped:
            for formatter in runner.formatters:
                formatter.scenario(self)

        runner.context._push()
        runner.context.scenario = self 
        runner.context.tags = set(self.effective_tags)

        hooks_called = False
        if not runner.config.dry_run and run_scenario:
            hooks_called = True 
            for tag in self.tags:
                runner.run_hook('before_tag', runner.context, tag) 
            runner.run_hook('before_scenario', runner.context, self)
            ...

So if I, in `before_scenario`, want to use the active tags to `skip()` the scenario, and am running with `--no-skipped`, I will still see the result of `formatter.scenario(self)` logged. We should call the hooks first, *then* check `run_scenario` to do the formatting.

**Comment by jenisys** [comment]
Well, there are two sides to view it. When your ``before_scenario()`` hook causes problems, it is better to understand that when the formatters are already informed about the scenario. I will look into that.

**Comment by yucer** [comment]
I run the same tests over the same system but using different databases. After that I do collect the results after that in order to evaluate the regression criteria.

I was trying to modify the scenario.name into before_scenario to include the database name. Those are different test cases for me and I want all the formatters reflect that name.

Can this issue be the cause ?

What should I do in the meanwhile, modify all the formatters ?

**Comment by jenisys** [comment]
There are several solutions to this problem.
For example, use a "Scenario Outline". 
It can have parameters from the Examples table as template parameters in the name.

In addition, I assume that you have multiple test runs, one with each database. Therefore, your test report does not need each scenario name annotated with the database name. Your test configuration must appear only once in the test report.

**Comment by jenisys** [comment]
IMPLEMENTED IN: behave-1.2.6.dev0
