### ISSUE TITLE
behave: error: unrecognized arguments: --foo --bar

### ISSUE THREAD

**Issue by carlosmmelo** [behave/behave#386]
I have removed the python version that came preinstalled with OSX (Darwin) on my mac and install the latest python `2.7.11`, however this seems to cause an issue on my environment with `behave 1.2.5`:

```
$ behave --tags register
usage: behave [-h] [--auth_host_name AUTH_HOST_NAME]
              [--noauth_local_webserver]
              [--auth_host_port [AUTH_HOST_PORT [AUTH_HOST_PORT ...]]]
              [--logging_level {DEBUG,INFO,WARNING,ERROR,CRITICAL}]
behave: error: unrecognized arguments: --tags register
```

I have installed behave via `pip` and `easy_install` and on both cases I'm still having the same issue.

Any way you guys could help me debug whats going on? I've also tried with python v `2.7.9` and still able to reproduce, not sure if theres an old symlink from the OSX package and the `parse` module that I need to remove or something like that.

**Comment by carlosmmelo** [comment]
This is my symlinks:

```
✗ ls -l /usr/local/bin |grep /Library/Frameworks/Python.framework |grep -v /System
lrwxr-xr-x  1 root        wheel     66 Dec 21 15:49 2to3 -> ../../../Library/Frameworks/Python.framework/Versions/2.7/bin/2to3
lrwxr-xr-x  1 root        wheel     68 Dec 21 15:49 2to3-2 -> ../../../Library/Frameworks/Python.framework/Versions/2.7/bin/2to3-2
lrwxr-xr-x  1 root        wheel     70 Dec 21 15:49 2to3-2.7 -> ../../../Library/Frameworks/Python.framework/Versions/2.7/bin/2to3-2.7
lrwxr-xr-x  1 root        wheel     66 Dec 21 15:49 idle -> ../../../Library/Frameworks/Python.framework/Versions/2.7/bin/idle
lrwxr-xr-x  1 root        wheel     67 Dec 21 15:49 idle2 -> ../../../Library/Frameworks/Python.framework/Versions/2.7/bin/idle2
lrwxr-xr-x  1 root        wheel     69 Dec 21 15:49 idle2.7 -> ../../../Library/Frameworks/Python.framework/Versions/2.7/bin/idle2.7
lrwxr-xr-x  1 root        wheel     67 Dec 21 15:49 pydoc -> ../../../Library/Frameworks/Python.framework/Versions/2.7/bin/pydoc
lrwxr-xr-x  1 root        wheel     68 Dec 21 15:49 pydoc2 -> ../../../Library/Frameworks/Python.framework/Versions/2.7/bin/pydoc2
lrwxr-xr-x  1 root        wheel     70 Dec 21 15:49 pydoc2.7 -> ../../../Library/Frameworks/Python.framework/Versions/2.7/bin/pydoc2.7
lrwxr-xr-x  1 root        wheel     68 Dec 21 15:49 python -> ../../../Library/Frameworks/Python.framework/Versions/2.7/bin/python
lrwxr-xr-x  1 root        wheel     71 Dec 21 15:49 python-32 -> ../../../Library/Frameworks/Python.framework/Versions/2.7/bin/python-32
lrwxr-xr-x  1 root        wheel     75 Dec 21 15:49 python-config -> ../../../Library/Frameworks/Python.framework/Versions/2.7/bin/python-config
lrwxr-xr-x  1 root        wheel     69 Dec 21 15:49 python2 -> ../../../Library/Frameworks/Python.framework/Versions/2.7/bin/python2
lrwxr-xr-x  1 root        wheel     72 Dec 21 15:49 python2-32 -> ../../../Library/Frameworks/Python.framework/Versions/2.7/bin/python2-32
lrwxr-xr-x  1 root        wheel     76 Dec 21 15:49 python2-config -> ../../../Library/Frameworks/Python.framework/Versions/2.7/bin/python2-config
lrwxr-xr-x  1 root        wheel     71 Dec 21 15:49 python2.7 -> ../../../Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7
lrwxr-xr-x  1 root        wheel     74 Dec 21 15:49 python2.7-32 -> ../../../Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7-32
lrwxr-xr-x  1 root        wheel     78 Dec 21 15:49 python2.7-config -> ../../../Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7-config
lrwxr-xr-x  1 root        wheel     69 Dec 21 15:49 pythonw -> ../../../Library/Frameworks/Python.framework/Versions/2.7/bin/pythonw
lrwxr-xr-x  1 root        wheel     72 Dec 21 15:49 pythonw-32 -> ../../../Library/Frameworks/Python.framework/Versions/2.7/bin/pythonw-32
lrwxr-xr-x  1 root        wheel     70 Dec 21 15:49 pythonw2 -> ../../../Library/Frameworks/Python.framework/Versions/2.7/bin/pythonw2
lrwxr-xr-x  1 root        wheel     73 Dec 21 15:49 pythonw2-32 -> ../../../Library/Frameworks/Python.framework/Versions/2.7/bin/pythonw2-32
lrwxr-xr-x  1 root        wheel     72 Dec 21 15:49 pythonw2.7 -> ../../../Library/Frameworks/Python.framework/Versions/2.7/bin/pythonw2.7
lrwxr-xr-x  1 root        wheel     75 Dec 21 15:49 pythonw2.7-32 -> ../../../Library/Frameworks/Python.framework/Versions/2.7/bin/pythonw2.7-32
lrwxr-xr-x  1 root        wheel     70 Dec 21 15:49 smtpd.py -> ../../../Library/Frameworks/Python.framework/Versions/2.7/bin/smtpd.py
lrwxr-xr-x  1 root        wheel     73 Dec 21 15:49 smtpd2.7.py -> ../../../Library/Frameworks/Python.framework/Versions/2.7/bin/smtpd2.7.py
lrwxr-xr-x  1 root        wheel     71 Dec 21 15:49 smtpd2.py -> ../../../Library/Frameworks/Python.framework/Versions/2.7/bin/smtpd2.py
```

**Comment by carlosmmelo** [comment]
Also I just noticed that arguments that does not starts the `runner` works just fine (like the `behave -h`), but any other args that starts the `runner` will result on my issue (like `behave -k`, `behave --tags`, etc)

**Comment by jenisys** [comment]
I assume to have somehow a broken installation of behave (or your SHELL setup is mixed up).
Assuming that you installed it with ``pip``:

```shell
# -- NOTE: Perform it twice that you are sure that behave is really uninstalled.
sudo pip uninstall behave
sudo pip uninstall behave
```

Before you do that:
* inspect which python-version/variant ``pip`` is using
* inspect which python-version/variant ``behave`` is using

Inspect the installed script and look at the SHE-BANG line (first line).
If your Python installation sits under ``Library/Frameworks/Python.framework/Versions/2.7/bin/python``, you should also use the ``pip`` script from there. Ensure that by providing the correct setup for your shell in "$HOME/.bash_profile" / "$HOME/.bashrc" or "$HOME/.profile".

If you are using ``homebrew`` ...
The "System Python" also uses "/Library/Python/2.7/..." (for site-packages) which is sometimes mixed up by your own installation.

**Comment by carlosmmelo** [comment]
@jenisys  just checked it

```
$ which python
/usr/local/bin/python
➜  which behave
/usr/local/bin/behave
➜ which pip
/usr/local/bin/pip
```
```
$ vim `which behave`
#!/usr/local/opt/python/bin/python2.7

# -*- coding: utf-8 -*-
import re
import sys

from behave.__main__ import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())

**Comment by carlosmmelo** [comment]
I've just reinstalled `behave` and also still having same issue.

**Comment by jenisys** [comment]
Which just points you to which scripts you are using.
The scripts use the SHE-BANG to determine which python interpreter is used by the script.
The output above (/usr/local/opt/python/bin/python2.7) points to another location than you stated initially.

Create a virtual environment and activate it.
Install behave there.
Check if the problem still persists.
If the problem is gone in the virtual environment, your python installation or your  shell configuration is broken. Determine what the problem is and/or uninstall the problematic parts and reinstall them.

**Comment by carlosmmelo** [comment]
Ok so I figured out what was my issue.

I'm using Google python library for google'd api (specifically to access emails on gmail) [google-api-python-client](https://developers.google.com/gmail/api/quickstart/python)

Following their example on the above link, the following was causing this issue with `behave`:

```
try:
    import argparse
    flags = argparse.ArgumentParser(parents=[tools.argparser]).parse_args()
except ImportError:
    flags = None
```

This is used by the [oauth2client](https://github.com/google/oauth2client) on its [run_flow method](https://github.com/google/oauth2client/blob/af6d3eb8067d5c95fb59af6fb62a192e6c7fa16b/oauth2client/tools.py#L115)

By just removing the above try/except statement this issue go away instantly.

Apparently this `argparse` is overriding whatever `argparse` defined in `behave`, however since I'm not having a server for this command line tool from google's library its OK for me to not have the try/except statement there, but It's a good catch to document this type of incompatibility if we try to use the `arparse` python library anywhere.

Hope this helps anyone that could potentially face this same use case.

**Comment by jenisys** [comment]
Good that you solved the problem and found out what is causing it.
:-)

**Comment by rodionAI** [comment]
@carlosmmelo had exactly the same problem! Thank you for posting the follow-up!!
