### ISSUE TITLE
No logging appears from environment hooks

### ISSUE THREAD

**Issue by quantoid** [behave/behave#387]
*Feature:* Logging
*Scenario:* Logging inside hooks

*Given* a minimal features directory with this simple hook:

    from time import sleep
    from logging import getLogger

    def before_all(context):
        context.config.setup_logging()
        context.logger = getLogger("steps")
        context.logger.warn(">> before_all")
        sleep(10)  # pretend to set up stuff
        context.logger.warn("<< before_all")

*When* I run behave
*Then* I see the logging from the hook in real time << **FAIL: No logging appears at all**

It doesn't appear to be possible to set things up so that logging from hooks appears in real-time, which is a problem if you have to set things up that take a while and you want to monitor progress.

**Comment by quantoid** [comment]
If I add this above the hook function then it works fine:

    config.dictConfig({
        'version': 1,
        'formatters': {
            'plain': {
                'format': '%(asctime)s %(levelname)s [%(name)s] %(message)s',
            },
        },
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
                'formatter': 'plain',
                'stream': stdout,
            },
        },
        'root': {
            'level': 'DEBUG',
            'handlers': ['console'],
        },
    })

**Comment by jenisys** [comment]
Look at the logging and log capture related features under ``features/log*.feature``.
Normally logging is captured per default. This means, it is only show when an error/failure occurs.
Use ``behave --no-logcapture features/`` to check if your log output appears.
If that is not the case, your log-level (warn) may be too low. Check with error level.
If everything fails, debug into the log-setup and log-output statements.

**Comment by quantoid** [comment]
Turning off logging capture makes logging visible but I really wanted to capture logging within scenarios because it helps to see what's happening on failed steps.

    $ behave --no-logcapture
    WARNING:steps:>> before_all
    WARNING:steps:<< before_all
    Feature: example # test.feature:1
    :

**Comment by quantoid** [comment]
Okay, my understanding is that normally `context.config.setup_logging` will only set up the capture handler, so nothing appears unless a step fails, unless you specify `--no-logcapture` in which case you get a stdout handler, so logging appears in real time. 

My solution here is to pass in a configuration file that sets up a stdout handler so you aways get real time logging, even in hooks, as well as captured logging on failed steps.

**Comment by quantoid** [comment]
So I guess the real issue here is the `@capture` decorator described in the documentation seems redundant since logging in hooks is always captured anyway.

**Comment by jenisys** [comment]
No, the behavior is different. It is actually what you are looking for, but just not sensible to use in the ``before_all()`` hook. There is the point where you need to setup the logging subsystem and the user needs to decide how the logging subsystem is set up.

Look at the documentation of the ``behave.log_capture.capture`` decorator. It captures the logging in the hook and prints it when you leave it (if any logging occurred) regardless of error conditions.
