### ISSUE TITLE
Last logging statement not printing in console

### ISSUE THREAD

**Issue by admas82** [behave/behave#389]
Trying to out put strings to the console the last logger.info() statement does not print.
If there is only one logger.info() then nothing prints.

Example:

feature file:
       Feature: Last logging statement does not print on screen

       Scenario: Print 4 lines in terminal

                Given I print 4 lines in the terminal
steps/steps.py file
      from behave import Given, When, Then
      import logging

      logging.basicConfig(level=logging.INFO)

      @Given("I print 4 lines in the terminal")
      def print_four_lines(context):

           logging.info('111111111111')
           logging.info('222222222222')
           logging.info('333333333333')
           logging.info('444444444444')

$ behave --no-capture

console:
Feature: Last logging statement does not print on screen # logging_bug.feature:2

  Scenario: Print 4 lines in terminal     # logging_bug.feature:5
    Given I print 4 lines in the terminal # steps/logging_steps.py:8
INFO:root:111111111111
INFO:root:222222222222
INFO:root:333333333333
    Given I print 4 lines in the terminal # steps/logging_steps.py:8 0.001s

1 feature passed, 0 failed, 0 skipped
1 scenario passed, 0 failed, 0 skipped
1 step passed, 0 failed, 0 skipped, 0 undefined
Took 0m0.001s

**Comment by admas82** [comment]
Only see this on mac terminal. 
It works fine on Cygwin and CMD(windows).

**Comment by jenisys** [comment]
Actually, it prints on screen but is overwritten by the pretty formatter.
The pretty formatter (with colouring enabled) prints the step twice:
1. Initially (in grey) to show that the step is executed
2. After execution of the step with result colouring (PASS or FAIL)

When you disable the capture mode, your logger writes also on the screen.
The pretty formatter knows nothing about this. Therefore, it only moves the cursor one line up and writes the second phase,

Use the plain formatter to verify that.
On Windows, colouring is normally disabled. Therefore, you don't observe the two phase print.
On Cygwin, you should not have this limitation. Therefore, I assume you use a Windows Python and not the Cygwin Python installation.

**Comment by admas82** [comment]
You are correct.
I used the command `$ behave -f plain` I get all lines printed.

I searched for how to display colors in Windows and have no success. Can you tell me please.

Thank You.

**Comment by GotGitHubAccount** [comment]
I tried to get the same. I have given print statement in Given, When and Then. However its printing what ever in the first given and then statement, but not printing for others. There is 2 given 2 when and 2 then in my behave test. However only for first given and then its printing not for any other. :(
