### ISSUE TITLE
Support variables

### ISSUE THREAD

**Issue by jwendell** [behave/behave#390]
It would be nice if we could define a variable in a step and reference it later.

Given $MY_FILE=/path_to_some_file
...
Then file $MY_FILE should contain ...
And file $MY_FILE should contain ...
And file $MY_FILE should contain ...

What do you think?

**Comment by jenisys** [comment]
This is already supported:
* when you provide such a mechanism in your step implementation and 
  store the variables in the context or  retrieve the variable information from the context
* when you use ScenarioOutline with the corresponding placeholders (as variable)

**Comment by jwendell** [comment]
I see... I was thinking about the first option, if behave could handle transparently variables assignments and substitutions.

Feel free to close if this is an idea that's not worth implementing...

Thanks.

**Comment by jenisys** [comment]
Think about it and provide a pull-request if this can be solved in a generic way. If this can be solved in a generic way, using decorators might be a way to inject the functionality and allows the step-writer the possibility to control it.

**Comment by jenisys** [comment]
CLOSED: 
* No pull-request was provided. 
* Functionality can be provided by extension that is used in step implementations
