### ISSUE TITLE
Logging output overwritten when using 'pretty' formatter

### ISSUE THREAD

**Issue by borbamartin** [behave/behave#394]
Hey there.

Just noticed the logging output gets overwritten by Behave's logger when using the default formatter ('pretty').

Here's an example:
<img width="1134" alt="screen shot 2016-01-12 at 16 50 20" src="https://cloud.githubusercontent.com/assets/9509643/12278010/9e1ff47e-b94c-11e5-84b9-51ae75ea9211.png">

As you can see after Behave's log, the actual logger line's first characters (date, class, logger level and a dict containing the headers) were replaced by Behave's message, instead of being output in a different line.

This does not happen when 'plain' formatter is specified, but the output is not pretty :(
I'm using 1.2.5.

Thanks!

**Comment by jenisys** [comment]
DUPLICATES: #389

**Comment by borbamartin** [comment]
The situation is kind of the same, still, it's not fixed, there should be a way it did not write over the upper line if logging is enabled. 

Do you think this is going to be developed or will we have to stick to 'plain' formatter @jenisys ?

Thanks!

**Comment by jenisys** [comment]
The situation is currently as is. You can still use the pretty formatter when you disable colours. Then the formatter uses an print only once mechanism that does not have the problem. Feel free to provide a pull-request that fixes the problem in a sane way.
