### ISSUE TITLE
How to use behave4cmd0 steps library

### ISSUE THREAD

**Issue by esciara** [behave/behave#395]
Hi,

I would like to use the steps library in `behave4cmd0` to test my own code. I am trying by copying a `features/steps/use_behave4cmd_steps.py` containing (copied from the same location in `behave`'s github):
 
```
import behave4cmd0.__all_steps__
import behave4cmd0.passing_steps
import behave4cmd0.failing_steps
```
But I get the following error:
```
Traceback (most recent call last):
[..]
  File "features/steps/use_steplib_behave4cmd.py", line 7, in <module>
    import behave4cmd0.__all_steps__
ImportError: No module named behave4cmd0.__all_steps__
```
What do I need to do to get around the pb and load the steps library? (still a few things to learn about the way python loads modules :-/ )

Em

**Comment by jenisys** [comment]
The ``behave4cmd0`` library is currently bundled in the ``behave`` source distribution. But it is not installed when you install behave. Therefore, you need to copy the "behave4cmd0" subdirectory tree to your project and you must ensure that it is located in the python search path (for example by using the ``PYTHONPATH`` environment variable). 

Note that you can also use the "features/environment.py" file to ensure that the python search path is currently set up to import your step libraries.

SEE ALSO:
  * Python documentation of ``PYTHONPATH`` environment variable
  * [features/environment.py](https://github.com/behave/behave/blob/master/features/environment.py)

**Comment by esciara** [comment]
Thanks It worked. :)

Is there a lot missing to make it a separate release? It is already full of useful things and I noticed that you mentioned it already in #245 , dated Dec 14, 2014 and commit in https://github.com/behave/behave4cmd dates Jul 6, 2013 .

**Comment by esciara** [comment]
@jenisys no chance to get an answer to my previous questions?

**Comment by jenisys** [comment]
@esciara 
I thought I already answered your questions ;-)

The problem with the current "behave4cmd" implementation (in my private repository) is time. The implementation is there. But I need to provide more tests and polish the documentation. In addition, I need to ensure python3 compatibility. Therefore, I bundled the small brother "behave4cmd0" with behave.

**Comment by esciara** [comment]
Thanks for the news. :) I see you might be as perfectionist as I am :)))

And I found some advantages in letting go of it some times... What about releasing the thing as it is and let others help with getting it up to scratch??!? If it becomes accessible, more people would use it and love to help out. I could, in some the little spare time I have, on the parts I would find useful.  Jul 6, 2013... that is a long time ago. ;-)

What you say?

**Comment by jenisys** [comment]
;-)

**Comment by zymergen-mbarton** [comment]
I agree. The behave4cmd library is useful and I would like to see it either installed as part of this package (#482) or released as a usable package by itself.
