### ISSUE TITLE
Problem with textutil in Assertation

### ISSUE THREAD

**Issue by FZetting** [behave/behave#396]
The textutil.text(value, encoding=None, errors=None) returns an invalid message string for the raised Assertation when the string is like u'XXXXX\\01_XXXXX.feature:60.'.
It seems that the escaping and replacing in line 79 is the problem.

The code shows the problem separated.

System Python 2.7.11. behave 1.2.5

-------------------------------------------------------------------------------------------------------------
    import re
    import os
    
    import six
    
    strings = ['{0}'.format('XXXXX\\01_XXXXX.feature:60.'),
               u'{0}'.format('XXXXX\\01_XXXXX.feature:60.'),
              '{0}'.format('XXXXX\\XXXXX.feature:60.'),
               u'{0}'.format('XXXXX\\XXXXX.feature:60.'),
              ]
    
    
    def raw_string(s):
        if isinstance(s, str):
            s = s.encode('string-escape')
        elif isinstance(s, unicode):
            s = s.encode('unicode-escape')
        return s
    
    def path_escape(path_string):
    
        data = str(path_string)
        text = six.text_type(data, "unicode-escape", "replace")
        return text
    
    
    if __name__ == '__main__':
        for pos, name in enumerate(strings):
            print pos, name
            print pos, path_escape(name)
            print pos, raw_string(path_escape(name))
            print pos, raw_string(name)

-------------------------------------------------------------------------------------------------------------

Franz

**Comment by jenisys** [comment]
DUPLICATES: #336 
NOTE: raw_string() implementation should not encode in both cases.
