### ISSUE TITLE
Add an option for only displaying the undefined step stubs

### ISSUE THREAD

**Issue by rapilabs** [behave/behave#397]
It would be nice addition to have an option that only shows the undefined step stubs so I can quickly redirect that output into a new python script.

Currently I can get the output down to a comment and the stubs with the following options:

`behave -d --format null --no-summary`

however it still displays the message "You can implement step definitions for undefined steps with these snippets:"

Perhaps an extra option that invokes the options listed above as well as removing that line would be awesome?

**Comment by rapilabs** [comment]
Oh and also, can we have the stubs printed to stdout, just makes it that little bit easier :)

**Comment by rapilabs** [comment]
Oh and PEP 8 compliance would be the cherry on top! ;)

**Comment by jenisys** [comment]
@rapilabs 
Implement a formatter (like: "formatter_ext/undefined_steps.py") that does exactly that.
Then you can run ``behave --dry.run -f undefined_steps -o my_undefined_steps.py``.

But note that you anyway need to implement the undefined steps. Therefore, you are allowed to write a few letters or remove some. And redirecting stderr (means skipping stdout output from the other formatters) should simplify to create a file for the undefined steps in the other use cases.

AFAIK, the snippets are PEP8 compliant.
Where do you see a problem?
