### ISSUE TITLE
How about tearDown?

### ISSUE THREAD

**Issue by vit1251** [behave/behave#399]
For example, we fall in the registration scenario on checking. Another start-up, has dropped because of the registration user already exists. Is it possible to do something like tearDown?

```
Given server
When Register                     #                       # Second fail there - user already exist
And Update Avatar              # First fail there - File too long
Then User profile exist
```

How to make clean up?

P.S. ... always must use "Background"?

Thanx.

**Comment by carlosgoce** [comment]
Check this out:

https://pythonhosted.org/behave/tutorial.html#environmental-controls

before_step(context, step), after_step(context, step)
These run before and after every step.

**Comment by vit1251** [comment]
Environment `after_scenario` not good idea: each scenario may create specific user and write "god remover" is not good idea. This solution unsuitable.

'Given the user xxx is not registered' is look more suitable but after this test system have unclean with thausend register users.  It looks that this test's design inaccurat.

**Comment by jenisys** [comment]
The last cleanup step that you suggest is BAD. It does not belong to the test (= the readable test description of the scenario). You can do it, but I would not recommend it. 
You are the implementer of the steps (hopefully). Therefore your step implementation may contain or add the cleanup logic where needed.

If you have complex cleanup semantics, you have the following possibilities (besides ``after_scenario()`` hook):

1. Use tags to mark specific setup/teardowns and add the needed logic where needed (like: @clean_userdb) in ``before_tag()`` (setup and maybe cleanup) and ``after_tag()`` hook (teardown).
This is sensible if you have only few specific cleanups. In addition, you may add these tags temporarily to scenarios (for diagnostics or fault isolation).

2. Add a ``scenario_janitor`` object to the context (in the ``before_scenario()`` or step implementation).
A step implementation can then register its cleanup functions, like:  ``context.scenario_janitor.register_cleanup(my_cleanup_function)``.
The ``after_scenario()`` hook can that trigger the cleanup like ``context.scenario_janitor.cleanup()``.
This approach is similar to what unittest frameworks like ``unittest`` module or ``py.test`` provide.

**Comment by vit1251** [comment]
Thanx. I thinking about `scenario_janitor` before you answer and now also thinking about you suggest. But I understand another you point "It does not belong to the test" and it more convincing.

**Comment by ncoghlan** [comment]
Regarding the "scenario janitor" suggestion, I just changed my `before_scenario` step to look like this:

    def before_scenario(context, scenario):
        context.resource_manager = contextlib.ExitStack()

while `after_scenario` gained the line `context.resource_manager.close()`

I've filed https://github.com/behave/behave/issues/505 to discuss the idea of recommending that explicitly in the docs, or even providing it by default.
