### ISSUE TITLE
Parameter autogeneration problem?

### ISSUE THREAD

**Issue by vit1251** [behave/behave#400]
Most common problem is generate parameter on table

Let's I show eample
```
Given registration users
    | Name | Username | Email       | BDay            |
    | abc     | abc            | abc@abc | 2012-12-12 |
    | abc1    | abc2         | abc2@abc | 2012-12-13 |
```

Here I would like imagine some DataProvider or parameter generator. What you think about that?

**Comment by jenisys** [comment]
Feature files are text. Generate it with your favourite template engine.
Or provide a step that generates it for you (with your DataProvider).
Or provide a step that reads it from a CSV/JSON file.

The problem is that there is no generic solution. What is sensible to you, may not be sensible for the next person. Therefore, you can adapt the step implementations to your needs.

**Comment by vit1251** [comment]
It just thinking about DataProvider but now I think that I just provide data provider via classic parameter and call by values = getattr('...')().

Thanx for answer.

**Comment by jenisys** [comment]
A final note. If you were thinking about something like [quick check](https://en.wikipedia.org/wiki/QuickCheck) as test data generator, look at [hypothesis](https://hypothesis.readthedocs.org/en/master/).

But as I said, you would normally use it:
* in a step implementation
* in the template (generation) for a feature file (by using a template engine)
* as tag for a ScenarioOutline Example table (but ``behave`` does not support tags there yet), like

```gherkin
# -- SOURCE: http://www.specflow.org/plus/excel/getting-started/
# @source tag mechanism loads table data from another file (example of a simple data generator)
ScenarioOutline:
    ... (some paramterized steps here)

   @source:CalculatorExamples.xlsx
   Examples:
      | case | a | b | result |
```
