### ISSUE TITLE
Parameter specify type

### ISSUE THREAD

**Issue by vit1251** [behave/behave#401]
Let's I show eample
```
Given customer create API request with property
   | Name                           | Value |
   | user_id                         | abc    |
   | user_network_address |  ???  | # Need some think like Jinja2  {{ network.ip }}
   | current_time                  | ???   |
   | debug                            | True  |   # There no "True" but type bool
   | request_number            | ???   |   # context.last_request_number + 1
```
Now I think we can use json.dumps but in future how about extends this interface with additional labnguage?

**Comment by jenisys** [comment]
The Gherkin syntax for feature file is defined as is.
But feature files are text file. If you need to generate your feature files from templates+data, feel free to do it. 

In your case. your step implementation can easily implemented the needed logic for automatic computed/discovered values. Just define a naming-convention or automatically provide computed values for properties that are missing in your property table, etc.

**Comment by vit1251** [comment]
OK. Thanx.

**Comment by jenisys** [comment]
A final note. If you were thinking about something like [quick check](https://en.wikipedia.org/wiki/QuickCheck) as test data generator, look at [hypothesis](https://hypothesis.readthedocs.org/en/master/).

But as I said, you would normally use it:
* in a step implementation
* in the template (generation) for a feature file (by using a template engine)
* as tag for a ScenarioOutline Example table (but ``behave`` does not support tags there yet), like

```gherkin
# -- SOURCE: http://www.specflow.org/plus/excel/getting-started/
# @source tag mechanism loads table data from another file (example of a simple data generator)
ScenarioOutline:
    ... (some paramterized steps here)

   @source:CalculatorExamples.xlsx
   Examples:
      | case | a | b | result |
```
