### ISSUE TITLE
How to fail when scenario does not steps

### ISSUE THREAD

**Issue by vit1251** [behave/behave#402]
Hello, how to fail scenario when no steps is implemented?

**Comment by jenisys** [comment]
A scenario that contains undefined steps (= not implemented steps) automatically fails.

SEE:
[features/step.undefined_steps.feature](https://github.com/behave/behave/blob/master/features/step.undefined_steps.feature)

**Comment by vit1251** [comment]
Now I see in xUnit reporter status pass.

**Comment by jenisys** [comment]
Which behave version are you using (pypi, Github) ?
Try to run the feature file from above with your behave version.

**Comment by vit1251** [comment]
I say about scenario without steps.
In real life no test without steps and this is unimplemented test and in best case it skipped.

**Comment by jenisys** [comment]
That is a matter of definition (or opinion). For example, in any test framework that I know, a test will pass when it has no implementation (body) with assert checks. 

Mark your "EMPTY-SCENARIOS" with tag ``@not_implemented``. That makes them easier to track, find or skip.
