### ISSUE TITLE
Log capturing researching

### ISSUE THREAD

**Issue by vit1251** [behave/behave#403]
Hello,

I design and implement some scenario with `progress` tag and debugging by write stdout and logging.

`stdout` capturing work well, but work with logging unpredict:

* Does not understand from documents how to work filtering (-foo,boo) and how about `root` logger?
* Logging only write when test is failed? Can I enable write logging capturing on everytime?

**Comment by jenisys** [comment]
Captured stdout/stderr/logging is normally only shown when a test fails.
To always show output (stdout/stderr/logging), try to disable capturing by using ``behave --no-capture ...``  (or: ``--no-capture-stderr``, ``--no-logcapture``) for example.

Logging filters allow you specify that some log categories are excluded from being captured (or specifically included).

**SEE ALSO:**
* ``features/*capture*.feature``
* example: [features/logcapture.filter.feature](https://github.com/behave/behave/blob/master/features/logcapture.filter.feature)

**Comment by LeoHuckvale** [comment]
I'm having trouble here too. I ideally would like to see the logging interwoven with the step printouts, like:

    Given thing happens
    When some step with logging
        INFO:steps:foo bar
    Then something else

I'm logging from within the step files, e.g.:

    import logging
    log = logging.getLogger('foo')

    @step('some step with logging')
    def step_impl(context):
        log.info('foo bar')

I've tried running the feature like:

    behave --no-logcapture --no-capture

I'd also like to see the log output even if everything passes. I find it useful while developing the test suite.

Any help would be much appreciated. I'd be happy to have a go with a pull request too, if you can give any pointers.

**Comment by jenisys** [comment]
@LeoHuckvale 
Note that the output order depends on the formatter when you disable the capture mode.
For example, the plain formatter prints the the step and its result after the step is executed and the result is known. Therefore, you will never ever have the desired behaviour with this formatter.
The pretty formatter in no-color mode behaves the same.

OUTPUT-ORDERING: 
Can only be ensured when you capture the output from stdout/logging.
But then you will not see the captured-output when the step passes.

**Comment by vit1251** [comment]
@jenisys how to create a mirror of captured logs in separate "debug.log" file?

**Comment by vit1251** [comment]
@jenisys you say that "Captured stdout/stderr/logging is normally only shown when a test fails." it no good idea and some time logs arrchiving and research on prevoius starting very usful. Could you provide always capture and store in JUnit error logs?

**Comment by jenisys** [comment]
@vit1251 
No, that is not a good idea to do that in junit reports. It will clutter them with irrelevant details even when all/many tests are passing. 

What you should do, is to log the stuff you are interested in into a log-file and use it when needed (for doing the research) even when tests pass. This helps you also with long-running tests (that you hopefully not have) to see up to which internal step the system came. But you should be able to do that already by using log-filters for log-categories (excluding them from log-capture mode).

**Comment by vit1251** [comment]
@jenisys I would like to understand how I can to log into a separate file when the --junit is captured logs and it's killing my settings made in basicConfig. This is the case the principle can be implemented, is it possible to write the logs and use --junit simultaneously or is it mutually exclusive?

Logs totally required later after month or year and we can make difference between response and debug information when problem occure around the tests. It very nice knowladge resource.

**Comment by jenisys** [comment]
@vit1251
You could for example use stdout/stderr for diagnostic info in failing steps and use logs in not-logcapture mode to log to a file. Otherwise, use logging-filters to ensure that information is always logged even when the scenario passes.
 
SEE ALSO:
* [features/logcapture.filter.feature](https://github.com/behave/behave/blob/master/features/logcapture.filter.feature)
* [features/logging.setup_with_configfile.feature](https://github.com/behave/behave/blob/master/features/logging.setup_with_configfile.feature)
