### ISSUE TITLE
General question about python application workflow

### ISSUE THREAD

**Issue by conFusl** [behave/behave#404]
Hi,
I'm not sure if this is the right place to discuss such a question, please let me know if there is another place or possibility where I can get the information needed. 

I'm currently working on my master thesis, where I develop a tool to use BDD testing in combination with embedded software. The thesis concentrates on integration tests, so I have an ECU with a running application and my tool which tests the application. The idea is to start my tool which parses some configuration files and sets up the test hardware, then the execution of the tests using `behave` and afterwards the execution of some other functions (generate/manipulate the test report and teardown functions).
Now my question: I'm having troubles to find an appropriate solution to handle the application workflow of my tool. For example I want to execute the tool like `behave `in the directory where the .feature files are located. The configuration file should also be located in the same directory. How can I get for example the directory from where the tool was called to pass it to my tool and parse my configuration file? `behave` also knows where the tool was called and searches in this directory for .feature and step files, so I'm wondering what's the best practice approach to face this kind of issue. 

I'm asking this here because I'm using `behave `inside my tool and the issue I'm facing is somehow also implemented in `behave`, therefore it would be great if someone could either explain this concept to me or send some information covering this issue. Also, I would be very grateful if someone is interested in my work to have a closer look on it and discuss some general points, issues or design facts.

If you need additional information to help me please feel free to ask. We can relocate the discussion also to another place (email, skype....)

I hope to get some kind of help, this is my first python application of this size and it would be great to get some feedback from people with more experience in python development.

BR,
conFusl

**Comment by jenisys** [comment]
## POINT 1: Accessing related resources/tools

There are basically 2 concepts:

1. CURRENT_DIR (current working directory) where your shell currently is
   when you start to execute a program (behave, your tool, ...)

2. HERE idiom: Computes where your file is located from within the file

The HERE idiom allows you to compute the location of related resources by knowing where a file is located and knowledge of a subdirectory tree structure (independent where the ROOT or TOP directory is installed)

The HERE idiom is rather robust when you want to relocate your subdirectory
tree (for example putting it on an USB stick or other drive). The main reason for that is that internal subdirectory changes less often than the exact location
were a program/project is installed or located.

Note that using the HERE idiom makes you independet what your CURRENT_DIR is.
Try to execute the following scripts from different CURRENT_DIRs:

```bash
#!/usr/bash
# EXAMPLE: HERE idiom in bash shell script (UNIX)

HERE=$(dirname $0)
RELATED_FILE="$HERE/../README.txt"

echo "HERE=$HERE"
echo "RELATED_FILE=$RELATED_FILE"
```

```python
#!/usr/bin/env python
# EXAMPLE: HERE idiom in python script

from __future__ import print_function
import os.path

HERE = os.path.dirname(__file__)
RELATED_FILE = os.path.abspath(os.path.join(HERE, "..", "README.txt"))
print("HERE=%s" % HERE)
print("RELATED_FILE=%s" % RELATED_FILE)
```

As you can see, it is rather important to define how your directory structure should look like. If your tool is in another location (and this location may vary), you often define an environment variable where the ROOT directory of the installed tool is located. 

SEE ALSO:
  * Python modules: os, os.path  
    (os.getcwd(): get current working directory, 
     os.environ: access environment variables or modify them)
  * Example for HERE idiom: [bin/behave](https://github.com/behave/behave/blob/master/bin/behave)

 
## POINT 2: Application workflow

There are different solutions:

* EXTERNAL SOLUTION: Use a build-script (shell script, makefile, ...) to glue the execution logic together how your tool (setup, ...), the test run, teardown and report post-processing should occur

* TOOL-INTERNAL SOLUTION: The coordination logic is implemented in your tool

* BEHAVE SOLUTION (with build-script): Use before_all(), after_all() hooks for setup/teardown with your tool (if needed)

Note that this assumes that your tool is a command-line tool that be executed as subprocess from python/behave. A GUI tool would need an API that could be used from python/behave.

In addition, note that setup/teardown should be often part of the BDD tests (but you may hide the gory details in the step implementation).

**Comment by conFusl** [comment]
Thanks for the detailed answer.
I'm trying to extend my question with an example, so I can check if I'm understanding your things correctly and search for the rest of the needed answers. 
Saying I have installed `behave` in `C:\Python27\Lib\site-packages\behave` and I have the feature files located in `D:\MyFolder\MyFeatureFiles` which is also my current directory. If I call `behave` in this directory, the HERE idiom would say, that HERE is the installation location of behave, named `C:\Python27\Lib\site-packages\behave` and this will not change, no matter where I call `behave` (except the installation path of `behave` changes. 
If I'm using `os.getcwd()` I get the path where I called my script (`D:\MyFolder\MyFeatureFiles`). Does this value stay constant for the rest of the application flow or is it possible that this value changes due to some operations(except intentional directory change)?

Thank you very much for your remarks. The tool will be command-line only. I'm not quite sure which parts I will outsource and for which things I will use the behave - environmental - controls. The main reason for own setup/teardown functions is that the user can specify the used hardware in the configuration file and doesn't have to worry about initialization and release in the tests. If implementing this with behave, every user has to implement it in every project where my tool will be used (at least implement the function calls to initialize/release). And due to the fact I'm dealing with embedded software, each project needs some kind of test hardware, therefore it's project independent. Does this sounds reasonable to you? 

BR

**Comment by jenisys** [comment]
If you install behave under python, you do not need the HERE idiom. Behave is installed globally and is frozen (meaning: you cannot/should not change it there). The python installation normally takes care that you can use it. On Windows, you should have ``C:\Python27;C:\Python27\Scripts`` in your ``PATH`` (the ``Scripts`` subdir part is missing sometimes after the Python installation under Windows).

You can only use the HERE within your projects, meaning in a script ``D:\MyFolder`` for example.
The HERE idiom helps you to provide a project structure (directory structure) than can easily be moved or used in different locations without need of configuring it. Scripts can automatically determine the location of other related files with the project structure.

REGARDING:  CURDIR = ``os.getcwd()``
Your tools, scripts or tests may change the current working directory, like ``os.chdir("C:\tmp"). Therefore, you need take that into account (especially when you use relative paths instead of absolute paths).

REGARDING: setup/teardown
That part can be put into a python library and/or step library. Then you can share it between different projects (and reuse the functionality).
