### ISSUE TITLE
Exit code should be 0 if there is no rerun output file

### ISSUE THREAD

**Issue by carlosmmelo** [behave/behave#405]
We use jenkins as our CI; we have a job to execute behave tests as follow:

```sh
behave -ksT --tags=~@xfail features/
behave @rerun.txt
```

With:

```
# -- .behaverc file

[behave]
format = rerun
outfiles = rerun.txt
logging_level = INFO
junit = true
junit_directory = junitResults

```

- If there is no `rerun.txt` generated it means that the entire test suite passed, however `behave` is failing with:

```
FileNotFoundError: rerun.txt
```
With exit code `1`

- If there is a `rerun.txt` file generated then the job will run the failing tests and pass the "build" process.

I know that there are other `FileNotFoundError` cases in `behave`, however specifically for the `rerun` case, I think it should be exit code `0` and dont print the FileNotFoundError exception. So basically just do nothing so that the user and the console assume theres nothing to `rerun`

**Comment by jenisys** [comment]
Mmh, but your CI script always tries to run the "rerun.txt" file in your second step.
You should put some minor intelligence in your script, like:

```sh
test -e rerun.txt && behave @rerun.txt
```

**Comment by carlosmmelo** [comment]
Oh you are right!

So based on [this](http://stackoverflow.com/questions/4510640/command-line-what-is-the-purpose-of) I need to use `||` in my case:

```
$ false || echo "Oops, fail"
Oops fail

$ true || echo "Will not be printed"
$  

$ true && echo "Things went well"
Things went well

$ false ; echo "This will always run"
This will always run
```

so:

```
behave -ksT --tags=~@xfail features/ || behave @rerun.txt
```

**Comment by jenisys** [comment]
:smile:
