### ISSUE TITLE
Documentation improve

### ISSUE THREAD

**Issue by vit1251** [behave/behave#406]
I suggest improve documentation about tags combination for various starts:

| Name | Command line | Idea |
| --- | --- | --- |
| Stable server | --tags=~@wip --tags=~@skip | Does not start @wip and not start @skip |
| Test Developer | --tags=@wip --targ=~@skip | Start only @wip and does not start @skip |
| App Developer | --tag=~@wip --tag=@skip | Start only @skip but does not @wip |

This also may be good idea suggest some common workflow testing process. But it another idea.

**Comment by bittner** [comment]
I like the idea of describing common testing workflows. Where would you add them in the documentation?

**Comment by vit1251** [comment]
@bittner I was searching this in tags section. But it may exists as individual section.
