### ISSUE TITLE
Test undefined error, even if step function is declared

### ISSUE THREAD

**Issue by Zigur** [behave/behave#407]
I have started using behave to define behaviour-driven tests on Python3. The first tests I implemented went fine, but now I am incurring in a most puzzling error.
I have already opened a question on Stackoverflow (http://stackoverflow.com/questions/35276199/behave-python3-test-undefined-even-if-the-step-function-is-present), I copy it here to have more visibility, because I cannot understand what I am doing wrong.
I am testing a conversion tools among different data formats (this is not relevant for the error itself)

I have define this Gherkin file `sra-to-isatab-batch-conversion.feature`:

    Feature: SRA to ISA-tab Batch conversion
    # perform a batch conversion of a set of SRA datasets, retrieved from the European Nucleotide Archive
    # to ISA-tab

    Scenario: Batch conversion form a list of SRA accession numbers
    Given An access number "ERA000084"
    And nothing else
    When the SRA to ISA tab conversion is invoked
    Then it should return a ZIP file object
    And the ZIP file should contain as many directories as the element in the list

Then I define the following step methods in a file `steps/sra-to-isatab-batch-conversion.py`

    from behave import *

    use_step_matcher("parse")

    @given('An access number "{access_number}"')
    def step_impl(context, access_number):
        context.access_number = access_number
        print(context.access_number)

    @step("nothing else")
    def step_impl(context):
        print("Nothing else") 

    @when("the SRA to ISA tab conversion is invoked")
    def step_impl(context):
        pass

    @then("it should return a ZIP file object")
    def step_impl(context):
        pass

    @step("the ZIP file should contain as many directories as the element in the list")
    def step_impl(context):
        pass

If I then run `behave sra-to-isatab-conversion.feature` the step function related to the when step appears to be missing:

    Feature: SRA to ISA-tab Batch conversion # sra-to-isatab-batch-conversion.feature:2

    Scenario: Batch conversion form a list of SRA accession numbers                  # sra-to-isatab-batch-  conversion.feature:6
    Given An access number "ERA000084"                                             # steps/sra-to-isatab-batch-conversion.py:6 0.000s
    And nothing else                                                               # steps/sra-to-isatab-batch-conversion.py:40 0.000s
    When the SRA to ISA tab conversion is invoked                                  # None
    Then it should return a ZIP file object                                        # None
    And the ZIP file should contain as many directories as the element in the list # None

    /Users/massi/Projects/oerc/isa-api/features/test_outputs

    Failing scenarios:
      sra-to-isatab-batch-conversion.feature:6  Batch conversion form a list of SRA accession numbers

    0 features passed, 1 failed, 0 skipped
    0 scenarios passed, 1 failed, 0 skipped
    2 steps passed, 0 failed, 2 skipped, 1 undefined
    Took 0m0.001s

    You can implement step definitions for undefined steps with these snippets:

    @when(u'the SRA to ISA tab conversion is invoked')
    def step_impl(context):
        raise NotImplementedError(u'STEP: When the SRA to ISA tab conversion is invoked')`

I have tried to redefine the step description change the number of given statements,I have even rewritten the files, but I always get this same errors. Even if I copy the statement suggested in the error message I still get the very same error.

Can anyone explain me what I am doing wrong? I am using Python 3.4 Behave 1.2.5 PyCharm 5.0.4 (notice that PyCharm BDD tools recognise the matching between statements in the Gherkin file and the step functions)

You can find the feature file here: https://github.com/ISA-tools/isa-api/blob/feat/sra2isatab/features/sra-to-isatab-batch-conversion.feature
And here the steps implementation: https://github.com/ISA-tools/isa-api/blob/feat/sra2isatab/features/steps/sra-to-isatab-batch-conversion.py

Thanks a lot for your help

**Comment by jenisys** [comment]
Sorry, I cannot reproduce your problem.
I tried it with your files and behave (version=1.2.5 and HEAD) and python versions 3.4.2 and 3.5.1 in clean virtual environments. The problem did not occur in any of the combinations.
Note that I only used the one feature file and the one steps as you requested.

Therefore, I assume that problem exists somewhere in your environment or installation.
Try to setup a clean, virtual environment and try to reproduce your problem there. Try to determine what the significant difference is that is causing your problem. Do it step by step.

**Comment by jenisys** [comment]
Another idea would be to set a breakpoint in the pretty formatter and run behave from the PyCharm debugger mode.

**Comment by Zigur** [comment]
Thank you. I will try as you suggested with a new virtual environment and see how it behaves. 
Thank you, I will let you know which was the issue when I find it out

**Comment by lucianofedericoolmedo** [comment]
I am having the same problem using Django 1.6.11 , python 2.7.11 , django_behave 0.3 and behave 1.2.5...

**Comment by lucianofedericoolmedo** [comment]
My issue is that i have one xxx.feature that recognize me everything and another one that is not working at all.

**Comment by jenisys** [comment]
@lucianofedericoolmedo 
How do you think I can help you when you provide me so little information. I never experienced the described behaviour.

* Do you use special characters (non-ASCII chars) ?
* Have all your feature files the same encoding (meaning: UTF-8) ?
* Use the steps formatter to check if all your steps are discovered correctly.
  This is basically a formatted dump of the step-registry contents.

EXAMPLE:
```sh
$ behave -f steps --dry-run features/
GIVEN STEP DEFINITIONS[40]:
  Given I setup the current values for active tags with                    # features/steps/behave_active_tags_steps.py:35
  Given the behave context has a parameter "{param_name}"                  # features/steps/behave_context_steps.py:37
  Given the behave context does not have a parameter "{param_name}"        # features/steps/behave_context_steps.py:41
...
 * I capture log records with level "{level}" or above                # behave4cmd0/log/steps.py:377
  * I capture log records                                              # behave4cmd0/log/steps.py:382
  * {word:w} step passes                                               # behave4cmd0/passing_steps.py:23
  * {word:w} step fails                                                # behave4cmd0/failing_steps.py:23

0 features passed, 0 failed, 0 skipped, 75 untested
7 scenarios passed, 0 failed, 5 skipped, 450 untested
0 steps passed, 0 failed, 15 skipped, 0 undefined, 1785 untested
Took 0m0.000
```

OTHERWISE: Try it with the newest version of behave (Github repository HEAD).

**Comment by lucianofedericoolmedo** [comment]
Sorry jenisys for such little description. Yes, all feature files has the same encoding and i am not using any special non-ASCII chars. Pycharm detect my steps.
Thank you for your time.

**Comment by lucianofedericoolmedo** [comment]
Actually, my tests are not working if I use something like this: 
# Created by spock at 20/09/16
Feature: FFF
  # Enter feature description here

  Scenario: GGG
    Given user enters register page
    When post data in register form
    Then it should be ok

But yes when I change the When for a Then and the @when with @then, they seem to work. Do not know why....

**Comment by jenisys** [comment]
@lucianofedericoolmedo 
Do you use explicit import of the step decorators in your step file ?

Like:
```
# -- FILE: features/steps/my_steps.py
from behave import given, when, then
...
```

NOTE: I sounds like you have (somehow) replaced the ``@when`` decorator with something else, like:

```
# -- FILE: features/steps/my_steps.py
from behave import given, when, then

# -- OVERWRITE DECORATOR (without intention)
def when(*args, **kwargs): pass

@when(u'I do something')   # -- OOPS: HERE
def step_impl(context):
    pass
...
```

**Comment by lucianofedericoolmedo** [comment]
No, I actually use from behave import * , but besides that, i do not
override the definition. It beats me..


2016-09-21 17:39 GMT-03:00 jenisys <notifications@github.com>:

**Comment by pratyush23** [comment]
hi
