### ISSUE TITLE
Error during run test on PyCharm with Behave runner (ImportError: cannot import name 'parse_scoped_name' )

### ISSUE THREAD

**Issue by safo-bora** [behave/behave#408]
Hello!
Do you support behave_runner.py for python 3.5 ?

PROBLEM:
I have Python 3.5
PyCharm 5.0.1

If I use python script for run test - everything works OK:
```
from behave import __main__

if __name__ == "__main__":
    __main__.main('./features --no-source')
```

I can't run test with runner.Have error:
```
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm 5.0.1\helpers\pycharm\behave_runner.py", line 245, in <module>
    from behave.formatter import _registry
  File "C:\Users\111111\AppData\Roaming\Python\Python35\site-packages\behave\formatter\_registry.py", line 4, in <module>
    from behave.importer import LazyDict, LazyObject, parse_scoped_name, load_module
ImportError: cannot import name 'parse_scoped_name'
```

![bdd_pycharm](https://cloud.githubusercontent.com/assets/4173393/13053878/78cf9480-d40f-11e5-8790-836af518567f.png)
![bdd_pycharm2](https://cloud.githubusercontent.com/assets/4173393/13053889/83dc04bc-d40f-11e5-9b71-ca9a521dc6ca.png)
![bdd_pycharm3](https://cloud.githubusercontent.com/assets/4173393/13053888/8334ac62-d40f-11e5-8372-05001c74ff4e.png)
![bdd_pycharm4](https://cloud.githubusercontent.com/assets/4173393/13053886/82eed30e-d40f-11e5-869f-410b2596e6ae.png)

**Comment by jenisys** [comment]
"behave_runner.py" comes from JetBrains PyCharm.

Which version of behave are you using ?
In a shell run ``behave --version`` .

It cannot be behave-1.2.5 because it does not contain the code that causes the error.
The current HEAD of the Github repository works, see Travis CI tests.

Try to uninstall and reinstall behave (with Python 3.5) or change your Python interpreter/path configuration in PyCharm.

**Comment by jenisys** [comment]
I tried to run a similar scenario like you in PyCharm 5.0.4 (OSX).
But note that I do not need to provide a command-script.
I just add a BDD run configuration with the correct working directory (and params).
I runs just fine when I select a feature in the project and use the run-configuration.

Are you using the Community version of PyCharm or the Professional version ?

**Comment by safo-bora** [comment]
Thanks for answer!
I use Professional PyCharm 5.0.1. Behave is 1.2.5.
I just reinstall behave and tests are OK.
It looks like was some my environment problem
