### ISSUE TITLE
Capture log from terminal to file

### ISSUE THREAD

**Issue by Kani999** [behave/behave#412]
Is there any way, to capture log from terminal:
  for example:
       
"""
Feature: Testing allocation committee # features/allocation_committee-extranet-test.feature:3

  @hoac_users
  Scenario: Add new project request in Allocation Committee                 # features/allocation_committee-extranet-test.feature:6
    When we click at Allocation committee at dropdown menu                  # None
    Then we should see new_project_requests button                          # None
    When we click at New
"""

and save it to file?

In enviroment.py i defined some functions, that creates a file and write into the file manually.
for example in:
def after_step(context, step): 
   context.log.write('        Step STATUS: '+ step.status+'\n')

If it's not possible, how can I sum number of skipped steps. 
I can calculate number of skipped features and scenarios, but not number of skipped steps:

   9features passed, 0 failed, 7skipped
   15scenarios passed, 0 failed, 6skipped
   53steps passed, 0 failed, 0skipped     #should be 57 skipped

I need log because of if log would be readed by some other script, and it detects a fail, it can send email to admins, or do something else.

Thanks for anwser.

**Comment by jenisys** [comment]
The easiest solution should be to provide your own Formatter and specify  it in the "behave.ini" configuration file. Note that you can use multiple formatters during a test run. 


Ciao,
Jens Engel
mailto:jens_engel@t-online.de

**Comment by Kani999** [comment]
Well i create my own logger, in enviroment.py i defined every before and after def's (step, scenario, feature ....) and call my methods from "behave_logger.py"

behave_logger.py
`# -*- coding: utf-8 -*-
# -- FILE: features/behave_logger.py
from datetime import datetime
import os
import re

whitespaces = 90
screenshot_path = './screenshots/'

features_passed = 0
features_skipped = 0
features_failed = 0
scenario_passed = 0
scenario_skipped = 0
scenario_failed = 0
step_passed = 0
step_skipped = 0
step_failed = 0
failing_scenarios = []


def log_before_all(path, context):
        # log file
    log = open(path, 'a')
    log.write(
        '##############################################################################\n')
    log.write(
        '####                                                                      ####\n')
    log.write(
        '####                           TEST STARTED                               ####\n')
    log.write('####                       ' + datetime.now().strftime(
        "%Y-%m-%d_%H-%M-%S") + '                            ####\n')
    log.write(
        '##############################################################################\n')
    log.close()


def log_exception(path, context, message):
    log = open(path, 'a')
    log.write("Unexpected error:", message)
    log.close()


def log_before_feature(path, context, feature):
    log = open(path, 'a')
    log.write(('Feature: ' + feature.name).ljust(whitespaces))
    log.write(' # ' + str(feature.location) + '\n')
    log.close()


def log_before_scenario(path, context, scenario):
    log = open(path, 'a')
    for group in scenario.tags:
        log.write('\n   @' + group + '\n')
    log.write(('  ' + scenario.keyword + ': ' +
               scenario.name).ljust(whitespaces))
    log.write('   # ' + str(scenario.location) + '\n')
    log.close()


def log_after_step(path, context, step):
    log = open(path, 'a')
    log.write(('      ' + step.keyword + ' ' + step.name).ljust(whitespaces))
    log.write('   # ' + str(step.location) + '  duration: ' +
              str(round(step.duration, 2)) + '\n')

    if step.status == 'passed':
        global step_passed
        step_passed += 1
    elif step.status == 'skipped':
        global step_skipped
        step_skipped += 1
    else:
        log.write('             ' + step.error_message + '\n')
        global step_failed
        step_failed += 1
        save_screenshot(screenshot_path, context, step)

    log.write('         step status: ' + step.status + '\n')
    log.close()


def log_after_scenario(path, context, scenario):
    log = open(path, 'a')
    log.write('   scenario status: ' + str(scenario.status) + '\n')
    log.write('   scenario duration: ' +
              str(round(scenario.duration, 2)) + '\n')

    for step in scenario.steps:
        if step.status == 'skipped':
            global step_skipped
            step_skipped += 1
            log.write(('      ' + step.keyword + ' ' +
                       step.name).ljust(whitespaces))
            log.write('   # skipped\n')

    if scenario.status == 'passed':
        global scenario_passed
        scenario_passed += 1
    elif scenario.status == 'skipped':
        global scenario_skipped
        scenario_skipped += 1
    else:
        global failing_scenarios
        failing_scenarios.append(str(scenario.location) + '  ' + scenario.name)
        global scenario_failed
        scenario_failed += 1

    log.close()


def log_after_feature(path, context, feature):
    log = open(path, 'a')
    log.write('feature status: ' + str(feature.status) + '\n')
    log.write('feature duration: ' + str(round(feature.duration, 2)) + '\n\n')
    log.close()

    if feature.status == 'passed':
        global features_passed
        features_passed += 1
    elif feature.status == 'skipped':
        global features_skipped
        features_skipped += 1
    else:
        global features_failed
        features_failed += 1


def log_after_all(path, context):
    log = open(path, 'a')
    log.write('Failing scenarios:\n')
    for fail in failing_scenarios:
        log.write('  ' + str(fail) + '\n')
    log.write('\n')
    log.write(str(features_passed) + ' features passed, ' +
              str(features_failed) + ' failed, ' + str(features_skipped) + ' skipped\n')
    log.write(str(scenario_passed) + ' scenarios passed, ' +
              str(scenario_failed) + ' failed, ' + str(scenario_skipped) + ' skipped\n')
    log.write(str(step_passed) + ' steps passed, ' +
              str(step_failed) + ' failed, ' + str(step_skipped) + ' skipped\n')

    log.write(
        '##############################################################################\n')
    log.write(
        '####                           TEST ENDED                                 ####\n')
    log.write('####                       ' + datetime.now().strftime(
        "%Y-%m-%d_%H-%M-%S") + '                            ####\n')
    log.write(
        '##############################################################################\n')
    log.write(
        '##############################################################################\n\n\n')
    log.close()


def save_screenshot(path, context, step):
    now = datetime.now().strftime('%Y-%m-%d_%H-%M-%S')
    tmp, filename = os.path.split(step.filename)
    s = filename + '-' + step.name + '-%s.png' % now
    s = re.sub(r"\s+", '_', s)
    context.browser.get_screenshot_as_file(path + s)
`

**Comment by jenisys** [comment]
Well, you basically reinvented the Formatter API (with your own means). If that serves you better, use it. But the formatter approach is much more flexible and configurable.

Just the ``save_screenshot()`` must be called from the environment when you need to access the browser.

**Comment by Kani999** [comment]
I dont know how to save log from API formatter to file, so i create my own. 
Well in the end, when i want to log, only some stuff like step fail, i dont have any problem with this now.
Thanks for your answer.

----- Původní zpráva -----
Od:"jenisys" <notifications@github.com>
Odesláno:‎26. ‎2. ‎2016 23:09
Komu:"behave/behave" <behave@noreply.github.com>
Kopie:"Kani999" <JanKrupa93@gmail.com>
Předmět:Re: [behave] Capture log from terminal to file (#412)

Well, you basically reinvented the Formatter API (with your own means). If that serves you better, use it. But the formatter approach is much more flexible and configurable.
Just the save_screenshot() must be called from the environment when you need to access the browser.

**Comment by jenisys** [comment]
Use the option 
```sh
$ behave --help
...
-o FILE, --outfile FILE
                        Write to specified file instead of stdout.
```
or with behave configuration file:
```ini
# -- FILE: behave.ini
[behave]
format   = rerun
    progress3
outfiles = rerun.featureset
    progress3.out
```

With this behave configuration file, you are using at least 3 formatters, 2 from the configuration file with outfiles (--outfile) attached, and a default-formatter or a specified formatter from the command-line writing to stdout. In general, you should have only one formatter writing to stdout. Otherwise, it may get confusing.

**Comment by janoskut** [comment]
> Well, you basically reinvented the Formatter API

Could someone elaborate where that "Formatter API" is documented? All I find is https://behave.readthedocs.io/en/stable/formatters.html.
