### ISSUE TITLE
Support for Jython 2.7

### ISSUE THREAD

**Issue by github-account-because-they-want-it** [behave/behave#414]
I've had a look over `tox.ini` and there seems to be support for Jython 2.5. I try to run some tests with 2.7 and I get this:

```
Traceback (most recent call last):
  File "/path/to/jython2.7.0/bin/behave", line 8, in <module>
    from behave.__main__ import main
  File "/path/to/jython2.7.0/Lib/site-packages/behave/__main__.py", line 5, in <module>
    from behave.configuration import Configuration, ConfigError
  File "/path/to/jython2.7.0/Lib/site-packages/behave/configuration.py", line 14, in <module>
    from behave.reporter.junit import JUnitReporter
  File "/path/to/jython2.7.0/Lib/site-packages/behave/reporter/junit.py", line 57, in <module>
    if sys.version_info.major == 3:
AttributeError: 'tuple' object has no attribute 'major'
```

**Comment by jenisys** [comment]
Should be easily fixed (if this is the only problem).

Jython support is seldom used for the following reasons:
* Jython 2.7 port took so long (but exists now)
* CI server, like Travis, have bad support for Jython (in most cases)
* Runtime performance of starting a subprocess sucks IMHO (sorry; process startup seems to be slow). 
  Therefore, running behave's own feature tests takes rather long.

If you are interested in using Jython 2.7 (or newer), take a look (and provide more tickets if anything else is not working).

**Comment by jenisys** [comment]
NOTE: Setting up a virtual environment for Jython 2.7 with ``virtualenv`` or ``tox`` currently fails (without manual fixes) due to problem in virtualenv/pip.

SEE ALSO: [github:pypa/virtualenv/issues/838](https://github.com/pypa/virtualenv/issues/838)

**Comment by jenisys** [comment]
INTEGRATED INTO: behave-1.2.6.dev0
Partial fix available.
Some issues still remain as described in the commit (unicode, ...).
