### ISSUE TITLE
JUnit XML output prone to non-XML-friendly stdout/stderr characters being captured

### ISSUE THREAD

**Issue by sanseihappa** [behave/behave#415]
If we enable JUnit and then have some step which captures non-XML-friendly characters, then we get invalid XML files.  This may cause consumers of the XML files to complain or error out.

**Comment by jenisys** [comment]
Make an example what you example mean and why do you think that XML consumer might have problems. Did you check the XML output for example with ``xmllint``?

**Comment by vit1251** [comment]
@jenisys for example you capture log and in log you send binary data from network. When parser try read Unicode char his cause Exception on Java or another XML parser. This require escape that sequance.

**Comment by jenisys** [comment]
@vit1251
You seem to be out of context. Show me a concrete JUnit XML output example and where it is wrong or invalid. Otherwise, we are talking about opinions instead of facts. In addition, use ``xmllint`` (or a similar tool) to verify that what you think is correct, is actually true.

**Comment by sanseihappa** [comment]
I'm seeing a bunch of escape characters that show up in the XML file as `^@` when viewed using vim.

**Comment by jenisys** [comment]
Can you provide a simple example that shows this problem ?

**Comment by sanseihappa** [comment]
Tiny behave example that exposes the problem is attached.
[behave-415.tar.gz](https://github.com/behave/behave/files/169751/behave-415.tar.gz)

**Comment by sanseihappa** [comment]
@jenisys Any update on this?  Could you point me to the portion of code that may need update and I'll be happy to contribute a PR with a fix

**Comment by sanseihappa** [comment]
This seems to work:
```diff --git a/behave/reporter/junit.py b/behave/reporter/junit.py
index 3b25700..cd12d01 100644
--- a/behave/reporter/junit.py
+++ b/behave/reporter/junit.py
@@ -3,7 +3,7 @@
 from __future__ import absolute_import
 import os.path
 import codecs
-import sys
+import string
 from xml.etree import ElementTree
 from behave.reporter.base import Reporter
 from behave.model import Scenario, ScenarioOutline, Step
@@ -16,6 +16,7 @@ import six
 def CDATA(text=None):   # pylint: disable=invalid-name
     # -- issue #70: remove_ansi_escapes(text)
     element = ElementTree.Element('![CDATA[')
+    text = filter(string.printable.__contains__, text)
     element.text = ansi_escapes.strip_escapes(text)
     return element
 
@@ -27,6 +28,7 @@ class ElementTreeWithCDATA(ElementTree.ElementTree):
 
         if node.tag == '![CDATA[':
             text = node.text.encode(encoding)
+            text = filter(string.printable.__contains__, text)
             file.write("\n<![CDATA[%s]]>\n" % text)
         else:
              # pylint: disable=no-member
```

**Comment by jenisys** [comment]
Serves as a work-around, but not the solution. Works also only for ASCII characters. Therefore, special characters like German Umlaute, French accented chars, Emoji, etc. are filtered out.

In addition:
```python
# -- HINT: Avoid direct use of special methods (like: __contains___())
# BETTER: Use operator.contains or `c in string.printable`
# NOTE: filter() function, as you use it, works only in Python2.
is_printable = lambda c: c in string.printable 
text = filter(is_printable, text)
```

SEE ALSO:
* [Porting Python3 to Python2: A.12 filter() function](http://www.diveintopython3.net/porting-code-to-python-3-with-2to3.html)

**Comment by sanseihappa** [comment]
How about this?

```
diff --git a/behave/formatter/ansi_escapes.py b/behave/formatter/ansi_escapes.py
index 1f0c975..41d0073 100644
--- a/behave/formatter/ansi_escapes.py
+++ b/behave/formatter/ansi_escapes.py
@@ -51,7 +51,7 @@ for alias in aliases:
 def up(n):
     return u"\x1b[%dA" % n
 
-_ANSI_ESCAPE_PATTERN = re.compile(u"\x1b\[\d+[mA]", re.UNICODE)
+_ANSI_ESCAPE_PATTERN = re.compile(u"\x1b\[\d+[mA]|\0", re.UNICODE)
 def strip_escapes(text):
     """
     Removes ANSI escape sequences from text (if any are contained).
```

**Comment by jenisys** [comment]
:smile: Sorry, that is also a hack for me because EOS is not an ANSI escape sequence. 
END-OF-STRING (EOS = ASCII 0 = '\0') should normally never appear in text/string.
Therefore, we need to understand why this happens (and where) and avoid it in the future.

**Comment by sanseihappa** [comment]
I agree that EOS / NUL should never appear in a string... but would it hurt to handle it?
How about this?

```
diff --git a/behave/formatter/ansi_escapes.py b/behave/formatter/ansi_escapes.py
index 1f0c975..cb277dc 100644
--- a/behave/formatter/ansi_escapes.py
+++ b/behave/formatter/ansi_escapes.py
@@ -52,14 +52,15 @@ def up(n):
     return u"\x1b[%dA" % n
 
 _ANSI_ESCAPE_PATTERN = re.compile(u"\x1b\[\d+[mA]", re.UNICODE)
+_NUL_ESCAPE_PATTERN = re.compile("\0")
 def strip_escapes(text):
     """
-    Removes ANSI escape sequences from text (if any are contained).
+    Removes ANSI and NUL escape sequences from text (if any are contained).
 
-    :param text: Text that may or may not contain ANSI escape sequences.
-    :return: Text without ANSI escape sequences.
+    :param text: Text that may or may not contain ANSI or NUL escape sequences.
+    :return: Text without ANSI or NUL escape sequences.
     """
-    return _ANSI_ESCAPE_PATTERN.sub("", text)
+    return _ANSI_ESCAPE_PATTERN.sub("", _NUL_ESCAPE_PATTERN.sub("", text))
 
 
 def use_ansi_escape_colorbold_composites():     # pragma: no cover
```

**Comment by sanseihappa** [comment]
@jenisys Wondering if the `_NUL_ESCAPE_PATTERN` is an acceptable solution?

**Comment by jenisys** [comment]
@sanseihappa No, I thought I made that clear. We need to solve the problem and not the effects of it. The solution is only a work-around (at least for me). If it helps you, use it until the real solution is provided.

**Comment by sanseihappa** [comment]
Ok sure.  Just to be clear then.  The solution here should be to eliminate the NUL character in the STDOUT being captured in the first place, and not handling it inside the behave code, right?  If so, I can live with that and we should close this issue out.  Thanks!

**Comment by sanseihappa** [comment]
Hmm, taking a step back, I think the only issue here is the corner-case handling of NUL characters.

@jenisys Where do you see handling of this special corner-case fitting into the existing code?

**Comment by dragonfi** [comment]
@sanseihappa Why did you close this? Is this no longer happens due to a merge?

**Comment by sanseihappa** [comment]
@dragonfi I closed because my proposed changes were not hitting the root of the issue.  No branch/version/commit was given because no merge has taken place.

Are you seeing a similar issue?
