### ISSUE TITLE
Move behave-django under the behave GitHub organization

### ISSUE THREAD

**Issue by mixxorz** [behave/behave#418]
Hey there!

I'm the maintainer of [behave-django](https://github.com/mixxorz/behave-django), a Django integration project for Behave. I made behave-django in the hopes of making Behave integration with Django easier. (Honestly, out of frustration with django-behave)

I was wondering if you'd be interested in moving behave-django under the behave GitHub organization. This would give behave-django more visibility, credibility, and ultimately make Django integration with Behave a whole lot simpler. Think of it as adding official support for Django.

Also, I'd like to mention that @bittner, behave-django's sole collaborator, was the one who thought of doing all this.

Anyway, what do you think? :grinning:

**Comment by jenisys** [comment]
:smile:, I made it short:
I created the repository under "https://github.com/behave" and imported your repository.
This will allow you to keep your repository and push pull-requests to the "new official repository".
You (@mixxorz) are currently assigned as Admin. Therefore, adapt what is still missing.
@bittner is currently proposed as collaborator with write-access. Therefore, he should be notified about this. If anything is missing, drop me a note or try to make the necessary changes.

**Comment by bittner** [comment]
Awesome!  :+1:

**Comment by jenisys** [comment]
:smile:

**Comment by bittner** [comment]
Hey @jenisys, thanks for the spectacularly unspectacular integration of behave-django into the behave organization! Looks like we're all set. Gitter chat room is active, builds are passing.

One minor (weird) thing I noticed about the organization membership: [behave](https://github.com/behave) shows up as an organization in @mixxorz's and my profile, but only when you're logged in. With anonymous, unauthenticated access it doesn't show. My other organization membership show though. That's probably some specifics about GitHub's new organization settings (privacy?) introduced some months ago.

**Comment by bittner** [comment]
Ah, the visibility setting is managed in the [people settings](https://github.com/orgs/behave/people) separately for each member. You can set this to "public" for me. Otherwise it may be in [team settings](https://github.com/organizations/behave/settings/teams). Cheers!

**Comment by mixxorz** [comment]
We did it!

**Comment by bittner** [comment]
@mixxorz Let me quote where I re-used your story (from above).  :hand: 

[Behavior-driven development. PyCharm + Python & Django](https://anvileight.com/blog/2016/04/12/behavior-driven-development-pycharm-python-django/#disqus_thread) (Disqus comment thread, AnvilEight blog)
