### ISSUE TITLE
RFE: allow backslash escaping long steps in feature files

### ISSUE THREAD

**Issue by lampmantech** [behave/behave#426]
This is a Request for a Feature enhancement that is very simple and works well for us.
We often have long step definitions, and often for example put required arguments as parameters in the step and optional arguments in a following table. Or parameters in the step may contain a long string like a filename.

So we patch behave to allow backslash escaping at the end of line in steps: the whitespace before the backslash newline and the whitespace at the beginning of the newline are collapsed into one space in parse_file of parser.py. Simply add:

data = re.sub('\ \ s*\ \ \ \ \ n\ \ s*', ' ', data)

before 

return parser.parse_feature(data, language, filename)

and at the top an

import re 

and then document the change.

Because of a github bug, I've put a space after each backslash above;
remove the space - there should be 2, 5 and 2 backslashes together in that code.

This allows us to keep our feature files pretty and easily to edit.

**Comment by jenisys** [comment]
I think I know what you want (a line-continuation for a step much like in a UNIX shell or makefile), but should at least provide a motivating example to show that.

How long are your lines anyway that you really need this feature ?
Just give me some number(s).

**Comment by lampmantech** [comment]
They'll often run 3 or 4 lines, and the line length also depends on the length of values
that are plugged in as parameters.

It's a one line change with I think no backwards incompatability, so I think it's good to add.

**Comment by jenisys** [comment]
Your suggestion breaks Gherkin compatibility. In addition, I think that you should in general avoid that lines get to long (if that is possible). Keep in mind that the scenario should be readable (and understandable). Therefore, I will reject your feature request.
