### ISSUE TITLE
wip mode resets tag passed via cmdline parameters

### ISSUE THREAD

**Issue by yucer** [behave/behave#427]
This line seems to overwrite the tags passed as parameters in the cmdline: http://bit.ly/1ZIlkrh

That have an effect over the test steps that verify the tags in the implementation to perform something.

As long as I understand, the **wip** mode should provide test context that I would have when I end the test.

**Comment by jenisys** [comment]
That is how the ``--wip`` option is defined to behave. 
It is basically a "macro option" that also sets other options and provides focus on features/scenarios marked with ``@wip`` tag. And the comment above exactly states that.

**Comment by vit1251** [comment]
@jenisys why you does not give to user possible to specify a test plan as an text file? Follow approach may will be integrated with company test ecosystem.

I mean, you may implement it as extensions or plugins and provide it as subsystem.

We research tags and absolutely sure that we never use it in future, but we create our "skip resolver" base on hook before it different way to resolve problem. May be require make interface to "test execute planing"?

**Comment by jenisys** [comment]
I am not sure what you are talking about.
Tags and configuration are two different concepts. 
And the ``--wip`` option is an implementation that was basically inherited from cucumber.
If you do not want to use it, than don't.

**Comment by vit1251** [comment]
> Tags and configuration are two different concepts. 

I tell about enum in file scenario name line-by-line for execution like it doing most application and provide within configuration in parameters "testplan=plan.txt" i.e. you have array with scenario for running and it one of extension filtrating scenario for running.

**Comment by jenisys** [comment]
Why are you not using "at-files" then ?
It is basically the same concept but uses file locations (in a one stage process).
But you can apply tag-filtering to the selected fileset.

```sh
# -- HINT: Check with and without tags
behave -f progress3 @plan.txt
behave -f progress3 --tags=@foo @plan.txt
```

SEE ALSO:
* [features/runner.feature_listfile.feature](https://github.com/behave/behave/blob/master/features/runner.feature_listfile.feature)

**Comment by vit1251** [comment]
@jenisys thanks for point me to "at-files". I will try using it.

Let's return to tags I also have difficult with working with tags.

Most of big problem is understand how to construct logic construction in command line.

What different "--tag=wip,~skip" and "--tag=wip --tag=~skip" we talk about this before with @jenisys and think that require documentation with examples.

Additional may be implement "--debug" for show some thing like that in console for  more understand what filter using now:

```bash
# behave --tag=... --debug
Filtering: ( "wip" && !"skip" ) or "error" 
```
Just for debugging?

**Comment by jenisys** [comment]
Sometimes, I am wondering if the people that are complaining about the missing documentation, read the documentation at all :wink: . See [behave/tutorial: controlling-things-with-tags](http://python-behave.readthedocs.org/en/latest/tutorial.html#controlling-things-with-tags)

Use:

```sh
behave --tags-help
```

In addition, the tag logic is explained and specified in the docs and in:
* [features/tags.tag_expression.feature](https://github.com/behave/behave/blob/master/features/tags.tag_expression.feature)
* [features/runner.tag_logic.feature](https://github.com/behave/behave/blob/master/features/runner.tag_logic.feature)

Therefore, we are not going to change that easily (and not with C-like if-expression syntax).

Having said that, there was a meeting of the cucumber team approx. 2 weeks ago, and Aslak proposed a more natural way to use tags. The proposal is more or less, like [py.test markers](http://pytest.org/latest/example/markers.html) is doing it right now, like:
```sh
py.test -m "not foo"
py.test -m "foo or bar"
```
But that is the future (and not now).

**Comment by yucer** [comment]
Thank you for the answers, sorry for the late feedback.

I prefer not to use only the "at-files" because sometimes our features are long and we select subsets via tags. We try to use really a feature file for every feature and there are some of them with many scenarios.

Regarding to the semantics of wip tags, I didn't know that it was strictly to use with the default tags. We do use it as part of the workflow for the development of the test this way:

1) When some feature / scenario is pending to implement we tag it with @todo

2) When someone is making a test, he selects what that need to be executed with the @wip tag. No @wip tags are committed to version control. We use it just locally. 

When an error appears, we run @wip tags with the --stop to raise. This way we can debug the same subset that we are developing.

3) Once the local runs are OK, we mark it with @done. So the quality guy can review the test before its executed by the CI.

4) The CI does not execute the features with @todo, @wip, @done tags.

We have some flexibility, because we use a cmd line **entrypoint** called run.sh that ensure the context for the test and behave parameters. That way we initialize shell variables and simplify the cmd interface to our needs. For example:

```bash
$ run.sh --wip
```
would run:

```bash
# ... other code
#
if [[ "$mode" = "ci" ]]; then
    export OES_SCOPE="for Continuos integration (fully implemented scenarios with no debug info)"
    # Test development workflow selectors
    b_options+=(--tags=-todo --tags=-done --tags=-wip)
    # Simple formats and redirect
    b_options+=(--tags=wip --no-snippets --format=plain --junit-directory=/tmp/bdd_junit --junit)
fi
```

As you would suspect, we have  interpreted @wip as a subset of the tests with the same context of execution. Our framework use another tags as a way to signal behavior and we would expect that selecting a subset of the test would not imply resetting the tag list to the defaults (http://bit.ly/1ZIlkrh)

That's not a problem for us right now, because we can adapt our **entrypoint** here:

```bash
if [[ "$mode" = "wip" ]]; then
    export OES_SCOPE="for Developer (just run the work in progress)"
    b_options+=(--wip)
fi
```
to use the equivalent options of that code without resetting the tags:

```bash
if [[ "$mode" = "wip" ]]; then
    export OES_SCOPE="for Developer (just run the work in progress)"
    b_options+=(--format=plain --no-color --stop --no-logcapture --no-capture )
fi
```

I understand that you want to be compatible with cucumber implementation.
Maybe you can talk in the cucumber meeting about the semantics of the @wip tag. :-)
