### ISSUE TITLE
Support for trailing ` :` in Gherkin steps

### ISSUE THREAD

**Issue by Goutte** [behave/behave#431]
Say I write a step like this :

``` gherkin
Given there is this user :
"""
username: Bender
password: (\/) (;,,;) (\/)
email: 2716057@robots.mom
"""
```

_(because yeah, deep down, Bender is rooting for Zoidberg)_

And define it like this :

``` python
@Given(u"there is this user :")
def there_is_this_user(context):
    # do stuff with context.text in YAML format
```

The trailing `:` screws up matching !
I **have to** define it like this, **with a trailing space** :

``` python
@Given(u"there is this user ")
```

_I know I can easily go around this problem by using the regex parser instead, but I'm trying to teach BDD to people that don't know first thing about regexes and we all need them to learn BDD fast._

**Comment by jenisys** [comment]
I know that the semicolon handling on steps is weird (and I will look into it when I have time). On of the problems in this case is to not break existing feature files.

But for now, I would advise you to drop the usage of the "trailing-space-before-semicolon" in steps of your feature files. That looks really weird to me.

**Comment by Goutte** [comment]
I absolutely dropped both the semi-colon and the trailing space, it was just to show you the full disclosure of what happened and how it's a caveat.

Looking at the features of behave, it looks like it works fine with just the trailing semicolon, without any space before it.

 ``` python
@Given(u"there is this user:")
```

I could not find a specific feature [in the specs](https://github.com/behave/behave/tree/master/features) covering the usage of multiline strings. I'm not even sure how best this could be done, embedding `"""` in `"""`.

In french, we write a space before a semicolon.

 ``` python
@Given(u"cet utilisateur existe :")
```

It's an edge-case that can totally wait for `v2.x`.

**Comment by jenisys** [comment]
@Goutte
The semicolon is handled in the Gherkin parser (in behave) and not the step definition.
 
SEE ALSO:
* [behave.example/tutorials/tutorial05.html](http://behave.github.io/behave.example/tutorials/tutorial05.html)
* [behave.example/tutorials/tutorial06.html](http://behave.github.io/behave.example/tutorials/tutorial06.html)
* https://github.com/behave/behave.example
