### ISSUE TITLE
Is it possible to have features in one directory and steps in a different directory?

### ISSUE THREAD

**Issue by edsuna** [behave/behave#436]
It seems like the steps directory needs to be directly below the features directory. We would like to organize our code separately from the features. Is there a configuration setting that could be used to point to a path to the steps directory?

**Comment by jenisys** [comment]
Use the step-library concept. This will make it simpler to test your step implementations. But you still need something like "features/steps/use_my_step_library.py" to import the steps of interest from your step-library(s).

But note, if you do not install the step-library(s) under python (site-package), you normally need to specify the ``PYTHONPATH`` environment variable or use "features/environment.py" to add additional search-paths to ``sys.path`` parameter (see Python documentation for more information).

SEE ALSO:
* [features/step.use_step_library.feature](https://github.com/behave/behave/blob/master/features/step.use_step_library.feature)
