### ISSUE TITLE
sentences in the same line

### ISSUE THREAD

**Issue by nickmeet** [behave/behave#437]
Can I write sentences in the same line?

The following works
Given step1
And step2

but the following returns NotImplementedError(u'STEP: Given step1 And step2')
Given step1 And step2

**Comment by jenisys** [comment]
Sorry, ``behave`` has no "mind-reading interface" (MRI, often called BCI), yet :smirk:
You just need to implement the corresponding composite step, like:

```python
# -- FILE: features/steps/my_steps.py
from behave import given

@given(u'step1 and step2')
def step_composite_setup(context):
    pass # -- MORE: To do here...
```

**Comment by jenisys** [comment]
Aah, you already pasted the missing step snippets into your steps file.
Otherwise, you wouldn't have the ``NotImplementedError``!!!
Well, the ``NotImplementedError`` just tells you need to implement the step !!!

**Comment by nickmeet** [comment]
Can I get all steps of type Given?

To get the idea, if I can do that, then I can write something like the following. Obviously this ticket is asking for info on using behave and not extending behave with such a mess.

```
import itertools
def bind_function(name):
    @given(name)
    def func1(context):
        context.log.info(name)
    func1.__name__ = name
    return func1

steps = ['step1', 'step2', 'step3']
for i in steps:
    bind_function(i)

for L in range(0, len(steps)+1):
    for subset in itertools.combinations(steps, L):
        bind_function(" and ".join(subset))
```

Worked at:
Feature: Combinations of steps of type Given
  Scenario: x
    Given step1
    And step2
    And step3
    And step1 and step2

**Comment by jenisys** [comment]
See behave's **steps** formatter for that (or one of the other step formatter variants).
It is basically using the ``step_registry`` for doing this.

```shell
$ behave -f steps --dry-run features/
GIVEN STEP DEFINITIONS[40]:
  Given I setup the current values for active tags with                    # features/steps/behave_active_tags_steps.py:35
  Given the behave context has a parameter "{param_name}"                  # features/steps/behave_context_steps.py:37
  Given the behave context does not have a parameter "{param_name}"        # features/steps/behave_context_steps.py:41
  Given the behave context contains                 
  ...
```

NOTE: Generic steps with ``@step()`` step-decorator are added to all step categories.

**Comment by jenisys** [comment]
Seems to be resolved !?
