### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by tjamet** [behave/behave#438]
Hi,

I'm currently looking into integrating behave into some libraries.
I have added behave to 'setup_requires' to gain the setuptools module but I'm stuck with '/usr/local/bin/python: can't open file 'behave': [Errno 2] No such file or directory', message.
Lookig at the sources, it looks like commit 4fa7582ab82b8ddaf05184eae8f5cab3f7ca333d would solve this issue.
Would it be possible to publish a new release to pypi?

Thanks

**Comment by jenisys** [comment]
Release is in the works. But I need also to do my homework.

WORKAROUND:
Copy ``setuptools_behave.py`` to your project. That should solve your problem, too (and you do not need to wait for me). You may need to setup the python path correctly (``sys.path`` in "setup.py").

**Comment by jenisys** [comment]
Closed (after providing the info for the work-around).
