### ISSUE TITLE
Need support for inline comments

### ISSUE THREAD

**Issue by willemt** [behave/behave#439]
This...
```gherkin
When I click on the button  # this is a comment
```
... results with this:
```python
@when(u'When I click on the button  # this is a comment')
def step_impl(context):
    raise NotImplementedError(u'STEP: When I click on the button  # this is a comment')
```

I'm going to try to write a PR for this soon.

**Comment by jenisys** [comment]
@willemt 
As far as I can tell this functionality is not supported in Gherkin (and behave's Gherkin parser).
SEE ALSO:
* Gherkin grammer: [cucumber/gherkin/gherkin.berp](https://github.com/cucumber/gherkin/blob/master/gherkin.berp)

QUESTION: 
Can you elaborate why need an inline-comment following a step ?

**Comment by willemt** [comment]
Apologies I hadn't realised this wasn't valid Gherkin grammar. My editor's Gherkin syntax highlighter gave me the impression that it was valid. I'm surprised that Gherkin's grammar doesn't support it. Using # to do a comment inline is intuitive if you use bash, python, ruby, etc.

Happy to close this issue considering that it's best to keep in-line with Gherkin's grammar.
