### ISSUE TITLE
Force color

### ISSUE THREAD

**Issue by aisbaa** [behave/behave#444]
Is it possible force colors even then stream is not tty?

There was a pull request for controlling color output https://github.com/behave/behave/pull/370 . As I understand current output depends on stream capabilities [pretty.py:L71](https://github.com/behave/behave/blob/master/behave/formatter/pretty.py#L7), for example if output is piped -> no colors.

Maybe grep approach would be nice?

```
grep --color[=(always|never|auto)]
```

**Comment by jenisys** [comment]
I already stated in pull-request #370 that the original suggestion will not be acceptable (to avoid command-line option explosions). Instead I already suggested an approach along the lines of your suggestion (which is not yet provided).

Therefore, I am not quite sure that is the novelty in this ticket (other than repeating the suggested solution in #370 in a slightly different way) ?!?

**Comment by aisbaa** [comment]
ql, will start working on this, because I really really need color output then piping behave output. This question was just to make sure that this feature is welcome :smiley:
