### ISSUE TITLE
Unicode is processed incorrectly for Py2 in "textutil.text"

### ISSUE THREAD

**Issue by throwable-one** [behave/behave#449]
I have Py2 and following ``steps.py``
```python
# coding=utf-8`
from behave import *
from hamcrest.core import assert_that, equal_to

@step("Russian text")
def foo(stop):
    assert_that(False, equal_to(True), u"Всё очень плохо") # cyrillic
```

And I also have ``UTF-8`` as my console charset. Running this code leads to "Assertion Failed: 'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)" error.

That is becase ``behave.textutil.text`` returns ``six.text_type(e)`` where 'e' is exception (https://github.com/behave/behave/blob/master/behave/textutil.py#L83).

Changing line 83 to ``six.text_type(value)`` solves this issue.

**Comment by jenisys** [comment]
FIXED IN: behave-1.2.6.dev0
