### ISSUE TITLE
exception in before_... hook aborts the whole test run

### ISSUE THREAD

**Issue by gabor-laszlo-schneider** [behave/behave#454]
When an exception is thrown inside a before_step / before_scenario / before_feature method of environment.py I expect the step / scenario / feature to fail. Instead of that the whole test execution returns with exception, no report is created about the previously executed test cases either.
If this is true it is a major bug in my opinion. Though I am surprised that I haven't found any mention of this here, neither on stackoverflow.

**Comment by gabor-laszlo-schneider** [comment]
I have found that in v 1.2.6.dev0 it does not abort execution. Though it is not OK still: 
All the steps are executed even after it is already decided that the scenario / feature has failed.
Also there is an issue with junit style xml report generation if the before_scenario method fails.

**Comment by jenisys** [comment]
That is how it is currently defined. 
You can easily fix that by handling the exception in your hook (and doing the right thing there). Or you could provide a suggestion how to improve the current implementation and why...

SEE ALSO:
* [features/runner.hook_errors.feature](https://github.com/behave/behave/blob/master/features/runner.hook_errors.feature)

**Comment by qakapil** [comment]
I experienced this issue too and I do feel that this is a major issue. 
Question - if we handle the exception in the hook, is there way to Skip the whole scenario/feature/step at runtime and move on to the next test ?

**Comment by jenisys** [comment]
@qakapil 
Yes, you can can skip the scenario/feature in the corresponding before-hook. Look for example at the description of [Active Tags](http://behave.readthedocs.io/en/latest/new_and_noteworthy_v1.2.5.html#active-tags) in the docs. But when you skip the feature/scenario, the error in the exception may not be as visible as expected.

**Comment by gabor-laszlo-schneider** [comment]
it is a good point @qakapil, but you should not skip but fail in this case, if your team is looking at the test report and they see all passed and some skipped scenarios, they will have the false illusion that everything went right.
@jenisys is there a way not to skip but fail the feature/scenario/step in the hook?

**Comment by jenisys** [comment]
Failing is currently not supported and it would be confusing because you would not see why it failed.

**Comment by Sjust** [comment]
Hi, There is an issue.

In this link you tell that if the exception is raised in a "before_feature/after_feature" hook, the feature es marked as failed.

The current behaviour is that if an exception is raised there, the behaviour is the same than in "before_all/after_all" hook. The whole test run is ignored.

Could you look at it?

**Comment by jenisys** [comment]
@Sjust 
Which behave version are you using ?
The feature file [features/runner.hook_errors.feature](https://github.com/behave/behave/blob/master/features/runner.hook_errors.feature) runs for me without any problems.

**Comment by jenisys** [comment]
NOTE: Original description resulted of behave-1.2.5 behaviour.
This changed in behave-1.2.6 (by capturing and reporting hook errors (first part), and by changing the runner behaviour (second part)).
