### ISSUE TITLE
Junit report: error message contains double quotes

### ISSUE THREAD

**Issue by gbisset** [behave/behave#457]
If an exception is caught and the error message contains double quotes then they are not being handled correctly (i.e. encoded) in the Junit report, i.e.

`<error message="Message: {"errorMessage":"Unable to find element with id 'user-profile'","reques..." type="NoSuchElementException">`

You'll see that the message attribute contains double quotes where they should be encoded to `&quot;`

**Comment by jenisys** [comment]
I cannot reproduce your results. I tried with a:
* failing assertion with text that contains double-quotes (causes: ``<failure ...>`` XML element)
* raising an exception with text that contains double-quotes (causes: ``<error ...>`` XML element)

In both cases the double-quotes are replaced by ``&quot;`` in XML element attributes (and other escape sequences). Note also that the char-escaping mechanism for XML is transparently provided in the ``xml.etree`` module.

MORE INFORMATION REQUIRED:
* Provide an example that allows me to reproduce your problem.
* Which behave version are you using (which platform, which python version) ?

**Comment by gbisset** [comment]
Hi jenisys,

Thanks for your reply.

It appears that I was wrong. I was looking at the xml after it had been imported into teamcity.  The double &quot; chacters had been replaced by double quotes in my web browser.

I checked the raw xml file today and they are indeed showing as &quot; in the message attribute.

Sorry for wasting your time.

**Comment by jenisys** [comment]
Resolved.
