### ISSUE TITLE
Documentation on @setup and @teardown

### ISSUE THREAD

**Issue by esciara** [behave/behave#461]
Hi there,

Could not find much documentation on the @setup and @teardown tags, what is their use and how they can be used. Not that easy to understand it from the code either.

Could you provide some explanations or pointers, please?

Em

**Comment by jenisys** [comment]
Scenarios that with ``@setup`` (and ``@teardown``) tag mark a scenario that is only to provided to setup the feature. This means, you have a scenario that performs setup only once in a feature. In comparison, a ``Background`` is basically executed before each Scenario. Note that the mechanism is currently only ensured when you use FileLocations, like ``features/alice.feature:123``. The runner ensures in that case that the Scenarios tagged with ``@setup`` are executed before the selected Scenario (at line ``123``).

**Comment by esciara** [comment]
Yep, I saw that when looking at the feature files (https://github.com/behave/behave/blob/master/features/runner.select_scenarios_by_file_location.feature for those who would like to know)

Would it be an idea to add that to the documentation/tutorial? Or are you waiting to make more use of it?

It is true that their usage is restricted tot he FileLocations for the time being. Plans to use it for something else?
