### ISSUE TITLE
Can I use Python Step Implementations out of the “steps” directory?

### ISSUE THREAD

**Issue by ladder1984** [behave/behave#463]
Can I use Python Step Implementations out of the “steps” directory?For example：
1. A .py file in one python package.
2.A .py file in one path.

If the answer is not,How can I use one Step Implementation in different projects.I don't want to copy and patse it.

**Comment by unklhe** [comment]
Of course you can. Make sure you have a py file under steps and it imports your actual implementation module.

**Comment by ladder1984** [comment]
@unklhe Thanks， But How？

**Comment by ladder1984** [comment]
@unklhe 

I write a step in a python package,But:

```
  File "build\bdist.win32\egg\behave\step_registry.py", line 81, in wrapper
  File "build\bdist.win32\egg\behave\step_registry.py", line 31, in add_step_definition
  File "C:\Python27\lib\site-packages\behave-1.2.4-py2.7.egg\behave\model.py", line 1600, in make_location
  File "C:\Python27\lib\ntpath.py", line 528, in relpath
    % (path_prefix, start_prefix))
ValueError: path is on drive C:, start on drive D:
```

**Comment by ladder1984** [comment]
I installed my package in C:\.Then,it's ValueError....Finally，I use the git subtree

**Comment by ladder1984** [comment]
@unklhe 话说featue想这样行不行？feature又不能import...

**Comment by jenisys** [comment]
You always need to provide a step directory with at least one file that imports the relevant steps from a step-library.

SEE ALSO:
* [features/step.use_step_library.feature](https://github.com/behave/behave/blob/master/features/step.use_step_library.feature)

**Comment by ladder1984** [comment]
@jenisys I want to use git subtree to add the library package to the “steps” directory.However,
```
You can implement step definitions for undefined steps with these snippets:

@given(u'XXXX')
def step_impl(context):
    assert False
```
Does behave not use steps in the sub directory?

**Comment by ladder1984** [comment]
@jenisys Thanks,I see https://github.com/behave/behave/issues/169.Git subtree may not be a compelling reason,But I really want it.
