### ISSUE TITLE
Does Behave support environment variables?

### ISSUE THREAD

**Issue by tarunlalwani** [behave/behave#465]
I was looking at the behave-http (https://pypi.python.org/pypi/behave-http/0.1.0) and it gave below example

```gherkin
Feature: Some API
  As an API client
  I want to be able to manage activities and sessions

  Background: Set server name, headers and reset test user's database
    Given I am using server "$SERVER"
    And I set base URL to "$URL"
    And I set "Accept" header to "application/json"
    And I set "Content-Type" header to "application/json"
    And I set BasicAuth username to "t@example.com" and password to "t"

  Scenario: Ensure account exists
    When I make a GET request to "account"
    Then the response status should be 200
```

```bash
$ SERVER=http://127.0.0.1:8081 URL=api behave
```

Now i am not interested in using behave-http as such as their format goes against BDD. But when I tried the $SERVER in a normal behave scenario, the variable was not resolved.

Is this something supported as such or its just that behave-http documentation is wrong?

**Comment by jenisys** [comment]
You need to ask the implementers of the step-library, in this case add an issue to the [behave-http](https://github.com/mikek/behave-http) project.

**Comment by ebuildy** [comment]
As a workaround, you could use a templating engine (jinja) to render features before.

**Comment by jenisys** [comment]
@ebuildy 
Sorry, I disagree. 
And it is rather easy to provide such a solution by using data types without any change in behave.

**Comment by ebuildy** [comment]
My use case is to run Behave test against several web servers, and I want to see the server URL used in the behave report:

    Given I am using server "$SERVER" ==> Given I am using server "http://www.XXX.com"

so I can read test reports faster, without templates or var sub. how can I achieve this?
