### ISSUE TITLE
Step.error_message is None in case of exception in 1.2.6

### ISSUE THREAD

**Issue by throwable-one** [behave/behave#468]
Say, I have the following code in ``environment.py``

    def after_step(context, step):
        print step.error_message

And I throw exception in step. def

    def step_impl(context):
       raise Exception("oops")

For ``1.2.5`` I have human readable message in ``step.error_message`` with Exception, its message and its stracktrace.

But for ``1.2.6`` I have ``None`` there. How ever, if I use ``assert False`` instead of exception it works even in ``1.2.6.``

**Comment by jenisys** [comment]
``Step.error_message`` is only set only ``after_step()`` hook processing because the hook itself may also fail. Therefore, you basing your use case on wrong assumptions. 

Your use case is no major use case because the default runner behaviour should  anyway print the ``Step.error_message``.
