### ISSUE TITLE
Overwrite first run Junit XML result file after rerun

### ISSUE THREAD

**Issue by Pramanth** [behave/behave#472]
We have a feature file where we use Scenario Outline along with Examples hence a step gets executed for different set of data. Since in the first run step was failing for few Examples we integrated rerun till we resolve the actual issue. Now the problem is after the run 2 junit xml are being generated and causing jenkins job to fail. Is there a option to overwrite the first junit xml after the rerun.

Step:
When I secure "document_type" with policy "policy_name" through CLI

Examples:
      | document_type   | policy_name | user      |
      | .docx           | Collaborate 
      | .xlsx           | View Only  
      | .pptx           | Track       

Behave Command:
behave features\modules --tags=smoke || behave @rerun.txt

Junit Files Generated:
1st Run : TESTS-policy_enforcement.require_authentication.xml
2nd Run : TESTS-modules.policy_enforcement.require_authentication.xml

**Comment by jenisys** [comment]
First you need to explain, why a rerun of the same test (without doing any changes) fixes something. In general, this smells like:

* your missing a setup
* your system has a race condition or is non-deterministic
* you may have a unreliable runtime environment

If you are sure, it is not the first two cases, but the third case, have a look at:
* [behave/contrib/scenario_autoretry.py](https://github.com/behave/behave/blob/master/behave/contrib/scenario_autoretry.py)
* [features/runner.scenario_autoretry.feature](https://github.com/behave/behave/blob/master/features/runner.scenario_autoretry.feature)

NOTE:
Your solution should only seem to work (if you are using the same output directory for both runs). The rerun iteration will run less than the 1st test run (only the failing scenarios). Therefore, the overridden XML files should lack the results of the first test run (if you are not running complete features or the same scenarios of each failed feature).

**Comment by Pramanth** [comment]
Thanks @jenisys for the valuable response. 

Currently in our case it is the second case i.e., your system has a race condition or is non-deterministic which is causing one or two example to fail during the first run. What you specified in note is exactly right.

I can split the example to different scenario but most of the steps are common and hence do not want to.
