### ISSUE TITLE
cucumber/aruba like step definitions for command line applications

### ISSUE THREAD

**Issue by fkromer** [behave/behave#473]
Refactoring the step definitions embedded in the _behave_ package into a separate package could ease the maintenance of reusable step definitions (compare [cucumber/aruba step definitions](https://github.com/cucumber/aruba/tree/master/spec/aruba).

**Comment by jenisys** [comment]
That is already planned. 
See [behave/behave4cmd](https://github.com/behave/behave4cmd) (currently not yet populated; currently exists only as my private repository).

**Comment by fkromer** [comment]
Would you accept pull requests on behave/behave4cmd? Or do you plan to make your private repository public in the near future that one can contribute to there?

**Comment by jenisys** [comment]
Pull requests to an empty repository do not make sense (and would cause more work).
But I plan to populate the Github repository soon.

**Comment by fkromer** [comment]
My mistake... I considered to contribute to [behave/behave/behave4cmd0](https://github.com/behave/behave/tree/master/behave4cmd0).

**Comment by jenisys** [comment]
``behave4cmd0`` is basically the small brother of ``behave4cmd`` which contains the essential functionality for testing ``behave``.

**Comment by nickmeet** [comment]
To use step definitions of behave4cmd should we do a different import than the following?

from behave4cmd0.command_steps import *

**Comment by fkromer** [comment]
@jenisys For cucumber there are step definition libraries like this [step definition library for cucumberjs](https://github.com/jdewit/cucumber-step-definitions). I would like to setup a package containing util functions and util step definitions ~ web backend and web frontend testing (e.g. with selenium webdriver) which could easily be integrated into a project by importing. Would you accept a pull request on the main project (behave)?

**Comment by jenisys** [comment]
@fkromer 
Step libraries are normally projects of its own. The main reason is, there is normally not the one solution that serves everyone, only that such a solution is usable in a certain problem domain, like web applications, etc.
