### ISSUE TITLE
Is it possible to register new formatter

### ISSUE THREAD

**Issue by aisbaa** [behave/behave#474]
Hi, is it possible to register formatter from third party library?

**Comment by jenisys** [comment]
@aisbaa 
Yes, look at [features/formatter.user_defined.feature](https://github.com/behave/behave/blob/master/features/formatter.user_defined.feature)

If you have not installed it with your third party library, you need to ensure that the ``PYTHONPATH`` environment variable is correctly setup. Most people seem to stumble over this point.

**Comment by aisbaa** [comment]
Thank it was exactly what I was looking for!
