### ISSUE TITLE
Feature request: Reporter raise report event on each scenario

### ISSUE THREAD

**Issue by vit1251** [behave/behave#477]
Hello,

    I want to report to my system information about scenario pass/fail immedatly after execution.

    Now Reporter interface only `feature` and `end` event.

Thanx.

**Comment by aisbaa** [comment]
Hi could you explain it in more detail. Is it:

1. step 2 out of 5 failed
2. you need formatter not to print steps 3,4 and 5
3. print something like scenario failed?

https://github.com/behave/behave/blob/master/behave/formatter/base.py#L188

**Comment by vit1251** [comment]
Yep. Formatter is more suitable. How about joint use a several formatter for example junit with my implementation. How to configure it. How about capture output in junit and may be create passtruth formatter to output to stdout and always capture stdout and logs?

**Comment by aisbaa** [comment]
I guess you could implement "multi" formatter. It could have a list of formatters that would be called one by one in turn.

It is possible to specify your own formatter from command line [here](https://github.com/behave/behave/blob/master/features/formatter.user_defined.feature#L76).

**Comment by jenisys** [comment]
@vit1251 
Your way to go is to use your own formatter.
The ``Reporter`` API is as it is and you can not provide your own reporter (currently).
