### ISSUE TITLE
Additional reporter

### ISSUE THREAD

**Issue by aisbaa** [behave/behave#478]
Is it possible to register/use customized reporter without forking? If so - how?

**Comment by jenisys** [comment]
No (and it is currently not planned).
If you want to use the ``Reporter`` API:

* provide a generic formatter class that provides the adaptation of the Formatter to the Reporter
* provide your own Reporter class (as workhorse for the output)
* provide your own Formatter class that delegates work to the instance of your reporter class
  by using the generic Formatter2Reporter

SKETCH:
```
from behave.reporter.base import Reporter
from behave.formatter.base import Formatter

class MyReporter(Reporter):
    ...

class Formatter2Reporter(Formatter):
      """Provides generic adapter implementation from Formatter to Reporter API."""

class MyFormatter(Formatter2Reporter):
      """Creates an instance of MyReporter and hands it to the base class to do the work.""" 
```

**Comment by aisbaa** [comment]
Okay, as I understand bridging points would be:

- Formatter.eof -> Reporter.feature
- Formatter.close -> Reporter.end 

Is there a plan to merge formatter and reporter interfaces? It seems that both are responsible for runner state representation just different points in time.

**Comment by jenisys** [comment]
Reporters are (currently) much more constraint and not so extensible in behave's internal usage.
One such concept should be sufficient. Currently, this is the ``Formatter`` because it contains support to use multiple formatters and you can define your own one.

**Comment by aisbaa** [comment]
Thank you.
