### ISSUE TITLE
--dry-run -f formatter should have return code 0

### ISSUE THREAD

**Issue by ignatenkobrain** [behave/behave#481]
in most of cases (formatter exists and steps are in place).

```
$ behave-3 -q --dry-run -f sphinx.steps -o ../doc/
sphinx.steps: Written 4 document(s) into directory '../doc/'.
0 features passed, 0 failed, 0 skipped, 54 untested
0 scenarios passed, 0 failed, 0 skipped, 92 untested
0 steps passed, 0 failed, 0 skipped, 451 undefined, 353 untested
Took 0m0.000s
$ echo $?
1
```

**Comment by jenisys** [comment]
Sorry, I cannot reproduce your problem.
Which version of ``behave`` are you using ?

NOTES:
* ``behave-3`` is not a ``behave`` script
* Result code is independent of formatters (in general)

**Comment by ignatenkobrain** [comment]
@jenisys python3-behave-1.2.5-17.fc26.noarch

`behave-3` is just renamed `behave`, but uses python3.

Just tried virtualenv:
```
(venv) [brain@x1carbon dnf-docker-test]$ behave -q --dry-run -f sphinx.steps -o doc/
sphinx.steps: Written 4 document(s) into directory 'doc/'.
0 features passed, 0 failed, 0 skipped, 55 untested
0 scenarios passed, 0 failed, 0 skipped, 93 untested
0 steps passed, 0 failed, 0 skipped, 447 undefined, 360 untested
Took 0m0.000s
(venv) [brain@x1carbon dnf-docker-test]$ echo $?
1
```

**Comment by ignatenkobrain** [comment]
also tried to install behave from git using pip in virtualenv, still reproducible.

**Comment by ignatenkobrain** [comment]
Note that not all of my `.feature` files are properly written:
```
@then(u'line from "stdout" should "start" with "TestE-1.0.0-1."')
def step_impl(context):
    raise NotImplementedError(u'STEP: Then line from "stdout" should "start" with "TestE-1.0.0-1."')
```

but when I use formatter it should not return <>0

**Comment by ignatenkobrain** [comment]
yes, once I fixed my feature files to work with new steps, it started giving return code `0`, but as I said above it should not really matter when I just want to get steps by using formatter.

**Comment by jenisys** [comment]
@ignatenkobrain 
You have undefined steps (according to the summary from above). Therefore, you always get a non-zero result code, even in dry-run mode.

SEE ALSO:
* [features/step.undefined_steps.feature#L289](https://github.com/behave/behave/blob/master/features/step.undefined_steps.feature#L289)
