### ISSUE TITLE
[Feature Request] Tags for Scenario Outline examples

### ISSUE THREAD

**Issue by donato** [behave/behave#485]
I would like to be able to run sets of examples independently using Tags
```gherkin
Feature: my feature
  Scenario Outline:
    Given <v>

  @a
  Examples:
    | v |
    | 1 |
    | 2 |

  @b
  Examples:
    | v |
    | 3 |
    | 4 |

```
https://github.com/cucumber/cucumber-js/issues/305#issuecomment-74038183

This is great for splitting up functionality, or for speeding up testing and local/dev

**Comment by gregsaun** [comment]
It's not include in the latest release but available on master. You have to install it from GitHub directly.

You can do this like this:
pip install -e git://github.com/behave/behave.git#egg=behave

**Comment by donato** [comment]
Wow, thanks @gregsaun - that truly exceeds my expectations!

**Comment by rado23** [comment]
Just wonder, was that released?

**Comment by jeremad** [comment]
Last release is from 2015 so no!
