### ISSUE TITLE
Recognize zero-breaking space as normal space for multiline text

### ISSUE THREAD

**Issue by ignatenkobrain** [behave/behave#488]
In #487 I tried to use zero-breaking space for emulating normal spaces (for better look in text editor), but actually it's not supported.

We can do something like:
```python
>>> text.lstrip(string.whitespace + "\u200b")
```

**Comment by jenisys** [comment]
From #487 you are working with Python2. 
When using unicode escapes (like above), you should ensure that you are using unicode strings.
This avoids part of the problem in Python2 with implicit encoding/decoding unicode-strings/byte-strings with default encoding="ascii".

**Comment by jenisys** [comment]
No reaction.
