### ISSUE TITLE
When to release v1.2.6 ?

### ISSUE THREAD

**Issue by thu2004** [behave/behave#490]
The current version v1.2.5 released on Jan 31, 2015 

There are a lot of changes since then. Should we make a new release soon ?

**Comment by aellwein** [comment]
+1 for new release

**Comment by aisbaa** [comment]
+1

**Comment by jenisys** [comment]
The release is planned. Some stuff needs to get fixed first, mostly Unicode related stuff.

**Comment by phunter00** [comment]
...and by the way Jenisys, you do a kick-ass job with this stuff and my team at least, is eternally grateful.

**Comment by lawnmowerlatte** [comment]
@jenisys, are the things that need to be fixed regressions or new issues? I'm wondering if I can push 1.2.6 to an internal PyPI server as-is and start leveraging the new features now.

**Comment by chrono** [comment]
@jenisys 

To repeat @lawnmowerlatte's question: Are these new issues or old ones? Are there tickets for those that can be worked on?

**Comment by lawnmowerlatte** [comment]
@chrono, @jenisys, I've pushed the latest dev build to our internal PyPI server and have been running it alongside our regular tests for almost two weeks and haven't experienced any problems. I've been enjoying the new  `@autoretry` feature.

**Comment by qlinden** [comment]
When can I expect the new 1.2.6 release of Behave?

**Comment by jenisys** [comment]
The release will be made before end of October.

**Comment by aellwein** [comment]
October of which year?

**Comment by bittner** [comment]
@jenisys Can we make a release happen in the next few days or weeks?

Apart from the fixes and features only available in the dev version, also the docs bother me: The [outdated version of the Django chapter](https://pythonhosted.org/behave/django.html) is still out there being presented as the canonical source by search engines.

**Comment by andreybehalf** [comment]
Any updates?

**Comment by iorlowrps** [comment]
Hello, Guys!
Are you working on future releases, do you plan to support framework?
Please, let us know.
