### ISSUE TITLE
Is it possible run all Examples group except a group selecting it by name?

### ISSUE THREAD

**Issue by iariasleon** [behave/behave#491]
I see that is possible run all rows of an examples (group) by selecting it by name.
http://pythonhosted.org/behave/new_and_noteworthy_v1.2.5.html#run-examples-group-via-select-by-name

If we define a placeholder into de file.feature as:
```
 @my_scenario   @my_scenario.group<examples.name>
  Scenario Outline:  scenario description
   ....
  Examples:
   | name |
     ... multi-rows
 Examples:
   | name |
     ... multi-rows
  Examples: my_example
    | name |
     ... multi-rows
```
And run:
```
behave file.feature -t my_scenario  -n my_example
```
It is executed the `my_example` Examples, only. Good!!!

But In mi question I wish the opposite, run all Examples group except the `my_example` Examples.

Something similar to:

behave file.feature -t my_scenario  **-n=-my_example**

**Comment by jenisys** [comment]
@iariasleon 
You are better of using tags instead. For tags, you have a simple negate or not operator.
Otherwise, you need a not-pattern for regular expressions that works with ``re.search()``.

**Comment by jenisys** [comment]
EXAMPLE (for such a negated regular-expression):
Select all scenarios that do not start with "Alice" in its name.
Or: Exclude all scenarios that start with "Alice" in its name.

```sh
BASED ON: features/runner.select_scenarios_by_name.feature
$ behave -f plain --name='^(?!Alice)' features/
Feature: Alice

Feature: Bob
  Scenario: Bob in Berlin
    Given a step passes ... passed

  Scenario: Bob in Florida
    When a step passes ... passed

1 feature passed, 0 failed, 1 skipped
2 scenarios passed, 0 failed, 4 skipped
2 steps passed, 0 failed, 4 skipped, 0 undefined
```

**Comment by iariasleon** [comment]
LGTM...Thanks
