### ISSUE TITLE
Same Test data or Example for all the scenario in a feature file

### ISSUE THREAD

**Issue by Pramanth** [behave/behave#492]
We have a feature file and all the scenario has Scenario Outline along with Examples and examples are same for all scenario as specified below. Is there a option to specify test data or example in one place and utilise in all the scenario. This is important for us as we change the test data more often. Thanks

Feature: Edit and Save As Restriction Feature
@desktop
  Scenario Outline: Create a new policy with only allow copypaste - disabled

  When I open document "document_name" of type "document_type"
 
    Examples: File-Type: <document_type>
      | document_name | document_type |
      | sample_docx   | .docx         |
      | sample_pptx   | .pptx         |
      | sample_xlsx   | .xlsx         |  

@desktop
  Scenario Outline: Check copy paste is allowed when enabled by policy

  When I open document "document_name" of type "document_type"

    Examples: File-Type: <document_type>
      | document_name | document_type |
      | sample_docx   | .docx         |
      | sample_pptx   | .pptx         |
      | sample_xlsx   | .xlsx         |

**Comment by jenisys** [comment]
Sorry, Gherkin does not support such a feature.
With Scenario Outlines, you already use the one "template feature" of Gherkin to avoid to replicate too many steps (while writing them).

Outside of Gherkin you have the following possibilities:
* Provide the data as ``userdata`` or by reading it from a configuration file (like JSON, CSV, ...)
* Iterate over all items/rows of data in your step implementation
* Otherwise: Generate your feature files from a template by using a template-engine (like: Jinja2, ...)
* Otherwise 2: Define your common data in a Background step. Each Scenario will execute it (but that lacks the iteration for each row => Must be done in step implementations)

```Gherkin
Scenario: xxx
   Given I use the standard documentation types       # Step implementation defines where data comes from.
   When I execute the following steps to each document type:
       """
       ...
       """
   Then the execution of the steps succeeds for each documentation type

**Comment by Pramanth** [comment]
Thanks @jenisys . But is it possible to run all steps for the data specified in JSON or CSV. 

Will give a try on the solution provided in https://github.com/behave/behave/issues/400

**Comment by jenisys** [comment]
@Pramanth 
Your step implementation must implement the for-loop.

**Comment by Pramanth** [comment]
@jenisys 
Since in our case test data in the example change more often and same data has to be used in all the scenarios(in our case we need to run all steps for each document specified in the example) I think better option is to generate the feature file on the go with a template engine.

Tried exploring but could not find a suitable starting point. Any pointers from your end to kick start. Thank you.

Please also can you little elaborate on the below solution you provided,

Scenario: xxx
   Given I use the standard documentation types       # I can get list of documents which needs to be tested with this step but how the following steps execute for each test data?
   When I execute the following steps to each document type: #can we have a list of steps which need to be executed for each doc?
       """
       ...
       """
   Then the execution of the steps succeeds for each documentation type

Sorry I may be asking for more but I am really stuck :)

**Comment by jenisys** [comment]
Regarding to the Scenario example that I provided above:

1. STEP: ``Given I use the standard documentation types``
  Define your "standard documentation types" list in python code (hardcoded data).
  A better approach would be to provide it as ``user data`` in a data file (JSON or INI config file).
  Look up the ``userdata`` concept in the documentation or look at [features/userdata.feature](https://github.com/behave/behave/blob/master/features/userdata.feature)

2. STEP: ``When I execute the following steps to each document type: <TEXT>``
   You basically execute the ``context.execute_steps(context.text)`` functionality in your 
   step implementation to execute the steps from the text/docstring part. The steps are executed for all documentation types (for-loop over steps).
   See: [features/step.execute_steps.feature](https://github.com/behave/behave/blob/master/features/step.execute_steps.feature) or [behave.example: Tutorial 8: Execute steps](http://behave.github.io/behave.example/tutorials/tutorial08.html)

Regarding template-engine:
I personally like [Jinja2](https://pypi.python.org/pypi/Jinja2) but you need to write a small script.
