### ISSUE TITLE
Is there a way to have behave print the summary only?

### ISSUE THREAD

**Issue by TAGC** [behave/behave#493]
I was wondering if there's a way to get behave to run tests but only print the summary, for instance like this:

```
$ behave --summary-only
4 features passed, 0 failed, 0 skipped
93 scenarios passed, 0 failed, 0 skipped
440 steps passed, 0 failed, 0 skipped, 0 undefined
Took 0m0.577s
```

The reason why I'd like this is that it takes several seconds between me running `$ behave` and seeing the summary, which is really all I care for. However, the summary says that the tests themselves only took about half a second. Ostensibly, all the additional delay is just to do with printing to stdout.

So assuming this can't be done already, I suppose this is a feature request: as a user I would like a `--summary-only` option in order to get faster feedback on the correctness of my program. :)

**Comment by jenisys** [comment]
Use the NULL formatter. It implements the Null pattern. 
Like:

behave -f null ...

**Comment by TAGC** [comment]
Cheers, mate. Unfortunately didn't give me quite the speedup I was hoping for.

`behave`:

real	0m21.867s
user	0m19.846s
sys	0m1.094s

`behave -f null`:

real	0m17.091s
user	0m16.400s
sys	0m0.522s

Still, answers my question and my own fault for thinking printing things to stdout added that much overhead. :)
