### ISSUE TITLE
Sphinx steps formater how to pass destdir

### ISSUE THREAD

**Issue by aisbaa** [behave/behave#494]
Hi, cant figure out how to pass `destdir` to `SphinxStepsDocumentGenerator` from command line or config file.

Related to https://github.com/behave/behave/issues/166 .

**Comment by nickmeet** [comment]
I guess that's part of sphinx-build. One way is to:

1. make a minimal feature file dummy.feature and run it with the following arguments: `behave --dry-run --no-summary -q --format sphinx.steps -o doc/source dummy.feature`
2. and then run: `sphinx-build -b html doc/source path/to/destdir`

**Comment by jenisys** [comment]
@nickmeet 
Correct (but normally, I use the complete feature directory to discover all steps).
The output directory contains the all step modules as ``*.rst`` files and an `index.rst`` as starting point (with a table of contents).

**Comment by aisbaa** [comment]
Brilliant, thank you guys!
