### ISSUE TITLE
Two different steps with the same name

### ISSUE THREAD

**Issue by gitcommitz** [behave/behave#496]
What i want to do is implement the same step, e.g "UserA calls UserB" in diffrent step files and to point the test to the correct step teach time.

For example:

The .feature file content:

Scenario: User A calls User B
  Given UserA calls UserB
then, in the step folder, i'll have a .py file that will contain:

@given('UserA calls UserB')
def step_impl(context):
   print('A call is being made')
And another step .py file that will contain:

@given('UserA calls UserB')
def step_impl(context):
   print('A call is being made in another method')
I want to have control over which one of these steps will be executed. Is there a clean way to do that?

**Comment by jenisys** [comment]
That depends. First: Both step definitions cannot be in the same python file.

POSSIBLE SOLUTIONS:
* Use the ``stage`` concept. Depending on the ``behave --stage=<STAGE> ...`` different step directories are used. This allows you that 2 teams (example: development team and integration team) uses the same feature files but different step implementations. See [features/runner.use_stage_implementations.feature](https://github.com/behave/behave/blob/master/features/runner.use_stage_implementations.feature) or [Test Stages](http://behave.readthedocs.io/en/latest/new_and_noteworthy_v1.2.5.html#test-stages) documentation

* Use 2 feature directories with same feature files but different step implementations for each directory.

**Comment by gitcommitz** [comment]
@jenisys Thank you very much. That's exactly what i was looking for
