### ISSUE TITLE
Refer to environment variables in Gherkin steps

### ISSUE THREAD

**Issue by c-mart** [behave/behave#497]
In my testing, I have defined envrionment variables directing the test suites how to log into my application (URL, username, password). I would like to refer to these environment variables in my features, e.g. `When I click on $USERNAME`, in a way that doesn't require me to modify each step definition. I have tried to do this in environment.py but could not figure out a solution. I also saw #250 but this isn't quite what I'm asking for.

Thank you!

**Comment by jenisys** [comment]
@c-mart 
Understand step parameter concept.
In addition, have look at the ``userdata`` concept how you can provide different test data in different test runs.

EXAMPLE: How you can use environment variables
```python
# -- FILE: features/steps/my_steps.py
from behave import when
import os

@when(u'I click on ${environment_var_name:w}')
def step_impl(context, environment_var_name):
      environment_var_value = os.environ[environment_var_name]
      if environment_var_name == "USERNAME":
          context.username = environment_var_value
      pass # DO WHATEVER YOU LIKE with environment_var_value
```

SEE ALSO:
* [features/userdata.feature](https://github.com/behave/behave/blob/master/features/userdata.feature)
* [Userdata description](http://behave.readthedocs.io/en/latest/new_and_noteworthy_v1.2.5.html#userdata) in the docs
