### ISSUE TITLE
Show captured logs of the whole scenario when a step fails

### ISSUE THREAD

**Issue by mvallebr** [behave/behave#500]
Some times, a step doesn't fail but prints error or warning logs and it's the cause of the failure of another step in the same scenario. 

When we run behave with capture options turned on, it only shows the logs of the failing steps, which makes it hard to analise problems in the scenario described above.

Therefore, it would be really nice to have a new command line option like, for instance, `--show-captured-for-failing-scope=scenario`, to set the scope of the logs shown when some test fails. 

I would still like to see the summary at the end, after logs, but instead of showing captured logs just for the failing step, I would like to show logs for the whole failed scenario.

Please let me know whether you agree with the issue or have concerns and also whether you're willing to develop it or accept pull requests, and in the later case, which kind of solution you would agree in accepting. 

Thanks!

**Comment by jenisys** [comment]
@mvallebr 
I am slightly confused by your description. You can capture:

* stdout
* stderr
* log

or not. From your description, I am not quite sure what you want to capture (stdout/stderr or log). A sane approach for you could be to capture stdout and stderr but leave logging alone (=not captured). This allows you to have all the details in the logfile afterwards if you need them for diagnostics.

In addition, you have access to the captured data (stdout, stderr, logging) in the ``after_step()`` and dump it in the ``after_scenario()`` hook. Therefore, if the sane default behaviour of ``behave`` does not suit your needs, provide your own behaviour, like:

```gherkin
Feature:

  @show_captured_output
  Scenario: Bad, fails sometimes
     Given ...
     ...
```

```python
# -- FILE: features/environment.py
def before_all(context):
    context.collect_captured_output = False

def before_tag(context, tag):
    if tag == "show_captured_output":
        context.collect_captured_output = True
        context.collected_stdout_captures = []
        context.collected_stderr_captures = []
        context.collected_log_captures = []

def after_step(context, tag):
    if context.context.collect_captured_output:
        context.collected_stdout_captures.append(context.stdout_capture.getvalue())
       # SAME WITH: context.stdout_capture.getvalue(), context.log_capture.getvalue()

def after_scenario(context, scenario):
    if "show_capture_output" in scenario.effective_tags:
          # -- SIMPLIFIED: Dump captured output/logs always
          print("\n".join(context.collected_stdout_captures))
          ...
```

**Comment by mvallebr** [comment]
@jenisys  - so "show_captured_output" will be present in `scenario.effective_tags` on a scenario failure even if `--capture` have been used in the command line options, right? 

I will try this later and then I will write the feedback here, thanks for the help provided!

**Comment by jenisys** [comment]
@mvallebr 
The tag ``@show_captured_output`` just marks that a specific scenario (or feature) should have this behaviour. The usage of ``scenario.effective_tags`` ensures that if you add the tag to the feature, all scenarios in this feature will automatically inherit this tag (and this behaviour). Using ``scenario.tags`` would only support to add this tag to a scenario (because it contains not the ``inherited tags`` from the feature).
