### ISSUE TITLE
The reporting and error logging need to be improved

### ISSUE THREAD

**Issue by fredizzimo** [behave/behave#504]
I think one of the biggest limitations of Behave is how the error messages are reported. It works ok, when you run the tests locally and use console output with debugging. But if you move the tests to a continous integration server that runs them automatically, you want to be able to find the issues by just reading the log files. 

There are several different issues, so let's look at them one at a time.
1. **The callstacks are ignored for the asserts.** This is fine if you always have good asserts messages, or if you break into the debugger as soon as there's an assert. However it's not easy to write the asserts with enough context to debug the issue, and many time something important might have been left out.
2. Related to the above, the actual error messages are formatted in Step class from the models module, which doesn't seem to be the correct place for doing something like this. IMO, we should only catch the assert, and let the formatter or reporter take care of the exact format of the error message. In that case, if we wanted to display full asserts messages, we could just write a custom reporter of formatter, based on the stored exception information. Technically this is probably already possible if the reporter just ignores the error message given, and always uses the stored exception instead.
3. There doesn't seem to be any good way to capture output unless the step fails. One way is to capture all logs by adding another logging device. But by doing this we loose the context of in which step the logged line actually happened. 
   
   Another approach is described in #500, but doesn't allow the reporters to decide what to do with the logs. It might be possible to store it in the model as an extra field, and read that in the formatter
   
   Another potential option would be to let the reporter read the context, and the captured output from there. However I'm not sure if the formatter has access to that information.
   
   In any case, both of these solutions seems like hacks, it would be much better if the captured output was always included in the model. 
4. Reporting errors from hooks is a mess, since hooks don't have proper models and support in the formatters. So for hooks I think you should include models that works almost exactly like steps. There should also be new callbacks for the hooks added to the formatters. 
   
   Hooks also suffers from the same formatting of error messages as described in 2. Additionally from reading the code, it looks like there's a bug; if a step fails and then immediately afterwards the hook for the same step fails, then the error message of the step would be overwritten by the one of the hook.
5. Generally, I think the interface for the formatters is quite hard to work with, as not all needed parameters are passed to all of the functions. It's also missing things like `end_scenario`. I think it should be something more similar to the hooks. But on the other hand if the models are good enough and contain all the information most of the formatters could be written as much more simple reporters instead, and only things that really need realtime output would use formatters.

There are probably more things that I have forgot, but I think you get the idea. The formatters/reporters should be passed all the needed information, and those should be the only ones that format error messages. But of course there could be some common functions for formatting exeptions for example.

**Comment by jenisys** [comment]
@fredizzimo 
Sorry, I disagree. The roles and responsibilities of the Step/ModelElement and the Formatter are clearly stated (and you even describe them correctly in some places and false in others).

My hint: Write your own formatter.
Use the exception context information that is stored in the ModelElement (Step, ...) to show the complete traceback of the Assertions. That seems to be at least one of your main concerns.

**Comment by fredizzimo** [comment]
Ok, let's not get into arguments about what's good code architecture or not. For me it's currently good enough that the full exception information is stored in the model, so I can use that in my custom formatter, rather than the preformatted error string. So I can live with 1. and 2.

But that said, the other concerns are at least as serious, but I forgot to bold them. So let's go through them again, and this time from the perspective of my needs

3. I want to display the full output in some of my reports, even when steps don't fail. Furthermore I want the output to show up belonging to the correct step or hook.

4. I want to report to include the result of all the hooks. I also want to be able to display a separate error message from the hook and the step in case both the step and the "after" hook fails.

5. I can live with that. But I still think the interface could be improved a lot, and more information, like the context should be passed. It should also include before and after functions for everything.

6. A new one. I want to be able to pass custom data to the reports, screenshots, crashdumps and so on. Passing the context could take care of that. Alternatively I could add extra data to the current step model, but I don't think we should do that. Additionally the context doesn't contain any attribute for the current step, so I can't directly access it from within my code, unless I write to the context, and copy the information to the model in a hook, but that seems like a very hacky way of doing things.

**Comment by fredizzimo** [comment]
This is starting to critical for me (I have to get this fixed within a couple of days) so, I'm wonder how to proceed.

I think a few improvements would solve all my problems.

1.  Make a new formatter interface. This would have mostly the same functions as the hooks, taking both the context and model as parameters. The context parameter would allow me to send custom data (like screenshots) to the formatters.

    But the regular hooks also needs reporting, so that the formatter for example accurately knows when the hooks start, finish and their results.  That means that the interface should have some additional callbacks in addition to the hooks defined in `environment.py`

    I believe the standard formatter could be implemented in terms of these callbacks, just like the reporter is implemented in terms of the formatter currently.

2. Add callbacks for each log message (not only log statements that occurs during steps, but also logs during hooks for example), to the new formatter, so that the it can decide what to do with them. This would mean overriding the logger globally. I don't see much use of the current log capture system, but for compatibility reasons it would have to remain. 

3. Add a way to totally disable all printing that occurs after the actual run has started. For example the runner prints hook errors print directly to stdio. I don't want that, the formatter should know better how to format the error in the correct way.

There are two ways of implementing this. I could modify the Behave source code with the new functionality and tests, and send a pull request. 

But there's one big but, the number of completely reasonable(IMO) pull requests open makes me reluctant to contribute anything, especially as most of the pull requests don't have any comments about why they haven't been accepted. 

So I'm pretty sure that I will do it in another way and add decorators to my hook functions in the `envionment.py` file and implement the new formatter that way, ignoring the built in formatters completely. The same with the log capturing system, I would just add a new logger, which would call my custom formatter, pretending that the log capturing system doesn't exist. This is fine, since I don't need any stdio output.

I still think that it would be good to get the logging system officially improved, but at least this way I can move on, and it should be quite easy to port my code if it's improved sometime in the future.

**Comment by jenisys** [comment]
@fredizzimo 
The problem that I have with this issue is that it is not an issue. Instead, it is a collection of issues (with points that you do not like). 

Guidelines for pull-requests to be acceptable:
* provide a pull-request that addresses one problem at a time (and not a JUMBO pull-request). 

Characteristics of non-acceptable pull-requests:
* doing the same thing in another way without adding additional value ("using another flavour").

**Comment by fredizzimo** [comment]
Hi @jenisys,

We managed to delay the need for proper reporting for a while, but now we really have to do something.

# Recap of the problems

The reason why I listed so many things is that I think they all can be solved by implementing a proper formatter interface and model. The current interface does not seem to be very flexible and well- thought-out and it has stayed basically the same since it was introduced many years ago. It's not only me that's having problems, there have been countless of other issues opened. Most of them have been closed without any real resolution, or with ugly workarounds as solutions. So I went through the issue list, and made a small summary.

The biggest problems are related to the logging and especially the log capturing. Some logging problems are:

1. Logs are only shown for failed steps and many people want them to always show
2. If they are shown, they are not necessarily in the correct order in relation to other output channels and the output from the formatter itself
3. The logs are not outputted in real-time. 
4. The log capture options and interface are very hard to control. 

Here's a list of related issues, I haven't categorized them to the numbers above, because the issues list several of the problems above.

* Logging during successful steps - #524 
* Show captured logs of the whole scenario when a step fails - #500
* Log capturing researching - #403
* No logging appears from environment hooks - #387
* Placing `@capture` decorator on before_step or after_step functions masks logging in steps files. - #376
* Does not print to console, or log pretty much at all. - #346

The issue below also reported issues with the logs but also wanted something very specific and ended up implementing something close to what I think the formatter should already provide.

* Capture log from terminal to file - #412

Furthermore, it's easy to see that the formatter absolutely need to be in charge of what's getting logged, as that's a requirement for implementing certain kinds of formatters. The formatter should also be in charge of the logging level, as we might want to log different things to the console in real-time, than what we log to persistent logs stored in files. 

* Last logging statement not printing in console #389
* Logging output overwritten when using 'pretty' formatter #394

Users want to pass custom data to formatters. For example screenshots.

* Custom Data to Formatters - #332

The reporters support a much more simple interface than the reporters, but lack for example support for writing to files. Unfortunately some reporter functionality can't easily be implemented by the current formatter interface, for example you can't get information of features that are not run, as can be seen by the following code snippet from the source code.
```python
# -- ALWAYS: Report run/not-run feature to reporters.
# REQUIRED-FOR: Summary to keep track of untested features.
for reporter in self.config.reporters:
    reporter.feature(feature)
```

The file output problem can be seen here.

* can't write summary to file - #312

The model structure lacks parent access, which would be very useful for reporting purposes.

* Access to scenario from step - #163

# Fixing it

So instead of looking and fixing each issue one by one, let's look at a complete solution which would fix all of these problems in one go. Since we are in a hurry and we know that you are busy with preparing the new release, we will implement this ourselves, but rather than hacking it together using hooks, as I was originally planning, do it properly by modifying the Behave source code and add tests and send a pull request when it's done. It doesn't really matter for us if the pull request will be accepted or not, but we would prefer to receive comments about the design so that is has a bigger chance.

**NOTE:** I'm basing this proposal on the latest master version, rather than the released version of Behave as some of the issues, especially related to hooks are even worse in the 1.2.5 release.

## Fixing the Models

The model classes are mostly good but they are missing a few important things. So here's a list of things that need to be improved or added.

### Add a root model

Let's call it `TestRun`. Currently there's no such thing, which makes it inconvenient for reporters to iterate through everything at either the start or the end of the run. This model would contain nothing more than a list of `Feature` models. If this was provided, then many reporters could be implemented by just traversing through the features, scenarios and steps after everything has been run. The reporter would get all the information it needs from the traversed models, including information about steps that weren't run.

### Provide models for the hooks

The hooks are currently not modelled, which means that there's no separate status for the hooks. The only thing that we know is that some hooks have failed or not, but there's no indication of which hook(s) failed, at least not directly without parsing the error message. There's also no way to get information about which hooks has been run. Possible hook exceptions are currently stored in the `Scenario`, `Feature` or `Step`, but only one exception is stored, so if for example two hooks fail you only get the exact error for one of them. 

Therefore, I propose a `Hook` model, which is derived from `BasicStatement`. The `keyword` could be `hook`, the `name` could be for example `before_scenario`, or in other words, the same as the names defined in `environment.py`. For tag hooks, the name of the tag would additionally be included. The `file` and `line` are more tricky, but I think we could use the same as for the hook owner, so a scenario hook would have the scenario file and line set.

The hooks need to be stored somewhere, therefore I'm suggesting to add the following two attributes to features, scenarios and steps: `before_hooks`, and `after_hooks`, both storing a list of hooks.

### Parent access

As indicated in [Access Scenarios From Steps](#163) is sometimes very useful for reporters and formatters, perhaps otherwise too to be able to traverse the models in both directions. Adding a `parent` attribute to all the models should be an easy fix for that.

### Steps know their background

Steps that belong to a background should have two different parents, the scenario and the background. I think a `background` attribute which can be `None` would take care of that. At least the official cucumber JSON format will need something like that, but I can imagine that many other types of formatters and reporters could use this extra information as well. 

It's of course possible to manually get this information by accessing the `background_steps` attribute, but I don't think you should need to do it.

## Changes to the formatter interface

### Add before and after functions to the formatter

The only functions that the formatter really need are `before` and `after`. Both functions take two parameters, `model` and `context`. The `before` function is always called before a model is processed, including the new `TestRun` and `Hook` models. Similarly, the `after` function is called after the model has been processed. 

The `model` parameter lets you access everything that is needed from the model, for example the name and the status, which includes `untested` and `skipped`. The `context` parameter lets you pass data from the steps and hooks to the formatter, which fixes a couple of the issues reported above.

A formatter could handle each model as it is processed for real-time output, while a reporter might only be interested in the `after` with a `TestRun` model.

To keep this simple, I don't propose a more fat interface with different functions for each model type, but a such interface could easily be implemented as a visitor pattern, or perhaps by something more pythonic, but I don't see any reasons for the runner and the models to call such an interface.

### Deprecate almost all existing functions

Almost all the existing functions of the formatter could be deprecated, since the `after` and `before` functions can do the same thing and provide more information. But this can wait until later, and will not be part of the modifications that we are going to make.

## Fixing the logging

It's considerably more tricky to fix the logging than the rest of the fixes presented above. This is mostly because we can't break the existing log capture system compatibility. But the goals are clear and simple, so let's go through them.

### Add logging callbacks to the formatter

As stated in the list of bug formatter above, the formatter need to get the all the log messages in real-time and in the exact same order as they occur. So for that we add three new functions `log`, `stdout` and `stderr`. These functions are always called no matter what log capturing mode you have enabled, so the formatter can decide if the output should be outputted further, or just ignored. 

The log function should receive messages from all log levels, and receive the full `LogRecord` information rather than the preprocessed one. The reason for this is that different loggers might have different verbosity and formatting. 

If it turns out to be too slow to process all log levels, there could be a way for the formatters to request which level they are interested in.

### Ideally the model should contain log information as well.

This is not something that we will do, but it would be good if the models always gathered the logs that occurred during their processing. That way the formatter don't need to do that automatically, if it wants to add the logs to reports rather than printing them directly for example.

The reason for not doing it yet, is that we can work around it by buffering at the formatter, but also because it's not easy to come up with a suitable design for it. Storing the full `LogRecord` could take up quite a lot of resources and memory for example. Also, some reporters might want to differentiate between `log`, `stdout` and `stderr`, while others want everything in the exact same order as they triggered.

Additionally, the current capture implementation might not always add the logs to the exact statement that was executing at that time, so it could break some things.

**Comment by jenisys** [comment]
As already stated: 
* This needs to be split-up into multiple issues to become acceptable
* In addition, pull-requests to provide "solutions" for the mentioned problems are not provided.
