### ISSUE TITLE
Idea: recommend contextlib.ExitStack for scenario resource management

### ISSUE THREAD

**Issue by ncoghlan** [behave/behave#505]
In https://github.com/behave/behave/issues/399#issuecomment-175869175 @jenisys suggested adding a "scenario_janitor" object to the context for scenario resource management.

Would it make sense to document this suggestion explicitly, with `contextlib.ExitStack` in the role of resource manager?

Alternatively, it would be possible to go a step further and implicitly create a scenario scoped `resource_manager` attribute, using `contextlib2.ExitStack` to support earlier Python versions that don't offer `contextlib.ExitStack` natively.

**Comment by jenisys** [comment]
A ``context.add_cleanup()`` functionality is underway and will be released soon. This will performed cleanups when the context layer is popped on scenario/feature/testrun level. This means:

* When you register a cleanup in ``before_scenario()`` hook or after it (in step-hooks or in steps), it will be executed after ``after_scenario()`` hook is called for this scenario
* When you register a cleanup in ``before_feature()`` hook, it will be executed after ``after_feature()`` hook is called for this feature
* When you register a cleanup in ``before_all()`` hook, it will be executed after ``after_all()`` hook is called

**Comment by aw2003** [comment]
The add_cleanup() concept sounds pretty clean, and flexible. Nice choice. I've been looking for something which could allow the equivalent of a "finally" clause in a testcase, as I have tests which can make extensive changes to the devices under test (embedded radios), and need a way to always "clean up" afterwards.

I can see this feature making a nice clean job of that, without needing to specify additional steps, by stipulating the mechanism to reverse out the changes in the step which makes the config changes to the radios.

**Comment by jenisys** [comment]
Added Context-cleanup concept.
INTEGRATED INTO: behave-1.2.6.dev0
