### ISSUE TITLE
Non english UTF-8 steps not working

### ISSUE THREAD

**Issue by MichaelLogutov** [behave/behave#507]
PyCharm 2016.2.3
Python 3.5.2

test.feature:
```
Feature: Тест

  Scenario: Тестовый сценарий
    Given Шаг 1
    When Шаг 2
    Then Шаг 3
```

test.py:
```
from behave import *

use_step_matcher("re")


@given(u"Шаг 1")
def step_impl(context):
    pass


@when(u"Шаг 2")
def step_impl(context):
    pass


@then(u"Шаг 3")
def step_impl(context):
    pass
```

Result:
```
"C:\Program Files (x86)\Python35-32\python.exe" "C:\Program Files (x86)\JetBrains\PyCharm 2016.2.3\helpers\pycharm\behave_runner.py"
Testing started at 15:34 ...

Test undefined
Please define test

Test undefined
Please define test

Test undefined
Please define test

Process finished with exit code 0
```

Both files saved in UTF-8
If I rename steps to english - it will start working.

**Comment by CyRaXMAN** [comment]
Behave supports [different languages](https://pythonhosted.org/behave/gherkin.html#languages-other-than-english) and Russian too. You can set language in "Run configuration"

**Comment by MichaelLogutov** [comment]
Thanks, but thats not what I mean. I don't mind English keywords - the problem is that it does not work with non-english (russian in this case) step names - behave simply don't see any steps defined.

**Comment by jenisys** [comment]
Well, i looks like ``behave`` is not finding your steps.
Behave does not care in which language you write your steps (after the keywords).
Behave expects a certain directory structure, like:

```
features/
   +-- steps/*.py
   +-- *.features
```

In addition, use the standard ``behave`` runner and not PyCharm's one. Otherwise, you need to ask the question in PyCharm trouble-ticket system.
