### ISSUE TITLE
Ubuntu AmbiguousStep Exception

### ISSUE THREAD

**Issue by TageNielsen** [behave/behave#511]
snip of stack trace
`bat/autotest/local/lib/python2.7/site-packages/behave/step_registry.py", line 85, in wrapper
    self.add_step_definition(step_type, step_text, func)
  File "/home/jenkins/workspace/test-tfw-finder-behave-dev-bat/autotest/local/lib/python2.7/site-packages/behave/step_registry.py", line 49, in add_step_definition
    raise AmbiguousStep(message % (new_step, existing_step))
behave.step_registry.AmbiguousStep: @then('the user can successfully authenticate with the "{platform}" client') has already been defined in
  existing step @then('the user can successfully authenticate with the "{platform}" client') at steps/authentication.py:10`

This fails because the path to module when called by behave and when imported by python 2.7 is different due to symlinks, but the module is in fact the same.

We are running python within a virtualenv on an Ubuntu node, which creates a local directory with symlinks to the non-local install for this [reason](https://github.com/pypa/virtualenv/blob/112b6a22452b3ed813943f092f48031d3477d081/virtualenv.py#L1294).

We bypass the issue by using `virtualenv autotest --always-copy` to remove any symlinks.

It is suggested that we fix [behave.model_core.FileLocation.__eq__](https://github.com/behave/behave/blob/master/behave/model_core.py#L180]), such that for
posixpath we use [samefile](https://docs.python.org/2/library/os.path.html#os.path.samefile) instead of comparing paths.

**Comment by jenisys** [comment]
I will look into it, but ``os.path.samefile()`` has some "problems":
* It is not implemented on all platforms (meaning: only UNIX)
* It fails when a path does not exist which causes currently the unit tests to fail (do to ``os.stat()`` usage)
