### ISSUE TITLE
Doubt regarding license

### ISSUE THREAD

**Issue by pksadiq** [behave/behave#514]
Hi. Reading the LICENSE, I don't understand which license this software is released in (though I believe it is BSD).

I checked if this package is in Debian. It isn't. One possible reason could be the license (That is, not much people interested in packaging this). Is it possible to dual license this project with current license and GPL2+ so that this software would be used by more people?

Thanks.

**Comment by jenisys** [comment]
@pksadiq The package was licensed as BSD from the beginning (AFAIK). I am not aware that would hinder anyone to add it to a package management system. Therefore, I do not intend to start a "license confusion" by adding different license variants. 

In addition, you can always install the package when ``pip`` is installed, even on a Debian system.

**Comment by nicholas-itpedia** [comment]
I agree that the license should stay as BSD. Behave is installed easily using pip so there is not an issue for Ubuntu OS users to use Behave.
