### ISSUE TITLE
Question about tests layout

### ISSUE THREAD

**Issue by pydo** [behave/behave#515]
First off, thank you for your continued development of behave. It's been an invaluable tool for our testing automation.
Now for my question.

I want to use this layout structure:

    tests/features/api/test_api.feature
    tests/features/ui/test_ui.feature
    tests/steps/api/test_api_steps.py
    tests/steps/ui/test_ui_steps.py
    tests/environment.py

I call behave from the parent directory like this `behave tests`

I get an error telling my the steps are not implemented because `behave` can't find the steps file.
I read https://behave.readthedocs.io/en/latest/gherkin.html#layout-variations but I did not see a way of specifying the steps directory.
Is there any way for me to use the aforementioned layout? 

Thanks in advance.

**Comment by jenisys** [comment]
You are trying to add a module system under the ``steps`` directory. That is currently not supported because only one level is supported. Start using a [step-library](https://github.com/behave/behave/blob/master/features/step.use_step_library.feature), if your complexity grows too much.

**Comment by pydo** [comment]
Thanks for the quick answer. I'll try using `tags` and a naming convention to differentiate the different types of tests.
