### ISSUE TITLE
using multi-bytes characters in step_impl()

### ISSUE THREAD

**Issue by dokenzy** [behave/behave#516]
I am using Python 3.4 and usually deals with multilingual, so need to test multi-bytes characters.

However testing with behave, I get error: "UnicodeDecodeError: 'cp949' codec can't decode byte".

Until now I get around this issue, but today I edit runner.py file like this.

line no: 299
from
```with open(filename) as f:```

to
```    with open(filename, encoding='utf-8') as f:```

It works but assumes that encoding is utf-8.

Am I missing a feature in behave? or this way is not bad?

**Comment by jenisys** [comment]
@dokenzy 
* Which behave version are you using?
* Where do you have the text encoding issues ? (feature files or step files (and other *.py))

NOTE:
* The steps encoding should be already solved in the Github repository.
  You may need to put an encoding spec, like "# -*- coding: cp949" into your python file.
* Currently, feature files need to be UTF-8.

**Comment by dokenzy** [comment]
I'm using behave 1.2.5 in Windows 7 64bit.
I have the issue in step files.
Even in comments, multi-bytes characters makes UnicodeDecodeError:
```
def step('blah blah'):
    # 한글
```
Actually I deals with not only Korean but Chinese, Japanese, and many others. Chinese in step file makes same error.

Feature files are no problem.

My python's and step file's encoding is all utf-8 and I have changed code point to 65001 in cmder(alternative of 'Command Prompt').

**Comment by dokenzy** [comment]
Oops. This issue has already been resolved in master branch #361 
But the version in pypi is still 1.2.5.

Thanks.
