### ISSUE TITLE
Scenario outline and execute_steps()

### ISSUE THREAD

**Issue by vlad-ki** [behave/behave#518]
Hi.
I have a problem, help me please.
I want to execute 'Scenario outline' steps with execute_steps() function. But it's does't work. 

I tried this: #117, but the result has not changed.
How can i do this?

Example:
```
    Scenario Outline: Create set with valid data
        Given valid set data <kat> <count> <price>
        When I enter set data
        And I see enabled button "btn_save_continue"
        And click on the "btn_create" button

        Examples: fields for set form
            |kat  |count|price|
            |one  |10   |100  |
```

`Failed to parse <string>: Examples must only appear inside scenario outline`

**Comment by jenisys** [comment]
Please be sure to check that the parse error comes from the example above. The parser error indicates that you use the "Examples:" keyword below a "Scenario: ..." and not below a "Scenario Outline: ...".

EXAMPLES for ``context.execute_steps()``:
* https://github.com/behave/behave.example
* http://behave.github.io/behave.example/tutorials/tutorial08.html
* [features/step.execute_steps.feature](https://github.com/behave/behave/blob/master/features/step.execute_steps.feature)
* [step.execute_steps.with_table.feature](https://github.com/behave/behave/blob/master/features/step.execute_steps.with_table.feature)

**Comment by vlad-ki** [comment]
Yes, it's does't work:
```
Scenario Outline: Create set with valid data
        Given valid set data <kat> <count> <price>
        When I enter set data
        And I see enabled button "btn_save_continue"
        And click on the "btn_create" button

        Examples: fields for set form
            |kat  |count|price|
            |one  |10   |100  |
```

```
@step('some step')
def step_impl(context):
    context.execute_steps('''
        Given valid set data <kat> <count> <price>
            When I enter set data
            And I see enabled button "btn_save_continue"
            And click on the "btn_create" button
            
            Examples: fields for set form
                |kat  |count|price|
                |one  |10   |100  |
    ''')
```

**Comment by jenisys** [comment]
@vlad-ki 
There seems to be a misunderstanding on your side. ``context.execute_steps()`` executes a number of steps, but not a (partial) Scenario Outline without ScenarioOutline title and Examples.

Your step implementation should look like:
```python
@step('some step')
def step_impl(context):
    context.execute_steps('''
        Given valid set data one 10 100
        When I enter set data
        And I see enabled button "btn_save_continue"
        And click on the "btn_create" button
    ''')

# -- ALTERNATIVE-IMPLEMENTATION: 
# NOTE: Either/or in one file
@step('some step')
def step_impl_alternative(context):
    context.execute_steps('''
        Given valid set data {kat} {count} {price}
        When I enter set data
        And I see enabled button "btn_save_continue"
        And click on the "btn_create" button
    '''.format(kat="one", count=10, price=100)
```

**Comment by jenisys** [comment]
Note that your step implementation does not match your feature file.

**Comment by vlad-ki** [comment]
Thank you!
