### ISSUE TITLE
NotImplementedError in Python 3 with some characters

### ISSUE THREAD

**Issue by lucasmello** [behave/behave#519]
I'm having this issue when using characters like "ã", or "ç". I'm using Python 3.5.2, but when I was using Python 2.7, I wasn't experiencing this issue.

 Simple example below:

**test.feature:**

```gherkin
Feature: Login Application

Scenario: Login Success
  Given usuário está na tela inicial do sistema
  When ele tenta realizar uma ação
  Then a ação deve ser concluída`
```

**test.py**

```python
# -*- coding: UTF-8 -*-
from behave import given, when, then


@given(u'usuário está na tela inicial do sistema')
def step_impl(context):
    pass


@when(u'ele tenta realizar uma ação')
def step_impl(context):
    pass


@then(u'a ação deve ser concluída')
def step_impl(context):
    pass
```

**error:**

```python
You can implement step definitions for undefined steps with these snippets:

@given(u'usuário está na tela inicial do sistema')
def step_impl(context):
    raise NotImplementedError(u'STEP: Given usuário está na tela inicial do sistema')
```

**Comment by jenisys** [comment]
Ensure that your step implementation really uses UTF-8 encoding and not only states that it uses UT-8 encoding. Also note that the features test for behave also run on Python 3.5 (and 3.6) without any problems.

**Comment by lucasmello** [comment]
I'm sure the file is using UTF-8, because I put '# -*- coding: UTF-8 -*-' in file header. 

I saw the feature tests for behave, but they don't contain portuguese characters, like "ã", "ç", etc.

I'm pretty sure it is a behave bug!

**Comment by jenisys** [comment]
Putting ``# -*- coding: UTF-8 -*-`` in the header of the python file does not ensure that it uses UTF-8 encoding. It is just a hint to the Python interpreter and may be supported by your editor or IDE that you want to use UTF-8 encoding for this file. Normally your editor indicates (for example in the footer) what encoding is used for a file. Otherwise, write a small Python script ``codecs.open(filename, "UTF-8", ...) and ``file.read()`` to ensure that no decoding problems occur (best in Python 3.5.2).

EXAMPLES: Feature files with non-ASCII characters
* [features/i18n.unicode_problems.feature](https://github.com/behave/behave/blob/master/features/i18n.unicode_problems.feature)
* [tools/test-features/french.feature](https://github.com/behave/behave/blob/master/tools/test-features/french.feature)

**Comment by demirciali** [comment]
Actually I am having the same issue. I have tried different editors but the result is the same.
I am using winpython 3.5.2
Also I have another problem with encoding. When I have moved project to another computer, in case of assertion error it gives exception unicode encoding exception when try to print error text to stdout. if I use outfile, no problem observed. it prints all the text without exception.

**Comment by jenisys** [comment]
@demirciali 
In my experience, at least half of the problems are self-made, for example the "encoding spec" is missing in python files, like: ``# -*- coding: UTF-8 -*-``.

One suggestion, try to use Python 3.6. Especially under Windows, the default encoding becomes UTF-8 (one of the new features in Python 3.6).

**Comment by lucasmello** [comment]
I'd rather not to force the users of my product to update to python 3.6, just because of this encoding issue. I'd really want a solution to this issue :(

**Comment by jenisys** [comment]
@lucasmello 
Which behave version are you using ?
The behave-1.2.5 or the latest on the github repository ?!?

* If you are not using the github repository, try to verify the problem exists with the current state of behave. I can currently not reproduce your problems.
* Are you using a Windows cmd shell or anything else ?!?

**Comment by lucasmello** [comment]
@jenisys sorry for the long delay to answer. I was using version 1.2.5 (I was installing through PIP), but I have forked the repository and installed that version (1.2.6-dev0) and now it's working!

Thanks for your help! But I wonder when are you going to update the PIP repository, because more people may be facing this issue...

Thanks again!
