### ISSUE TITLE
Set a custom heading name for sphinx steps documentation

### ISSUE THREAD

**Issue by ivanprjcts** [behave/behave#520]
Currently, steps sphinx documentation heading is generated automatically from module name.
https://github.com/behave/behave/blob/master/behave/formatter/sphinx_steps.py#L224

But, final result is too long for me,
"package.module.module.module...steps.py"

Is there any way to set a custom name?

**Comment by jenisys** [comment]
Then maybe you should implemented your derived formatter based on ``behave.formatter.sphinx_steps. SphinxStepsDocumentGenerator`` and use it. Or you provide a pull-request how the formatter might be improved to serve your case.
