### ISSUE TITLE
Executing a complete "scenario outline" in a step

### ISSUE THREAD

**Issue by demirciali** [behave/behave#523]
I did some search and read documentation, but I couldn't find a way to execute a complete "scenario outline" in a step in a similar method defined in "Tutorial 8: Execute Other Steps in a Step" example.
Is there a way or I need to do it by coding again.

**Comment by jenisys** [comment]
The [behave.example](https://github.com/behave/behave.example) repository contains the ready-to-use code for ``context.execute_steps()`` in [features/steps/step_tutorial08.py](https://github.com/behave/behave.example/blob/master/features/steps/step_tutorial08.py). Actually, when the Sphinx documentation is build, this code gets executed as living-documentation (that verifies itself).

SEE ALSO:
* [features/step.execute_steps.feature](https://github.com/behave/behave/blob/master/features/step.execute_steps.feature)
