### ISSUE TITLE
Step definitions for web testing

### ISSUE THREAD

**Issue by fkromer** [behave/behave#526]
I started to collect some generic step definitions (and util functions they depend on) related to web testing in [behave-stepdefs](https://github.com/fkromer/behave-stepdefs). (The frontend steps depend on selenium.) Feel free to contribute.

**Comment by jenisys** [comment]
@fkromer 
Thanks for the info.

FEEDBACK:
After a quick look over your step definitions [behave-steps/steps/frontend.py](https://github.com/fkromer/behave-stepdefs/blob/master/behave-stepdefs/steps/frontend.py).
Are you sure that this code runs ?!?
* ``behave-stepdefs/steps/frontend.py`` seems to be lacking an import ``webcommon``.
* "behave-stepdefs" is not a valid python module name (use underscore on the 2nd level: ``behave_stepdefs``)

HINT: If I am right, maybe it is a good idea to use a static code analyser, like [pylint](https://pypi.python.org/pypi/pylint) or ...

**Comment by fkromer** [comment]
@jenisys I know about some issues 😅. I just wanted to setup some basic directory structure and file content. (I was inspired by some "external" code but did not want to use it as is.) Regarding the invalid python module name and the missing linitng there is no excuse!
