### ISSUE TITLE
Problem with encodings in behave under Windows7

### ISSUE THREAD

**Issue by DaulGitHub** [behave/behave#528]
When I run the test with  behave under Windows7, such a problem:
behave encodes a string from the utf8, and then decodes in cp1251 (this is the root of the problem), translating into a script he does following (python3)
```
s = "АБСДЕ"
print (len (s2.encode ( 'utf8'). decode ( 'cp1251')))

```
and if we consider the problem of real scenario, I get the following:
nav_menu = NavigationMenu (context.browser)
```
checkString = "Объекты"
assert nav_menu.objects_button.text == checkString, "Falling test: Language not change" # test here falls (although it should not)

```
that is, it turns out that in nav_menu.objects_button.text includes fair value of the browser, "Объекты" and checkString contains a modified string, as I described above ( " 'RћR ± SЉRμRєS,S <'").
If I do the same thing does not behave in the context of the transformation of this line does not occur.
On Ubuntu test runs without errors, but Windows7 this fail (at the beginning of the file I put # - * - coding: utf-8 - * - although it is not required on python3).
if you encountered such a problem in behave?

the problem does not occur if I put in the beginning of the file # - * - coding: cp1251 - * -, but it is a crutch ...

**Comment by jenisys** [comment]
If the solution is that everything is fine when you put an encoding hint into the header of the python file, like:

```python
# -*- coding: cp1251 -*-
...
```

this means that your Python file uses actually ``encoding=cp1251`` and not ``encoding=UTF-8``. This also the default assumption in Python3 (AFAIK). Therefore, you should use Python files with UTF-8 encoding (and may not need an encoding spec in Python3) or you use your favourite encoding and need to place an encoding hint into the header of your python file.

**Comment by DaulGitHub** [comment]
Maybe I'm wrong to put it, I reformulate the question. 
Why Behave translate the string "Объекты" in the string "РћР±СЉРµРєС‚С‹" ?
I run program in Windows7 x86, python3.6, at the beginning file # -*- coding: utf-8 -*-

**Comment by jenisys** [comment]
Which behave version are you using ?
* If behave-1.2.5, this is fixed in the repo
* If not, say otherwise.

**Comment by DaulGitHub** [comment]
I am use behave-1.2.5

**Comment by jenisys** [comment]
As I said, verify if the problem persists with the Github repository.

**Comment by DaulGitHub** [comment]
I've updated the code from the repository(behave 1.2.6.dev0), where the problem is solved.
Thank you for the good work!)

**Comment by jenisys** [comment]
Thanks.
