### ISSUE TITLE
The attribute of the context, which set in hook 'before_scenario', is not available.

### ISSUE THREAD

**Issue by vlad-ki** [behave/behave#529]
HI! I have a problem here. 
The attribute of the context, which set in hook 'before_scenario', is not available in the steps if scenario.
environment.py:

```
def before_scenario(context, scenario):
    context.driver = get_driver(context.config.driver)
    context.URL = context.config.URL
````
`AttributeError: 'Context' object has no attribute 'driver'`

BUT with before_feature it's working perfect!
How I can do this with 'before_scenario'??

**Comment by jenisys** [comment]
The context object works as a stack of layers. Before you enter a scenario, a layer is added to the stack and when the scenario is finished, the layer is popped from the stack. All the changes to the context object remain only valid until the scenario is finished (or left). Same concept applies to feature and test-run layer.

SEE ALSO:
* [Behave Docs: Context Attributes](http://behave.readthedocs.io/en/latest/context_attributes.html) (in Appendix)
* [features/context.local_params.feature](https://github.com/behave/behave/blob/master/features/context.local_params.feature)
* [features/context.global_params.feature](https://github.com/behave/behave/blob/master/features/context.global_params.feature)

**Comment by jenisys** [comment]
The problem above normally means that your step implementations requires something that is not done yet. Either you make your step implementation more robust or you ensure that the requirements/assumptions are met.

**Comment by jenisys** [comment]
And also note that driver is no attribute in ``behave``'s configuration object. Use the ``userdata`` concept if you want to inject your own data.
