### ISSUE TITLE
If i want to run a feature or scenario multiple times, how should i do it?

### ISSUE THREAD

**Issue by yangjin795** [behave/behave#530]
If I want use behave to do performance test and I need to run one feature or scenario multiple times and calculate some performance indices. 
How should I do it?
Any suggestions?

**Comment by jenisys** [comment]
For example:
* Use a build script that provides the for-loop and calls behave in each iteration
* Write your own behave runner "behave_repeated.py" that provides a ``-repeat=N`` option
* Use a variation of [behave/contrib/scenario_autoretry.py](https://github.com/behave/behave/blob/master/behave/contrib/scenario_autoretry.py) to always run tagged scenarios or features repeatedly
* Use a feature file as test runner (with ``behave``, ``behave4cmd`` and your step implementation), like:

```gherkin
@slow
Feature:
   Scenario: Run a features many times
      When I run "behave features/alice.feature" 1000 times
      Then the worst-case feature runtime per iteration is less than 0.5 seconds
      But note that "I am really happy now ;-)"
```

HINTS:
* For the last case, you have to write a step implementation that calls ``behave4cmd0.command_steps.step_i_run_command()`` multiple times in a for-loop.
* In many cases the first suggestion (build-script based solution) is the best choice. For example, use [invoke](http://www.pyinvoke.org) as build-tool.

**Comment by mrosanes** [comment]
Maybe this can be useful for you; the following runner script (testrunner.py) allows to run many times a given scenario, scenario outline, feature-file, ... 

[testrunner.txt](https://github.com/behave/behave/files/5561796/testrunner.txt) (just change the '.txt' extension by the '.py' extension)

**testrunner script features:**

Python script named `testrunner` to be used in conjunction with behave tests, with the following options:
- Run a single test scenario x times (option -n)
- Run any given number of different test scenarios x times (option -n)
- Run a single feature x times (option -f)
- Run any given number of different feature files x times (option -f)
- Run the whole testsuite x times
- The logs can also be stored on a file (option -o)
