### ISSUE TITLE
stdout from after/before_feature are not present in junit output XML

### ISSUE THREAD

**Issue by lagin** [behave/behave#535]
Anything what is not printed in steps is not present in output XML.
Is it bug, or is it feature? Is there way how to capture it?
I tried @capture but, that did not help.
Thx.

**Comment by lagin** [comment]
Any news/info on this?

**Comment by lagin** [comment]
Here is code sample...
[behave.zip](https://github.com/behave/behave/files/879941/behave.zip)

**Comment by jenisys** [comment]
Currently a "feature".

**Comment by jenisys** [comment]
@stalebot: reopen
