### ISSUE TITLE
question :: share step between domain

### ISSUE THREAD

**Issue by rmerkushin** [behave/behave#537]
Is there a way to share step definitions between features in different domains?

My tests structure looks like this:

```
├── example
│   ├── data
│   │   ├── user_1_info.json
│   │   ├── user_12_info.json
│   │   └── user_list.json
│   ├── receiving_user_information.feature
│   ├── steps
│   │   ├── receiving_user_information.py
│   │   └── user_management.py
│   └── user_management.feature
└── idp
    ├── data
    ├── initial_dump_processing_service.feature
    └── steps
        └── initial_dump_processing_service.py
```

I want to share step definitions between example and idp domains. How can i do this?

**Comment by jenisys** [comment]
@rmerkushin 
Use a step library, like in [behave/features/steps/use_steplib_behave4cmd.py](https://github.com/behave/behave/blob/master/features/steps/use_steplib_behave4cmd.py) .

SEE ALSO:
* [features/step.use_step_library.feature](https://github.com/behave/behave/blob/master/features/step.use_step_library.feature)
* [behave docs search: step library](http://behave.readthedocs.io/en/latest/test_domains.html?highlight=step%20library)
