### ISSUE TITLE
How to use "print" in behave?

### ISSUE THREAD

**Issue by lizhaode** [behave/behave#539]
The feature file is 

```
Feature: sample

    Scenario:
        Given I have 3
        when  I compare with 2
        then   Got result
```

The .py file is 

```
from behave import *

@given('I have {num}')
def setup1(context,num):
    context.num = num

@when('I compare with {num2}')
def setup2(context,num2):
    context.num2 = num2
    print('1234')
    

@then('Got result')
def setup3(context):
    assert context.num > context.num2,context.num + '比2小！'
```

When I in terminal run behave like this `behave`,the result is 

![](https://s10.postimg.org/ki755ajl5/QQ20170320_130343_2x.png)

Not print 1234 !!!!!!!

now I run this `behave --no-capture`,the result is 

![](https://s12.postimg.org/cgd91ofa5/image.png)

also not print 1234 !!!!!

if I change feature file like 
```
Feature: sample

    Scenario:
        Given I have 1
        when  I compare with 2
        then   Got result
```

the `1234` printed 

![](https://s2.postimg.org/ys9pwimah/image.png)

so , how did I use print ?

**Comment by lizhaode** [comment]
@

**Comment by lizhaode** [comment]
@jenisys Please help me,thanks!!

**Comment by jenisys** [comment]
@lizhaode
First, before anything else: 
You are entering and comparing strings and not numbers in your steps.

Per default, ``behave`` captures stdout. This captured output is only shown if a failure occurs.
This behaviour is sufficient for most cases.

If you do not like that, disable it by using options ``--no-capture``, ``--no-capture-stderr``, ``--no-logcapture``. One approach for you could be that you do not capture logging data (and write that to a file). For example, store your desired default value for the options in ``behave.ini``:

```ini
# -- FILE: behave.ini
# SEE: behave/configuration.py or read the docs.
[behave]
stdout_capture = true
stderr_capture = false
log_capture = false
```

SEE ALSO:
* [features/capture_stdout.feature](https://github.com/behave/behave/blob/master/features/capture_stdout.feature)
* [features/capture_stderr.feature](https://github.com/behave/behave/blob/master/features/capture_stderr.feature)
* [features/logcapture.feature](https://github.com/behave/behave/blob/master/features/logcapture.feature)
* [features/logging.no_capture.feature](https://github.com/behave/behave/blob/master/features/logging.no_capture.feature)

**Comment by lizhaode** [comment]
@jenisys 
Sorry,I have to say I don't understand your `features/capture_stdout.feature`

I don't know why I need use command `behave -f plain --no-capture` to print something.
Why I use sample `behave --no-capture` command to print?  I like `pretty` format

**Comment by jenisys** [comment]
That is not the point. You can use the pretty formatter. The test uses the plain formatter that is all. The capture/non-capture concept is independent of the formatter.

**Comment by lizhaode** [comment]
But 
 when I use `behave --no-capture` command,the `print('something')` not print in console

**Comment by jenisys** [comment]
When you use the pretty formatter in coloured mode, it writes the output in 2 phases:

* Before a step is executed, it print the step in grey color
* After the step is executed, it rewinds and uses green (step passed) or red colour (step failed)

Easy to test if your text is overwritten by the formatter:
* Print multiple lines (just to test it)
* Use the another formatter, for example the plain formatter

If your text shows now (at least partially), then your text is overwritten.
If you needs the textual output, write to a file or use logging to a file.

**Comment by dridk** [comment]
I agree, 
It is really confusing ...   The --no-capture doesn't work with colors . I lost many time to understand why:
 
The following command will not print anything: 

```bash
behave --no-capture 
```

But this line will  : 

```bash
behave --no-capture --no-color
```

The following print works :  
```python
print("hello", context) 
```
But not this one : 
```python
print("hello") 
```

It is a bug . --no-capture should display print every time.

**Comment by pengi** [comment]
From a technical standpoint, `--no-capture` may no be a bug that it doesn't capture the stdout. It might be useful in some formatters and usecases.

But it is in my opinion definitely a bug that `--no-capture` is intended to get access to print() statements when developing test cases.

As a user, I don't mind if behave captures stdout or not, I'm interested in getting access to the `print()` statements so I can track internals of the steps even if they succeed, so I can track the state of my test fixtures. If it captures the prints and then reprints them is ok for me. If I have to use another logging facility, then it's ok for me too.

**Comment by Danl2620** [comment]
Has there been any update here? I'm trying to use print debugging and there doesn't seem to be any combination of command line parameters that will consistent output anything. I'm unable to inspect the context or fixture correctly. Thanks!
