### ISSUE TITLE
Include step in JUnit/XML <failure> tag

### ISSUE THREAD

**Issue by quantoid** [behave/behave#54]
The XML test results are great for integration with Hudson but it's frustrating that the failure messages don't include the step. The message attribute is blank and the content is just the assertion exception message, so all you have to go on is the feature and scenario names and the captured stdout.

For example:

    :
    <testcase class="example" name="Alert on boundary case just inside threshold" time="1.028">
    <failure message="None" type="NoneType">Assertion Failed: intensity is 50
    Captured stdout:
    :
    </failure>
    </testcase>
    :

It would be more logical to populate the XML report as follows:

    <testsuite ...>
        <testcase ...>
            <failure message="{exception message}" type="{exception type}">
                {scenario steps with passed/failed/skipped result on each one}
                {stack trace for exception related to failed step}
            </failure>
            <system-out>
                {captured sysout if capture option is active}
            </system-out>
            <system-err>
                {captured syserr if capture option is active}
                {captured logging if logcapture option is active}
            </system-err>
        <testcase>
    <testsuite>

**Comment by jenisys** [comment]
Long solved (verified).
