### ISSUE TITLE
Extend Feature Files?

### ISSUE THREAD

**Issue by rahulkp220** [behave/behave#540]
This isn't a issue, but a question rather.

Can we have a feature in behave wherein there is a base feature file (something like base.feature) and then there can be multiple other sub feature files which can inherit from the base?

```
my_behave_folder
		|- steps
		|- features
				|-base.feature
				|-sample.feature
```

base.feature will have some predefined business requisites which can be common for all
other feature files.

syntax can be like
----------------------
extends base.feature

The steps for this base.feature may be defined in a base step file, but can be overriden
depending upon the use case(but at the same time keeping the base feature's behaviour intact).

**Comment by jenisys** [comment]
You are basically asking for a template extension mechanism. [Gherkin](https://github.com/cucumber/cucumber/tree/master/gherkin) does not have such a functionality. But you can easily use template-engines for that purpose, for example [Jinja2](http://jinja.pocoo.org).

PROCEDURE (performed by build-script):
* Before execution, generate feature-files from ``*.feature.in`` (if needed)
* Then execute the feature-files with ``behave``
