### ISSUE TITLE
Different approaches to improve logging

### ISSUE THREAD

**Issue by pprzetacznik** [behave/behave#541]
I would like to improve logging by adding console logging while also generating report. Is there any way to add my custom formatter which can log to log file using my own logger?

Also it would be very helpful to be aple to print current step name from inside of the step. Is it possible using context property?

**Comment by jenisys** [comment]
Have a look at the ``features/*log*.feature``.

SEE ALSO:
* [features/logging.setup_with_configfile.feature](https://github.com/behave/behave/blob/master/features/logging.setup_with_configfile.feature)
