### ISSUE TITLE
KeyboardInterrupt stops behave run without calling after_all()

### ISSUE THREAD

**Issue by candeira** [behave/behave#543]
I tried to set up a signal handler in the `environment.py` module to catch `SIGINT` and clean up, but my function doesn't get called. A KeyboardInterrupt exception handler catches the signal

Then I figured out that maybe `after_all()` would be called by behave on KeyboardInterrupt, but it doesn't seem to be, either.

**Comment by jenisys** [comment]
* Which behave version are you using ?
* Have you looked [features/runner.hook_errors.feature](https://github.com/behave/behave/blob/master/features/runner.hook_errors.feature) ?

**Comment by jenisys** [comment]
Close => No response
