### ISSUE TITLE
Don't output .xml files when a whole feature is skipped

### ISSUE THREAD

**Issue by mbeltre** [behave/behave#544]
Is there a way to prevent the junit reporter from creating an output file when a feature file was completely skipped?

**Comment by jenisys** [comment]
Can you provide an example when that happens ?

For example, the following command does not generate any XML files as JUnit XML reports:

```sh
$ behave --tags @unknown --junit --junit-directory=reports features/
0 features passed, 0 failed, 75 skipped
0 scenarios passed, 0 failed, 464 skipped
0 steps passed, 0 failed, 1838 skipped, 0 undefined
Took 0m0.000s
```
