### ISSUE TITLE
after reset_runtime is called, step_registry.registry is not the actual "step registry" anymore

### ISSUE THREAD

**Issue by ftartaggia** [behave/behave#549]
`__main__` module imports `runner` module, causing the latter to hold a reference to instance `R1` of `step_registry.registry` (named `the_step_registry`). Also note that `step_registry.setup_step_decorators()`'s optional `registry` param is bound to `R1`.

`__main__.run_behave` function calls `reset_runtime()` which replaces `step_registry.registry` with instance `R2`.

Now, when the Runner runs, it lazily initialises its `self.step_registry` to be `the_step_registry` (which is `R1`, not `R2`).
Moreover, the Runner loads step definitions injecting some customised globals into step definition .py files (via `exec_file`). Those globals are, as far as I can tell, the `"given", "when", "then"` decorators. The point here is that those decorators are produced calling `setup_step_decorators` with the default value of the `registry` param, which, again is `R1` and not `R2`.

As a consequence, everything is working fine, but the global variable `registry` in the `step_registry` module is not the step registry that is actually used by behave during its execution.

If someone was to programmatically register a step using `registry_step.registry` (for example in the `before_all` hook), they would add the step to an unused registry and get an undefined step warning.

Is `reset_runtime()` really needed?

**Comment by jenisys** [comment]
Yes, ``reset_runtime()`` is needed to reach a clean state.
When you do not want it, provide your own ``behave`` runner that does something else.

You are hinting that you want to perform some "dirty registration" of well-known steps under the hoods. That is in most cases bad practice in my opinion and leads to unexpected behaviour for the user.

**Comment by ftartaggia** [comment]
I'm saying that public global behave.step_registry.registry is NOT the actual registry being used by the ModelRunner.

This behaviour is different than 1.2.5 and is not immediately clear reading the code.

So, the current lifecycle is, at least, error prone and confusing.

Instead of reinstantiate the registry, why not resetting its internal state in reset_runtime()?
