### ISSUE TITLE
Make `given`, `then`, and `when` equivalent in step definitions

### ISSUE THREAD

**Issue by abingham** [behave/behave#550]
Currently the `@given` decorator will only match "Given" steps, the `@then` decorator will only match "Then" steps, and so forth. Ultimately it seems like the distinction between these is entirely for human readers of feature file, and it would be convenient (in some cases, at least) to remove the distinction in the actual step definition. That is, it would simplify some step implementations if `@given`, `@when`, and `@then` (and others, I guess) were all interchangeable and equivalent. 

Maybe there's a reason to differentiate them at the step implementation level, but I haven't encountered it. IIRC, the javascript cucumber implementation doesn't make the distinction.

**Comment by jenisys** [comment]
Sorry, there is a reason for this. It make the test more readable and more concise.
But you can also use the ``@step()`` decorator if you do not want to be precise.
In addition, you can use multiple decorators on one step, like in:
[behave4cmd0/command_steps.py::step_i_run_command](https://github.com/behave/behave/blob/master/behave4cmd0/command_steps.py#L144)

**Comment by abingham** [comment]
`@step` is perfect for my needs. The differences between given, then, etc. are largely cosmetic (i.e. not semantic) to me, so I didn't want them to intrude any further into my code than necessary. Thanks!
