### ISSUE TITLE
Summary Reporter: Should report actual test-run duration instead of accumulated step durations

### ISSUE THREAD

**Issue by eykd** [behave/behave#555]
I have a fairly large behave test suite that takes a while to run. When I run it w/ `time behave`, this is the summary that I get:

```
$ time behave
[...]
34 features passed, 0 failed, 0 skipped
218 scenarios passed, 0 failed, 0 skipped
4182 steps passed, 0 failed, 0 skipped, 0 undefined
Took 6m34.927s

real    21m0.351s
user    3m23.149s
sys     0m32.905s
```

Behave's self-reported time taken is laughably wrong, vs. wall clock time. Is my server traveling at relativistic velocities, or is there a problem with behave? :)

**Comment by jenisys** [comment]
Behave measures time for executing steps and accumulates it. The time spent in hooks, etc. is currently not taken into account.

**Comment by eykd** [comment]
That makes sense, *and* gives me a clue as to why the test suite is taking so long. Thanks!

Is there a plan to count overall time, rather than just step time? I could see it being useful to know both. Or I could just use `time behave` like I've been doing.
