### ISSUE TITLE
Skipped steps still appear in final counter and jUnit report with -k argument

### ISSUE THREAD

**Issue by pokiz** [behave/behave#557]
It is not really an issue, but in our case, we use Jenkins to run behave and aggregate jUnit reports and then display everything in Kibana.
Everything works great, excepting that even with '-k' command line argument, skipped tests still appear in final counter, and in jUnit report as skipped.
How to bypass this behavior (in case this is the expected one) ?
I could work on it if necessary, just wait for a feedback.

Thanks for reading,

Victor

**Comment by jenisys** [comment]
@pokiz 
The ``behave --no-skipped ...`` or ``behave -k ...`` option only affects the formatter but not the summary output.

When you aggregate JUnit reports (from multiple test runs ?), you must be precise.

```shell
$ behave --junit features/tags.active_tags.feature:100
...

1 feature passed, 0 failed, 0 skipped
2 scenarios passed, 0 failed, 12 skipped
9 steps passed, 0 failed, 53 skipped, 0 undefined
Took 0m0.265s
```

But the test report under ``reports/TESTS-tags.active_tags.xml`` indicates that only 2 tests are run and none are skipped by using the ``testsuite.@tests`` and ``test suite.@skipped`` attributes:

```xml
<?xml version='1.0' encoding='UTF-8'?>
<testsuite errors="0" failures="0" hostname="xxx" name="tags.active_tags.Active Tags" 
   skipped="0" tests="2" time="0.264558" timestamp="2017-04-15Txx:01:02.149321">
<testcase classname="tags.active_tags.Active Tags" name="Feature Setup" status="passed" time="0.006038">
...
```
