### ISSUE TITLE
Use 'zh-CN' Language can not distinguish test case

### ISSUE THREAD

**Issue by yileye** [behave/behave#560]
In my case:

#pip list |grep behave:
behave (1.2.5)

I add a line to the top of the feature files like (for Chinese):
like this:
‘# language: zh-CN
功能: 功能
  In order to verify the new demand,
  As a QA
  I want to test the $FeatureName

  场景: 测试
    假如 测试1
    当  测试2
    那么  测试3’

The Feature file can really identify keywords，then I create a step file like this:

`from behave import *
from hamcrest import *
use_step_matcher("re")
@given(‘测试1')
def verify_element1(context):
    assert_that(context.testPage.get_data(), is_(1))

@when('测试2')
def verify_element2(context):
    assert_that(context.testPage.get_data(), is_(1))

@then('测试3')
def verify_element3(context):
    assert_that(context.testPage.get_data(), is_(1))`

The step in Feature file can correspond in step file, but when I run the feature file:

'Testing started at 下午7:18 ...
2017-04-23 19:18:44,658 [ INFO] [lib.webtools.base_test]  Start of test: 测试
Test undefined
Please define test

Test undefined
Please define test

Test undefined
Please define test
2017-04-23 19:18:45,303 [ INFO] [lib.webtools.base_test]  End of test: 测试. Status: FAILED !!!'

What should I do

**Comment by jenisys** [comment]
Which version of behave are you using ?

The current tip of the Github repository supports it (related to #344; CHANGES: parser).
For the released version, ``behave-1.2.5`` it it probably best to specify the language in behave's configfile, like (if all features are using the same language):

```ini
[behave]
lang = zh-CN
...
```

**Comment by jenisys** [comment]
And note that you still need UTF-8 encoding in feature files.
