### ISSUE TITLE
ParseError: Failed to parse | Examples must only appear inside scenario outline at line 15

### ISSUE THREAD

**Issue by karbon62** [behave/behave#561]
Hi, 

I've come across this issue where I run my tests and I see "ParseError" following "Examples must appear inside scenario outline...."

I can't find anything that is related to my issue online and hope someone could help me out on this. 
I am struggling to understand what has even caused error. 

Many Thanks, 
Karbon62

**Comment by phunter00** [comment]
The contents of the feature file would be helpful...:-)

**Comment by jenisys** [comment]
As @phunter00 stated an example feature file would be helpful.

The parser tells you that the ``Examples`` keyword/section is only allowed in a ``Scenario Outline``.
You probably have something like:

```gherkin
Scenario: One
   Given a user with name "<name>"
   
  Examples:
    | name |
    | Alice |
    | Bob  |
```

instead of:

```gherkin
Scenario Outline: One
   Given a user with name "<name>"
   
  Examples:
    | name |
    | Alice |
    | Bob  |
```

**Comment by karbon62** [comment]
Hi, 

I have of the following:


Feature: valid login

  Scenario Outline: user login with valid username
    Given user is not logged in
    When user taps on username field
    Then user should enters valid username


  Scenario Outline: user login with valid password
    Given user enters valid username
    When user taps on password field
    Then user should enter valid password '

  Examples:
  |username|password|
  |Karbon62|1234    |


I've ran the script but its not identifying the tests so no tests have passed.

**Comment by karbon62** [comment]
@jenisys sorry it took such a long time to get respond. 

I have included the following Scenarios, wondering how I could improve this. Thanks.

**Comment by jenisys** [comment]
@karbon62 
Sorry, you are not showing me any valid/sensible ScenarioOutlines:

* Your ScenarioOutlines contain no placeholders, like: ``Given ... "<username>"... "<password>"`` .
* Your ScenarioOutlines are also not processed Gherkin output because your Examples data is not contained in them

SEE ALSO:
* [behave.example/tutorials/tutorial04.html](http://behave.github.io/behave.example/tutorials/tutorial04.html)
