### ISSUE TITLE
How to write customized step description/definition in Behave

### ISSUE THREAD

**Issue by SudheeraRavichettu** [behave/behave#562]
I have below scenarios

Scenario: 1:Match simple parameter
    Given I use the regular expression step matcher

Scenario: 2:Match simple parameter match
    Given I **will** use the regular expression step matcher

Both **Given** steps should go to same step implementation, the only difference in them is **will** otherwise both are same.

**Comment by jenisys** [comment]
Potential solutions:
* Use multiple step decorators (simplest solution in most cases)
* Provide a placeholder parameter that catches the word(s) as syntactic sugar
* One step implementation calls the other (requires: step functions with different names)
* Move the the the body of the step implementation into a function that is called by both steps

Example 1:
```python
# -- FILE: features/steps/example_steps.py
from behave import given, when, then

@given(u' I use the regular expression step matcher')
@given(u' I will use the regular expression step matcher')
def step_use_regexp_step_matcher(ctx):
    pass    # -- TO BE IMPLEMENTED
```

BUT: In your case it is probably better to decide which of both variants you like more and use it.
