### ISSUE TITLE
The behave performs non-ordering features/tags

### ISSUE THREAD

**Issue by reinaldorossetti** [behave/behave#563]
The behave performs non-ordering features, either --tags=@one, @two first runs to two feature, and fails to run order.

example:

C:\Users\xxxx\Documents\projeto_xxx>behave -t=@autofacil,@autofacil_sem_ass
istencia

@login
Feature: Login # features\login.feature:3
  """
  Feature para efetuar o login no sistema.
  """
  Scenario: Cenario Efetuar Login.                      # features\login.feature
:7
    Given Realizar o login no sistema.                  # None
    When Digitar o login e o password.                  # None
    And Efetuar a autenticacao.                         # None
    Then Validar o acesso ao menu principal do sistema. # None

@logout
Feature: Logout # features\logout.feature:3
  """
  Feature para efetuar o logout do sistema.
  """
  Scenario: Cenario Efetuar Logout.         # features\logout.feature:7
    Given A pagina principal do sistema.    # None
    When Selecionar a opcao sair do sistema # None
    Then Validar o logout do sistema.       # None

Feature: Seguro Autofacil Sem Assistencia. # features\seguro_autofacil_sem_assis
tencia.feature:3

  @autofacil_sem_assistencia
  Scenario: Formulário de Adesao de Seguro Autofacil Sem Assistencia.  # feature
s\seguro_autofacil_sem_assistencia.feature:6
    Given Selecionar o item "Autofacil Sem Assistencia".               # feature
s\steps\global.py:13
Error ao validar o elemento:  Message:

      Assertion Failed: Assertion failed

Feature: Para selecionar o tipo de seguro atraves das tags. # features\seleciona
r_tipo_de_seguro.feature:3

  @autofacil
  Scenario: Cenario Selecionar o Seguro Autofacil.  # features\selecionar_tipo_d
e_seguro.feature:6
    Given A pagina principal do sistema.            # features\steps\logout.py:5

Failing scenarios:
  features\seguro_autofacil_sem_assistencia.feature:6  Formulário de XXX.

1 feature passed, 1 failed, 2 skipped
1 scenario passed, 1 failed, 4 skipped
3 steps passed, 1 failed, 13 skipped, 0 undefined
Took 0m35.900s

Behave version: 1.2.5
OS: Windows 7

**Comment by jenisys** [comment]
Tags (expressions) provide a boolean expression to select which features/scenarios are of interest and should be executed. They basically provide a filter criteria. But they do not provide an ordering criteria in which features are run (if that was what you meant).
