### ISSUE TITLE
How to get the examples table item that is displayed in terminal output?

### ISSUE THREAD

**Issue by simi823** [behave/behave#564]
Not an issues, but I am trying to get the number that gets displayed in the terminal output which lists the scenario number and data table row.
For example, one of my tests shows this:
Scenario Outline: Verify Top Rail Menu button expands -- @1.7 Affiliates  # verifico/features/example.feature:23

which is the Scenario Outline name and then @1 is the first table while 7 is the 7th item in the table. Can I programmatically get this?

**Comment by jenisys** [comment]
In principle yes:
- Scenario.name: You need to extract this information from the string
- ScenarioOutline can define tags that contain this information

SEE ALSO:
* ScenarioOutline improvements: http://behave.readthedocs.io/en/latest/new_and_noteworthy_v1.2.5.html
