### ISSUE TITLE
How to access a Scenario Outline from context

### ISSUE THREAD

**Issue by mathewtrivett** [behave/behave#569]
Hi, thanks so much for making behave.  It is a great tool that I really enjoy using.  I am trying to access a Scenario Outline from inside a step definition off the `context` object.  I want to be able to control different test code depending on the example name.  I have tried `context.scenario` which is of type Scenario but has the keyword Scenario Outline.

What is the easiest way to access a Scenario Outline from context or cast `context.scenario` to a Scenario Outline?

**Comment by mkusz** [comment]
Probably you don't need to do it. Please elaborate what is your problem because more likely it's possible to achieve it differently that taking data from internal behave objects.

**Comment by jenisys** [comment]
You cannot access the ScenarioOutline element (and their should not be any need for it). Only the generated Scenario element and its table row data (``context.active_outline``) is provided.

**Comment by mathewtrivett** [comment]
Hi, thanks for the comments.  In the end I just matched a string in the Scenario to manage control flow.  Essentially I had two different types of tags but used a Scenario Outline to test the same functionality.  I wanted to query different db tables by using the scenario outline name, e.g. 'tagtypeA' and 'tagtypeB'.
