### ISSUE TITLE
Make make_undefined_step_snippet compatible with flake8

### ISSUE THREAD

**Issue by lorddaedra** [behave/behave#570]
We need to create 2 empty lines between steps here:
https://github.com/behave/behave/blob/8686820899a8f86b6c6b0ceebedbcc3f9a033d01/behave/runner_util.py#L371

Also it's good idea to hide prefix for Python 3 here:
https://github.com/behave/behave/blob/8686820899a8f86b6c6b0ceebedbcc3f9a033d01/behave/runner_util.py#L365

**Comment by jenisys** [comment]
The undefined step output is a convenience mechanism. If you do not like it, feel free to adapt the text output when you implement the steps or preprocess it with a script.
