### ISSUE TITLE
Echo stdin when using PDB

### ISSUE THREAD

**Issue by sdressler** [behave/behave#572]
I am trying to debug some of my steps with PDB so I usually do

```python
def step_to_debug(context):
    import pdb
    pdb.set_trace()
    [...]
```

This works very well when I set

```ini
stdout_capture=no
stderr_capture=no
```

in `behave.ini`. However, I cannot see what I am typing (because behave is probably swallowing that). Is there a way to enable echo-ing stdin to stdout in that case?

**Comment by jenisys** [comment]
See the [gitter channel: May 29](https://gitter.im/behave/behave) that provided an answer to this question (if I understood it correctly).

In general, it is far simpler to debug the behave run from within an IDE (like PyCharm or Eclipse PyDev) and add a breakpoint to the the problematic step. The simplest way to do this is to provide your own python script that runs behave. This allows you to start the behave run under control of the IDE debugger (by using the normal python script debugging/run mechanism of the IDE debugger). 

EXAMPLE:
```python
# -- FILE: behave_run.py
# Run behave with own python script
if __name__ == "__main__":
    import sys
    from behave.__main__ import main 
    sys.exit(main())
```

SEE ALSO:
* [bin/behave](https://github.com/behave/behave/blob/master/bin/behave)
* https://gitter.im/behave/behave

**Comment by darrenleeweber** [comment]
For those landing here from a google search, the gitter channel snippet noted above is not so easy to find (but thanks @jenisys).  Anyways, I did find it and it works, it's
```
import sys, pdb; pdb.Pdb(stdout=sys.__stdout__).set_trace()
```

**Comment by gutierri** [comment]
It seems to be interesting to put this @darrenleeweber  tip in the documentation (maybe [tutotial](https://behave.readthedocs.io/en/latest/tutorial.html?highlight=pdb) section?).
