### ISSUE TITLE
Document exit codes and distinguish test failures from other exceptions

### ISSUE THREAD

**Issue by quantoid** [behave/behave#575]
I'm using Bamboo to execute acceptance tests and I need to distinguish between failing tests (which raise `AssertionError`) and any other exceptions (such as `AmbiguousStep`).

It would be useful if `behave` exited with different codes for those two cases, with those codes documented:

- `0` = all scenarios passed
- `1` = some scenarios failed
- `2` = scenarios could not be executed

For failing tests I want my behave task to be successful because I need the next task to run, which publishes the test results (using the generated XML report) and will fail if any of the tests in the report failed. 

For other exceptions I want my behave task to fail, otherwise the next task succeeds if the XML test report doesn't contain any failed tests and my build appears to be successful.

**Comment by jenisys** [comment]
Sorry, this is currently not supported. Behave does not distinguish between failures (AssertionError) and errors (other unexpected exceptions). 

The return code of the behave script only supports the first two cases. 
The third case is up to you.

The same is true for your CI integration. If you need this specific behaviour then provide it.
