### ISSUE TITLE
add suport for And, But tags for readability

### ISSUE THREAD

**Issue by tangorboyz** [behave/behave#577]
I just think that And and But tags would be great for readability since behave only support then.
While features file in gherkin we could define step with "And" and "But", but it just didn't match if in python it just replace with "then" .

**Comment by phunter00** [comment]
Steps are defined with given, when, then the keywords in the regex, but can be used with And or But following an initial use of the correct keyword. Like this:
Given an application to test
  And the application is running

When I do this
  And I do that
  And I do something else
Then the damned thing should do the right thing
  And should not throw an error

Are your regexes formatted like this in Python? 
@given(r'there are (\d) or more channels on the AFG')
@when(r'I turn (ON|OFF) the scope')
@then(r'FastAcq should be set to (0|1|ON|OFF) on the scope')

**Comment by tangorboyz** [comment]
I mean if I write the feature file like:
Given an application to test
When I do this
And I do do that
Then the something else happen
And should not throw an error

In in python it should be like:
@given(u'an application to test')
@when(u'I do this')
@And(u'I do that')
@then(u'something else happen')
@And(u'should not throw an error')

Not the regex, since it hard to read.

**Comment by tangorboyz** [comment]
But no @And or @But in behave that let us do that, just @Then

**Comment by tangorboyz** [comment]
sorry I mean @And since 'and' is keyword

**Comment by phunter00** [comment]
You define the steps in code using only @given, @when and @then. And and But are interpreted as the leading keyword type by the parser.

**Comment by jenisys** [comment]
``And`` and ``But`` keywords are for Gherkin text in feature files and not for redundant declarations of step definitions in Python step files. In addition, the first step in Gherkin must always use the ``Given``, ``When``or ``Then`` keyword. Only following steps can use ``And`` or ``But`` and fall into the same category as the first step (in a group of steps).

Also note: 
@given and @when steps may be usable on the same step implementation, but normally never @then.
Then steps check assumptions with assertions.
