### ISSUE TITLE
Could not get list of supported language with command behave --lang-list

### ISSUE THREAD

**Issue by tangorboyz** [behave/behave#578]
python version: 3.6.1
os: ubuntu 16.04
behave version: 1.2.5

When I run command `behave --lang-list` from the terminal, instead of list of supported language,
I get an error message:

`
Traceback (most recent call last):
  File "/usr/local/bin/behave", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/behave/__main__.py", line 65, in main
    iso_codes.sort()
AttributeError: 'dict_keys' object has no attribute 'sort'
`

**Comment by jenisys** [comment]
If you want to use Python 3.6, it is probably best if you use the current tip of the repository (that does not have this problem).
