### ISSUE TITLE
--steps-catalog (--format=steps.catalog) doesn't respect --include/--exclude

### ISSUE THREAD

**Issue by smadness** [behave/behave#581]
It seems that the --format=steps.catalog aspect of CLI behave doesn't respect --include (and --exclude) paths.  So when something like `behave --steps-catalog --include banana.feature` is run, steps are printed for all .feature files instead of just banana.feature.

```
me% python3 --version
Python 3.6.1

me% behave --version
behave 1.2.5

me% ls  
apple.feature	banana.feature	steps

me% cat apple.feature 
Feature: Apple

Scenario: Eat Apple
	Given that I have an apple
	When I eat that apple
	Then I should have apple skins in my teeth

me% cat banana.feature 
Feature: Banana

Scenario: Eat Banana
	Given that I have a banana
	When I eat that banana
	Then I should have a banana peel on my desk

me% behave --steps-catalog --include banana.feature | grep .
Given that I have an apple
Given that I have a banana
When I eat that apple
When I eat that banana
Then I should have apple skins in my teeth
Then I should have a banana peel on my desk

# below is meant to show that it's the --format arg as culprit

me% behave --include banana.feature --dry-run --no-summary -q
Feature: Banana

  Scenario: Eat Banana 
    Given that I have a banana
    When I eat that banana
    Then I should have a banana peel on my desk

me% behave --include banana.feature --dry-run --no-summary -q --format=steps.catalog | grep .
Given that I have an apple
Given that I have a banana
When I eat that apple
When I eat that banana
Then I should have apple skins in my teeth
Then I should have a banana peel on my desk

```

**Comment by jenisys** [comment]
Your are mistaken. Works as designed. 
The primary reason for steps.catalog (and most other step formatters) is to show which step implementations are available (by using the registered steps) and which can be used in a feature file. In addition, even steps that are not used in feature files are shown.

The intention is not to show the steps that are contained in the selected feature files (or scenarios).
Reading the feature files should be sufficient for that.

**BUT:** ``behave -f=steps.usage --dry-run features/background.feature`` 
works as you intended and only shows steps that are related to the selected features.

**Comment by smadness** [comment]
Thanks for the workaround.

The use case I'm looking for is to be able to more easily see all my steps arranged by type (Given/When/Then) to be able to standardize their language.  For example, I've found that I've sometimes created duplicate steps with different wording in a large feature file.  In this case it's hard to find this just when scanning the full text of that feature file, and something like `cat banana.feature | grep Given` doesn't resolve the 'And's that compile into Givens, so utilizing the resolution that's already within Behave is valuable.  So `behave --..etc banana.feature | grep Given` neatly displays all the Givens closely together to aid in inspection / standardization.

Although -f=steps.usage seems to work, it's a bit more noisy than the steps.catalog (i.e. python syntax rather than Gherkin),
   @given('that I have an apple') # steps/apple-steps.py:13
rather than
  Given that I have an apple

So I suppose my preferred workaround will be to just move .feature and steps.py files out of the working directory before running --steps-catalog.
