### ISSUE TITLE
Fixture support in behave (contextmanager like functionality)

### ISSUE THREAD

**Issue by djrobstep** [behave/behave#594]
It would be nice to be able to use context managers to set up the environment. 

For instance to set up a browser for testing:

```
from contextlib import contextmanager

@contextmanager
def browser():
    context.browser = webdriver.Whatever()
    yield
    context.browser.quit()
```
Instead of having to define this behaviour separately in before and after. Similar to how you can do fixtures with yield in pytest. Thoughts?

**Comment by jenisys** [comment]
INTEGRATED INTO: behave-1.2.6.dev0
