### ISSUE TITLE
Steps with accented letters doesn't seem to work.

### ISSUE THREAD

**Issue by dabradmp** [behave/behave#597]
Hi, I'm brand new here so sorry if it's not the right place to ask the question/issue.

I recently started using behave for automation testing at my new job but I can't make my scenario test properly if I use french accented letter ( éèàç ) in my scenario steps. 

here's the result of a test I did just to see if I could just french in the scenario:

Fonctionnalité: Account Holder transfers cash # features\account_holder_transfers_cash.feature:3
  **In order to** transfer money between accounts
  **As** an Account Holder
  **I want to** transfer cash from an ATM
  Scénario: francais ordinaire (uid:741e47de-893e-42af-b98c-44e9594bc938)  # features\account_holder_transfers_cash.feature:8
    Soit allé                                                              # None
    Quand comment                                                          # None
    Alors cava                                                             # None

Failing scenarios:
  features\account_holder_transfers_cash.feature:8  francais ordinaire (uid:741e47de-893e-42af-b98c-44e9594bc938)

0 features passed, 1 failed, 0 skipped
0 scenarios passed, 1 failed, 0 skipped
0 steps passed, 0 failed, 2 skipped, 1 undefined
Took 0m0.000s

You can implement step definitions for undefined steps with these snippets:

@given(u'allé')
def step_impl(context):
    raise NotImplementedError(u'STEP: Given allé')

The first test is considered undefined because I use the "é" in the steps.

Even if I copy the exact step definition in the exemple given by behave, It still doesn't work.

Everything works perfectly fine if I don't use any accented letters.

I hope someone can help me with that.
Thanks

**Comment by jenisys** [comment]
This is probably a codec/encoding problem of the steps file and/or feature file.
Ensure that your steps file has **UTF-8 encoding** (as well as the feature file).
This is at least the  assumption in behave-1.2.5.
NOTE: The current tip of the repository automatically detects the encoding of the steps file when steps are loading.

HINT: Use encoding hint in Python file.
```python
# -*- coding: UTF-8 -*-
# FILE: features/steps/my_steps.py
...
```

SEE ALSO:
* [tools/test-features/french.feature](https://github.com/behave/behave/blob/master/tools/test-features/french.feature)

**Comment by dabradmp** [comment]
I added the encoding  like you mention but it doesn't change anything...... I added the 2 files in a zip but there's not much in them.
[steps.zip](https://github.com/behave/behave/files/1304629/steps.zip)

**Comment by jenisys** [comment]
I have no problems w/ your provided files. After I moved the steps file under the "steps/" directory, everything works fine (using the current tip of the github repository). Good means: I see the French keywords and the accent on "allé". In addition, the files seem to use UTF-8.

```shell
$ behave -f pretty features/
Fonctionnalité: Account Holder transfers cash # features/account_holder_transfers_cash.feature:5
  **In order to** transfer money between accounts
  **As** an Account Holder
  **I want to** transfer cash from an ATM
  Scénario: francais ordinaire (uid:741e47de-893e-42af-b98c-44e9594bc938)  # features/account_holder_transfers_cash.feature:10
    Soit allé                                                              # features/steps/account_holder_transfers_cash.py:6
    Quand comment                                                          # features/steps/account_holder_transfers_cash.py:10
    Alors cava                                                             # features/steps/account_holder_transfers_cash.py:15

1 feature passed, 0 failed, 0 skipped
1 scenario passed, 0 failed, 0 skipped
3 steps passed, 0 failed, 0 skipped, 0 undefined
```

* Which version of behave are you using (behave-1.2.5 or github-repo master-tip) ?
* Which Python version (2.7.x, 3.5.x, 3.6.x) 
* Which platform and OS version (Windows, Linux, macOS) ? 
  Seems to Windows (from above traces)

**Comment by jenisys** [comment]
There is only a problem when you use Python2 (Python-2.7, ...) if you do not specify the encoding hint in your steps file (or your steps file has another encoding).
