### ISSUE TITLE
Question: How to clear output buffer in between scenarios

### ISSUE THREAD

**Issue by walterdolce** [behave/behave#602]
Hi,

How do I clear the output buffer filled by `print` statements in between scenarios?

I don't want/need to specify CLI options or globally disable the capturing as specified by the first two answers [here](https://stackoverflow.com/questions/25150404/how-can-i-see-print-statements-in-behave-bdd). I only want to clear the buffer after each scenario is executed.

Something like:
```
def after_scenario(context, scenario):
   do_the_thing_that_clears_the_buffer_collected_during_a_scenario_run
```

Thank you!

**Comment by walterdolce** [comment]
Same question applies for step definitions. How would I clear the buffer after each step?

Thank you.

**Comment by jenisys** [comment]
You should not meddle with the capture functionality.
In addition, the capture mechanisms is reset/setup at the beginning of each scenario.
NOTE: Clearing the captured output after each step will be in conflict with the capture functionality.

**What is your use case ?**

**Comment by walterdolce** [comment]
Testing fabric commands output.

**Comment by jenisys** [comment]
Are you running fabric it as subprocess or from within the current python process ?

**Comment by walterdolce** [comment]
I'm using the Python subprocess module directly within the step definitions code.

**Comment by jenisys** [comment]
Then I am not quite sure why you need to clear the output buffer (that is used by ``print()``). The captured output from the subprocess call in your step is in your hands and not directly printed (normally). 

Why are not using something like ``behave4cmd.command_steps`` (or a similar approach) ?

**Comment by jenisys** [comment]
CLOSED: Due to inactivity.
