### ISSUE TITLE
how to provide unicode scenario names to the --name argument?

### ISSUE THREAD

**Issue by alluir42** [behave/behave#606]
Hi,

I've been struggling this for a while - I don't know where the problem really is. I'm trying to use the "--name" argument with a unicode string (py 2.6), and I just can't seem to get it working.

my locale is set to utf-8
```
bash-4.1$ locale
LANG=en_US.UTF8
LC_CTYPE="en_US.UTF-8"
```
[...etc-etc...]

I can see that I can have unicode commandline arguments in general:
```
bash-4.1$ date +"キ%a"
キTue

```
however, when trying to call behave, it fails
```
bash-4.1$ behave --include self --name キ
Traceback (most recent call last):
  File "/usr/bin/behave", line 9, in <module>
    load_entry_point('behave==1.2.5', 'console_scripts', 'behave')()
  File "/usr/lib/python2.6/site-packages/behave/__main__.py", line 53, in main
    config = Configuration(args)
  File "/usr/lib/python2.6/site-packages/behave/configuration.py", line 607, in __init__
    self.name_re = self.build_name_re(self.name)
  File "/usr/lib/python2.6/site-packages/behave/configuration.py", line 670, in build_name_re
    pattern = u"|".join(names)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 0: ordinal not in range(128)

```
I'm not really sure where the problem is, I tried:
--name "u'\u30ad'"
and 
--name u'\u30ad'
and 
as well. Then it does not complain, but it cannot match the scenario name either.

Is there a way to get it working in py2?

**Comment by jenisys** [comment]
FIX INTEGRATED INTO: behave-1.2.6.dev0
