### ISSUE TITLE
Install failed under Python 3.5.1

### ISSUE THREAD

**Issue by ricard33** [behave/behave#611]
Since commit 692bc7776088de3f804d1c188eab8d1920918993, the installation (using pip) fails with following error:
```
error in behave setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected version spec in argparse; python_version < '2.7' at ; python_version < '2.7'
```

Not tested with other version of Python.

**Comment by jenisys** [comment]
* Which platform are you using ? (macOS, Linux, Windows)
* Which pip version are you using ?

NOTE: 
pip installation works for me w/o any problems for Python 3.5.x (for 3.5.3, 3.5.4) ?
But I am using pip-9.0.1.

**Comment by ricard33** [comment]
Hum... I don't know why, but today, it works.
I can't find a way to reproduce it, even doing the same sequence than last week...

My OS is Windows Seven and I'm using the last pip version (9.0.1) with Python 3.5.1 (32 bits)

Maybe a reboot solved the problem. I don't know...
