### ISSUE TITLE
Test sharding with behave 

### ISSUE THREAD

**Issue by ThibF** [behave/behave#612]
Hi,
First thanks for the work on behave, it's really useful and nice to use.
I would like to know what do you think of test sharding with behave.
`Test sharding enables spreading tests across devices to get faster test execution, increase throughput and scale continuous delivery with a short feedback loop.`

I would like to do this but I don't know what is the most appropriate with behave: 

- Should I split statically features before launching behave on multiple instances and try to join the result generated? This mean that I should work on a launcher of behave.
- There is a way to add this behaviour into behave? Maybe this doesn't respect the spirit of the current architecture.
- Something already exist and I didn't know? 

Thank you!

**Comment by lawnmowerlatte** [comment]
The way we've decided to do this is by sharding by directory. Our `features` folder has multiple sub-directories (ie. `web`, `cli` etc.) and we run the test in parallel across different instances with the directory name as a parameter. Each test runs all the `.feature` files in the subdirectory. We then pull the result files back to the main job for processing.

**Comment by ThibF** [comment]
Thanks for your feedback, this make sense if you have clearly separated interfaces to test.
But in my case, I would split only for performance reasons, which would result in unclear split of `feature` files.

> We then pull the result files back to the main job for processing.
Do you merge Junit file together or use other results files ?

**Comment by lawnmowerlatte** [comment]
It’s definitely not a perfect solution, just thought I’d share our solution.

We use a Jenkins plugin to digest the JUnit so no merging is necessary. L

**Comment by jenisys** [comment]
Test sharding is a special case of a behave parallel runner. Behave has no parallel runner, yet. There is one or more pull requests for a parallel runner using multi-processing (which is not sufficient in your use case). I have prototype code of a parallel runner that has the correct architecture to support test sharding. The runner consists of the following processing chain:

```
# -- DESIGN BLUEPRINT: Processing chain of behave parallel runner:
frontend => executor => N workers   (running in multiple threads / processes / devices / ...)  
```

The frontend performs the split-up into work-items, hands them over to the executor, collects the results from the executor and shows the results by using a formatter.

The executor is the variation point of the parallel runner (it knows how parallel execution is implemented). The executor knows how dispatch the code to a number of workers that execute the code. In addition, it collects the results from the workers.

In your case, the workers are running on the devices. A worker is basically the normal behave runner (in your case) that is indirectly controlled by the behave parallel runner (frontend / executor combination) on your PC or CI server.

A distributed executor would also need to synchronize files (feature files and python files) with the other devices where the worker run before the work-items (features or scenarios) are executed by them.
