### ISSUE TITLE
Documentation for step library writers

### ISSUE THREAD

**Issue by spyoungtech** [behave/behave#613]
It would be nice to have at least a small section of documentation dedicated to describing how one could write their own reusable step libraries and how users can use them. A small amount of guidance (best practices, cautionary information, tips, tricks, etc) in this area could go a long way in encouraging the development of such libraries.

At the moment, I am writing a [webdriver step library](https://github.com/spyoungtech/behave-webdriver) but feel like I'm flying blind a bit.

If there's agreement behind this, I wouldn't mind authoring a small section to get it started.

**Comment by jenisys** [comment]
Could you describe in more detail (some question or points) what you are missing ?

NOTES (before hand):
* Step library design is similar to library design or framework design
* There are a number of articles on good / bad step design on the web.
* It is often good to write down which kind of steps you want to support 
  (but you seem to have already done that on your "README.md")

ADVICES:
* use parse-expressions instead of regular-expressions for your parameters. Then you get type conversion for free.
* BDD should describe the "business logic rules" and not the "interaction with the user interface" (in many cases)
  REASON: UI is normally brittle, meaning it changes often. 
  Therefore, you will change your feature files rather often (or need to provide new steps).

**Comment by spyoungtech** [comment]
Hi @jenisys thanks for your time and effort on the behave project and thank you for taking the time to consider my thoughts. 

For the most part, I've been able to figure things out, but a lack of documentation in this area and scarcity of examples in the wild, sometimes left me wondering about certain design decisions. Besides these things, I think the mere presence of such a section in the documentation _will help encourage others to write libraries for behave and, hopefully, help writers avoid pitfalls and use good practices._

I have spent a good deal of time trying to figure out the ideal interface for a step library *user*. I've been able to (I think) sensibly answer most questions that arose, but just one or two things that I'm not terribly confident in that I feel should probably be documented.

Here is one such situation that raised questions that I think would be appropriate to be anticipated/answered in such a section for using/writing step libraries.

----

### How should step library users use step definitions from a library?  
#### (and, by extension, how should library writers provide them)

Maybe this question arises because this is my first and only use of a BDD framework in Python.

To me, the most natural thing seemed to be that one would just `import` the steps from the library to their own steps directory. I.E.

```py
# user-project/features/steps/mysteps.py
from behave import *
from behave_webdriver.steps import *

@then(u'I expect "{something_particular}" to my project to happen')
def step_impl(context, something_particular):
    # user logic
```

### Challenges & lessons learned

#### Put the step matcher back where you found it.

One hole I fell into here is that `use_step_matcher` modifies a global state. This introduces a few pitfalls for library writers / users. When importing the steps, the matcher may change on the user unexpectedly; to whichever matcher the library happened to use last.

The first solution that came to mind was to just end all my step definition files to set the step matcher to the default 'parse'. This is not perfect because the user may not have been using the default and may have changed the matcher prior to importing the library steps.

I then think to myself, "Wouldn't it be great if I could knew the matcher being used, so I can set it back to the right one?". This may be a way...

```python
# step_library/steps/libsteps.py
from behave import *
import behave

# save the original matcher before doing anything else
original_matcher = behave.matchers.current_matcher

# always do this, because the matcher may have been changed by a user or misbehaving library
use_step_matcher('parse') 

# write step definitions here

# restore the original matcher at the end of the module
behave.matchers.current_matcher = original_matcher # not sure if we should be monkeying around...
```

There are maybe one or two other problems/solutions like this I've come across. If you think it's worthwhile, I'll be happy to submit a PR or discuss the finer points. It may also be nice to have some complete examples of step libraries, either fictional ones or links to libraries in the wild.

Thanks.

**Comment by jenisys** [comment]
Answers to your two questions:

1. Reuse steps from a step-library:
  
    * Solution 1: Use context.execute_steps(...)
    * Solution 2: Use unique step-method-names (not: ``step_imp()``). 
      Then you can directly call the other step. See [behave4cmd0/command_steps.py](https://github.com/behave/behave/blob/master/behave4cmd0/command_steps.py)
    * See issues #574 , #537

2. Step matcher is reset to the default-step-matcher after each step-module import

NOTES: 
* You can define the default step-matcher for your project in the "environment.py" file.
* You should not meddle w/ behave internals if this can be avoided for you. This may change w/o notice: ``use_step_matcher()`` is part of the public api, use it.
* See use_step_matcher algorithm: [issue.features/issue0073.feature](https://github.com/behave/behave/blob/master/issue.features/issue0073.feature)

Otherwise, developing a good step-library is a learning process. You seem to have started at least on this way. Therefore, post an article or blog-post how you did it or provide a pull-requests for behave's documentation (with a new page that covers this topic).

**Comment by spyoungtech** [comment]
Thanks for your feedback and insight. I learn more and more about behave every day it seems. Though, I'm not 100% sure we're on the same page. I'd like to explain myself a bit more. 

> You should not meddle w/ behave internals... use_step_matcher() is part of the public api, use it.

I fully agree. That's what I do right now, as I described -- I call `use_step_matcher('parse')` at the end of all my step modules. Otherwise, a user of my library could unknowingly be using the re matcher if I did not, which is the problem in the example I described. 


> Step matcher is reset to the default-step-matcher after each step-module import

I don't believe this is entirely accurate, particularly in the case of importing steps from another package. The reason is because importing the steps can change the global state. I have started [an explanatory writeup with a complete executable example](https://github.com/spyoungtech/behave-problem-example) that hopefully will fully explain and demonstrate what I mean.

If you don't mind, I'd like to bounce those ideas off you, as a sanity check, if nothing else. If I were to write this documentation today, it would be based off of decisions I've made on solely my own thoughts on how step libraries 'ought to be written and used. Your feedback would be invaluable.

It may also be the case that there is cause for submitting an issue/patch to behave and/or providing new interfaces for library writers instead of using certain strategies. (like the mentioned `get_matcher_name` function, for example)

Thanks again, for your time and attention to this. It's **sincerely** appreciated!

----

**P.S.**
As an aside, I'd like to pick a small point:  
I'm not so worried about it, but to be fair, in absence of guidelines for step library writers,  if `current_matcher` is to be considered non-public, it should have a leading underscore and library writers will have a much stronger indicator that using it is risky.  

That said, because step library writers (or other extenders of behave) may have to dig deeper than the typical behave end-user, I don't think it's unreasonable for these developers to have to deal with frequent deprecations and breaking changes more. This may be something worth documenting in such a proposed section, too.

Perhaps if we get this documentation started, it will invite others to contribute their ideas on step libraries and other extensions to behave and help shape behave to be more friendly for extenders in the future. That's my personal vision, anyhow.

**Comment by jenisys** [comment]
@spyoungtech 
Mmh, I didn't think about other imported step-library modules (that modify the matcher).
Will be hard to fix. You would something like a context manager in/around the python-import-hook (that restores the current matcher from before the import).

BEST PRACTICE: It is always a good idea to use only one kind of matcher in a project.

Just curious: Is there a real reason why you need to change the matcher often ?

**Comment by spyoungtech** [comment]
Yeah, I can see how that would be a complicated thing to address from behave. Trying to hook around the python import system is problematic. Without going into detail, I think it's sufficient to say it would be an unduly complex solution for the size of the problem.

For this reason, I suggest that writers of step libraries should be mindful of this and take responsibility to avoid unexpected consequences for users and other libraries. Therefore, it may be helpful to have some documentation around this, for example. 

One key problem is, in the case of a user using a custom matcher, as far as I can tell, the only way for a library writer to handle this appropriately is to inspect and later modify  `behave.matchers.current_matcher` since it would be hard to discern what name to use with `use_step_matcher` for a custom user-defined matcher.

It's not so much that a single person/project would change the matcher so many times in their project, but mostly just thinking about users using (possibly multiple) step libraries that may change the matcher.

**Comment by jenisys** [comment]
Mmh, one simple solution would be by using the ``use_step_matcher(...)`` as ``contextlib.contextmanager``, like:

```
# -- FILE: features/steps/foo_steps.py
from behave import given, when, then, use_step_matcher, scoped_step_matcher

with scoped_step_matcher("cfparse"):
    @given(u'a person with "{name}" ')
    def step_impl(ctx, name):
        ...
    ...
# -- SCOPE-EXIT: Initial step-matcher is restored.
```

**Comment by spyoungtech** [comment]
That's an interesting idea. I imagine the context manager would look something like

```python
from behave import use_step_matcher
from contextlib import contextmanager
import behave

@contextmanager
def scoped_step_matcher(matcher=None):
    _matcher = behave.matchers.current_mathcer
    if matcher:
        use_step_matcher(matcher)
    yield
    behave.matchers.current_matcher = _matcher
```

Though, I guess that would mean nearly the entirety of each step module would be a huge indented block. I don't know how much I like that particular aspect. 

I wonder if something like this would be palatable... (if it even works)

```python
# some_library/steps/__init__.py
from behave import scoped_step_matcher

with scoped_step_matcher():
    from . import _my_step_module
    from . import _other_step_module
```

I'm still not sure I'm crazy about it, though. I'll put some more thought into this and do some testing.
Thanks.

**Comment by spyoungtech** [comment]
Sorry for the long delay in getting back. I've been busy with the release of [behave-webdriver](https://github.com/spyoungtech/behave-webdriver) v0.1.0! (shameless plug) -- And 1.2.6 is working great for us, by the way, great work!

Anyhow, I've been thinking about this problem a lot and I'll open a separate issue with an idea that I hope will be well-received that would address that importing issue, as well as provide what I think is a significant enhancement for behave library writers and general users.

I still plan to work on a small writeup for library writers of the present. I'll probably start it as a contributing guide for my own project, and then submit a more general version as a PR here. Thanks again for your time and attention to this. 👍

**Comment by lu-maca** [comment]
> I still plan to work on a small writeup for library writers of the present. I'll probably start it as a contributing guide for my own project, and then submit a more general version as a PR here. Thanks again for your time and attention to this. +1

Hi @spyoungtech, I'm pretty interested in this topic; have you written somewhere the documentation you mentioned in 
this post? 

Thanks :)
