### ISSUE TITLE
Context __getattr__ should raise AttributeError instead of KeyError

### ISSUE THREAD

**Issue by anxodio** [behave/behave#619]
When trying to do something like:
```python
foo = getattr(context, '_foo', 'bar')
```
Behave fails with:
```
  File "[...]/behave/runner.py", line 208, in __getattr__
    return self.__dict__[attr]
KeyError: '_foo'
```

I think this is because the `__getattr__` method in Context ([here](https://github.com/behave/behave/blob/master/behave/runner.py#L313)) don't raise properly AttributeError when the key don't exists in the dict, so the default behaviour of getattr is not executed (see [docs](https://docs.python.org/3/reference/datamodel.html#object.__getattr__))

**Comment by jenisys** [comment]
BAD BOY: When you try to access behave's Context protected attributes, you get bitten ;-)

Is that a real use case for you ?

**Comment by afibanez** [comment]
Ok, so I misunderstood how to use Context and I was using the underscore prefix to save some temporal context variables.
So my use was: if `foo` is a variable that i will use in a lot of cases, modify, etc. it will be `context.foo`. But if `bar` is a variable that is intended to be only read by certain helper methods, it will be `context._bar`.
So if are protected attribures used by Behave itself, I will stop using them in that way. But the bug still exists ;)

**Comment by jenisys** [comment]
The ``Context`` object has some internal attributes that should be kept private, therefore Python protected/private naming conventions w/ leading underscore(s). Otherwise, how you use the Context object is mostly up to you, meaning: You should get warnings when you try to use attributes names that are used/provided by behave.

Also note, depending when you add an attribute to the context, it will be removed after the end of the current scenario, feature (added in ``before_feature()`` hook) or test-run (added in ``before_all()`` hook), because the corresponding context layer w/ all its attributes is removed.

SEE ALSO:
* [docs: Appendix -- Context Attributes](https://github.com/behave/behave/blob/master/docs/context_attributes.rst)

**Comment by afibanez** [comment]
Wow, thanks for the explanation @jenisys 😄

**Comment by spyoungtech** [comment]
With regard to the `__getattr__` /`__setattr__` /`__delattr__` methods, this is a hole I've stepped in myself... I think it's reasonable that users should also be able to set non-public attributes on the context using the leading underscore convention. As long as they don't use the same attribute names as behave, everything should be kosher, unfortunately that doesn't seem to be the case.

An issue I once had was exacerbated by the fact that the getattr and setattr actually behave differently [based on whether the attribute starts with a `'_'`](https://github.com/behave/behave/blob/master/behave/runner.py#L324), but delattr does not.

In short, I was using the leading underscore naming convention to mark an attribute on the context as non-public, but also needed to delete it on occasion... and that's where I stepped in the hole big time.

A simplified version of the setup looks like

```python

def before_all(context):
    # do expensive object creation
    context._myattr

def after_step(context, step):
    if cleanup_required(...):
        # sometimes we need to do cleanup...
        del context._myattr

def before_step(context, step):
    if not hasattr(context, '_myattr'): # check if we need to create it again if it was cleaned up
        # do expensive creation of object
        context._myattr = obj
```

So `del` would not work properly in this case. Further, the mentioned behavior of setattr/getattr also caused some other obscure problems where in a very particular situation, `getattr(context, 'attr', 'default')` caused the test to hang entirely. I'll try to find this and share a reproducible example...

Ultimately, there was a workaround found, but after this discovery, we (begrudgingly) opted to not use the leading underscore convention for non-public attributes on the context and put some strong documentation around those attributes, instead.

The short of it though is that the docs say users may set their own attributes on the context which get cleaned up at various stages. It's my thought that means inclusive of non-public attributes using the leading underscore naming convention... but it produces these oddities.

**Comment by jenisys** [comment]
@spyoungtech 
Sorry, I disagree. 

Protected and private context attributes are for the framework and not the user.
I might fix the behaviour above about which exception is thrown. 
But in addition, I might disable that you as a user sets any protected/private attributes.

In addition, I see no compelling argument, why private/protected attributes should be used.

**Comment by jenisys** [comment]
INTEGRATED-INTO: behave-1.2.7.dev0
