### ISSUE TITLE
Exclude skipped scenarios out from Junit report

### ISSUE THREAD

**Issue by andreypetrenko82** [behave/behave#624]
Could you add additional command-line argument which will exclude skipped scenarios out from junit report?
For example. If I run scenarios by tags using --junit argument I will get a report with all scenarios but some of them have skipped status. And I want to get a report without them.

**Comment by jenisys** [comment]
Look at the implementation of the [JUnit reporter showSkipped() method](https://github.com/behave/behave/blob/master/behave/reporter/junit.py#L222):
Skipped scenarios are shown if:

* ``show_skipped`` is used on command-line or configuration-file
* ``behave.reporter.junit.show_skipped_always`` in behave userdata

I would expect that you only need to disable the ``show_skipped`` in the configuration-file (or on command-line):

```ini
[behave]
show_skipped = false

# -- PROBABLY NOT NEEDED:
[behave.userdata]
behave.reporter.junit.show_skipped_always = False
```
