### ISSUE TITLE
Formatter documentation is inaccurate for some methods.

### ISSUE THREAD

**Issue by throwable-one** [behave/behave#625]
```
    def result(self, step_result):
        """
        ........
        :param step_result:  Step result (as string-enum).
        """
        pass
```
Actually it is ``Step`` class (at least in 1.2.5) (See ``formatter.result(self)`` in ``model.py``)

```
 def step(self, step):
        """
        Called before a step is executed (and matched).
```

It may be good idea to document execution order excplicitly:

Feature
Scenario1
Step1
Step2
...
StepN
Match (for Step1) # technically step execution starts here
Result (for Step1) # and ends here
Match (for Step2)
Result (for Step2)
Match (for StepN)
Result (for StepN)
Scenario2

etc.

**Comment by jenisys** [comment]
INTEGRATED INTO: behave-1.2.6dev0
