### ISSUE TITLE
class-based step implementations

### ISSUE THREAD

**Issue by spyoungtech** [behave/behave#630]
Currently, step implementations are provided as module-level functions. I am proposing that behave should support the ability to provide step implementations as methods in a class.

I strongly feel that class-based definitions would be a great enhancement for behave. 
Some of the possible benefits of this feature includes:

- Provides a defined pattern understood by both step library writers and users
- A more flexible way for step library writers to provide steps to users, allowing easy extension of previous works
  - users can subclass library steps to extend/override its methods, providing new ways for behave users to solve unique challenges
  - users can pick & choose what step definitions get into the registry
- A simple and beautiful, yet powerful interface to behave internals
  - Keep signatures cleaner, so `context` need not be the first argument of every step
- Easier to write tests for your tests! (e.g. easier dependency injection via inheritence)
- Less direct reliance on global state, while maintaining compatibility
- (possibly) Make it easier for IDE plugins to detect definitions from step libraries
- Solves some [obscure problems](https://github.com/spyoungtech/behave-problem-example) for step library writers
- And much more

I hoping to discuss this idea here.

# Proposal draft; one possible interface

The following is a conceptual sketch of just one possible interface for this vision. There are a lot of ideas baked in here that, for brevity sake, are not totally explained. Naturally, there are a lot of details that would need to be worked out to implement something like this. For now, use your imagination and assume that obstacles to achieving this can be overcome :)

## A base class or mixin

Behave may provide some base class or mixin containing some behave-specific logic and internal interfaces.

```python
# behave/step_registry.py ?
class StepImplMixin(object):
    step_matcher = 'default' # use default defined in environment.py or parse
    _local_registry = LocalStepRegistry()
    


    @property
    def context(self):
        """proxy for retrieving the current context"""
        # some smart logic
        return ctx

    def register(self, method_names=None):
        """
        Inserts methods specified in ``method_names`` from the local registry to the global step registry.
        if ``method_names`` is not specified, all methods from the local registry will be inserted
        (maybe register definition patterns with (an instance of?) this class?)
        """
        ...


    # probably other cool stuff, maybe unittest assertion matchers?
```

Then a library writer (or even users) could provide step definitions something like

```python
# some_library/steps/some_steps.py
class SomeSteps(StepImplMixin, OtherClass):
    step_matcher = 'parse' # override the default matcher
    # this decorator would put the method into the class-local registry
    @given_impl(u'I do "{something}"') # write a given step using the class-level matcher
    def given_something(self, something):
        self.context.result = self.other_method(something)

    # override matcher just for this method
    @then_impl(u'the result should( not)* be "([^"]*)?")', matcher='re')
    def check_result(self, negated, subject):
        if negated:
            self.assertNotEqual(subject, self.context.result)
        else:
            self.assertEqual(subject, self.context.result)
```

For basic use, a user of a step library might simply do the following:

```python
# my_project/features/steps/my_steps.py
from some_library import SomeSteps

SomeSteps.register()

# my additional steps
```

Or more advanced use, a user (or other library writer reusing another library) could extend/tweak the step library class

```python
from some_library import SomeSteps

class MySteps(SomeSteps, AnotherClass):
    
    # uses same step matching from the superclass's ``given_something``
    def given_something(self, *args, **kwargs):
        self.anoter_method() # do this first
        return super(MySteps, self).given_something(*args, **kwargs) # then execute the superclass's method.
```

## Other possible niceties

Perhaps these cases can provide `before_step`/`after_step` methods that is called before ONLY the steps defined in that class. This behavior would also be configurable by subclassers.

Imagine a step library provides the following

```python

class SomeSteps(StepImplMixin):
    # ....
    def before_step(self, step):
        # do some library-specific setup

    def after_step(self, step):
        # do some library-specific cleanup

```

And a user could extend or override this

```python
from some_library import SomeSteps
from behave import *

class MySteps(SomeSteps):
    def before_step(self, step):
        super(MySteps, self).before_step(step) # let the library do its setup first
        # then do some project-specific setup
        
    def after_step(self, step):
        """Only allow superclasses to do their clean up under some condition"""
        if some_condition:
            super(MySteps, self).after_step(step)


# this step implementation is not affected by the before_step/after_step above
@given(u'I do "{another_thing}"')
def given_another_thing(context, another_thing):
    # ...
```

**Comment by spyoungtech** [comment]
Been playing around with this and I have a (very early) prototype in my fork that allows one to define steps and override in a subclass as well as override the default matcher on a per-method basis.

Consider the following step file...

```python
from behave import *
from behave.step_registry import local_step_registry
from behave.matchers import RegexMatcher
MyStepsBase = local_step_registry()

class MySteps(MyStepsBase):
    @MyStepsBase.given(u'I do "{foo}" with "{bar}"')
    def do_foo(self, ctx, foo, bar):
        print(self)
        print(ctx, foo, bar)


class ExtendedSteps(MySteps):
    def do_foo(self, *args, **kwargs):
        print(self)
        print('extended do foo')
        super().do_foo(*args, **kwargs)

    @MySteps.given('I do (a|b)', matcher=RegexMatcher)
    def re_func(self, context, a_or_b):
        print(a_or_b)

ExtendedSteps().register()
```
and feature file

```gherkin
Feature: some feature
  feature description

  Scenario: test
    Given I do "bacon" with "eggs"
    And I do b
```

then run `behave --no-capture` and I get

```
Feature: some feature
  feature description

  Scenario: test
    Given I do "bacon" with "eggs"
    And I do b
```

Kinda neat!

**Comment by spyoungtech** [comment]
I decided it may be more appropriate to provide this functionality as a 3rd party package. So, I've created `behave-classy`, which has been released to PyPI.

Feel free to close this issue.

**Comment by fiber-space** [comment]
It is not necessary to add classes to support step polymorphism. Also one doesn't have to override steps as methods but just specialize the step decorators ( which are significant, whereas the names of the step functions are not ):

**environment.py**
```python
class A(Domain): pass
class B(A): pass

register_domains(B)
```
**some step files**
```python
import A, B
@A.given(u'I do "{foo}" with "{bar}"')
def step_impl(context, foo, bar):
    "Step implementation in domain A"

@B.given(u'I do "{foo}" with "{bar}"')
def step_impl(context, foo, bar):
    "Step implementation in domain B"
```

Each of the *domains* A and B are equipped with their own step registry. Since B formally inherits from A, steps registered at B override those registered at A. I only drafted the basic idea - getting the implementation right is a valuable exercise.

The plain function approach has some benefits: there is a canonical way to decompose steps into substeps (via `context.execute_steps()` ) and it is easy to understand and use by testers who are not primarily Python programmers. State should be treated alongside the context stack and its push/pop operations. The class based approach looks like an attempt to fight the order of scopes introduced by Behave itself [1] whereas dealing with that order seems to me a "behaviorist" way of doing stuff. 

[1] There might be use cases for handling state independently in complex test applications. For that reason I added a `context.app = Application(...)` attribute in a `before_all` hook and allow `app` to maintain its own state. However the `Application` object neither calls steps nor hooks. It doesn't cross the lines.

**Comment by jenisys** [comment]
@spyoungtech 
If you are interested, we/you can host it under https://github.com/behave-contrib .
Tell if if you are interested, then I create the repo and assign you as owner.

**Comment by spyoungtech** [comment]
Hey @jenisys this is definitely something I will strongly consider. 

I've also got `behave-webdriver` which may be of interest for this as well. (speaking of which, I'm working on a [killer feature](https://github.com/spyoungtech/behave-webdriver/pull/62) there that could add new degree of flexibility for step definitions)

Though, my question is: why a whole new GitHub org for this, instead of using the existing behave org?

**Comment by fiber-space** [comment]
About the user request you mentioned. We don‘t use regex matchers but parse matchers + type converters. This means that transformations of step arguments are delegated to type converters. A rationale we follow is that steps aren‘t cleaning, validating and transforming inputs. Not all constraints can be mitigated nicely, but some have fairly good solutions within the framework.

**Comment by gaganhattar** [comment]
> @spyoungtech
> If you are interested, we/you can host it under https://github.com/behave-contrib .
> Tell if if you are interested, then I create the repo and assign you as owner.

Hi jenisys and spyoungtech,
Please inform if there has been any progress on behave facilitating libraries that are called by feature files like Robot does?
Our team is finding robot preferable to behave because of this reason. 

Thanks,
Gagan

**Comment by spyoungtech** [comment]
Hi @gaganhattar I'm not familiar with Robot, but there are several examples of step libraries for behave. Maybe consider taking a look at those.

I author a selenium step library using behave at https://github.com/spyoungtech/behave-webdriver

I also author `behave-classy` which is designed for library providers to make their behave libraries more extensible with ease through Python classes. https://github.com/spyoungtech/behave-classy
