### ISSUE TITLE
Scenario Outline variables not possible in table headings

### ISSUE THREAD

**Issue by mschnelle** [behave/behave#631]
If I have an example variable in a table heading it is not mapped to the example value.
In the following example the step es called with table heading ``<method>`` twice instead of ``GET`` and ``POST`` 

```
When the following request is sent
   | <method>     |
   | /example-url |
Then ...

Examples: Supported methods
  | method |
  | GET    |
  | POST   |
```

**Comment by jenisys** [comment]
Verified. 
Currently, this does not work w/ the column header.
I look into it.
