### ISSUE TITLE
parse empty value in feature examples

### ISSUE THREAD

**Issue by AilsaQian** [behave/behave#632]
![image](https://user-images.githubusercontent.com/37043580/37277752-a4eea316-2620-11e8-91da-2e4e2b3be59c.png)

PROBLEM:
parsed one empty value, got the error "You can implement step definitions for undefined steps with these snippets:
@when('parse params /user/api-key/add，post，aliyun，，None')
def step_impl(context):"
-----------
actually, I had defined the step - 
"
@when(u'传入参数{subUrl}，{method}，{provider}，{key}，{secret}')
def import_accessKey(context, subUrl, method, provider, key, secret):
    params = {
        'provider': provider,
        'key': key,
        'secret': secret,
    }
...
"

**Comment by jenisys** [comment]
The default type in the ``parse`` module (for key) is "\w+", meaning: One or more non-whitespace character(s). But you are using an empty string !!!

Use for example an optional type, like:

```python
# -- FILE: features/steps/my_steps.py
from __future__ import print_function
from behave import when, register_type, use_step_matcher
import parse

@parse.with_pattern(r"\w+")
def parse_string(text):
     return text.strip()

register_type(Name=parse_string)
use_step_matcher("cfparse")

@when(u'I provide a {key:Name?} or not')
def step_impl(context, key):
     print("key: %r" % key)
    # -- NOTE: key="... some string ..." or key=None when no key is provided.
```

SEE ALSO:
* Use cardinality fields with ``cfparse``: http://behave.github.io/behave.example/step_matcher/use_optional_part.html
* http://behave.github.io/behave.example/datatype/cardinality_zero_or_one.html
