### ISSUE TITLE
Ability to use environmental variables in Feature and Scenario Names

### ISSUE THREAD

**Issue by Jiff21** [behave/behave#635]
I think this is a feature request, but let me know if it's possible and I'm just missing something. but I think it would be useful to be able to use environmental variables in Scenario and Feature descriptions.  For example I'd like to do something like this:

```
Feature: The homepage does not have unexpected visual changes on "TEST_ENV"

  Scenario Outline: Homepage has expected visual style using "BROWSER"
    Given ...
    Then ...
```

The specific problem I'm running into now is trying to use Allure Reports and allure seems to differentiate tests based on Feature and Scenario Name. I'd like to be able to run the same tests and have it differentiate between ones run on the testing environment and the production environment or in different browsers. 

I specifically request environmental variables as if I have to set this in a Behave config it will make us have to set variables in a variety of places if we're using other tools. For example I'm running locust.io tests and then running behave assertions off the csv results, etc. If this is a behave specific config file, it requires duplicating a lot of settings in multiple places.

**Comment by jenisys** [comment]
Use userdata (or the test stages concept).

```shell
behave -D STAGE=product ...
behave -D STAGE=develop ...
```

SEE ALSO:
* [behave.docs: Userdata](http://behave.readthedocs.io/en/latest/new_and_noteworthy_v1.2.5.html?highlight=userdata#index-7)
* [behave.docs: Test Stages](http://behave.readthedocs.io/en/latest/new_and_noteworthy_v1.2.5.html?highlight=userdata#test-stages)


RELATED: Environment variables
* #497
* #250

**Comment by Jiff21** [comment]
Aw man you posted right as I came across that and had this kind of long explanation about how having to remap your Environmental Variable is a pain.  That being said it does seem possible if Remap environmental variables as use linked to, duplicate a lot of the info across [Examples for Scenario outlines](http://behave.readthedocs.io/en/latest/new_and_noteworthy_v1.2.5.html?highlight=outline).

I do only see in that documentation for outlines that you can use <var> from the examples in the Scenario outline. 
But can you reference these variables in the Feature Files? I don't see any documentation of that.  It kind of looks like you should be able to [here](http://behave.readthedocs.io/en/latest/new_and_noteworthy_v1.2.5.html?highlight=userdata#index-7), or there's just an extra Double Quote in this example. 
```
@given('I setup the system with the user-specified server"')
```
Looking for something like
```
Feature: The homepage does not have unexpected visual changes on <context.config.userdata.server>

  Scenario Outline: Homepage has expected visual style using <context.config.userdata.browser>
    Given ...
    Then ...

```

**Comment by jenisys** [comment]
Currently, only Example columns (and some generic ScenarioOutline metadata) can be referenced.
Normally, you just need the data in your step implementations. What you are looking for seems to be a more generic templating mechanism. Therefore, use a template engine, like Jinja2 for it to generate your feature files w/ your data (as preparation/preprocessing build-step).

SEE ALSO:
* http://behave.readthedocs.io/en/latest/new_and_noteworthy_v1.2.5.html?highlight=row.id

**Comment by Jiff21** [comment]
For anyone else here I have somewhat hacky workaround. 

Say you run with something like:
`
behave -D server="testing" qa/functional/features/ 
`
You could do something like this which will append a string to the end of the Feature or Scenario Name. 
```
import os
os.getenv('SOME_ENV_VARIABLE', 'default value')

def before_feature(context, feature):
    if context.config.userdata['server'] is not None:
        feature.name += ' on ' + context.config.userdata['server'] + ' environment'

def before_scenario(context, scenario):
    scenario.name += ' with ' + SOME_ENV_VARIABLE
```

I should note for browser (from my request) I prefer something like this that gets the info off the actual driver rather than what you pass in: 
```
def before_scenario(context, scenario):
    if 'browser' in context.tags:
        context.browser = Browser()
        context.driver = context.browser.get_browser_driver()
        scenario.name += ' in ' + context.driver.capabilities['browserName'] + ' ' + context.driver.capabilities['version']
```
