### ISSUE TITLE
Feature Request: Define an Example once and use on multiple scararios

### ISSUE THREAD

**Issue by Jiff21** [behave/behave#636]
Apologies if I'm incorrect, but  i don't see a way in the [docs](http://behave.readthedocs.io/en/latest/new_and_noteworthy_v1.2.5.html?highlight=outline) to define an example in one location and then use it across many scenario outlines.  

Currently it seems like you if you use the same Example across multiple Scenario Outlines, the only way to achieve this is to copy and paste it below each Scenario Outline. Then if you need to make additions or changes you're editing the same Example table multiple times in multiple places.

**Comment by jenisys** [comment]
Feature files in Gherkin are simple text files. If you like DRY then use tools that help you with it.
For example, you can always generate your feature files from templates, like with [Jinja2](http://jinja.pocoo.org).

NOTE:
I my experience, I never had the problem that I needed to use the same Examples table twice. Either I do not understand your use case or you are repeating yourself.

**Comment by Jiff21** [comment]
```
Feature: The cart works correctly

  Scenario Outline: User has more than enough money
    Given <user> has a <balance> <currency>
    When they try to purchase a “5” item
    Then the transaction should be successful

  Examples: People
  | User | balance| currency |
  | Bob  | 20               | USD      |
  | Joe  | 16.33           | Euro     |
  | Dan  | 26.15          | CDN      |
  | ASA  | 2130.46     | YEN      |

  Scenario Outline: User doesn't have enough money
    Given <user> has a <balance> <currency>
    When they try to purchase a "40" item
    Then the transaction should not be successful

  Examples: Generic Example
  | User | balance| currency |
  | Bob  | 20               | USD      |
  | Joe  | 16.33           | Euro     |
  | Dan  | 26.15          | CDN      |
  | ASA  | 2130.46     | YEN      |


  Scenario Outline: User Exactly enough money
    Given <user> has a <balance> <currency>
    When they try to purchase a “20” item
    Then the transaction should be successful

  Examples: Generic Example
  | User | balance| currency |
  | Bob  | 20               | USD      |
  | Joe  | 16.33           | Euro     |
  | Dan  | 26.15          | CDN      |
  | ASA  | 2130.46     | YEN      |

**Comment by Jiff21** [comment]
I urge you to reconsider, as some people have a need to repeat themselves over efficiency. 

You take something like escaping user input, the most efficient way to test something like that would be to have one function that deals with that and unit test that one function and then use that function everywhere it needs to be used. But with something that important a QA department would not be content with 1 unit test because there's a large group of people building something, you can't just trust that every one is going to use the 1 function that's solidly unit tested. With something that important you might want to run the same test against every API Endpoint. Some larger companies that don't need to worry about test cost are going to want to run the same test on a bunch of different places even if it's something less important. 

Anyway though, behave is mostly awesome. Thank you for your work.

**Comment by jenisys** [comment]
Sorry, Behave supports Gherkin and what you want is not supported by Gherkin. As I said, it is rather easy to use templates to accomplish this task without any problems. Use the right tools for the right things and this is no problem at all. Otherwise, if you really want this, provide a feature request to add this to Gherkin within the Cucumber repository. 

SEE ALSO:
* https://github.com/cucumber/cucumber monorepo using topic "Gherkin: ..."

NOTE: Your example lack the currency exchange rate. 
Therefore, the examples are only correct if you use this hidden implicit knowledge.

**Comment by jenisys** [comment]
On second thought, there is a solution to this but is not supported yet by behave.

```gherkin
Scenario Outline: User doesn't have enough money
    Given <user> has a <balance> <currency>
    When they try to purchase a "40" item
    Then the transaction should not be successful

  @table_generator.from_file=example_data.json
  Examples: Populate Example Table from external JSON file (using column-headers as data-selectors)
    | user | balance | currency |


Scenario Outline: User Exactly enough money
    Given <user> has a <balance> <currency>
    When they try to purchase a “20” item
    Then the transaction should be successful

  @table_generator.from_file=example_data.json
  Examples: Populate Example Table from external JSON file (using column-headers as data-selectors)
    | user | balance | currency |
```

The Examples tag ``@table_generator.from_file=example_data.json`` acts as a preprocessing step by populating the Examples table before it is expanded into Scenarios, one per Examples table row.

SEE ALSO:
* #621 
* #622

**Comment by jenisys** [comment]
@Jiff21 
I have been thinking about your feature example.
Actually you are testing 2 different aspects in each of the 3 scenarios:

* Behavioral outcome: Enough money, exact money, not enough money
* Currency conversion w/ hidden currency conversion rate

In general, it is better to test each aspect on its own, like:

```gherkin
Scenario Outline: Currency Conversion Computation

  Given <user> has <amount> <currency>
  When the currency exchange rate is <currency_exchange_rate> <currency>/USD
  Then the user has <amount_in_USD> USD 

  | user | amount    | currency | currency_exchange_rate | amount_in_USD |
  | Bob  | 20        | USD      |    1                   | 20 |
  | Jośe | 16.33     | Euro     |    0.8165              | 20 |
  | Sa'ad| 26.15     | CDN      |    1.3075              | 20 |
  | 朝   | 2130.46   | YEN      |  106.523               | 20 |


Scenario Outline: User Transaction Succeeds or Fails: <case>

    Given <user> has a <balance> <currency>
    When they try to purchase a “<purchase>” <currency> item
    Then the transaction should <outcome>

  Examples:
    | user   | balance   | purchase | currency | outcome           | case |
    | Alice  | 20        | 5        | USD      | be successful     | Enough money  |
    | Bob    | 20        | 20       | USD      | be successful     | Exact money |
    | Charly | 10        | 20       | USD      | not be successful | Not enough money |
```

As you can see, if your doing that the example-table duplicates no longer exist.

**Comment by Jiff21** [comment]
Yeah that would be a better way to do it if you're unit testing. But if I'm testing an api I can't test the conversion independently.  But the generic example would have to be accompanied by some custom ones but it would still save you time to be able to reuse. 
```
  Examples:  Handles other numbers 
  | User            | balance     | currency |
  | Negative        | -100        | USD      |
  | Zero            | 0           | USD      |
  | fake_larg number| 1000000000  | USD      |
```
That being said, maybe this wasn't the best example of what might call for reusing example tables, as you would probably need to be generating the data off conversion rates so maybe Jinja would be better option here, sorry it was just off the top of my head as we were both be online at the time.  
What prompted me to think about this was I'm running other tests Galen Framework Visual regressions test that generate json for a website with a bunch of different locations and languages.  Then running behave assertions off the results to generate allure reports. The current setup runs the galen tests on all locations first, then runs through the Examples to grab the json by file name based on location, then iterates through each page and section and makes sure there were no errors.  I get why you approach behave from unit testing perspective but it's so useful that I'm kind of shimming other tests into BDD with it and I encourage you to keep it as versatile as possible.

I think my point remains valid about some people not being in a situation where they need to test the same thing multiple times remains valid so I would be  interested in `@table_generator.from_file=example_data.json` down the line. Were you planning on supporting that at some point.

**Comment by jenisys** [comment]
Sorry, that is (functional) separation of concerns, not unit testing. And that is normally also a good idea with ATDD.

Otherwise, table_generator/table_transform for ScenarionOutline example tables is on my agenda. But I cannot promise you a definitive date when it will be available. For a working solution right now, I would use Jinja. And when the feature becomes available in behave, you can reconsider if you stick with your approach or use the new feature.

**Comment by jenisys** [comment]
@stalebot
Remains open.

**Comment by jenisys** [comment]
@stalebot
Remains open.
