### ISSUE TITLE
Steps are not found with multiple paths defined in config file (MWE provided)

### ISSUE THREAD

**Issue by davethecipo** [behave/behave#638]
Hello, thank you very much the library. I might be making a stupid mistake configuring the library, but I don't understand what.

I created a minimal working example [here](https://github.com/davethecipo/possibly-a-bug-in-behave/tree/master), where I defined two packages, each of which containing features and steps.

The `behave.ini` looks like the one in the docs to me, but the steps for the second package are not found. Is this maybe a mistake on my part for indicating the paths?

I'm using python 3.5.2 and behave 1.2.6.

**Comment by jenisys** [comment]
Currently, Behave imports only steps from the first step directory. In your case, this is "package/features/steps/".
Therefore, there are three solutions for you:

* Use a build script like with "invoke" that executes the features from each package (in two steps).
* Import the steps from the other step directory in your first step directory (you need to add the search-path to sys.path)
* Write your own test runner w/ this functionality (or provide a pull-request)

**Comment by davethecipo** [comment]
Thank you for the quick response! I will probably choose the first or second solution.
