### ISSUE TITLE
Pylint errors when importing `given - when - then` from `behave`

### ISSUE THREAD

**Issue by lktslionel** [behave/behave#641]
Hi,

I'm have some issues with the import statement : 
```
from behave import given, when, then
```

I use `pylint-v1.8` and it shows the following errors in my editor (vscode) : 

```
[pylint] E0611:No name 'given' in module 'behave'
[pylint] E0611:No name 'when' in module 'behave'
[pylint] E0611:No name 'then' in module 'behave'
```

Below some info about my environment : 

```
Python: 3.6.4
pipenv, version 11.8.3
behave 1.2.6
```

- Any idea of why pylint is showing errors ? 
- Why It can't find `behave` annotations ? 

Thanks

**Comment by jenisys** [comment]
Pylint seems to have a problem w/ wildcard-imports that are perfectly legal in Python. 
If you replace the wildcard-import with explicit imports, everything is fine for pylon.
Add an issue to pylint to get this fixed.

**Comment by rrueth** [comment]
I ran across this issue while starting to adopt behave today. @jenisys, what do you mean by "if you replace the wildcard-import with explicit imports, everything is fine?"  If I do:

```
import behave

@behave.when("I run a test")
def foo():
  pass
```

I get the following error from `pylint`: 
```
[E1101(no-member), create_user] Module 'behave' has no 'given' member
```

Is there a way that I can import `behave` and `given`/`when`/`then` that would eliminate the error?

For reference, these are the two issues that I found on the pylint side:
- https://github.com/PyCQA/pylint/issues/535
- https://github.com/PyCQA/pylint/issues/1394

**Comment by jenisys** [comment]
@rrueth 
The core question is if the python-interpreter is right or pylint is right.
The used construct in ``behave`` is a completely legal construct in python AFAIK (and older versions of pylint did not complain about it).

SEE:
* https://www.python.org/dev/peps/pep-0008/#id24

NOTE: By the way, why do you get an error on "given" when you are not using it ?!?

**Comment by rrueth** [comment]
Sorry, my mistake in the example.  I copied the wrong line of my pylint ouput =).  It is actually:

```
[E1101(no-member), create_user] Module 'behave' has no 'when' member
``` 

The same error would show up for `given` and `then` if I had done `@behave.given` or `@behave.then` instead.

I'm not sure about the pylint vs python-interpreter question.  In this case, I was mostly curious if there was another way I could go about importing `behave` such that pylint would understand the given/when/then.  Scanning through the code, it looked like the step decorators were dynamically generated, so I didn't see a fix.

**Comment by jenisys** [comment]
The different styles of importing things will not make any difference in pylint.
IMHO you have the following options:

* Tweak pylint configuration (by disabling this error)
* Provide a behave extension for pylint (you !!! and not me)
* Use another static code analyser
* ...

**Comment by rrueth** [comment]
Thanks, @jenisys.  That sounds about what I was expecting.  If it's bothering me enough, I may pursue trying to add the extension for pylint. =)

**Comment by flyte** [comment]
Same problem here, and a way to reproduce it:

```
flyte@demosthenes:/tmp/behave
$ virtualenv ve
Using base prefix '/usr'
New python executable in /tmp/behave/ve/bin/python3
Also creating executable in /tmp/behave/ve/bin/python
Installing setuptools, pip, wheel...done.

flyte@demosthenes:/tmp/behave
$ . ve/bin/activate

(ve) flyte@demosthenes:/tmp/behave
$ pip install behave pylint
Collecting behave
  Using cached https://files.pythonhosted.org/packages/a8/6c/ec9169548b6c4cb877aaa6773408ca08ae2a282805b958dbc163cb19822d/behave-1.2.6-py2.py3-none-any.whl
Collecting pylint
  Downloading https://files.pythonhosted.org/packages/a5/06/ecef826f319055e6b231716730d7f9047dd7524ffda224b521d989f085b6/pylint-2.2.2-py3-none-any.whl (750kB)
    100% |████████████████████████████████| 757kB 5.4MB/s 
Collecting six>=1.11 (from behave)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting parse>=1.8.2 (from behave)
  Using cached https://files.pythonhosted.org/packages/60/1c/065a39ceaf2f2e1ed74130bda8c87b71e01a2315d78ab612af86c0914abb/parse-1.11.1.tar.gz
Collecting parse-type>=0.4.2 (from behave)
  Using cached https://files.pythonhosted.org/packages/a2/c9/e6fd8092a5a06f2519ec434ca8e9e42238384f64c9b659456d98b0593b89/parse_type-0.4.2-py2.py3-none-any.whl
Collecting mccabe (from pylint)
  Using cached https://files.pythonhosted.org/packages/87/89/479dc97e18549e21354893e4ee4ef36db1d237534982482c3681ee6e7b57/mccabe-0.6.1-py2.py3-none-any.whl
Collecting astroid>=2.0.0 (from pylint)
  Downloading https://files.pythonhosted.org/packages/fc/53/8809bc008bad0300897281a7b320b286dc0e84e836396c0cff6279841e8a/astroid-2.1.0-py3-none-any.whl (176kB)
    100% |████████████████████████████████| 184kB 1.8MB/s 
Collecting isort>=4.2.5 (from pylint)
  Using cached https://files.pythonhosted.org/packages/1f/2c/22eee714d7199ae0464beda6ad5fedec8fee6a2f7ffd1e8f1840928fe318/isort-4.3.4-py3-none-any.whl
Collecting lazy-object-proxy (from astroid>=2.0.0->pylint)
  Using cached https://files.pythonhosted.org/packages/10/88/d7b8274edf912be71d73a1e5de7988f62b63d9e88e591da2e6f921ab69e6/lazy_object_proxy-1.3.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting wrapt (from astroid>=2.0.0->pylint)
  Using cached https://files.pythonhosted.org/packages/67/b2/0f71ca90b0ade7fad27e3d20327c996c6252a2ffe88f50a95bba7434eda9/wrapt-1.11.1.tar.gz
Collecting typed-ast; python_version < "3.7" and implementation_name == "cpython" (from astroid>=2.0.0->pylint)
  Downloading https://files.pythonhosted.org/packages/b1/62/7e0bfe7bb75bf8a41b58ccb7bd3ab3afaec61e06d9abfda113ad0dc227be/typed_ast-1.3.1-cp35-cp35m-manylinux1_x86_64.whl (734kB)
    100% |████████████████████████████████| 737kB 4.9MB/s 
Building wheels for collected packages: parse, wrapt
  Building wheel for parse (setup.py) ... done
  Stored in directory: /home/flyte/.cache/pip/wheels/11/ef/7a/b4e5692572b93ce67bb9d0680bc8e840ff9a21fab73a3bff56
  Building wheel for wrapt (setup.py) ... done
  Stored in directory: /home/flyte/.cache/pip/wheels/89/67/41/63cbf0f6ac0a6156588b9587be4db5565f8c6d8ccef98202fc
Successfully built parse wrapt
Installing collected packages: six, parse, parse-type, behave, mccabe, lazy-object-proxy, wrapt, typed-ast, astroid, isort, pylint
Successfully installed astroid-2.1.0 behave-1.2.6 isort-4.3.4 lazy-object-proxy-1.3.1 mccabe-0.6.1 parse-1.11.1 parse-type-0.4.2 pylint-2.2.2 six-1.12.0 typed-ast-1.3.1 wrapt-1.11.1

(ve) flyte@demosthenes:/tmp/behave
$ echo "from behave import given, when, then" > mymodule.py

(ve) flyte@demosthenes:/tmp/behave
$ pylint mymodule.py
************* Module mymodule
mymodule.py:1:0: C0111: Missing module docstring (missing-docstring)
mymodule.py:1:0: E0611: No name 'given' in module 'behave' (no-name-in-module)
mymodule.py:1:0: E0611: No name 'when' in module 'behave' (no-name-in-module)
mymodule.py:1:0: E0611: No name 'then' in module 'behave' (no-name-in-module)
mymodule.py:1:0: W0611: Unused when imported from behave (unused-import)
mymodule.py:1:0: W0611: Unused given imported from behave (unused-import)
mymodule.py:1:0: W0611: Unused then imported from behave (unused-import)

--------------------------------------
Your code has been rated at -180.00/10
```

**Comment by mikedlr** [comment]
@flyte 

As mentioned above, this is a problem with *pylint*, not a problem with *behave*.  The behave code is working as expected.  This issue is closed because it's an issue in the behave bug tracker.  Please open an issue in pylint's bug tracker and put a link here so that other people can find it in future.  

What should ideally be happening is that pylint should be detecting the fact that `given`, `when` and `then` are made available when doing imports from behave even though they aren't visible there as explicit exports.  Either pylint should ignore this or, if it doesn't like it, it should give a warning about bad style with information about how to disable the warning.  

If you want to work around the problem when linting step files then in the pylintrc you have an option
```additional-builtins=```
if you add `given`, `when` and `then` as builtins when linting your step files that will probably solve the problem.  This is perfectly reasonable for step files since a step file actually is interpreted in a different context from a normal python file and so actually does have a slightly different set of rules.

**Comment by essamzaroura** [comment]
No name 'when' in module 'behave'pylint(no-name-in-module)
what is the solution ? Please clearly?

**Comment by mattli001** [comment]
> No name 'when' in module 'behave'pylint(no-name-in-module)
> what is the solution ? Please clearly?

workaround:
`from behave import given, when, then # pylint: disable=no-name-in-module`

**Comment by mtbun** [comment]
Solution:

Click “Code” -> Click “Preferences” -> Click “Settings”
Now in the settings, you have a search bar on top, search:
python.linting.pylintEnable and set it to false

**Comment by manipes-ag** [comment]
> Solution:
> 
> Click “Code” -> Click “Preferences” -> Click “Settings”
> Now in the settings, you have a search bar on top, search:
> python.linting.pylintEnable and set it to false

@mtbun If you do this, you'll disable linting to your entire project. I think that's not what the op is trying to do here :)
