### ISSUE TITLE
Unable to add comments on table data lines

### ISSUE THREAD

**Issue by lhaskins** [behave/behave#643]
It is no longer possible to add comments to the tables in the feature files. For example, the following table returns a "Malformed table at line {X}" error:
```
Examples:
    |  name  |   size  |
    |   me   | 1048576 | # 1MB
    | myself | 2097152 | # 2MB
    |   I    | 4194304 | # 4MB
```

This worked in behave version 1.2.5 and is not working in 1.2.6

**Comment by jenisys** [comment]
In which version should it have been working ?

**Comment by jenisys** [comment]
You are mistaken. 
The same ScenarioOutline w/ comments after the Examples rows fails in behave-1.2.5.

HINT:
Just put your "comment-data" into an additional column of the table instead of using comments.

```gherkin
Scenario Outline: ...
    ...

Examples:
    |  name  |   size  | Comment |
    |   me   | 1048576 | 1MB |
    | myself | 2097152 | 2MB |
    |   I    | 4194304 | 4MB |
```
