### ISSUE TITLE
Update practical_tips.rst for Toolium

### ISSUE THREAD

**Issue by j7an** [behave/behave#644]
The linked web page under "Visual Testing" section of practical_tips.rst is quite outdated. A lot of the projects seemed abandoned. It would be great if this section can be updated with example code for [Toolium](https://github.com/Telefonica/toolium). This project supports Behave, Selenium, and Visual Testing. It is also quite active with 555 commits.

**Comment by jenisys** [comment]
@bittner 
Can you have a look a this issue (hint: You provided the pull-request for the "Visual Testing" part AFAIK).

@j7an 
Otherwise, I will have a look.

**Comment by bittner** [comment]
I think Dave Haeffner’s article is - still - okay. And while I don't know Toolium (yet) I agree that linking to it and providing a fully functional code snippet to demonstrate visual testing integration would be awesome. I would even sympathize with having a new section added that explains other things that Toolium also seems to cover, such as PageObjects.

With the "Practical Tips" chapter we should provide guiding hints on:

1. making people get started quickly
1. w/o walking into "wrong directions" and make mistakes that others have made before
1. and give an overview on what else (beyond Selenium) there is that makes sense to combine with *behave*.

People should really start to understand that BDD is more than just *"an alternative to unit testing"* that (even worse) is *"done with Selenium"* when they read this section.

@j7an Would you want to try and prepare some text and a code sample in a PR?

@20tab @gabbork @filippo-20tab Would you mind [reading over the entire chapter](http://behave.readthedocs.io/en/latest/practical_tips.html) and tell whether the content makes sense (i.e. whether it's confusing or helpful) and what we could rewrite to make jumping in into BDD really easy for everyone?

**Comment by j7an** [comment]
@bittner Sure, I can definitely make a PR.

**Comment by j7an** [comment]
@jenisys Please keep open. I've been busy but will look into doing the PR soon.
