### ISSUE TITLE
Behave doesn't find accented steps in Windows

### ISSUE THREAD

**Issue by reebr** [behave/behave#646]
I'm tryin to run a scenario that have accented steps, on Windows, something like:
```python
# -*- coding: UTF-8 -*-

@when(u'o usuário acessar a tela de download')
def download_acess(context):
    context.driver.get('http://localhost:8080/download')
```
```
# encoding: utf-8
# language: pt

Funcionalidade: Inicio de sessão
    Cenário: Deve apresentar o indicador de download
      Quando o usuário acessar a tela de download
      E clicar em "Download"
```
When I run this feature on CMD (or Powershell), it gaves me a:
```
You can implement step definitions for undefined steps with these snippets:

@when(u'o usuário acessar a tela de download')
def step_impl(context):
    raise NotImplementedError(u'STEP: When o usuário acessar a tela de download')
```

If I change the " á " character to " a ", the scenario runs OK. It appears to be the same thing reported on #597. The problem occurs on Windows shell, on Ubuntu 18.0.4 its works fine. I don't know if there's something related but...

```python
import locale
locale.getpreferredencoding() # UTF-8 - on Ubuntu 18.0.4
```

```python
import locale
locale.getpreferredencoding() # cp1252 - on Windows 10.
```

How can I resolve this issue?

**Comment by Lelor** [comment]
did you try declaring the string as unicode explicitly?

**Comment by Lelor** [comment]
maybe changing the following behave runner.py line (299 in behave 1.2.5) will fix it for you
with open(filename) as f: 
to
with open(filename, encoding='utf-8') as f:

**Comment by jenisys** [comment]
@reebr 
Which Python version are you using ?

OTHERWISE: 
* Writing an encoding-hint with UTF-8 does not mean that the file has UTF-8 encoding. Python encoding is automatically discovered when step-files/environment-files are loaded. Behave uses the normal python mechanism in this case.
* Currently, feature files need to have UTF-8 encoding (and an encoding hint in this case is just a comment for you)

**Comment by reebr** [comment]
@jenisys  I'm using `3.6.4`.

**Comment by jenisys** [comment]
Have you verified your encodings (primarily the feature file) ?

**Comment by jenisys** [comment]
Can you run ``behave tools/test-features/french.feature`` ? 

SEE ALSO:
* [tools/test-features/french.feature](https://github.com/behave/behave/blob/master/tools/test-features/french.feature)

**Comment by lucasmello** [comment]
@reebr which behave version are you using? We had the same problem here when we were using 1.2.5, but from 1.2.6 on, we don't have this problem anymore.

**Comment by reebr** [comment]
I've tested the same scenario with version 1.2.6 and it worked as expected.
Thank you @lucasmello.

Closing this issue, @jenisys.
