### ISSUE TITLE
How to setup python project using pybuilder and behave

### ISSUE THREAD

**Issue by afrancoc2000** [behave/behave#647]
I'm new to python and I'm kind of lost here, I have a gherkins project in lettuce but I found i am creating a project using behave.

I created these files and folders:

    features
    features > steps
    features > steps > example.py
    features > environment.py
    features > example.feature

Then while I was running it, I found it didn't had the dependencies needed, because I'm getting this error:

    ModuleNotFoundError: No module named 'pynput'

So, I looked for a build tool for python and found pybuilder that seems like a good choice, so I created a **build.py** like this:

    from pybuilder.core import init, use_plugin, task
    from subprocess import call

    use_plugin("python.core")
    use_plugin("python.install_dependencies")

    default_task = "behave"

    @init
    def initialize(project):
        project.depends_on("pynput")

    @task
    def behave(project):
        call(["behave"])

But the problem persists it doesn't pick the dependency on "pynput" and I'm still getting the same error, and I found that other sites use a file requirements.txt for dependencies instead, and I'm not sure if its possible but I would preffer to use the pybuild structure for a project and maybe that's the reason nothing is working, something like this:

    src
    src > test 
    src > test > python
    src > test > python > example.py
    src > test > features
    src > test > features > example.feature

Is this possible? or should I use a different build tool for behave? and why haven't I been able to import dependencies?

Thanks

**Comment by jenisys** [comment]
Newer Python versions (>= 2.7.x and 3.x) have a tool called [pip](https://pypi.org/project/pip/).
You can use install other packages from the [Python Package Index](https://pypi.org).

```shell
# -- Windows: Update pip package, then the other packages
python -m pip install -U pip
pip install pynput
pip install -r requirements.txt

# -- UNIX: Needs SUDO => Update pip package, then the other packages
sudo pip install -U pip
sudo pip install pynput
sudo pip install -r requirements.txt
```

Otherwise, create a [virtualenv](https://pypi.org/project/virtualenv/) (as virtual-environment for Python) with your packages for this project and install them with ``pip``.
