### ISSUE TITLE
Debug-on-Error tutorial code sample incorrect

### ISSUE THREAD

**Issue by hateno** [behave/behave#648]
The _Debug-on-Error (in Case of Step Failures)_ sample code from behave/tutorial.rst is incorrect since `step.status` returns an Enum and not a string, hence the user will never be able to perform debug upon a step failure since the comparison is invalid.

https://github.com/behave/behave/blob/master/docs/tutorial.rst#debug-on-error-in-case-of-step-failures

**Comment by jenisys** [comment]
You are wrong, the example is still correct. See description in pull-request #649
