### ISSUE TITLE
Fixture documentation: Challenges in implementing the example as a first-time user

### ISSUE THREAD

**Issue by reed9999** [behave/behave#650]
Though I very much appreciate documentation on fixtures, I'm finding this documentation: 

https://github.com/behave/behave/blob/master/docs/fixtures.rst

really confusing as a first-time example to implementing them. My intuition is that the example under "Providing Fixtures" is depending on a few pieces it's not fully explaining:

* What does the code in the step look like when it invokes the feature? Or is there any?
* What's the connection between the name of the feature ```browser_firefox``` and ``` @fixture.browser.firefox```?  If I just want to instantiate an app, could I use feature ```app``` and ``` @fixture.app```? Or are the underscores and dots doing some Python magic?
* ```from somewhere.browser.firefox import FirefoxBrowser``` -- does it matter what's in FirefoxBrowser? I like the real-world nature of the example, but perhaps a toy example showing what's being called should come before, or perhaps it should come after.

Now, granted, the doc may well be effective for someone reading straight through. I'm the type to dive in and start doing things, and then go back to docs as needed, so there may be antecedent knowledge I'm missing.  But I wager I'm not the only one who learns this way, so it would be good to point to the antecedent knowledge (if that's the problem).

This issue is intended to be constructive so I'm happy to contribute once I've better learned how to use fixtures.

---

So my present issue is the fixture code not getting hit when I run tests, but I suspect the problem is in my understanding, not the behave code. That's why I logged this as a documentation issue.

**Comment by jenisys** [comment]
Mmh, all the information is there just below your nose. Maybe I should write less ;-)
Yes, you need a mapping between your fixture or fixture-function (as code) and the fixture-tag (as name) that is used in the feature file. This mapping occurs in the examples in the ``before_tag()`` hook. You either do it:

* by hand (like in the simple-example below) with ``use_fixture()`` or 
* use a mapping/dict with ``use_fixture_by_tag()``. 
  The mapping/dict defines the mapping between the fixture-tag (as name) and the fixture (function).

SEE ALSO:
* http://behave.readthedocs.io/en/latest/fixtures.html
* http://behave.readthedocs.io/en/latest/fixtures.html#using-a-fixture  (simple example at the end)
* http://behave.readthedocs.io/en/latest/fixtures.html#realistic-example
* http://behave.readthedocs.io/en/latest/new_and_noteworthy_v1.2.6.html#fixtures
* [features/fixture.feature](https://github.com/behave/behave/blob/master/features/fixture.feature)

**Comment by jenisys** [comment]
@reed9999
Contribution is welcome and you can always help to make things better.
Therefore yes, provide a pull-request.
