### ISSUE TITLE
Specify a configuration file on the command line

### ISSUE THREAD

**Issue by DaveTaddei-CR** [behave/behave#652]
We have a use case where two behave.ini files are required.  One for running on developers machines and one for running as part of a CI process.  It would be extremely useful to be able to specify a config file and it's location via the command line.

Expected behaviour:
- no config file specified use the current behaviour
- config file specified, override any config file from the current running directory
- config file plus path specified, override any config file from the current running directory

**Comment by jenisys** [comment]
Use:

* [userdata](http://behave.readthedocs.io/en/latest/new_and_noteworthy_v1.2.5.html#index-7) (Advance Usecases) or
* [test stage](http://behave.readthedocs.io/en/latest/new_and_noteworthy_v1.2.5.html#test-stages) concept

**Comment by DaveTaddei-CR** [comment]
Actually I had custom formatters in mind but in the same link you provided I see this is available with the -f option.  Thanks but I still feel there would be value in having the config file as a configurable command line option.
