### ISSUE TITLE
before_step hook not running

### ISSUE THREAD

**Issue by afrancoc2000** [behave/behave#653]
Hi, 

I created a project using the tutorial and in the environment.py file included a before_all, before_escenario, after_escenario, before_feature and before_step methods in it, they are all running except for the before_step.

This is my environment.py:

    def before_all(context):
        print("before all")

    def before_scenario(context, feature):
        print("before scenario")

    def after_scenario(context, feature):
        print("after scenario")

    def before_step(context, step):
        print("before step")

    def before_feature(context, feature):
        print("before feature")

This is the output:

    before all
    before feature
    Feature: showing off behave # features/example.feature:1
    before scenario

    Scenario: run a simple test        # features/example.feature:3
        Given we have behave installed   # features/steps/example.py:3
        When we implement a test         # features/steps/example.py:7
        Then behave will test it for us! # features/steps/example.py:11
    after scenario

    1 feature passed, 0 failed, 0 skipped
    1 scenario passed, 0 failed, 0 skipped
    3 steps passed, 0 failed, 0 skipped, 0 undefined
    Took 0m0.001s

I'm using behave 1.2.6, is there some extra configuration needed for the before_step method to work?

Thanks

**Comment by spyoungtech** [comment]
By default, Behave captures output and print statements in steps won't be shown for successful steps.

If a step fails, it will provide you the contents from stdout.

You can provide the `--no-capture` option to behave to change this behavior.

**Comment by afrancoc2000** [comment]
Ok thanks!

**Comment by jenisys** [comment]
@afrancoc2000 
Output is captured and only shown when the scenario/step fails as @spyoungtech has pointed out.
You can also verify it by producing an error in the ``before_step()`` like:

```python
# -- FILE: features/environment.py
...
def before_step(ctx, step):
    x = 1 / 0  # CAUSE: ZeroDivisionError
```

and running the a feature. Now it should before the first step of each scenario.

NOTE:
As suggested in [PyCon 2016: Ned Batchelder: Machete-mode Debugging](http://pyvideo.org/pycon-us-2016/ned-batchelder-machete-mode-debugging-hacking-your-way-out-of-a-tight-spot-pycon-2016.html)
