### ISSUE TITLE
Python 3.4 on Travis

### ISSUE THREAD

**Issue by jayvdb** [behave/behave#661]
I tried to do a build on Python 3.4, as I am investigating a problem on that version in a @coala project. c.f. https://github.com/coala/coala-ls/issues/5

I had a similar problem locally here.  It seems there are a few problems with `six` 1.10, which is probably why behave uses `six>=0.11`.  But on Python 3.4, that isnt enough to bypass the problems.  easy_install seems to be still installing 0.10

```
Searching for six>=1.11.0
Reading https://pypi.python.org/simple/six/
Downloading https://files.pythonhosted.org/packages/16/d8/bc6316cf98419719bd59c91742194c111b6f2e85abac88e496adefaf7afe/six-1.11.0.tar.gz#sha256=70e8a77beed4562e7f14fe23a786b54f6296e34344c23bc42f07b15018ff98e9
Best match: six 1.11.0
Processing six-1.11.0.tar.gz
Writing /tmp/easy_install-ml1c7_vh/six-1.11.0/setup.cfg
Running six-1.11.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ml1c7_vh/six-1.11.0/egg-dist-tmp-52rvhofa
no previously-included directories found matching 'documentation/_build'
zip_safe flag not set; analyzing archive contents...
__pycache__.six.cpython-34: module references __path__
creating /home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/six-1.10.0-py3.4.egg
Extracting six-1.10.0-py3.4.egg to /home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages
Adding six 1.10.0 to easy-install.pth file
Installed /home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/six-1.10.0-py3.4.egg
```

https://travis-ci.org/jayvdb/behave/jobs/388576411

**Comment by jenisys** [comment]
Python 3.4 installations of behave work without any problems when  I use tox (with python 3.4.2 on macOS). But I am using a current version of ``pip >= 10.0`` which enforces that I have a newer versions from setuptools but I could install behave in a virtualenv with setuptools >= 24.2.0 (better: 36.2.0 or newer).
