### ISSUE TITLE
setup.py fails on Python 3.3

### ISSUE THREAD

**Issue by jayvdb** [behave/behave#662]
tox.ini says behave supports 3.3, but out of the box `setup.py` fails

```
$ python setup.py -q install
/opt/python/3.3.6/lib/python3.3/distutils/dist.py:258: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
error in behave setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected version spec in traceback2; python_version < '3.0' at ; python_version < '3.0'
```

https://travis-ci.org/jayvdb/behave/jobs/388593320

**Comment by jayvdb** [comment]
c.f. https://github.com/behave/behave/issues/661 which also needs to be fixed if py33 is to be supported.

**Comment by jenisys** [comment]
Sorry, I think you are mistaken. This does not look like a behave problem. This looks like a setuptools problem. Use a current version of setuptools / pip and you will not get this problem. 
NOTE: ``python_requires`` support was added in "v24.2.0" (2016-07-20). I assume that you have an older version installed.

SEE ALSO:
* https://setuptools.readthedocs.io/en/latest/history.html
