### ISSUE TITLE
[Question] Tests Stages: Tests that uses the same preconditions but differ only in validation

### ISSUE THREAD

**Issue by rafaeldelucena** [behave/behave#664]
Hello,

I have some tests that uses the same steps, they share the preconditions and background but differ only on validations.

There's a nicer way to do this without duplicate the precondition steps or put the validations in the same step impl?

[]s

**Comment by lucasmello** [comment]
Have you considered using Scenario Outline?

**Comment by jenisys** [comment]
@rafaeldelucena
If I understand you correctly only the then-steps differ?
 
Are you aware of the step-library concept ?
It allows you to import steps from other places (in the python search path).
Therefore, import the "common steps" (with the preconditions, ...) from the common step library.

Potential other solution (depending on the complexity in your steps):
Hide the validation in a validator. 
This allows you to select a validator for your step(s). 
The selection logic decides on your environment/userdata what to do.
