### ISSUE TITLE
STDOUT to 2 sources

### ISSUE THREAD

**Issue by lucasmello** [behave/behave#667]
I'm using allure formatter on Jenkins, and I would like to have the steps printed in Jenkins and Allure.

Is it possible to have these steps printed in both systems?

**Comment by jenisys** [comment]
Probably yes, if you want to completely garbled output from multiple formatters.
BACKGROUND: Each formatter has its own concept when its output is printed/flushed. In general, this is done after each step (or significant line(s)).

In general you use only one formatter that uses STDOUT.
And all the others write to a file. Which formatter uses STDOUT is up to you. 
But the other formatter should use a file (or directory; depends on formatter implementation).
