### ISSUE TITLE
execute_steps fails on  'ascii' codec can't encode characters

### ISSUE THREAD

**Issue by modehnal** [behave/behave#668]
Calling context.execute_steps from another step sometimes fails on "Assertion Failed: 'ascii' codec can't encode characters in position 346-348: ordinal not in range(128)"

At first I thought its just because of special characters but now this issue has appeared in calling with just letters. Following lines are called from another step: 
context.execute_steps(u'* Left click "File" "menu"')
context.execute_steps(u'* Left click "Import From Folder" "menu item"')
I use these two lines right next to each other, first one succeeds, second one fails on codec encode error. I just found out about this issue, which makes me believe in the latest update something changed as I have used these two lines, and many more in this style, in my projects for over a year and never saw this issue.

I should mention that execute_steps method was the last one I thought was failing, I have made quite an effort to inspect all data in behave run with debugger and found nothing. But once I deleted the line and switched to python function call. Making the lines like this:
context.execute_steps(u'* Left click "File" "menu"')
mouse_click(context, "Import From Folder", "menu item")
The issue disappeared immediately.

I also have no troubles with content of execute_step while called from feature file instead of another step. Which makes me believe there is some issue with encode handling inside of an execute_steps method.

**Comment by jenisys** [comment]
NEED: Python version and platform information (Windows, Linux, ...)
HINT: Looks like a hidden Unicode character in your step files. Or in your implementation below.

Try to switch the order of the "context.execute_steps()" calls.
If the second call fails again, I might consider it a problem in ``execute_steps()``.

**Comment by modehnal** [comment]
python2-behave-1.2.5-18.el7.noarch python-2.7.5-74.el7.x86_64 Linux: Red Hat Enterprise Linux

Hidden Unicode character seems unlikely, I have retyped and deleted character by character several times, and used site like https://www.textmagic.com/free-tools/unicode-detector to verify my characters. No such character was found.

While trying to switch the steps the second one (now first) still fails on ascii codec, but only in form of context.execute_steps(), the function call itself still raises no such errors. It could mean my test for Unicode character is flawed, but than why is not function call failing too. Description in previous paragraph is the way I tested my behave sentence for Unicode characters. If there is any other way I am not familiar with, please let me know.

Also if you have any other idea how to get to the bottom of this I am willing to test it all to figure out what is wrong. While this issue is not exactly "an issue" as I can workaround it pretty easily, it is still quite annoying to not know why it behaves as it behaves. (no pun intended /joke)

Have a nice day.

**Comment by jenisys** [comment]
If the second execute_steps() call (which was now the first) still fails after you changed the ordering, the reason for this is on your side and not with behave. In addition, try to use behave-1.2.6.
