### ISSUE TITLE
Custom directories for steps

### ISSUE THREAD

**Issue by denizdogan** [behave/behave#670]
Is there any way to use a custom directory for steps modules, so that the steps directories are siblings to the features directories?

```
/project
  /features
    something.feature
  /steps
    something.py
```

The above is roughly what I'm trying to achieve. Is this possible?

**Comment by jenisys** [comment]
No, the steps directory is as described.
But you can use the step-library concept to place step-implementations outside of feature directory (and simplify the reuse in other places).
