### ISSUE TITLE
Error while running behave_main from windows

### ISSUE THREAD

**Issue by sonishbnair** [behave/behave#671]
**What i am trying**      
I am trying to run behave from a Window machine which don't have behave installed (without PIP install) or any other depended libraries pip installed.
1. Including all modules path to sys.path.        
2. Running behave using behave_main method.
Python - 2.7 .  
Behave - 1.2.6 .  

**Code sample:**

    import sys
    sys.path.append('C:\\MyWorkspace\\synthetics\\features\\modules\\behave-1.2.6')
    sys.path.append('C:\\MyWorkspace\\synthetics\\features\\modules\\parse-1.8.4')
    sys.path.append('C:\\MyWorkspace\\synthetics\\features\\modules\\selenium-3.13.0')
    sys.path.append('C:\\MyWorkspace\\synthetics\\features\\modules\\parse_type-0.4.2')
    sys.path.append('C:\\MyWorkspace\\synthetics\\features\\modules\\traceback2-1.4.0')
    sys.path.append('C:\\MyWorkspace\\synthetics\\features\\modules\\linecache2-1.0.0')
    sys.path.append('C:\\MyWorkspace\\synthetics\\features\\modules\\nose-1.3.7')
    sys.path.append('C:\\MyWorkspace\\synthetics\\features\\modules\\six-1.11.0')
    sys.path.append('C:\\MyWorkspace\\synthetics\\features\\modules\\enum-0.4.6')
    
    from behave.__main__ import main as behave_main
    behave_main(["C:\\MyWorkspace\\synthetics\\features\\", "-n Login"])

I am able to run behave script this way from my Mac OS, having issue doing the same from Windows machine.

**Error:**

    C:\MyWorkspace\synthetics\features>python run_behave.py
    Traceback (most recent call last):
      File "run_behave.py", line 16, in <module>
        behave_main(["C:\\MyWorkspace\\synthetics\\features\\", "-n NEAT"])
      File "C:\MyWorkspace\synthetics\features\modules\behave-1.2.6\behave\__main__.py", line 182, in main
        config = Configuration(args)
      File "C:\MyWorkspace\synthetics\features\modules\behave-1.2.6\behave\configuration.py", line 647, in __init__
        self.reporters.append(SummaryReporter(self))
      File "C:\MyWorkspace\synthetics\features\modules\behave-1.2.6\behave\reporter\summary.py", line 49, in __init__
        self.feature_summary = {Status.passed.name: 0, Status.failed.name: 0,
    AttributeError: 'int' object has no attribute 'name'

**Comment by sonishbnair** [comment]
I was able to eliminate this issue by running the code with Behave 1.2.5. This issue exists in 1.2.6 version.

**Comment by jenisys** [comment]
Sorry, but I think you have digged this hole for yourself.
If you have such a weird use case, you need to resolve it yourself.

BETTER:
Just install ``behave`` with ``pip``, for example in a virtual environment with ``virtualenv`` and use it, and your problems are gone. If necessary use ``pip download --dest downloads -r py.requirements/all.txt`` to download all required packages first.

NOTE:
* The Status changed from ``string-enum`` in behave-1.2.5 to ``enum.Enum class-value`` in behave-1.2.6. May be the python interpreter finds an installed behave-1.2.5 version ?!?
Bu that does not explain the error above. And a normally installed behave-1.2.6 does not show this problem.
* Your command-line parameters that you use for the ``behave_main()`` are incorrect. Program name is missing as args[0] and arg ``-n Login`` needs to be two args in argv.
