### ISSUE TITLE
Feature files cannot be found within symlink directories

### ISSUE THREAD

**Issue by smadness** [behave/behave#675]
It looks like the default behavior for `behave` is to not follow symlinks when looking the current directory structure for .feature files.

With a directory structure like this:

- steps
- features -> ../git-sub-module/features

when executing `behave` it fails with

me% behave
ConfigError: No feature files in "[ working dir ]"

I cannot find any documentation to force behave to follow symlinks to find feature files.  Could this be added to support advanced workflows?

**Comment by jenisys** [comment]
Mmh, you cannot make up a directory structure that you like to use. You need to use the one that is supported (and documented). The ``features/`` directory needs a ``steps/`` subdirectory.

```
+-- features/
      +-- steps/*.py
      +-- *.feature
```

HINTS: 
* The problem is not the symlink. 
* In addition, I assume your symlinked destination directory is not populated: 
  Therefore, no feature files are found.
  That is the only way how I can reproduce the behave error-message.

**Comment by smadness** [comment]
I modified the os.walk methods in `behave` to follow symlinks, in the two places that the project seems to use them, outside of the `bin/behave.junit_filter.py` file that I didn't understand the impact of.  Adding `followlinks=True` to the two instances (ignoring tests for now) seems to fix this issue.

Here's an example diff:  https://github.com/behave/behave/compare/master...smadness:behave-675

I haven't added any tests yet or submitted a PR.  But after a few glances I can't think of any substantial issues this would cause.  Thoughts?

**Comment by jenisys** [comment]
@smadness
Provide a PR for the ``os.walk(..., followlinks=True)`` functionality.

NOTES: 
The layout variations description just indicates that can provide multiple feature subdirs under a common directory w/ steps (in this case: ``tests/``). In your initial description, you left out the common root directory.

**Comment by smadness** [comment]
Created https://github.com/behave/behave/pull/680 for this.

**Comment by jenisys** [comment]
INTEGRATED INTO: behave-1.2.7.dev0
