### ISSUE TITLE
Scenario Outline: Support tags with commas and semicolons

### ISSUE THREAD

**Issue by lawnmowerlatte** [behave/behave#678]
I've noticed an issue in behave where Scenario Outlines don't see commas within tags. The tag is still available for the scenario, but any commas in it are stripped out. You can see this by running the `@wip` tests on [my branch](https://github.com/lawnmowerlatte/behave/tree/scenario-outlines-dont-support-tags-with-commas):

```
$ python -m behave --tags wip
@wip
Feature: Scenario Outlines can read tags with commas # features/outline_tags.feature:2

  @tag,with,commas
  Scenario: Scenario can see tags with commas  # features/outline_tags.feature:5
    Given I print the tags                     # features/steps/check_tag_steps.py:5 0.000s
    Then I see the tag tag,with,commas         # features/steps/check_tag_steps.py:10 0.000s

  @tagwithcommas
  Scenario Outline: Scenario Outline can see tags with commas -- @1.1   # features/outline_tags.feature:16
    Given I print the tags                                              # features/steps/check_tag_steps.py:5 0.000s
    And I see the tag tag,with,commas                                   # features/steps/check_tag_steps.py:10 0.000s
      Assertion Failed: Tag tag,with,commas is not detected
      Captured stdout:
      ['wip', 'tagwithcommas']


  @tag,with,commas
  Scenario Outline: Scenario Outline can see tags with commas in examples -- @1.1   # features/outline_tags.feature:25
    Given I print the tags                                                          # features/steps/check_tag_steps.py:5 0.000s
    And I see the tag tag,with,commas                                               # features/steps/check_tag_steps.py:10 0.000s


Failing scenarios:
  features/outline_tags.feature:16  Scenario Outline can see tags with commas -- @1.1

0 features passed, 1 failed, 78 skipped
2 scenarios passed, 1 failed, 487 skipped
5 steps passed, 1 failed, 1983 skipped, 0 undefined
Took 0m0.001s
```

Note that the feature actually has commas in the tag, the output above actually shows that the formatter also shows it without tags.

This doesn't affect Scenarios nor Features. It also doesn't affect Scenario Outlines when the Example table is tagged.

**Comment by lawnmowerlatte** [comment]
I've discovered the issue. In `Tag.make_name` tags are mangled to restrict the allowed characters. However this function is not applied across all objects, it's only applied by `ScenarioOutlineBuilder` when generating `Scenario` objects within a `ScenarioOutline`. It isn't even called on the tags from the `Example` object within the `ScenarioOutline`. This is why it only affects tags on the `Scenario Outline` itself.

Here is a traceback for reference:
```
File "~/behave/behave/__main__.py", line 187, in <module>
    sys.exit(main())
File "~/behave/behave/__main__.py", line 183, in main
    return run_behave(config)
File "~/behave/behave/__main__.py", line 127, in run_behave
    failed = runner.run()
File "~/behave/behave/runner.py", line 808, in run
    return self.run_with_paths()
File "~/behave/behave/runner.py", line 828, in run_with_paths
    return self.run_model()
File "~/behave/behave/runner.py", line 630, in run_model
    failed = feature.run(self)
File "~/behave/behave/model.py", line 321, in run
    failed = scenario.run(runner)
File "~/behave/behave/model.py", line 1119, in run
    for scenario in self.scenarios:     # -- REQUIRE: BUILD-SCENARIOS
File "~/behave/behave/model.py", line 1024, in scenarios
    self._scenarios = builder.build_scenarios(self)
File "~/behave/behave/model.py", line 903, in build_scenarios
    row_tags = self.make_row_tags(scenario_outline.tags, row, params)
File "~/behave/behave/model.py", line 861, in make_row_tags
    new_tag = Tag.make_name(tag, unescape=True)
```

The fix is either:
* to add the comma to the list of acceptable characters (see my fork)
* to allow other characters (see [line 1695-1698](https://github.com/lawnmowerlatte/behave/blob/scenario-outlines-dont-support-tags-with-commas/behave/model.py#L1695)
* to just not invoke `Tag.make_name` on [line 861](https://github.com/lawnmowerlatte/behave/blob/scenario-outlines-dont-support-tags-with-commas/behave/model.py#L861)

It might be good to just invoke `Tag.make_name` when a `Tag` is created for consistency. Or just remove it entirely.

While investigating, I also noticed that semicolons are not allowed which we also need. I've included this in my fork as well.

h4. Sidebar on why we want this
I didn't see anything in the documentation about restricting the contents of tags, so I don't really see a reason not to allow it. I understand tags with commas cannot be used from the command line because commas already have a meaning in that context. However, we use commas within tags to invoke a custom implementation of fixtures, for example:

```
@fixture.example.local:parameters=x,y,z;name=namespace
```

This tag invokes a fixture described in `fixture/example/local.py` with the parameters specified after the colon. The commas allow lists to be passed in as arguments. Semicolons separate key/value pairs. This works great for us, except when using Outlines.

**Comment by lawnmowerlatte** [comment]
I've reworked my branch to better fit in line with the existing test structure. I ran all the tests on `py36` and `py27` and it came back clean.

**Comment by kwesolowski** [comment]
Is this really good idea given commas are used on command line to separate tags that are "OR" ed together?

**Comment by lawnmowerlatte** [comment]
@kwesolowski I can certainly see the reluctance to introduce something that's potentially confusing like this but the truth is you can already do this with other test types, just not Scenario Outlines. The code path I changed is actually only invoked for Scenario Outlines and not for Scenarios or Examples. It's not something that a new user is going to run into unless they deliberately add commas to their tags and then expect to be able to filter on those tags from the command line.

**Comment by jenisys** [comment]
INTEGRATED INTO: behave-1.2.7.dev0 (with pull-request #679)
