### ISSUE TITLE
Steps with same names but in different .feature files

### ISSUE THREAD

**Issue by Glazz87** [behave/behave#683]
I have steps with same name in different .feature files and i want bind this steps on *different* step_impl functions.

Example:
payment.feature

>   Scenario: payment by credit card
>     Given payment page
>     ...
>     **When click to Submit button**
>     ...

linkcard.feature

>   Scenario: change user avatar
>     Given user profile page
>     ...
>     **When click to Submit button**
>     ...

Is there any way to have different implementations for steps in different .feature files?
Maybe there is another best practice to resolve my problem?

**Comment by ns-ckao** [comment]
Look into the use of [page objects](https://the-creative-tester.github.io/Python-Web-Browser-Automation-Behave/) to define interactions and elements for various pages. Then you can have one step that can be generalized by getting the button labeled "Submit" on the current page.

**Comment by jenisys** [comment]
@Glazz87 
In your specific case, you should use the suggested "page objects" solution.
The "given-step" step creates the specific page object and stores it in the context.
The "when-step" just uses the page object in context, like:

```python
@given(u'payment page')
def step_setup_payment_page(context):
    context.page_object = PaymentPage()

@given(u'user profile page')
def step_setup_user_profile_page(context):
    context.page_object = UserProfilePage()

@given(u'click to Submit buttion')
def step_when_i_click_the_submit_button(context):

@when(u'click to Submit buttion')
def step_when_i_click_the_submit_button(context):
    context.page_object.submit()
```

Otherwise (in general), you need to put the feature files in different feature directories, each with its own `steps` directory, like:

```
+-- features_1/
|     +-- steps/step_impl1_*.py
|     +-- *.feature
+-- features_2/
|     +-- steps/step_impl2_*.py
|     +-- *.feature
```

**Comment by jenisys** [comment]
Question seems to be answered.
