### ISSUE TITLE
Accessing list of objects stored in context

### ISSUE THREAD

**Issue by denizdogan** [behave/behave#685]
For our use case, we store objects that are re-used between steps in the context, like:

```python
def something():
  invoice = Invoice.objects.get(...)
  context.that_invoice = invoice

def another():
  invoice = context.that_invoice
  print(invoice)
```

Is there any simple way to access every object that's been stored in this manner in the `before_step` function? In our use case, we want every object whose name is `that_*`, but I couldn't figure out a nice way to do it.

**Comment by ns-ckao** [comment]
```python
import re
those_things = [value for key, value in vars(context).items() if re.match(r'that_*', key)]
```

Better approach would be to put a `dict` or `list` on the `Context` in `before_all` that can act as a container for the objects you want to retrieve. Ex:
```python
# In environment.py
def before_all(ctx):
    ctx.invoices = []

# In whatever file you have your helpers
def something(ctx):
    for invoice in ctx.invoices:
        # Do something
```

**Comment by jenisys** [comment]
Answered by @ns-ckao
