### ISSUE TITLE
HTML formatter lost in python3

### ISSUE THREAD

**Issue by modehnal** [behave/behave#686]
behave was installed with: python3 -m pip install behave-py3

$ python2 -m behave --format help
Available formatters:
  html           Very basic HTML formatter
  json           JSON dump of test run
  json.pretty    JSON dump of test run (human readable)
  null           Provides formatter that does not output anything.
  plain          Very basic formatter with maximum compatibility
  pretty         Standard colourised pretty formatter
  progress       Shows dotted progress for each executed scenario.
  progress2      Shows dotted progress for each executed step.
  progress3      Shows detailed progress for each step of a scenario.
  rerun          Emits scenario file locations of failing scenarios
  sphinx.steps   Generate sphinx-based documentation for step definitions.
  steps          Shows step definitions (step implementations).
  steps.catalog  Shows non-technical documentation for step definitions.
  steps.doc      Shows documentation for step definitions.
  steps.usage    Shows how step definitions are used by steps.
  tags           Shows tags (and how often they are used).
  tags.location  Shows tags and the location where they are used.

$ python3 -m behave --format help
Available formatters:
  json           JSON dump of test run
  json.pretty    JSON dump of test run (human readable)
  null           Provides formatter that does not output anything.
  plain          Very basic formatter with maximum compatibility
  pretty         Standard colourised pretty formatter
  progress       Shows dotted progress for each executed scenario.
  progress2      Shows dotted progress for each executed step.
  progress3      Shows detailed progress for each step of a scenario.
  rerun          Emits scenario file locations of failing scenarios
  sphinx.steps   Generate sphinx-based documentation for step definitions.
  steps          Shows step definitions (step implementations).
  steps.catalog  Shows non-technical documentation for step definitions.
  steps.doc      Shows documentation for step definitions.
  steps.usage    Shows how step definitions are used by steps.
  tags           Shows tags (and how often they are used).
  tags.location  Shows tags and the location where they are used.

**Comment by jenisys** [comment]
Mmh, you are installing an official `behave-py3` (as unofficial fork) and expect help here ?!? 

NOTES:
* The html formatter was never officially distributed w/ behave.
   It currently resides on a special branch.
* Behave supports Python3. Therefore, why are you using the unofficial fork ?
* https://github.com/sunliwen/behave is the unofficial fork that you are using

**Comment by bittner** [comment]
This works for me with Python3 when I run it as described above by the original poster.

See also: https://github.com/behave/behave/issues/25#issuecomment-743715515
