### ISSUE TITLE
[Feature Request] Steps definitions catalog is displayed by module and with colors

### ISSUE THREAD

**Issue by ducdetronquito** [behave/behave#690]
Hello everyone !

Currently, when someone displays its steps definition with `--steps-catalog`, the output does not mention in which module the step is defined, and does not highlight its type well (Given, When and Then).

<img
    src="https://user-images.githubusercontent.com/9960268/45493892-2339a280-b770-11e8-824d-5712337951a6.png"
    height="300px"/>

Do you think it could be worth it to improve the `--steps-catalog` output ?

An humble example (besides, we could also use different color for Given, When and Then)

<img
    src="https://user-images.githubusercontent.com/9960268/45493655-9262c700-b76f-11e8-8e8b-61791e257af6.png"
    height="300px"/>

**Comment by jenisys** [comment]
@ducdetronquito 
Have you looked at the other step formatters, like:

```bash
$ behave -f help
Available formatters:
...
  sphinx.steps   Generate sphinx-based documentation for step definitions.
  steps          Shows step definitions (step implementations).
  steps.catalog  Shows non-technical documentation for step definitions.
  steps.doc      Shows documentation for step definitions.
  steps.usage    Shows how step definitions are used by steps.
...

$ behave -f steps --dry-run features/
GIVEN STEP DEFINITIONS[42]:
  Given I setup the current values for active tags with                    # features/steps/behave_active_tags_steps.py:34
  Given the behave context has a parameter "{param_name}"                  # features/steps/behave_context_steps.py:37
  Given the ...
```

Note that the location where to find each step is already provided.
And the `sphinx.steps` formatter groups steps by source file.
