### ISSUE TITLE
Specifying a "Given...And" with step parameters isn't matching

### ISSUE THREAD

**Issue by pcn** [behave/behave#691]
I'm not certain if I'm doing this right, but this seems like it should work.

First, I'm not familiar with behave, or with cucumber. I'm using examples from a book in prerelease called "the ray tracer challenge" that's built around cucumber tests.

The feature I have defined is here: https://github.com/pcn/trtc/blob/49bffbea4a5e5158c849280161fbeae9ef2bdaea/python3/trtc/features/tuples.feature#L31-L34

And the test is at: https://github.com/pcn/trtc/blob/49bffbea4a5e5158c849280161fbeae9ef2bdaea/python3/trtc/features/steps/tuples_steps.py#L98-L100

Running the test under python 3.6.6 and 3.7.0 results in the same result:

```

  Scenario: 'Point' describes tuples with w=1  # features/tuples.feature:22
    Given p is a Point of "4", "-4", "3"       # features/steps/tuples_steps.py:76 0.000s
    Then p = tuple "4", "-4", "3", "1"         # features/steps/tuples_steps.py:80 0.000s

  Scenario: 'Vector' describes tuples with w=0  # features/tuples.feature:26
    Given v is a Vector of "4", "-4", "3"       # features/steps/tuples_steps.py:85 0.000s
    Then v = tuple "4", "-4", "3", "0"          # features/steps/tuples_steps.py:90 0.000s

  Scenario: Adding two tuples                     # features/tuples.feature:31
    Given a1 is a tuple of "3", "-2", "5", "1"    # features/steps/tuples_steps.py:94 0.000s
    And a2 is a tuple of "-2", "3, "1", "0"       # None
    Then a1 + a2 is a tuple of "1", "1", "6", "1" # None


Failing scenarios:
  features/tuples.feature:31  Adding two tuples

0 features passed, 1 failed, 0 skipped
4 scenarios passed, 1 failed, 0 skipped
19 steps passed, 0 failed, 1 skipped, 1 undefined
Took 0m0.002s

You can implement step definitions for undefined steps with these snippets:

@given(u'a2 is a tuple of "-2", "3, "1", "0"')
def step_impl(context):
    raise NotImplementedError(u'STEP: Given a2 is a tuple of "-2", "3, "1", "0"')
```

For some reason even though the "Given" line is working, the "And" line is not, even though I believe that it should?

The documentation states that "Given...Given" should be valid, but that has the same failure.  The only working solution I have at the moment is to create a test where I can't pass parameters, which I think is not what I would prefer.

Any insight into why this is happening, and what I can do to make this work for me?

Thanks!

**Comment by jenisys** [comment]
You seem to have already solved the problem, as I can see from your currently checked-in solution in the repo. But there are still some step definitions missing (at least on the current HEAD of the repo).

As you seem to have discovered by yourself:

* regular expressions (the underlying mechanism) are greedy, 
  meaning they may match more than you think
* you are better off if you specify a type, what you expect (numbers and/or floating-point numbers)

SEE ALSO:
* Issue #665 (search: `parse_unquoted()`)

**Comment by pcn** [comment]
Yes, I'm still learning how this works.  Since I'm coming from something that has tests that I'm mostly copying, it was an interesting speed bump to realize how parsing's matching of numbers would be a bit less flexible in this case.

But thanks for the explanation, as you said things are working now.
