### ISSUE TITLE
Print chained exception for HOOK error

### ISSUE THREAD

**Issue by jonathand131** [behave/behave#692]
Hello,

The log printed while handling exception from a hook only shows the main exception but does not show the cause exception(s) and does not benefit of the chained exception feature available in Python 3.

The problem is located in `ExceptionUtil.describe` where there is already a note about this matter.

A proposal is to replace (L64 in _types.py in v1.2.6)
`text += u"".join(traceback.format_tb(exc_traceback))`
with
`text += u"".join(traceback.format_exception(type(exception), exception, exc_traceback))`

This change works for me but I let you decide the better to implement this.

Regards.

**Comment by jonathand131** [comment]
Please remove wontfix

**Comment by retorquere** [comment]
Can I monkey-patch this in as a temporary workaround without modifying the behave code? Without stack traces my behave setup is hard to debug.
