### ISSUE TITLE
Running Behave from external application causes AttributeError 

### ISSUE THREAD

**Issue by JonKoser** [behave/behave#694]
If behave is run internally from a non-python (or really a non-command-line) application, there is no sys.argv[0] for argparse.py to default to. Because of this, argparse.py throws an AttributeError at line 1622:
![image](https://user-images.githubusercontent.com/9324338/46390581-292efd80-c6f6-11e8-9e26-d048e67ba5d1.png)

![image](https://user-images.githubusercontent.com/9324338/46390975-3d73fa00-c6f8-11e8-89b0-a04809c65c0a.png)

However, there is the ability to pass in the "prog" when setting up the parser:
![image](https://user-images.githubusercontent.com/9324338/46390654-7dd27880-c6f6-11e8-8704-95cc417775f1.png)

Unfortunately, when running behave via \__main__.main(), there is no way to pass a value for prog through to \__main__.main() -> Configuration() -> setup_parser() (line 583 of configuration.py) -> argparse.ArgumentParser() (line 480 of configuration.py) so that it doesn't need to use sys.argv[0].

Additional Info: 
- OS: Solaris 10
- Python Version: 3.4.5

**Comment by jenisys** [comment]
Sorry, you are mistaken, you can pass args though behave `main(args=None)`.
But args should be `sys.argv[1:]`.
If you are calling `behave` from a non-python application, this can only occur by starting behave as subprocess (and there is no problem w/ it).

**Describe in detail how you start `behave`**, 
because the snippet from above makes no no sense 
(reason: Python always has a `sys.argv` 
but maybe you have forgotten to import the `sys` module or are faking it).

**Comment by JonKoser** [comment]
Hi there,
    I think there was some miscommunication; hopefully this helps. Yes, you can pass args to behave’s main, but they are not the args I’m looking for. The arguments we can pass are _for behave_. I’m saying that you can’t pass any additional arguments through to argparse.ArgumentParser(), which is where I’m having the problem. Here’s what I mean:
Here’s how I’m calling behave (via main) – this is my file being run from my outside application. By that I mean that my outside application actually has an embedded python interpreter which executes the python files I give it within my application's own process. It does not spawn a separate sub-process and nothing is actually run via command line:
 
![image](https://user-images.githubusercontent.com/9324338/46489351-c3607580-c7ca-11e8-8537-cbed755647f9.png)

See that I am actually using the ability to pass arguments. So, when I call main we come here (in behave’s code):
 
![image](https://user-images.githubusercontent.com/9324338/46489366-c9565680-c7ca-11e8-980d-a68a7fd03bd0.png)


And then we set up our configuration here (in behave’s code):
 
![image](https://user-images.githubusercontent.com/9324338/46489375-cfe4ce00-c7ca-11e8-8a0b-2dbb1530eceb.png)

So, this is fine and good until we set up our parser in Configuration here (in behave’s code):
 
![image](https://user-images.githubusercontent.com/9324338/46489382-d6734580-c7ca-11e8-935d-ea4bff6074f9.png)

First, notice how none of our arguments passed into main() originally get passed into setup_parser(). Then in setup_parser, we only set the usage and description strings (in behave’s code):
 
![image](https://user-images.githubusercontent.com/9324338/46489384-da9f6300-c7ca-11e8-8d8c-be0bd4d8c4ea.png)

So, there is no way for us to pass forward prog as an argument into argparse.ArgumentParser() when running behave via main().
Additionally, notice  how I am not invoking behave as a subprocess – it is actually in-line with my main application's process due to an internal python interpreter. Because I am importing behave’s main function and running it programmatically, this does not require a subprocess to be started (and it actually the only way I can use behave for my project). There is no command line involved at all in executing behave, thus there is no argv instantiated for the sys module.

**Comment by jenisys** [comment]
You are thinking too complicated. 
The following works perfectly if you drop the first parameter (arg0):

```python
#!/usr/bin/env python
# -- FILE: my_behave.py

from __future__ import absolute_import, print_function
from behave.__main__ import main as behave_main
import sys

if __name__ == "__main__":
    cmdline = " ".join(sys.argv[1:])
    print("behave: %s" % cmdline)
    sys.exit(behave_main(cmdline))
```

**Comment by JonKoser** [comment]
Found my fix! This was actually the exact same issue as https://github.com/googleapis/oauth2client/issues/642
Fix was just adding 

import sys

if not hasattr(sys, 'argv'):
    sys.argv  = ['']

to my behave runner.

**Comment by JonKoser** [comment]
I don't know if tags really matter or not, but it might be nice to change the tags on this, too. I wasn't mistaken - there's just a good workaround and it's arguably argparse's fault, not behave's.
