### ISSUE TITLE
Using JUnit enable stdout and stderr capturing even for console output

### ISSUE THREAD

**Issue by HonzaTuron** [behave/behave#695]
Hi!

First of all, thanks for your work on behave. I recently found issue while using JUnit logging.
I run behave via CLI with following flags:
`--no-capture --no-capture-stderr -i=(0_)?({}). -k -t=wip --junit --junit-directory=C:\\tmp\\tests\\reports`
when stdout and stderr is still captured. When I remove JUnit flags to:
`--no-capture --no-capture-stderr -i=(0_)?({}). -k -t=wip`
console print logs and errors uncaptured as expected. It looks capturing is switched by JUnit as one can see in [configuration.py](https://github.com/behave/behave/blob/0a9430a94881cd18437deb03d2ae23afea0f009c/behave/configuration.py#L640-L644).
Is this expected behavior and/or is workaround available?

Thanks!

**Comment by jenisys** [comment]
The lines in `behave/configuration.py` were intended. Otherwise, could not contain the captured parts (stdout, stderr, logging). If this is the best behaviour is another question.

**Comment by raviteja2200** [comment]
So does this mean that I will not

**Comment by raviteja2200** [comment]
@jenisys So do you mean we couldn't capture logs when junit is enabled?

**Comment by jenisys** [comment]
@raviteja2200 
Actually, It is the other way around: Only what is captured can become part of the JUnit report (independent if it is actually written to the JUnit XML report).

Logging is a complete different story, especially if you log to files.
If you log to files and don't capture it, `behave` will not intercept the log records (and output them on failures). If you capture log records, these are normally only shown on failures.
Besides, there are log filters that allow you to determine what is captured and what is not (therefore something in between).

**Comment by ramonasuciu** [comment]
We had the same issue recently - we needed junit reports and also the logging output to be displayed in the console.
How we solved this was by extending the logging module in Python - https://docs.python.org/3/howto/logging.html - and we used a configuration file, which makes it far easier to change log level, handlers, formatters, etc.

Furthermore, junit is true, and we had no issues in this way generating junit compatible reports.
Hopefully, this helps others as well.

Have a good day,
Ramona

**Comment by BrambleRamble** [comment]
I'd find it very helpful to have a flag combination that lets me create JUnit reports and also log full details. In the context of build jobs, the JUnit reporting is fantastic for integrating with reporting tools to display the big picture, but at the same time, it's very valuable to have complete logs of exactly what happened to facilitate troubleshooting.

I appreciate that JUnit captures the output for failing scenarios, so this can be accessed, but seeing what happened in the run-up to a failing scenario is also potentially useful. In a perfect world there would be no interaction between the scenarios, but in the context of data setup and asynchronous processing, it's not always so neat and tidy.

In the meantime I'll try to follow @ramonasuciu 's approach.

**Comment by BrambleRamble** [comment]
I have managed to get the behaviour that I want, more or less, although it seems I have broken the `--no-capture` flag through doing this. Unfortunately I have limited time to troubleshoot this now, so I think I'll just have to accept it.

@jenisys I think it would be worth considering whether the current behaviour is the best behaviour. In the context of running tests in build jobs, where it would be very reasonable to create JUnit reporting at the same time as creating details logs, I think that the configuration options could be improved.

**Comment by BrambleRamble** [comment]
@ramonasuciu Please could you share more detail of your configuration to get logging alongside using the JUnit flag? I keep on uncovering more misbehaviour in what I've currently implemented, so I'd really appreciate help to get on the right tracks.

**Comment by dani29** [comment]
@BrambleRamble @ramonasuciu Came across this issue while trying to solve pretty much the same thing - get JUnit reports while streaming logs to stdout during execution. Can you share your solution's configuration if you achieved anything satisfactory?

Thanks!

**Comment by BrambleRamble** [comment]
@dani29 Looking back on my notes, I wasn't satisfied with my solution _at all_, but here's some of what I did in the limited time I had:
- Run tests with a custom parameter `-D log_everything`
- Add support for `-D log_everything` by adding the following to `before_all`:
```
    logging.shutdown()
    logging.getLogger().setLevel(logging.INFO)
    if 'log_everything' in context.config.userdata:
        log_formatter = logging.Formatter("\t%(asctime)s [%(levelname)-5.5s]  %(message)s")
        console_handler = logging.StreamHandler(sys.stdout)
        console_handler.setFormatter(log_formatter)
        logging.getLogger().addHandler(console_handler)
```
- in `after_all`, add `logging.shutdown()`
- Change environment.py to use `print` instead of `logging.info` (My notes: "I noticed that, when multiple features were run in the same batch, if logging.info was used in the setup and teardown steps in environment.py, after the first feature file had completed running, all the logging got sent to the console for subsequent features, rather than staying invisible, as it should by default ... I don't entirely understand why this is, but it's caused by the magic that Behave does to capture (or not) stdout in different circumstances, and the fact that we're working against this. Using print instead of logging.info in environment.py gets the logging in the console behaving [so that] there is a way for builds to get full console logging of this in the context of the scenarios/steps being executed, alongside JUnit test summaries.")

I wouldn't _recommend_ doing this because it's pretty hacky and doesn't give ideal results, but maybe someone more knowledgeable can jump in and tell us both how to do something similar-but-better.

**Comment by dani29** [comment]
@BrambleRamble thanks a lot for the recipe. I'll give it a try!

**Comment by BrambleRamble** [comment]
@dani29 You're welcome! I hope it's of some use. Calling it a recipe _may_ be on the optimistic side ;-)

**Comment by dani29** [comment]
I ended up doing the following, in case it's useful for @BrambleRamble or anyone else.

I pass junit=true in my behave.ini file, and in `before_all()`, I patch the runner's CaptureController to actually stop capturing the log, stdout and stderr. Afterwards, I setup my own logger and happily live thereafter.

```
def before_all(context):
    context._runner.teardown_capture()
    context._runner.capture_controller.stdout_capture = sys.stdout
    context._runner.capture_controller.stderr_capture = sys.stderr

    logging.shutdown()
    logging.basicConfig(
        level=logging.INFO,
        format="[%(asctime)s] %(levelname)s [%(name)s."
               "%(funcName)s:%(lineno)d] %(message)s",
        datefmt="%H:%M:%S"
    )
```

This works well even with hooks like `ipdb.post_mortem()` after failed steps, which is very nice.
