### ISSUE TITLE
API for extending automatic step generation?

### ISSUE THREAD

**Issue by nataliazon** [behave/behave#696]
Hi,

Is there any way in behave for the user to extend the automatic step generation code?

For example, depending on the text in the gherkin step definition, I would like it to have a specific implementation. Right now I'm doing it by copy-pasting the steps skeletons which behave generates for unimplemented steps and then parsing those to add bits and pieces where needed. But, I'd like this to be handled automatically rather than having to copy and paste the steps skeleton code from console output, and then having to use my own parsing code to know where to add specific lines.
The parsing of gherkin is somewhere in behave (I haven't looked in the source of behave - I'd rather just use the API). Is there any API provided for this purpose?

**Comment by jenisys** [comment]
The step snippets for missing steps is a convenience feature for **LAZY PEOPLE** (like you and me ;-)). You cannot provide a generic implementation that can be right for everyone. But it already provides a good skeleton what you need.

This said: Why are you not using [behave.contrib.formatter_missing_steps.py](https://github.com/behave/behave/blob/master/behave/contrib/formatter_missing_steps.py) or providing your own formatter that does the same or something similar ?

**Comment by jenisys** [comment]
@nataliazon 
Resolved ?
