### ISSUE TITLE
Clean exit when resource errors occur during a behave test run

### ISSUE THREAD

**Issue by lhaskins** [behave/behave#697]
During our behave test runs in our CI environment, we have occasionally have resource errors that causes behave to crash with the following traceback:

```
06:12:57 Traceback (most recent call last):
06:12:57   File "/usr/local/bin/behave", line 11, in <module>
06:12:57     sys.exit(main())
06:12:57   File "/usr/local/lib/python2.7/dist-packages/behave/__main__.py", line 183, in main
06:12:57     return run_behave(config)
06:12:57   File "/usr/local/lib/python2.7/dist-packages/behave/__main__.py", line 127, in run_behave
06:12:57     failed = runner.run()
06:12:57   File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 804, in run
06:12:57     return self.run_with_paths()
06:12:57   File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 824, in run_with_paths
06:12:57     return self.run_model()
06:12:57   File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 626, in run_model
06:12:57     failed = feature.run(self)
06:12:57   File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 321, in run
06:12:57     failed = scenario.run(runner)
06:12:57   File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 1114, in run
06:12:57     failed = scenario.run(runner)
06:12:57   File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 711, in run
06:12:57     if not step.run(runner):
06:12:57   File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 1379, in run
06:12:57     formatter.result(self)
06:12:57   File "/usr/local/lib/python2.7/dist-packages/behave/formatter/pretty.py", line 151, in result
06:12:57     self.stream.write(indent(step.error_message.strip(), u"      "))
06:12:57   File "/usr/lib/python2.7/codecs.py", line 370, in write
06:12:57     self.stream.write(data)
06:12:57 IOError: [Errno 11] Resource temporarily unavailable
```

As a result of this crash, the reports are generated based on the features that have been completed before the crash. This causes some false positives in our test suite. 

Ideally, if behave crashes, there will be some sort of error instead of just a traceback.

**Comment by jenisys** [comment]
Mmh, I disagree. If you would see only the last line what would you do or understand ?!?
What are you doing with your platform or environment that something like that happens ?
Either you are running out of space in your filesystem or RAM disk or ... 

If a python program exits w/ an exception traceback, the result code of the program is not 0 (zero).
Therefore, the test run has failed. Most CI systems that I know are able to detect that.
So, why are there any false positives ?!?

**Comment by lhaskins** [comment]
Yes, I agree that the exit code will be non-zero and that our CI system should catch when these failures occur. That said, it would be nice to have the reports generated contain the test case that caused the failure.

**Comment by jenisys** [comment]
Is the  "IOError: [Errno 11] Resource temporarily unavailable" caused by a test or by some other conditions on your platform environment ?

Meaning, the formatter fails because it cannot write to the output (file).
Therefore, you want to know the problem location on the console output ?!?
But you can already inspect the formatter output on the console before the exception was thrown.
That should indicate how far you have come in the execution of your test run.
That should make it rather easy to understand where the problem occurred.
