### ISSUE TITLE
Is it possible to access variable's value in table?

### ISSUE THREAD

**Issue by aliabbasrizvi** [behave/behave#698]

**Comment by aliabbasrizvi** [comment]
Hi

I am wondering if I can have a table which references a variable. For example if I have a value stored in `test_variable`, I can reference it in a step like `$test_variable`, but I want to use it's value in a table for it to be something like this in a step:

```
And I have data
    |  variable_key  |  variable_value  |
    |  test_var         |  $test_variable   |
```

Please let me know.

**Comment by jenisys** [comment]
How you interpret the data table in the step implementation is up to you (the step implementer).
Therefore, in principle you can do that. The cell of table row is passed into the step as string.

You need to define where you get the placeholder value from.
For example from:

* an environment variable
* a userdata value (in behave)
* the context object
* or a mixture of several or all possibilities above

You could for example use a data type to perform the placeholder retrieval

```python
from parse import Parser, with_pattern
from parse_type import TypeBuilder
from behave import step

@with_pattern(r'\$\w+')
def parse_placeholder(text):
    assert text.startswith("$")
    text = text[1:]    # Strip leading dollar-sign (placeholder-marker)
    return os.environ.get(text, None)

@with_pattern(r'.*')
def parse_anything(text):
    return text.strip()

parse_placeholder_or_text = TypeBuilder.make_variant([parse_placeholder, parse_anything])
cell_parser1 = Parser("{variant:PlaceholderOrText}", 
                      dict(PlaceholderOrText=parse_placeholder_or_text))

@step(u'I have data')
def step_i_have_data(context):
    assert context.table, "ENSURE: Data table is provided."
    for row in context.table:
          cell_text = row["variable_value"]
          cell_value = cell_parser1.parse(cell_text)
          ... # Process cell_value
```

SEE ALSO:
* https://github.com/jenisys/parse_type
