### ISSUE TITLE
setup_logging disables all existing loggers silently

### ISSUE THREAD

**Issue by rafalslaby** [behave/behave#702]
Behave 1.2.6
setup_logging called as presented in docstring:
```
def before_all(context):  
    context.config.setup_logging()
```
with configfile subsequently calls:
`fileConfig(configfile)`
which silently disables all existing loggers.
Some seemingly random loggers will be disabled making it really hard to track the reason.
Loggers that happened to be created before before_all which is quite common since:
`logger = logging.getLogger(__name__)`
at gobal level in module or in __init__.py is a common pratice.

It's actually not a bug, but it may discourage many programmers from using logging module with behave after hours of investigating why some loggers doesn't work.
Just make it more explicit that existing loggers will be disabled by simply allowing to pass that flag as false to setup_logging.

**Comment by jenisys** [comment]
Well, any logging setup logic that I know does exactly that.
In your opinion, where should existing loggers come from before `before_all()` hook ?!?
(and I already probably know the answer; but you are mistaken or you have bad-behaving module setups, etc.)

NOTE: This is specific to the `logging` module.
For example, you can call `logging.basicConfig(...)` many times with different parameters.
But only the initial call does what you think it should do. All the other calls and their parameters are ignored after you have setup the logging module/subsystem.

**Comment by jenisys** [comment]
@rafalslaby 
How many such logger objects do you have that get initialised when a module is imported ? 
(as module global data)

**Comment by rafalslaby** [comment]
Only one for now, but i get the point. If any existing logger is not configured in config file then it will be disabled. Seems the problem was the lack of experience with python logging.
