### ISSUE TITLE
Formatter printing colored step lines twice in CI

### ISSUE THREAD

**Issue by zhammer** [behave/behave#703]
Weirdly on my circleci builds,  when I run behave tests with color, the default output formatter prints out each step-line twice, first without color (and weirdly without timing info) and the second time with color and timing info.

Has anyone run into this before? It's not a crucial bug but it would be nice to have color reports without double prints.

### Standard run with color (every second step line is green)
```
#!/bin/bash -eo pipefail
pipenv run behave --junit --junit-directory=test-results/behave
Feature: Submit a listen to morning_cd # tests/behavioral/submit_listen.feature:1

  Scenario: I submit a valid song to morning.cd during the day                # tests/behavioral/submit_listen.feature:3
    Given my name is "Zach"                                                   # tests/behavioral/steps/submit_listen.py:22
    Given my name is "Zach"                                                   # tests/behavioral/steps/submit_listen.py:22 0.000s
    And I live in new york                                                    # tests/behavioral/steps/submit_listen.py:27
    And I live in new york                                                    # tests/behavioral/steps/submit_listen.py:27 0.000s
...
```

### With `--no-color`
```
#!/bin/bash -eo pipefail
pipenv run behave --junit --junit-directory=test-results/behave --no-color
Feature: Submit a listen to morning_cd # tests/behavioral/submit_listen.feature:1

  Scenario: I submit a valid song to morning.cd during the day                # tests/behavioral/submit_listen.feature:3
    Given my name is "Zach"                                                   # tests/behavioral/steps/submit_listen.py:22
    And I live in new york                                                    # tests/behavioral/steps/submit_listen.py:27
...
```

### With `--no-timings` (every second step-line is green)
```
#!/bin/bash -eo pipefail
pipenv run behave --junit --junit-directory=test-results/behave --no-timings
Feature: Submit a listen to morning_cd # tests/behavioral/submit_listen.feature:1

  Scenario: I submit a valid song to morning.cd during the day                # tests/behavioral/submit_listen.feature:3
    Given my name is "Zach"                                                   # tests/behavioral/steps/submit_listen.py:22
    Given my name is "Zach"                                                   # tests/behavioral/steps/submit_listen.py:22
    And I live in new york                                                    # tests/behavioral/steps/submit_listen.py:27
    And I live in new york                                                    # tests/behavioral/steps/submit_listen.py:27
...
```

**Comment by jenisys** [comment]
Use another formatter, for example `plain`.
The `pretty` tries make things "pretty". Therefore, it makes two passes when a step is run:

* Pass one: Before the step is executed (normally in grey)
* Pass two: After the step is executed, the step result and the step duration is known (normally in free/red)

NOTE:
* Your terminal is lacking ANSI escape sequences or you are using some kind of pipe mechanism.
Or the cursor-up ANSI escape sequence is not handled correctly.
* These two passes of the `pretty` formatter are normally only noticeable if a step takes rather long to execute.
* If you use `--no-color` option on command-line, you basically disable the two-pass mode of the formatter. It uses only one pass (after the step result is known).

**Comment by zhammer** [comment]
Ah that makes sense. Thanks for the quick / clear response

**Comment by zhammer** [comment]
Out of curiosity, is there any current option to run the `pretty` formatter and only perform the second pass? Or would that require a custom formatter (at least at the moment)

**Comment by jenisys** [comment]
You have already used only the second pass by using the `--no-color` option.

**Comment by jenisys** [comment]
You are assuming too much. That would be nice, therefore it is not implemented
 that way (just joking). 

The easiest solution is to provide your own formatter w/ the suggested functionality (and use an alias in the config-file to use it with `behave -f pretty ...` on your CI server).

**Comment by zhammer** [comment]
ha yeah i'm going to look into custom formatters when i have some time. it seems like this is also the issue at hand in https://github.com/behave/behave/pull/592.

appreciate the responses.
