### ISSUE TITLE
Formatter processing logic is different than what is in base.py

### ISSUE THREAD

**Issue by schidlo** [behave/behave#704]
Currently in behave/formatter/base.py in class Framtter is defined processing logic. But when I run formatter (for example pretty) the logic is different.
The part `for step in scenario.all_steps:...` it is run like this:
First for all steps the step function is called. Then for every step is called match->match.run->result.
e.g.: For steps first, second, third:
step(first)
step(second)
step(third)
match(first)
result(first)
match(second)
result(second)
match(third)
result(third)

**Comment by schidlo** [comment]
Thank you for your answer. If it's intended, then I can close this.

**Comment by jenisys** [comment]
@schidlo 
A final comment. I know that this behaviour is weird when you begin to understand what is happening. But it the reason why it is done this way is the following: The formatter gains knowledge of all the steps in a scenario before the scenario is executed (meaning the steps in it). When the scenario is executed and a step fails, the remaining steps are not executed. But the formatter can still show the them (and there step.status) to indicate what has happened.
