### ISSUE TITLE
[Question] Is it possible to run behave tests in parallel mode with python 3.7 and allure report?

### ISSUE THREAD

**Issue by testingplusme** [behave/behave#710]
Hey Guys,
Is it possible to run behave tests in parallel mode with python 3.7? 
Do you have any solution for this? Or only it's possible on python 2.7?
Also, I have a question about Allure with behave. Is it possible run behave in parallel mode with Allure report?

Cheers,
Michał

**Comment by jenisys** [comment]
Yes, we can: if you make the parallel runner work ;-)

NOTES:
* `behave` can be used in Python 3.7 without any problems (see: Travis CI)
* the `AllureFormatter` should work AFAIK, but I am not the maintainer of the `AllureFormatter`
* `behave` has currently no parallel-runner. But there is a branch provided by others. Just try it out and use it if it works for you.

**Comment by xrg** [comment]
I'd be happy if you tried the PR #616 branch, which should work with any output plugin.

**Comment by testingplusme** [comment]
@xrg I'am happy to try. What should I do after clone? only `python setup.py install ` or maybe something else?

**Comment by xrg** [comment]
@testingplusme Yes, just a standard `setup.py install [options]` should do. Then try running in parallel with `behave --processes N`

**Comment by mcadam** [comment]
Hi @xrg thank you for your PR, its working pretty well but I am also using Allure reporting to have nice report in Jenkins and your parallel implementation seems to break those.
Could you take a look?

Cheers,
Adam

**Comment by xrg** [comment]
Hi @mcadam . Can you please post some information (or contact me in private), about the breakage? I may not have the time to fully replicate your setup, but hopefully I could answer if I got something like a traceback or error message...

**Comment by testingplusme** [comment]
@xrg  I think that it can be as the same issue which had @mcadam  I reported to allure-python https://github.com/allure-framework/allure-python/issues/321 in a nutshell allure-results is creating empty when is running on parallel mode without it works correctly.

**Comment by xrg** [comment]
Indeed, I had a peek at 'behave-allure's source code. The problem is in that implementation, in 'listener.py'. There, 'allure' tries to hook into the running scenarios or features, in order to collect their output. This won't work for anything but a single local process.

**Comment by xrg** [comment]
After this /quick/ look, I can only expect that 'listener.py' would need rewritting, so that it becomes an output plugin of behave. Doable, but not a quick fix.
In the meantime, I'm personally using the JUnit report and it works fine.

**Comment by mcadam** [comment]
Cool thanks, I will check and maybe switch to JUnit reports for the speed of it, even though Allure are quite nice :)

**Comment by johnprakashgithub** [comment]
@mcadam I tried the PR #616 and not able to execute behave parallel in python 3.7. You were able to get it working in python 3.7?

**Comment by johnprakashgithub** [comment]
@xrg behave parallel is working fine in python 2.7. 
I have a queue of the resources with thread lock accessed by parallel features. Each of these concurrent feature accessing this queue always returns with the first element of the queue. However, I want them to access each element in the queue. How can I get access to feature thread in the step implementation?

**Comment by xrg** [comment]
@johnprakashgithub Some initial tests had shown that parallel from #616 would be compatible with python3.x . However, due to some specifics of my own project, I am doing all development still against 2.7. If you have any particular finding against 3.7, please share and I will be happy to resolve it, make the patch fully 3.7 compatible.

**Comment by xrg** [comment]
@johnprakashgithub About the "shared queue". I think locks can *not* be shared across processes (as in the parallel ones). But queues can. 
In my design (parallel of #616), there is a queue of work items (either features or scenarios, as per the arguments), from which the children workers can pick one item at a time (never the same one). 
This is achieved by the `multiprocessing.Queue` , which syncs its state (remaining items) across the sub-processes. A standard `queue.Queue` would be copied to sub-processes, yielding all of the items to each process. I believe in your case you can use the `multiprocessing.Queue` for any kind of resource you want to share among the parallel workers.

**Comment by Bidonus** [comment]
@johnprakashgithub Hi ! I have same question as you about accessing unique element for each process. DId you make it ? Can you tell me about your experience ?

**Comment by masudr4n4** [comment]
What is the final answer for this issue so far?

**Comment by hrcorval** [comment]
If you are using the Behave framework for your automated testing, and need to run your tests in parallel, or want easy to read HTML test execution reports, I highly recommend checking out the BehaveX library. BehaveX is a wrapper that extends the Behave framework with additional features that can significantly improve the performance of your test suites, like the following ones:
* Parallel test execution for improved performance
* Easy-to-read HTML test execution reports with embedded test metrics (Automation Rate, Pass Rate and Steps Executions|Duration|Reusability)
* Test logs per scenario
* Mute test scenarios in build servers
* Improved dry runs: See the full list of scenarios in an HTML report
* Re-execute failing test scenarios
Additional information:
* BehaveX is open source and available on GitHub: https://github.com/hrcorval/behavex
* BehaveX is compatible with Behave v1.2.6.
* BehaveX is tested on Windows, macOS, and Linux.
