### ISSUE TITLE
Is it possible to group steps into classes? 

### ISSUE THREAD

**Issue by zahessi** [behave/behave#711]
Hi. Is there a way to group steps definitions instead of stand-alone functions into the classes like 

```
class StepsHolder:
    @step("I make a request")
    def step_impl(context):
    ....

    ....
```

**Comment by spyoungtech** [comment]
Class-based definitions are not currently part of `behave`.

Is there a problem you're trying to solve or a particular goal you're trying to achieve with classes?

I've written a small extension called [`behave-classy`](https://github.com/spyoungtech/behave-classy), which provides an API for class-based step definitions, which may be useful to you.

**Comment by jenisys** [comment]
@zahessi 
Could you explain why (you think) you need it ?

**Comment by zahessi** [comment]
I think that class-based definitions are more readable and convenient. If the library doesn't provide this opportunity, it's OK, I was just exploring.

**Comment by jenisys** [comment]
@zahessi 
Sorry, currently not supported except in @spyoungtech extension.
I just wanted to know if you have a compelling reason for class-based steps.

At least for me it is readable but I group my steps in functional step-modules.
In addition, I have normally not more than 20 steps per step-module/file.
If you have considerably more steps per file, either split them up into multiple files or have a look @spyoungtech 's extension.
