### ISSUE TITLE
Make a scenario outline with dynamic examples

### ISSUE THREAD

**Issue by Tiagojdferreira** [behave/behave#714]
I have recently written a test where I go to all the urls in my django app and test that they load without any javascript errors and without a 404. To do this I had to do a scenario with a main step:
```
@then('I should test pages are not 404')
def step_page_works(context):
    pages_to_test = ...
    for page in pages_to_test:
        context.execute_steps(
                """
            When I visit "{page}" page
            Then I should see the page loaded
            And the "{page}" has no javascript errors
        """.format(page=page)
        )
```
And my test looks like:
```
Scenario: Anonymous user navigates pages with no arguments
    Then I should test pages are not 404
```

Ideally I would use a scenario outline with a decorator to give the variables. (or something else similar, that would allow to set the examples to use in this scenario outline)
```
@examples_pages_to_test
Scenario Outline: Anonymous user navigates to pages
    When I visit "<page>" page
    Then I should see the page loaded
    And the "<page>" has no javascript errors
```

**Comment by jenisys** [comment]
The solution for you right now is to generate the Feature files with a template-engine, like Jinja2.

There is a solution in the works that does what you indent to do by generating/loading data for the `Examples` table of a `Scenario Outline`.

SEE ALSO: 
#707 and the related referenced issues.

**Comment by jenisys** [comment]
reopen
