### ISSUE TITLE
Can not use Step Parameters

### ISSUE THREAD

**Issue by Lanuet** [behave/behave#716]
I following this instrucstion [Use Step parameters](https://github.com/behave/behave/blob/master/docs/tutorial.rst#step-parameters) 
My code:

**Feature:**
```gherkin
Scenario: Check Teko Accounting page
  Given Login to FM system
  When Click Teko Accounting
  Then Validate text "Bank statements" appeared
```
**Steps:**
```python
@then('Validate text "{text}" appeared')
def step_impl(context, text):
    text_is_displayed(context, text)
```
But when i run feature file, I received a notification that my steps "Then Validate text "Bank satements" appeared" is undefined

Anyone can help me?
Thanks

**Comment by Lanuet** [comment]
Hi @jenisys:
**Features file**:  My projects/finance/features/test.feature
**steps file**: My projects/finance/features/steps/test.feature
Other steps like (Given, when) can found step action, only step uses 'Step Parameters' can not.
I dont think it's the cause.

**Comment by jenisys** [comment]
Step files end with „*.py“ and not with „*.festure“.

**Comment by Lanuet** [comment]
ah yes, of course steps files end with **.py, sorry Im mistake.
Any idea for this problem?

**Comment by jenisys** [comment]
Use the https://github.com/behave/behave.example repository. It provides executable examples. Then check what you did differently. The only things that I can think of is that your steps module contains invalid Python code and cannot be imported.

**Comment by Lanuet** [comment]
Hi @jenisys 
i found the cause
By default, I'm using use_step_mathcer("re") so steps cannot match steps. 
i must use use_step_matcher("parse") or nothing.
Thank u for your reply
