### ISSUE TITLE
Broken links under behave/doc

### ISSUE THREAD

**Issue by ki4070ma** [behave/behave#719]
I found some broken links in [behave/docs/gherkin.rst](https://github.com/behave/behave/blob/master/docs/gherkin.rst).

E.g.
* .. _`Python step implementations`: tutorial.html#python-step-implementations
* .. _`environmental controls`: tutorial.html#environmental-controls
* .. _`configuration file`: behave.html#configuration-files

These should be rst, not html.
I didn't check other rst files.

**Comment by jenisys** [comment]
See reason in #720.
