### ISSUE TITLE
Call step by method signature, it is ok?

### ISSUE THREAD

**Issue by Free1man** [behave/behave#721]
HI Behave Team,
As I know I can call step as part of another step like that:

```
@step("I can confirm that details are saved in my profile")
def step_impl(context):
    context.execute_steps(u"""
            given I can confirm that I can login
        """)
```

but from a maintenance perspective, it is not very fun for me (this Christmas I refactored all our tests and I found it painful navigate steps)

so I found that I can do that: 
```
@step("I can confirm that details are saved in my profile")
def step_impl(context):
     step_impl_with_some_name(context)
```
So I prefer last option because of it easier to refactor and navigate code.  
Any problem with that approach, it is fully supported? I was unable to find the answer in the documentation.  

Thanks,
Ilia.

**Comment by jenisys** [comment]
Yes, you can directly call the step functions.
But for this, the step-function must be in the same file or be imported.
Therefore, you get a dependency to the python module that implements the step-function.
HINT: Avoid cyclic import dependencies between to step modules.

The advantage of the `context.execute_steps()` is:

* Simpler to write and understand when multiple steps are used (as step-script/macro)
* You decouple yourself from where the step-function is implemented.
* Step-function lookup is delayed until runtime (later than by direct call to step-function).

`behave4cmd0` module uses the direct calls of step-functions extensively.

SEE ALSO:
* [behave4cmd0/command_steps.py](https://github.com/behave/behave/blob/master/behave4cmd0/command_steps.py#L158)

**Comment by Free1man** [comment]
Thanks for the answer :+1:
