### ISSUE TITLE
Docs support Chinese?

### ISSUE THREAD

**Issue by 9468305** [behave/behave#723]
Hi guys,
Do you have plan to support Chinese docs on https://behave.readthedocs.io ?
Thanks.

**Comment by jenisys** [comment]
@9468305 
Do you mean a Chinese translation of the `behave` documentation ?!?
No, this is currently not planned 
(but the same is true for other languages, like: French, German, Spanish, ...).

Are you willing to provide (and maintain) the Chinese translation of the documentation ?
But that would also mean that you are willing to maintain the Chinese pages when changes in the documentation occurs.

**Comment by jenisys** [comment]
@9468305 
We basically need to insert a language level below docs, like:

```
BEFORE:
  behave/
    +-- docs/

AFTERWARDS: With support for multiple languages
  behave/
    +-- docs/
    |       +-- en/                        -- BEFORE: behave/docs/*.rst in English. 
    |       +-- zh-CN/ 
```

But let me check with readthedocs 
(that will automatically rebuild the docs when the git repo changes).

**Comment by jenisys** [comment]
@9468305
OK, I prepared the basics.

WORKFLOW:

* Generate or update the messages/message-catalog under: `locale/<LANG>/LC_MESSAGES/*.po`
* Fill out the message translations in the `*.po` files for a language
* Build the sphinx docs for this language

WORKFLOW EXAMPLE:
```bash
# ASSUMPTION: Use the current tip of the behave repository.
# ONCE: Install sphinx-intl, etc.
pip install -U -r py.requirements/develop.txt

# -- STEP 1:
# OR: Adapt "invoke.yaml" => sphinx.languages: Add or uncomment item
invoke docs.update-translation     #< Update all languages
invoke docs.update-translation --language=<LANG>  #< Update only one language: <LANG>="zh-CN"

# -- STEP 2: Manually make the translation in the "*.po" files
# -- STEP 3: Generate sphinx-docs for this language to: "build/docs/html/<LANG>/"
invoke docs --language=<LANG>
```

OPEN ISSUES:
* Build docs (and translations) w/ https://readthedocs.org

**Comment by NEOOOOOOOOOO** [comment]
@jenisys & @9468305,

I am willing to join the Chinese translation task, please let me know if there is anything I can do.

Regards.

**Comment by jenisys** [comment]
@NEOOOOOOOOOO 
Follow the workflow that is described above.
Provide the translations as pull-request: `locale/<LANG>/LC_MESSAGES/*.po`
Let me know if anything else is needed
