### ISSUE TITLE
Scenario Outline description lines seem to be ignored

### ISSUE THREAD

**Issue by nizwiz** [behave/behave#725]
If a feature file contains description lines for a scenario outline (i.e. free-form text lines following the "Scenario Outline:" header), they do not seem to be taken over into the description attribute of the created Scenario model objects (in contrast to ordinary scenarios). Consequently, the description lines also do not appear in the files created by formatters (though I can only speak for the json formatter, as that is the only one I tried).

**Comment by jenisys** [comment]
You are right. 
The ScenarioOutlineBuilder did not copy the the `description` to the created scenarios.

**Comment by jenisys** [comment]
INTEGRATED INTO: behave-1.2.7.dev0
TODO: Provide a test for it.
