### ISSUE TITLE
How to rerun the failures in the python behave 

### ISSUE THREAD

**Issue by writetomaha14** [behave/behave#728]
Hello All,

Can anyone tell me how to re-run the failures in Python behave. 

I want to re-run the failed test cases automatically.

behave.ini file contains
# -- file:behave.ini
[behave]
format   = rerun
outfiles = rerun_failing.txt

post execution i did try to execute using the command behave @rerun.txt

I am getting the error message as

FileNotFoundError:rerun.txt

Any help would be appreciated. 

Thank you.

**Comment by jenisys** [comment]
If you use the outfield name "rerun_failing,txt", you must use:

```sh
behave @rerun_failing.txt
```

or you must use:

```ini
[behave]
format = rerun
outfiles = rerun.txt
```

**Comment by writetomaha14** [comment]
this file is not getting generated, getting the error message as FileNotFoundError:rerun.txt

**Comment by jenisys** [comment]
@writetomaha14 
Behave is an obedient tool. It only does what you tell it to do.
You are probably missing the information in "behave.ini".

SEE:
* [behave.ini](https://github.com/behave/behave/blob/master/behave.ini)
* [features/formatter.rerun.feature](https://github.com/behave/behave/blob/master/features/formatter.rerun.feature#L194)
