### ISSUE TITLE
Cannot process both --format and --output in one command

### ISSUE THREAD

**Issue by brianbartilet** [behave/behave#729]
--format takes precedence in execution and there is no way to have both.

using this formatter:
https://pypi.org/project/behave-teamcity/

**Comment by jenisys** [comment]
@brianbartilet 
Sorry, this statement is wrong. 
`format(ter)` and `output` (for the formatter) come in pairs.
Only the last format statement (normally) on command-line, can have an optional `output`.
If it is missing, stdout will be used.

WRONG REPOSITORY:
You need to add this issue in: https://github.com/iljabauer/behave-teamcity
