### ISSUE TITLE
Get feature file name from step function

### ISSUE THREAD

**Issue by redsox10** [behave/behave#730]
Hi,

Is there a way to get the name of the feature file (gherkin) from inside a step function that is being invoked?

**Comment by attilammagyar** [comment]
There is, e.g:

    @when('foo')
    def step_foo(context):
        assert context.feature.filename == 'bar', context.feature.filename

See the the docs for the [`context`](https://behave.readthedocs.io/en/latest/context_attributes.html#behave-attributes) and the [`Feature`](https://behave.readthedocs.io/en/latest/api.html#behave.model.Feature.filename) class.

**Comment by jenisys** [comment]
@attilammagyar 
Well answered.
