### ISSUE TITLE
Logging level being ignored

### ISSUE THREAD

**Issue by ethagnawl** [behave/behave#732]
I'm unexpectedly seeing the following log entries (INFO, WARNING) while running my behave suite inside a [Djangae](https://github.com/potatolondon/djangae) project with logging_level set to FATAL.

```
cat behave.ini
[behave]
logging_level=FATAL

source ~/environments/foo-2.7/bin/activate && django_env=test python manage.py behave --verbose
INFO     2019-03-15 11:07:40,848 blobstore_service.py:74] Starting blobstore service on localhost:8080
Creating test database for alias 'default'...
Loading config defaults from "./behave.ini"
Using defaults:
 logging_format %(levelname)s:%(name)s:%(message)s
          color True
   default_tags
   show_timings True
 stderr_capture True
          stage None
       userdata {}
  steps_catalog False
        dry_run False
 stdout_capture True
          junit False
    log_capture True
        summary True
more_formatters {}
   show_skipped True
  show_snippets True
 default_format pretty
  logging_level FATAL
scenario_outline_annotation_schema {name} -- @{row.id} {examples.name}
    show_source True
Using default path "./features"
Trying base directory: /home/me/projects/foo/features

Feature: Foos # features/foos.feature:1
WARNING  2019-03-15 15:07:43,210 middleware.py:131] settings.CSRF_COOKIE_SECURE is not set to True, this is insecure
WARNING  2019-03-15 15:07:43,211 middleware.py:131] settings.SESSION_COOKIE_SECURE is not set to True, this is insecure

  Scenario: View foos       # features/foo.feature:3
  ...
WARNING  2019-03-15 15:10:50,089 middleware.py:91] SECURITY : fetching non-HTTPS url 'http://localhost:8080/_ah/gcs/foos/49/foos/None/example.jpg'
  ...
```

It's probably worth noting that I see the same behavior as the above when using command line flags. (It's also very possible this issue is the result of end user error or an unexpected interaction with Behave Django.)

Relevant Environment:
Python 2.7.13
Behave 1.2.6
Behave Django 1.1.0
Django 1.11.20
Djangae 0.9.11

**Comment by jenisys** [comment]
If you provide a ``before_all()`` hook (in the "features/environment.py" file) or injected somehow,
you currently need to setup the logging subsystem in this hook (because it can only be set once):

```python
# -- FILE: features/environment.py
def before_all(context):
    context.config.setup_logging()
```

SEE ALSO:
* [features/logging.setup_level.feature](https://github.com/behave/behave/blob/master/features/logging.setup_level.feature)
* [behave/configuration.py: Configuration.setup_logging() description](https://github.com/behave/behave/blob/master/behave/configuration.py#L721)

**Comment by ethagnawl** [comment]
Thanks for following up, @jenisys. 

Unfortunately, calling this method in my `before_all` hook (w/wo passing a `level`) has no effect.

**Comment by jenisys** [comment]
@ethagnawl 
This normally indicates that the logging module is already setup by code that is executed before the hook above is called. See `logging.basicConfig()` methods.
You should see at least that the root-logger has the desired/configured log-level.

HINT: `logging.fileConfig()` overrides any pre-configured log handlers, `logging.basicConfig()` preserves pre-configured log handlers and ignores the new configuration.

**Comment by ethagnawl** [comment]
Thanks for following up @jenisys. I'm no longer working on the project using Behave on a daily basis, but I'll try to investigate using your suggestions when I can find some time.
