### ISSUE TITLE
Debugger (sset_trace) generate signal SIGSEGV

### ISSUE THREAD

**Issue by dunossauro** [behave/behave#736]
I upgraded to 1.2.6

Using breakpoint sset_trace or spost_mortem, when debugger call stdout to write anything in shell, behave fails

Example:
```
     """
      user = {
          'username': 'test',
          'password': '1234'
      }
      """

> ....py(6)check_user_in_data_base()
      4 @given('...')
      5 def check_user_in_data_base(context):
----> 6     assert False

ipdb> context

fish: 'behave tests/behavior_tests/fea…' terminated by signal SIGSEGV 
```

I'm using python 3.7.2, behave 1.2.6, ipdb 0.12, ipython 7.4.0

If needs more data i can send to you

**Comment by jenisys** [comment]
HINT: Entering the debugger while behave is in captured mode is tricky, because the normal file handles are redirected to the captured streams. When you debug steps, you are normally in captured mode.

Try to use/enter the debugger while running behave in non-captured mode.
