### ISSUE TITLE
No content in the results.log 

### ISSUE THREAD

**Issue by jpatel13** [behave/behave#737]
I have the following in the before_all() function in my environment.py: 
<pre><code>
  context.config.format = ['pretty'] #,'allure_behave.formatter:AllureFormatter']
     context.config.summary = True
     context.config.outfiles = ['results/result.log']
     context.config.outputs = [StreamOpener('results/result.log').open()] //have to .open() otherwise stream not openned and file not created 
     context.config.reporters.append(SummaryReporter(context.config))
     set_environment(context)
</code></pre>
Expected: The result.log file should be populated with details of the test run 

Actual: The result.log file is empty 

Note if I pass in via command line I get expected result, but I need to create timestamped folders and store the report in the corresponding folder.

**Comment by jpatel13** [comment]
I also noticed that the configuration object when initialized has a SummaryReporter which takes in a configuration object which in turn has a SummaryReporter ... and so on is there a reason for this?

**Comment by jenisys** [comment]
The `before_all()` is before the test-run.
The `result.log` is opened by the formatter that writes to it (or uses it as output stream).

I am not quite sure, if I understand you correctly.
You are trying to configure formatters, etc. in the `before_all()` ?
This hook is not intended for this kind of functionality.
Use a build-script that calls `behave`, for example `invoke`.

**Comment by jpatel13** [comment]
Hi jenisys,  
    I agree with what you are saying but I was looking for a way to do it without using a build script. I managed to get it working from the before_all()  but will eventually move to a build script.
 Thanks!
