### ISSUE TITLE
Scenarios are skipped in report if letters NA are in the name

### ISSUE THREAD

**Issue by peter-kinzelman** [behave/behave#738]
I have a parallel test runner that runs a handful of Scenarios in parallel. It reads through a Feature file and runs each Scenario independently. Noticed something very strange going on. At first i thought it was the ( ) parens i had in the name. 
Prereqs: 

- Capability for parallelized tests
- Run tests with flag: **-f allure_behave.formatter:AllureFormatter**
- Run tests with flag: **-o some/output/dir**
- Allure installed locally

Steps: 

In a Feature file:
- Create a Scenario with the name "Some New Test NA" 
- Create a Scenario with the name "Some New Test ()" 
- Create a Scenario with the name "Some other - test" 
- Run tests
- Copy path of output directory from abovec
- cd to bin of local Allure install, **allure serve {path copied from above}**

Actual Behaviour: 2/3 tests are listed in test report 

Repeat steps above excpet remove NA from first Scenario name. 

Actual Behaviour: 3/3 tests are listed in test report

**Comment by jenisys** [comment]
Behave does not support parallel testing, yet.
Therefore, I assume that the failure location resides in the parallel test runner that you are using.
