### ISSUE TITLE
JSON Formatter: —no-timings/-T option is not working

### ISSUE THREAD

**Issue by CollinRea** [behave/behave#739]
Hey Team,

Our command:

behave -T -f json.pretty -o output.json 

Is still showing durations in the output, which is causing issues on our side with some Json Validations, since we covert our behave reports into cucumber reports and cucumber does expects duration in nanoseconds.

Any reasons this would not be working?

**Comment by CollinRea** [comment]
A flag to possible change the duration format in the output would also solve the problem.

**Comment by jenisys** [comment]
Other possible solutions are: 
* Provide a pull-request that fixes the behaviour (in a sane way)
* Provide your own JSON formatter (and use it) or 
* fix the conversion tool

HINT: 
No-timings is really relevant for console output formatters, like: pretty, plain, ...
JSON is normally written to a file.

**Comment by xiaoxianma** [comment]
I will create PR to fix json format bug when flagging -T

**Comment by xiaoxianma** [comment]
this ticket is closed without fix merged
