### ISSUE TITLE
steps.usage formatter reports step as unused if used only in execute_steps()

### ISSUE THREAD

**Issue by snke** [behave/behave#741]
I was using the _steps.usage_ formatter with

 `behave --dry-run --no-summary -q --format steps.usage features/foo.feature`

and one step was reported in the _UNUSED STEP DEFINITIONS_ section of the formatter output.

That step is actually not unused, but is only used within a call of context.execute_steps().

Is this expected behavior?

**Comment by xrg** [comment]
I think this should be expected. It is not trivial to scan within python code for `context.execute_steps()` usage. You might also be doing something advanced, like::

    text = "When I perform this action"
    context.execute_steps(text)

which would then evade the scanner, you see...

**Comment by snke** [comment]
Your example makes sense, yes.

At first I thought that especially behave should have the possibility to know the "coverage" of the steps it has successfully reached/executed.
Maybe the "dry run" mode is the problem here? Because it does not actually execute steps.

**Comment by snke** [comment]
I think this a "won't fix" really. Closing this.
