### ISSUE TITLE
Importing local modules

### ISSUE THREAD

**Issue by retorquere** [behave/behave#742]
I have some code that I'd like to split off from `steps.py` for readability into a file called `zotero.py`. How should I import this? If I do `import zotero` I get `No module named 'zotero'`, but if I do `from . import zotero` (I'm using python 3.7) I get 

```
  from . import zotero
KeyError: "'__name__' not in globals"
```

**Comment by jenisys** [comment]
The seconds import syntax above is only valid within a python package. The step directory is not a python package. Therefore, you cannot use the syntax above.

But the step directory is inserted into the python search path while the steps are imported.

Use:

```python
import zotero
...
```

HINT: 
If that does not work for you or the python module is somewhere else, it indicates that your python search path is not setup correctly (or you the environment variable `PYTHONPATH=.` or similar). If you need to setup the python search path, do it in the "environment.py" file.

SEE ALSO:

* http://behave.github.io/behave.example/tutorials/tutorial03.html
* https://github.com/behave/behave.example
