### ISSUE TITLE
Separated only environment with parameter --stage=ci 

### ISSUE THREAD

**Issue by adaskow** [behave/behave#744]
Hi, 

I have a question about this option `--stage=<something>`.
I need a different `environment` file for CI - but with the same steps for now. I want to not duplicate `steps` directory to have also `ci_steps`. 

I sow that when I create `ci_environment.py` it is used when I run `behave --stage=ci` but there is a requirement to have different steps directory also.

Or maybe there is some different option to run tests without something in `before_all`/`after_all`

**Comment by jenisys** [comment]
The stage functionality currently requires that different step directories are used for each stage.
But the steps directory does not need to have the step implementations. It is possible to import the steps from somewhere else (step_library approach). Therefore, you can reuse steps but you need the glue code.

POTENTIAL SOLUTIONS:

1. Use the "stage" functionality and and provide steps directory for each stage that only import the steps (step_library approach).
2. Use the "stage" functionality and use symlinks to steps directory for each stage (would work on UNIX operating systems). Symlinks can be checked in if you use Git as version control system.
3. Do not use the "stage" functionality but a userdata variable (or environment variable) in the "environment.py" file to import the "stage environment file"
