### ISSUE TITLE
Enhancement: make it possible to add additional import paths via configuration

### ISSUE THREAD

**Issue by nizwiz** [behave/behave#745]
It would be nice to be able to configure additional import paths that are effective when executing environment.py / step definition files, via behave command line argument and / or config file or similar.

Let me elaborate why. Our test setup is somewhat like this:

```
test_root
    - bdd_lib
    |    - environments
    |    |    - common_env.py
    |    |    - special_env_1.py [from bdd_lib.environments.common_env import *; ...]
    |    |    - ...
    |    - steps
    |    |    - ...
    |    - helper_modules
    |    |    - ...
    - features
    |    - feature_area_1
    |    |    - environment.py [from bdd_lib.environments.common_env import *]
    |    |    - steps
    |    |    |    - use_step_library.py  [from bdd_lib.steps import foo_steps]
    |    |    |    - area_1_steps.py [from bdd_lib.helper_modules import foo_helpers]
    |    |    - test_data
    |    |    |    - ...  
    |    |    - some.feature
    |    |    - ...
    |    - feature_area_2
    |    |    - environment.py [from bdd_lib.environments.special_env_1 import *]
    |    |    - steps
    |    |    |    - use_step_library.py  [from bdd_lib.steps import foo_steps, bar_steps]
    |    |    |    - ...
    |    |    - some_other.feature
    |    - ...
```
So we need bdd_lib to be on the import path. However, we cannot use PYTHONPATH because we would like to use command line argument -E when invoking python to execute behave tests.
We have quite a lot of feature areas, consequently quite a lot of environment.py files that basically contain only an import statement. But since it is not possible to configure the import path, we have to add this to each one of those environment.py files:
```
  import sys
  import os
  sys.path.append(os.path.join(os.getcwd(), '../..'))
```

(The features are executed with their respective parent folder as cwd to be able to easily access local test data).

It is also conceivable that further step / environment libraries are installed completely elsewhere, which would make it even harder to use them.

**Comment by retorquere** [comment]
I can provide a PR for this if it's deemed desirable. I have a working implementation.

**Comment by jenisys** [comment]
Mmh, therefore you have Python path management (``PYTHONPATH``, ``sys.path``).

* The easiest solution for you is a small "my_behave" python script that setup the python search path correctly in your environment and runs `behave`.
* Use tools like [direnv](https://direnv.net) to setup your environment when you enter a directory.
* Use your own build-script to setup the python search path before you run `behave`
* ...

HINTS:
Use HERE idiom instead ``os.getcwd()``. 
Otherwise, the test run will break, if you execute it from another directory.

**Comment by odelucca** [comment]
> I can provide a PR for this if it's deemed desirable. I have a working implementation.

Hi! Can you provide it? I would appreciate this feature :)
