### ISSUE TITLE
IOError: [Errno 11] Resource temporarily unavailable

### ISSUE THREAD

**Issue by bharadwajambati95** [behave/behave#748]
The following traceback is found in the logs, once the behave test failed.

**Exception IOError: [Errno 11] Resource temporarily unavailable
23:40:31 Traceback (most recent call last):
23:40:31   File "/usr/local/bin/behave", line 11, in <module>
23:40:31     sys.exit(main())
23:40:31   File "/usr/local/lib/python2.7/dist-packages/behave/__main__.py", line 183, in main
23:40:31     return run_behave(config)
23:40:31   File "/usr/local/lib/python2.7/dist-packages/behave/__main__.py", line 127, in run_behave
23:40:31     failed = runner.run()
23:40:31   File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 804, in run
23:40:31     return self.run_with_paths()
23:40:31   File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 824, in run_with_paths
23:40:31     return self.run_model()
23:40:31   File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 626, in run_model
23:40:31     failed = feature.run(self)
23:40:31   File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 321, in run
23:40:31     failed = scenario.run(runner)
23:40:31   File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 1114, in run
23:40:31     failed = scenario.run(runner)
23:40:31   File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 711, in run
23:40:31     if not step.run(runner):
23:40:31   File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 1379, in run
23:40:31     formatter.result(self)
23:40:31   File "/usr/local/lib/python2.7/dist-packages/behave/formatter/pretty.py", line 151, in result
23:40:31     self.stream.write(indent(step.error_message.strip(), u"      "))
23:40:31   File "/usr/lib/python2.7/codecs.py", line 370, in write
23:40:31     self.stream.write(data)
23:40:31 IOError: [Errno 11] Resource temporarily unavailable**

Unable to figure out why and where this IOError is popping out. Can someone help me out in resolving this issue?

Thanks in advance..

**Comment by xrg** [comment]
This sounds more like a problem of your own system. Are you using some sort of network storage, over which your formated output would be written?

**Comment by bharadwajambati95** [comment]
@xrg We are running the feature tests on Jenkins, on which this traceback pops out when a scenario failed

**Comment by bharadwajambati95** [comment]
I observed a new thing from my logs. If the size of the stdout logs is less than 50-60K then it's not throwing the IOError and letting the other tests to run. If it is greater than that, it's throwing the IOError and not letting the other tests to run. Can someone help me out with this?

Thanks in advance.

**Comment by bharadwajambati95** [comment]
Redirected the logs to a file
