### ISSUE TITLE
Steps cannot be reused if different prefix (Given vs When)

### ISSUE THREAD

**Issue by amcgaugh** [behave/behave#753]
Behave is throwing an error for missing step definition when the same step has a different prefix (Given vs. When). 

Example:
Given I am on the home screen 
When I am on the home screen

If step definition was created for @given('I am on the home screen') it would throw an undefined step definition for the when step, when really it should take the same step (similar to cucumber frameworks).

**Comment by xrg** [comment]
That's not an issue, it is so by design:
if you want the same sentence to apply to all keywords, use `@step` . Otherwise, `@given`  / `@when` and `@then` only provide a narrow assignment.

**Comment by jenisys** [comment]
* Use `@step() ...` decorator which makes it available for Given / When / Then / *
* Use multiple decorators on the step implementation

NOTE:
In general, it does not make sense to use a step with all 3 keywords.
The `Then` steps for example asserts / verifies a certain outcome.
This makes normally no sense with the other step types, etc.

SEE ALSO:
* [behave4cmd0/command_steps.py](https://github.com/behave/behave/blob/master/behave4cmd0/command_steps.py#L181)
