### ISSUE TITLE
Is there a way to set unique pre-conditions for each feature file?

### ISSUE THREAD

**Issue by Songyu-Wang** [behave/behave#758]
I know I can use before_feature() to do some pre-condition
However, is there a way that i can execute different pre-condition for different features? 
Maybe something like this? https://radish.readthedocs.io/en/latest/tutorial.html#scenario-precondition

**Comment by Songyu-Wang** [comment]
I read https://github.com/behave/behave/issues/456
but I didnt quite follow the idea of using tags.
Should I have something in before_feature() that `execute something tagged as @setup`  and after_feature() that `execute something tagged as @teardown`?

**Comment by jenisys** [comment]
@Songyu-Wang 
First terminology: `precondition` is a check without side-effects at the beginning of a block that a certain criteria is true (normally a check on input parameters).

`Radish precondition` means something completely different (bad usage of terminology IMHO).
It means: Please run me this other feature before you run this scenario.
This does not make sense to me. Before you begin a Feature/Scenario, you normally only want to setup stuff, not test that some other Feature/Scenario is correct.

Therefore, there is the question what you actually want to do:
* Perform a setup before the Scenario / Feature is run: Use **fixtures** and **fixture-tags**.
* Check if a Scenario/Feature should run by retrieving information from the testbed / test-environment and skip the Scenario/Feature if these condition(s) are not met: Use **Active-Tags**.

**Comment by jenisys** [comment]
Same functionality as in `radish` could be provided in a fixture by using a fixture-tag:

```gherkin
Feature:
   ...

    @fixture.setup_with_included_scenario=SomeFeature.feature::An_awesome_Scenario
    Scenario: Do some crazy stuff
      ...
```

How to implement that is left to you as an exercise :smile:
NOTE: The problem with this approach is that you can no longer read Feature and understand what is going on / intended unless you run the feature file.
