### ISSUE TITLE
Logging: Capture Behave Logs/Reports to file AND log informational messages to console

### ISSUE THREAD

**Issue by collin-miller** [behave/behave#762]
I'd like to be able to capture the the standard behave logging to an output file while simultaneously log informational messages to console. The only time the messages are written to console are in the failures. I'd like to log information in positive scenarios as well.

Summary:
- write behave standard logs output to file
- write custom (informational/debugging) logging to console (for success and failure scenarios)

Reasoning: the tests will execute and run against an asynchronous queued messaging system and depending on the number of messages in the queue, or other factors, the tests can run for quite some time. It would be best if we track the progress by including some custom logging; however, when I try to use the `logging` library I am unable to write informational messages to the console. 

Is there a recommendation for logging under these conditions?

**Comment by jenisys** [comment]
You are probably talking about two things:

* (captured) stdout/stderr output
* (captured) logging

In your case, it is probably best that you disable log capture (using `--no-logcapture` or with config-file). Your logging configuration determines if you log to a file, the console or both.
