### ISSUE TITLE
ask for random test of scenario outline table

### ISSUE THREAD

**Issue by luwang-vmware** [behave/behave#764]
Hello, I am using Behave for our testing. It is great framework and I like it very much. Currently there is test requirement to randomly pick one row of scenario outline table for our testing, not loop each row of the outline table. I am not sure whether the current framework has supported it or not. If yes, would you please tell me how to use it? If not, is there any other alternative method for it?

Thanks very much for reading my message.

**Comment by The-QA-Geek** [comment]
Gherkin doesn't define any way to do that, and Cucumber doesn't implement any built-in mechanism for that, nor have I seen anything like that in Behave. 

As a workaround you could give each row of every examples table a tag (or break the Examples tables into multiple Examples tables and give each table a tag), and randomly pick a tag at runtime. That would require that every Examples table have the same number of rows - rather clumsy, but you could break your feature files into groups; each group would have Examples tables that were identical in size.

Or, write a pre-processor that goes through your feature files before execution and randomly deletes every Examples row except one from each table.

**Comment by jenisys** [comment]
Currently, behave does not support the functionality.
You can either take the approach that @The-QA-Geek  suggested or wait for a feature that provides `table_generator` and/or `table_transform` for Examples table(s):

```gherkin
Scenario Outline: 
  Given I use the address of person "<name>"
  ...

  @table_transform.select_one_row_by_random
  Examples:
    | name |
    | Alice |
    | Bob |
```

HINT: 
* That is basically a preprocessor that is applied to the Examples table before it is expanded into Scenarios.
* I cannot say when this feature will be implemented (just that it is an interesting idea that will be approached in the future).
* See #707 and the linked other issues.

**Comment by jenisys** [comment]
One other idea: 
The line of the examples row allows you to select the corresponding Example row scenario by using a FileLocation, like: "features/one.feature:123" where line=123 is the line of a Examples row. Therefore, if you somehow randomly select the line and run:

```sh
behave features/one.feature:123
```
or write it to a text file "randomly_selected_examples_row.txt" and run:

```sh
behave @randomly_selected_examples_row.txt
```
 you have a simple solution to your problem.

**Comment by jenisys** [comment]
Or you provide a behave formatter `my_formatter:RandomScenarioSelectorFormatter` as preprocessor that randomly selects scenarios and write their FileLocation(s) to a text file:

```sh
behave --dry-run -f my_formatter:RandomScenarioSelectorFormatter -o random_selected_scenarios.txt features/
behave @random_selected_scenarios.txt
```

**Comment by luwang-vmware** [comment]
Thanks @jenisys and @The-QA-Geek . I will take a look on how to use formatter as preprocessor for my requirements.

**Comment by Vadmeggy** [comment]
I run into a similar issue. I want to parallelize my tests, and want to run each Example from the scenario outline. 

`Pages1 is loaded -- @1.1`
`Pages2 is loaded -- @1.2`

When i try to run `behave -n "Pages1 is loaded -- @1.1"` all of the examples are run. Is there a workaround for this?

**Comment by jenisys** [comment]
@Vadmeggy 
Not reproducible for me with current HEAD of this Git repository.
Only one example row is executed of the ScenarioOutline.

**Comment by jenisys** [comment]
Reopen.
