### ISSUE TITLE
Data Tables without a header row are not handled correctly

### ISSUE THREAD

**Issue by The-QA-Geek** [behave/behave#765]
Data tables are not required to have a header row (column titles), but Behave is parsing a data table with the same code as an Examples table. Examples tables are _required_ to have a header row (or column?), and Behave strips this off - but that means that the first row is lost from data tables that don't have a header row. (The second data table example in the official Cucumber documentation at https://github.com/cucumber/cucumber/tree/master/datatable shows a data table that has the titles/keys in the first column rather than the first row. At one time this was also legal for Examples tables; it may still be but I don't have Cucumber installed here to test it.)

Feature: Data Tables

User Story: As a user, I would like the first row of a data table to be included in context.table

Scenario: Reading rows from a data table will return all rows, beginning with Row 0
	Given these users in the database
		| User1			|
		| User2			|
		| User3			|

from behave import *

@given(r'these users in the database')
def resources_in_the_database(context):
    for row in context.table:
        print("Row: ", row)
    raise NotImplementedError

Running this scenario produces:
      Captured stdout:
      Row:  <Row ['User2']>
      Row:  <Row ['User3']>

The first row - User1 - is missing.

**Comment by jenisys** [comment]
And as you can the see, the pre-existing Table implementation example in Cucumber Gherkin provides table headers, too: https://cucumber.io/docs/gherkin/reference/#data-tables

I am looking forward to your pull-request w/ the DataTable implementation in Python ,-)
(and I am aware of @mpkorstanje DataTable implementation).

**Comment by mpkorstanje** [comment]
Too clarify and for what it is worth; in gherkin a table is a list of lists of strings. `datatable` is sugar that turns it into more usable forms. Most cucumber implementations provide a rudimentary form of it e.g. a list of maps where the header is used as the key value.

When a scenario outline is compiled the header of the example table is used to fill in the place holders in the scenario.

When used as an argument the entire table is available in the AST. Even without implementing the transforms in `datatable` you can pass this as an argument to the step definition.

From an AST perspective the headers in the gherkin example are identical to any of it's rows. So I am not sure how this is leads to the conclusion they either mandatory or need not be provided to the step.

I suspect doing so now will be a breaking change now. 😔

**Comment by The-QA-Geek** [comment]
@mpkorstanje, please clarify a little bit:
   1) What is 'AST'?
   2) When you said "I am not sure how this is leads to the conclusion they either mandatory or need not be provided to the step", did you mean "header rows are not mandatory, and should be provided to the step"?

I agree that changing Behave to include Row Zero in context.table will be a breaking change, and I have been trying to think of ways to avoid that. 

We could provide a completely new object, context.raw_table, that includes all rows and columns. That is the most backward-compatible way that I can think of. It still leaves us with the problem that context.table doesn't support Examples tables where the keys/titles are in the first column rather than the first row.

Do you have any other suggestions?

**Comment by mpkorstanje** [comment]
1. AST is the abstract syntax tree. It's the data structure you get after parsing a features file.

2. In short. All table cells should be available.

This doesn't apply to example tables though. There the header is required and must be the first row.

**Comment by The-QA-Geek** [comment]
After thinking about implementation and backward compatibility, the best approach I can think of is:
    - Leave the existing context.table object unchanged.
   - Create two new objects:
        - context.examples_table
        - context.data_table

Context.examples_table will be exactly the same as the current context.table. The reason I would create it is so that it is named properly - if a new user looks at the documentation and sees a context.data_table and a context.examples_table, there is no ambiguity; they will know exactly what each one is for. If they see only context.data_table and context.table they will have to read further to figure out the difference. Doing it this way means that we can deprecate context.table and eventually remove it.

Context.data_table will contain the _entire_ table, including the header row (if there is a header row). Similarly, context.date_table.rows will contain all of the rows, including the header row if there is a header row. Context.data_table will have exactly the same methods and attributes as context.examples_table (including context.table.headings).

The only thing I don't like about this approach is that, if the Data Table has a header row, the developer must start accessing the data from row1, not row0. That is row0["name"] would simply return "name", because row0 is the header row. The developer must remember to start with row1 if there is a header row, but with row0 if there isn't a header row. This is unlike accessing the data in an Examples Table, where row0["name"] will return an actual data value. If anyone has a good suggestion to make them behave the same when indexed by the header names, I would like to hear it.

Thoughts? Is this a good approach?

**Comment by mpkorstanje** [comment]
I think `context.data_table` makes sense.

Not sure why you'd want to provide people access to the examples table.  Example tables and data tables are two different things. Though they use the same format, people would only ever access the the data table, not the examples table. The example values are in-lined into the step.

```feature

Scenario Outline: This uses a example table
  Given a thing name <name>
  Then the name will be jack
  Examples:
     | name |
     | jack |

Scenario: This uses a data table
  Given a data table
     | name |
     | jack | 
  Then  step will receive the entire table
```
  
> The only thing I don't like about this approach is that, if the Data Table has a header row, the developer must start accessing the data from row1, not row0. That is row0["name"] would simply return "name", 

This part I don't understand. Are we working with a lists of lists or with a list of maps/hashes/dictionaries?

I would expect `context.data_table.as_lists[0][0]` to return `name` and  `context.data_table.as_maps[0][name]` would return jack.

**Comment by The-QA-Geek** [comment]
I would provide people access to the Examples table because Behave does that today, and I don't want to have both context.data_table and context.table; I think that would be confusing. I agree that I don't know why anyone would want direct access to the Examples table, but if we are going to deprecate context.table, I would like to provide a path forward for any existing code that accesses the Examples table. @jenisys, what do you think?

I like the .as_lists and .as_maps approach; I will do that - thank you for the suggestion.

**Comment by jenisys** [comment]
First, we do not break existing code:

* `context.table` is used for step tables and will be in the future (independent which class is used)
* `context.table` attribute is part of the API and the way how a step implementation can access its table (object) if one exists.
* AFAIK Gherkin does not specify how the table is internally created (as: `list of list of string`). This is a candidate how to do it and an implementation detail. Behave has currently a different handling. Again, if a change occurs here, it needs to be backward compatible to existing parts.

OTHERWISE:

* I see currently no need to expose `Examples table` as `context` attribute (`context.examples_table`), same as @mpkorstanje .
* We do not add context attributes for different classes of the same thing: `context.table` and `context.data_table`. Because it already exists, `context.table` will remain. The Table class behind this attribute can be changed or exchanged as long it is somehow backward compatible to the existing Table implementation.
* Therefore, we are only talking about two different Table classes: One for step tables (DataTable) and one for Examples tables (ExampleTable)
* The knowledge of the characteristics of a step table is known rather late: Specified either as step decorator for the step implementation or in the step implementation itself. At these points a table transformation or a table conversion can be performed before the table data is processes/accessed.

```python
# -- FILE: features/steps/my_steps.py
...
# -- SOLUTION 1: Table transformation in step decorator 
#    (occurs as internal preprocessing step before step implementation is called/executed)
@given('...', table_traits=TableWithoutHeaderTraits())
def step_impl(context, ...):
    # -- HINT: Table transformation takes place in step decorator

# -- SOLUTION 2: Table transformation in step implementation body
# HINT: Works already today by providing own table transformations.
@given('...')
def step_impl(context, ...):
    table = transform_to_headerless_table(context.table)
    ...
```

BACKGROUND INFO:
* The Gherkin parser currently parses the 2 table types and creates Table objects for them (currently by using the `Table` class objects in both cases).
* The Gherkin parser is generic. Therefore, it can/should have no knowledge about table characteristics like "Header-less table". It just adds the table data to the table object independent if column headers are contained or not.
* The current default expectation is that a Table has headers if not otherwise specified (later-on). Reason: Backward compatibility.

**Comment by TKlauenberg** [comment]
As I am just seeing this issue. At the moment I am learning behave and was using cucumber-js before. There it is implemented in a way that you can transform the datatable in a represenation you need.

For example "table.rows()" only represents the data whereas "table.raw()" also gives you the header.
You can find the documentation [here](https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/data_table_interface.md)

**Comment by jenisys** [comment]
@TKlauenberg 
I am aware of Cucucumber's DataTable implementation/feature. But currently, behave has a different Table implementation that pre-existed DataTables.

**Comment by TKlauenberg** [comment]
@jenisys 
But would you be interested in such an implementation? Because it is also something which someone could get around at the step level.

I would be interested in implementing such a representation as I am trying to translate a codebase with existing feature files.

**Comment by mpkorstanje** [comment]
@TKlauenberg the documentation you linked is for JS. For Java we've moved on too a more sophisticated system:

https://github.com/cucumber/cucumber/tree/master/datatable

**Comment by TKlauenberg** [comment]
@mpkorstanje  you are right this approach is much cleaner I just thought that the JS version maybe would be with less breaking changes to the current implementation

**Comment by jenisys** [comment]
Reopen
