### ISSUE TITLE
use_fixture_by_tag doesn't return fixture if fixture registry has bare functions

### ISSUE THREAD

**Issue by jgentil** [behave/behave#767]
Right now if you use `use_fixture_by_tag` and your registry is bare functions (instead of function/args/kwargs tuples) the fixture itself isn't returned from `use_fixture_by_tag`.   But it is returned if the triple tuple is present.  

Lines in question:
https://github.com/behave/behave/blob/c2ef9aa02334e97455d826cdb38e8e9a96b84ea2/behave/fixture.py#L273-L279

**Comment by jenisys** [comment]
MERGED INTO: behave-1.2.7.dev1
