### ISSUE TITLE
Does behave support optional text in Gherkin expressions?

### ISSUE THREAD

**Issue by george-ge** [behave/behave#769]
I want to have optional text in my expressions: for example, sometimes my sentence has "an" or "a" and I want a single step to take care of both sentences.  

Cucumber has support in the form of parentheses: https://cucumber.io/docs/cucumber/cucumber-expressions/#optional-text

But I have tried that and it doesn't seem like it works in behave.

Is there any support for it or am I missing something in the documentation?

**Comment by jenisys** [comment]
The supported solution in `behave` is currently to use multiple decorators on a step.

SEE ALSO:
* [behave4cmd0/command_steps.py#L170](https://github.com/behave/behave/blob/master/behave4cmd0/command_steps.py#L170)

**Comment by george-ge** [comment]
Thanks. Any reason why the parentheses functionality isn't supported?

If, for example, I have multiple optional text in my sentence, then I might have to create a long list of multiple decorators when I could have had a single decorator.

**Comment by jenisys** [comment]
Behave is using parse-expressions.
Parse-expressions (and similar solutions in Behat, ...) served as starting point for cucumber-expressions.
But both are not the same (features and syntax is slightly different).

Use multiple decorators on a step implementation to get the same solution.

**Comment by george-ge** [comment]
thanks for the clarification
