### ISSUE TITLE
Behave crashes when it finds 'Examples:' with no Examples table

### ISSUE THREAD

**Issue by The-QA-Geek** [behave/behave#772]
Feature: Illustrate how not to use Examples tables

Scenario Outline: foo
Given an 'Examples:' statement
But no Examples table
When we run Behave
Then we get an ugly crash

Examples:

-----------------
'Examples:' can be followed by anything that isn't an Examples table - end of file, another Scenario, a second Examples keyword, etc.; all of these will cause the crash.

The crash is inside build_scenarios; it doesn't anywhere mention the offending Feature file or line of Gherkin, so it took me a long time to debug this. The best hint it gave me was "for row_index, row in enumerate(example.table):
TypeError: 'NoneType' object is not iterable"

So I knew that it had something to do with an Examples table, but it still took a lot of searching to find it. The parser should catch this and point the user to the offending line.

**Comment by jenisys** [comment]
BASIC FIX integrated into behave-1.2.7.dev1
