### ISSUE TITLE
How can i define User Keyword?

### ISSUE THREAD

**Issue by woshiwjma956** [behave/behave#773]
Hi,How Can i define my own keyword? Like Example..
I want to define a keyword read data from excel.
It can read excel row deliver to every Scenario. Like Example..

Thanks!

**Comment by jenisys** [comment]
It is currently not supported to read other files to specify table rows/contents of a ScenarioOutline Examples table.

SEE ALSO: Issue #636 (and others)

**Comment by jenisys** [comment]
DUPLICATES: #636
