### ISSUE TITLE
before_all not called before going through step implementations

### ISSUE THREAD

**Issue by mjalas** [behave/behave#775]
I'm trying to load environment variables from a `.env` file in the `before_all`hook, but it doesn't seem to be called before other python files are executed. In this particular case I have a `config.py` file that loads some environment variables, which is used inside the supporting code for the step implementations. However, for some reason the `before_all` function is not called before `config.py` file is imported, so I end up with a KeyError due to environment variable not existing. I only need to load environment variables during development, since in the pipeline they are specified dynamically. Below is the implementation of the `before_all` hook. 

```python
def before_all(context):
    environment = context.config.userdata.get("environment", "develop")
    if environment == "develop":
        from dotenv import load_dotenv, find_dotenv
        env_path = find_dotenv()
        if env_path:
            load_dotenv(env_path)
```

Should `before_all` not be called before any step implementations are executed?

**Comment by jenisys** [comment]
**QUESTION: Should before_all not be called before any step implementations are executed?**
The ``before_all()`` hook is called before any feature / scenario / step is executed.

BUT:
* You are hinting at an import-order problem, not an execution problem.
* (Re-)Importing a module that is already imported is a NO-OP, meaning nothing is done.
* If your module was imported before ``before_all()`` hook is called, then ...

**Comment by mjalas** [comment]
@jenisys, you hare correct. It was an import problem, which I was able to get to work in the end by changing my approach. The `before_all` worked as it should when I used it for another use case. I'll close this one as it ended up not being a bug at all. Thanks for your help!
