### ISSUE TITLE
How to combine behave with hypothesis (property-based testing)

### ISSUE THREAD

**Issue by pjljvandelaar** [behave/behave#781]
As a user, I don't always want to provide a table with values.
I would like a tool like [hypothesis](https://github.com/HypothesisWorks/hypothesis) to generate these values for me.
The values might have constraints that I want to specify.
E.g. I might want to add the constraints that the first integer must be smaller than second integer.

I can't however nowhere find how to combine behave with hypothesis.
Is this impossible?
If possible, is it documented somewhere?

See also https://github.com/HypothesisWorks/hypothesis/issues/2128

**Comment by jenisys** [comment]
How to use property-based testing in behave or cucumber (or other BDD frameworks) is an ongoing issue. We talked already about 3 years ago at Cucumber workshop in Kopenhagen how this can be done.

The most sensitive approach is to use a ScenarioOutline and somehow generate Examples table contents by ``hypothesis`` (in Python) or QuickCheck in other programming languages. Behave is currently lacking a functionality that is required to do that: to generate the Examples table.
This requires a preprocessing steps before the Scenarios of a ScenarioOutline is expanded.

SEE ALSO:
* #764 
* #707
* http://gasparnagy.com/2016/11/property-based-bdd-examples-with-specflow-and-fscheck/
* https://github.com/cucumber/cucumber/issues/250

**Comment by leonardopsantos** [comment]
Dumb suggestion, can't you `before_scenario(context,scenario)` and the data in `scenario._row` to mark a property like `context.should_I_run = True/False`, then in the step implementation use something like:

```
@step('everything is alright')
def step_impl(context):
    if context.should_I_run:
        actually_do_something()
```
