### ISSUE TITLE
Combine JUnit output or place individual files in their own folder

### ISSUE THREAD

**Issue by jonny7** [behave/behave#782]
Hi

I have the following .ini file

```
junit = yes
junit_directory = reports
```
Which generates files by `TEST-{featurename}.xml. Wondering how I could either combine these to 1 file, or how to place them into their own folders like
```
- reports
   - featurefile1
         - TEST-featurefile1.xml
   - featurefile2
         - TEST-featurefile2.xml
...
```

**Comment by tamasmagyar** [comment]
You can use other libraries to merge xmls. ([https://pypi.org/project/junitparser/]
