### ISSUE TITLE
Is code completion in PyCharm compatible with Behave context?

### ISSUE THREAD

**Issue by neonfink** [behave/behave#784]
Possibly a naive question as I was not able to find anything about this online but I'll try my luck here.
As a simplest example, when I initiate a driver in my `environment.py` inside of `before_all()`:
```
from selenium import webdriver

def before_all(context):
    driver = webdriver.Firefox()
```
And in my step definition inside of `steps.py` I want to access the methods available inside of the `driver`:
```
@when('I visit url "{url}"')
def step(context, url):
    context.driver.get(url)
```

Is there any way to make PyCharm aware of the context as I am typing the step definitions and actually show me code suggestions as soon as I type `context.driver.` to see what methods are actually available inside? 
So far I only find myself switching back and forth between my `steps.py` and `environment.py` where I can peek `driver` methods, since that is where it's initialized. 
Any suggestions about  how to work around this limitation are highly appreciated! :)

**Added:**
I did find a closed issue after I opened my own:
https://github.com/behave/behave/issues/717

Since it's almost a year old, any chance that there are any new workarounds available since then?

**Comment by xrg** [comment]
At Friday, 18 October 2019 2:49 Μ.Μ. Andrii Dosenko wrote:
> 
> Is there any way to make PyCharm aware of the context as I am typing the
> step definitions ...?

This cannot happen at the moment. You see, code completion can only work on 
statically-defined attributes of `context`, or ones that can be put in that 
class'es docstring. But context gets dynamic attributes while tests run.

The best you could get would be to define a `Context.__dir__()` and only let 
the *evaluate* window of Pycharm hint on the available attributes. But that 
would only work while the tests are running, in debug mode.



-- 
This email is free from antivirus checks.

**Comment by jenisys** [comment]
The Context class is somewhat special and contains mostly dynamic attributes provided by the user. As already stated in #717, this is an IDE issue and not a behave issue.
