### ISSUE TITLE
Is there a way to disable the logging of passed tests?

### ISSUE THREAD

**Issue by meeky333** [behave/behave#785]
I have a lot of tests to run at one time, and its becoming a pain to debug. I can't just use tags to test them individually because I'm experiencing a lot of bugs that have something to do with tests being dependant on each other (and I'm trying to make them not depend on each other)

Is there a way to turn off the logging on all the passed tests? So it's easier to scroll through the failed tests and compare.

**Comment by jenisys** [comment]
* Do you mean logging or output ?

Captured-output and captured-logging is normally suppressed for passed tests
HINT: If you excluded logging from being captured: `Adjust your logging configuration`

**Comment by jenisys** [comment]
CLOSE IT => No response to question to clarify the statement
