### ISSUE TITLE
inconsistent API using formatters

### ISSUE THREAD

**Issue by dunossauro** [behave/behave#786]
**behave version**: 1.2.7.dev1

I note little trouble in `behave` behavior when setting a formatter in behave.ini.

For example:

```ini
; behave.ini
format = rerun  ;rerun is just an example
outfile = rerun.txt
```

In this case, behave produce a `rerun.output` file. Not `rerun.txt`. But if I set in the plural form, it works fine.

```ini
; behave.ini
format = rerun
outfiles = rerun.txt
```

In this case I don't need to specify many outfiles, only one.

Another case, when I use `-f rerun -o rerun.txt`, this specifies one formatter and one outfile. Because of that works fine, generate outfile, but don't print plain on stdout.

But, if describe only in `behave.ini`, don't need to call plain formatter. Behave aways print on stdout

**Comment by jenisys** [comment]
Use it as intended and specified and you have no problems.
Should I change `format` to `formatters` and break the specification for all the others ?
Hell, no.
