### ISSUE TITLE
Behave should automatically exclude hidden files

### ISSUE THREAD

**Issue by tjstub** [behave/behave#789]
Behave seems to attempt to run all *.feature and all files within the step directory if they hit some matching parameters. This also includes unix-style hidden files.

 This means that if there are any hidden files (e.g., Say editor bread-crumbs,  like Emacs' `.#steps.py`), behave will try to load them and choke on them.

I can see why someone might put hidden files into behave's path, but I can't see a reason why behave would ever want to run a hidden file. Therefore, it seems that behave should automatically exclude hidden files from import/execution.

This issue is seen on behave 1.2.6

**Comment by jenisys** [comment]
This is an Editor / IDE problem related to Emacs (as it seems).
Behave has no naming conventions for feature-files, it only looks for the extension `*.feature`.

HINTS:
* Try to tweak the naming conventions in Emacs (such a wonderful flexible tool)
* Try to use the `--exclude=PATTERN` option to filter these files out (and put it in the config-file).

**Comment by tjstub** [comment]
I respect if this is closed because it is considered out of scope. 

As a clarification though, I have encountered it with other editors besides emacs (vim for instance), as that was just an example, and it occurs with step files, not just feature files.
