### ISSUE TITLE
Support reading features from markdown files

### ISSUE THREAD

**Issue by tomdottom** [behave/behave#790]
It would be nice to be able keep feature tests inside other markdown formats in order to include further documentation outside the scope of the actual feature test.  [TheRobotFramework](https://robotframework.org/) and [Guage](https://gauge.org/) do something similar.

The simplest way may be to parse markdown files for code-blocks annotated with `gherkin` formatting and to consider treat code-block and independent feature file.

**./features/my_feature.md**

    # My File

    Some markup outside of the scope of the feature background
    possibly including a history of design decisions, images, diagrams, etc ...

    ```gherkin
    Feature: showing off behave
    
      Scenario: run a simple test
         Given we have behave installed
          When we implement a test
          Then behave will test it for us!
    ```

**Comment by jenisys** [comment]
You normally do it the other way around.
Meaning: Your documentation should include the feature files (for example with Sphinx).

SEE ALSO: `literalinclude` command
* https://raw.githubusercontent.com/behave/behave/master/docs/new_and_noteworthy_v1.2.6.rst
* https://behave.readthedocs.io/en/latest/new_and_noteworthy_v1.2.6.html

HINTS:
* This would require another parser (a markdown-gherkin parser)

**Comment by tomdottom** [comment]
@jenisys thanks for the reply and suggestion.

I appreciate that this way is a possibility.  Unfortunately for many small private projects we've found generating and hosting docs adds a little to much friction and effort to make it worth it (and yes we've even looked a paying for private ReadTheDocs account).

GitHub markup rendering explicitly stops any sort of includes from working owing to security concerns so we can't simply use `literalinclude` and have GitHub render it for us.

So for these small projects I was hoping to just have `.md` or `.rst` files with the features embeded.

## Sketch of implementation

WRT to your _Hint_.  Does the following rough sketch seem an appropriate way to proceed?

Change:

https://github.com/behave/behave/blob/5ae7f3bcc8742e2fc1f43acaed6e1db50c993deb/behave/parser.py#L54-L58

to something like:

```python
def parse_file(filename, language=None):
    # file encoding is assumed to be utf8. Oh, yes.
    with open(filename, "r", encoding="utf8) as f:
        if filename.endswith(".md"):
            data = MarkdownTextIO(f).read()
        else:
            data = f.read()
    return parse_feature(data, language, filename)
```

With `MarkdownTextIO` defined as:

```python
from collections import namedtuple
import io
import itertools


Boundary = namedtuple("Boundary", ["open", "close"])


class MarkdownTextIO(io.TextIOBase):

    def __init__(self, text_io):
        self._boundries = []
        self._text_io = text_io
        self._find_boundries()

    def _is_open_tag(self, line):
        return line.startswith("```") and ("gherkin" in line) and ("behave" in line)

    def _is_close_tag(self, line):
        return line.startswith("```")

    def _find_boundries(self):
        state = "closed"  # or open
        tmp = Boundary(None, None)
        for index, line in enumerate(self._text_io):
            if self._is_open_tag(line) and state == "closed":
                tmp = Boundary(index, None)
                state = "open"
                continue
            if self._is_close_tag(line) and state == "open":
                tmp = Boundary(tmp.open, index)
                self._boundries.append(tmp)
                tmp = Boundary(None, None)
                state = "closed"
                continue
        self._text_io.seek(0)

    @property
    def boundries(self):
        for b in self._boundries:
            yield b

    def read(self, size=-1):
        return "".join(
            itertools.chain.from_iterable(
                itertools.islice(self._text_io, b.open + 1, b.close)
                for b in self.boundries
            )
        )



# if __name__ == "__main__":
#     # Simple test
#     import tempfile
#     fn = tempfile.NamedTemporaryFile(mode="w", suffix=".md")
#     with open(fn.name, "w") as fh:
#         import textwrap as tw
#         fh.write(tw.dedent("""
#             # Heading

#             Some text.


#             ```gherkin + behave
#             Foo
#             Bar
#             Baz
#             ```

#             Some more text.
#         """).lstrip())
#     with open(fn.name) as fh:
#         print(MarkdownTextIO(fh).read())
#
```

And of course change:

https://github.com/behave/behave/blob/5ae7f3bcc8742e2fc1f43acaed6e1db50c993deb/behave/runner_util.py#L527

to

```python
 if filename.endswith(".feature") or filename.endswith(".md"): 
```

and change:

https://github.com/behave/behave/blob/5ae7f3bcc8742e2fc1f43acaed6e1db50c993deb/behave/runner.py#L761

to

```python
 if [fn for fn in filenames if (fn.endswith(".feature") or fn.endswith(".md"))]: 
```
