### ISSUE TITLE
Support for Accessing Tags in before_all

### ISSUE THREAD

**Issue by jwignall** [behave/behave#792]
Hello, 

My apologies if this is already possible and I've just missed it, but I would like to be able to access the tags specified on the command line at runtime, preferably within the before_all method. 

I would like to do something along the lines of 
`if "foo" in tags: tags.append("~bar")` so that I can include/exclude tests based on a tag specified on the command line. Of course, I could do this manually, but it's more so I can check the test configuration before I run in since some tags cannot run in conjunction with others. 

Is this possible? Does an example exist somewhere? If not, would it be plausible to add it?

**Comment by jenisys** [comment]
That is not really useful.

HINT: 
* The command-line (or config-file) specifies a tag-expression, a boolean expression.
  You are basically suggesting that you want to rewrite the tag-expression based on one part of it.
* The tag expression is applied to features / scenarios to determine if this feature / scenario should run
* The current HEAD supports tag-expressions v2: `(foo or bar) and baz`
