### ISSUE TITLE
Tag expressions doesn't seem to be working

### ISSUE THREAD

**Issue by puttagunta** [behave/behave#793]
Environment: python 3.7, 32-bit on windows 10
Setup: Have a feature file, somefeaturefile.feature, with multiple scenarios, say 5 scenario outlines for 41 scenarios. Tag a couple with @WillAutomateLater and others with @SomeotherTag. Run behave with the following command line.
Command1:
behave --tags="not @WillAutomateLater" somefeaturefile.feature
0 features passed, 0 failed, 1 skipped
0 scenarios passed, 0 failed, 41 skipped

Command2:
behave --tags="@WillAutomateLater" somefeaturefile.feature
1 feature passed, 0 failed, 0 skipped
24 scenarios passed, 0 failed, 17 skipped
72 steps passed, 0 failed, 51 skipped, 0 undefined

Command2 worked as expected but, Command1 did not work as expected. With Command1, I was expecting 17 scenarios passed and 24 skipped. Instead, everything is skipped.
I also tried with "@Someothertag and @WillAutomateLater" but, did not work either.

I was referring to, https://behave.readthedocs.io/en/latest/tag_expressions.html for using it with tags. Can someone help me getting it worked for me?

**Comment by puttagunta** [comment]
I got it working with --tags=-WillAutomateLater to ignore scenarios/features with that tag. I didn't quite understand why is it not documented. I got it working from https://stackoverflow.com/questions/36482419/how-do-i-skip-a-test-in-the-behave-python-bdd-framework

**Comment by jenisys** [comment]
HINT: The new tag-expressions work on the current HEAD of the Git repository (only). The latest documentation matches this state.

SEE: https://behave.readthedocs.io/en/latest/new_and_noteworthy_v1.2.7.html

**Comment by adibo** [comment]
Just to clarify, as I came along a similar issue. 
I can confirm current master works for tags like `--tags="not slow"`
But what about dotted tags? For example: tags named as `disabled.feature` with behave executed as `--tags="not disabled.*` does not seem to bring a desired effect. At least for me. I presume the dotted tags are not supported in this case. Or am I doing something wrong?

**Comment by jenisys** [comment]
@adibo
Dotted tags work for me (because I use them, too and designed this feature into cucumber-tag-expressions). Same for tag-expression name matching. One example why tag-matching would be useful was a dotted-tag.

SEE ALSO:
* [features/tags.tag_expression_v2.wildcards.feature](https://github.com/behave/behave/blob/master/features/tags.tag_expression_v2.wildcards.feature)
