### ISSUE TITLE
Bind table headings parameter to scenario outline variables

### ISSUE THREAD

**Issue by DvirDukhan** [behave/behave#794]
hi
I see that this is an issue already handled in #631, but I'm having difficulties in getting the parameter data.

I'm using behave to validate Cypher coverage for RedisGraph(https://github.com/RedisGraph/RedisGraph), using the openCypher TCK scenarios (https://github.com/opencypher/openCypher/tree/master/tck).

One of the scenarios is as follows:
```
    Scenario Outline: `percentileDisc()`
        Given an empty graph
        And having executed:
            """
            CREATE ({price: 10.0}),
            ({price: 20.0}),
            ({price: 30.0})
            """
        And parameters are:
            | percentile |  <p>  |
        When executing query:
            """
            MATCH (n)
            RETURN percentileDisc(n.price, $percentile) AS p
            """
        Then the result should be:
            | p        |
            | <result> |
        And no side effects

        Examples:
            | p   | result |
            | 0.0 | 10.0   |
            | 0.5 | 20.0   |
            | 1.0 | 30.0   |
```
Retreving the headings of the table 
```
| percentile |  <p>  |
``` 
returns the strings `percentile` and  `<p>` where I would expect to have the value of p instead.

please advise.

**Comment by jenisys** [comment]
Use the current HEAD of the Git repository where #631 is fixed and reverify that it is the case for you by running `behave issue.features/issue0631.feature`.
