### ISSUE TITLE
context.USER weirdness

### ISSUE THREAD

**Issue by grahamoptibrium** [behave/behave#797]
I have found a 'feature' in the context variable that I can't find in the documentation:

```python
def step_impl(context):
    print(context.USER)  # prints 'user'
    context.USER = 'something else'
    print(context.USER)  # still prints 'user'
```

This was weird to track down.

**Comment by jenisys** [comment]
Therefore, it is not supplied by `behave`. It is supplied by you (in your code) or the steps that you are using or in the environment hooks (`features/environment.py`).

**Comment by grahamoptibrium** [comment]
@jenisys @BogdanOptibrium

Not supplied by me, that is why it is weird... steps to replicate:

`features/stories/weirdness.feature` contains:
```gerkin
Feature: weirdness

Scenario:
    Given weirdness happens
```

`features/steps/weirdness.py` contains:
```python
from behave import given

@given('weirdness happens')
def step_impl(context):
    print(context.USER)  # prints 'user'
    context.USER = 'something else'
    print(context.USER)  # still prints 'user'
    assert context.USER == 'something else', context.USER
```
Run with the command:
```bash
# behave 1.2.6
behave 
```
Gives the output:
```bash
Feature: weirdness # features/stories/test.feature:1

  Scenario:                 # features/stories/weirdness.feature:4
    Given weirdness happens # features/steps/weirdness.py:4 0.000s
      Assertion Failed: user
      Captured stdout:
      user
      user

Failing scenarios:
  features/stories/test.feature:4  

0 features passed, 1 failed, 0 skipped
0 scenarios passed, 1 failed, 0 skipped
0 steps passed, 1 failed, 0 skipped, 0 undefined
Took 0m0.000s
```

**Comment by jenisys** [comment]
Ok, I checked the source code.
The Context class has a static constant Context.USER that is used internally (same as: Context.BEHAVE, ...). Static variables of the Context class seem to overlay the normal context attributes.

This should not be a problem for you because you are a good Python programmer and follow PEP8 naming conventions ... ;-)
