### ISSUE TITLE
pdb exposes strange behavior

### ISSUE THREAD

**Issue by twelve-this** [behave/behave#802]
Hi,

I really like behave and working with it. Thanks for the effort and nice work.

I like the python pdb module and love to explore and debug code by setting breakpoints.

The strange thing with behave is: pdb does not really work with behave.

I use python 3.8 and behave itself works just fine.

This is the part where I struggle - a snippet from a step implementation:

```python
@given('some given situation')
def step_impl(context):
    breakpoint()
```
Executing the command `behave` will just run fine until it hits `breakpoint()`. However, the prompt from the pdb module is weird and pdb is not properly set up. I cannot really use the pdb capabilities. Strange: when inputting "c" and pressing enter, the program appears to normally resume.

Changing `breakpoint()` to `import pdb; pdb.set_trace()` has - as expected - no effect and the result is just the same.

What am I doing wrong here?

Thanks in advance!

**Comment by twelve-this** [comment]
I found an efficient solution. Just put the following configuration into `behave.ini`:

```
[behave]
stderr_capture = False
stdout_capture = False
```
pdb works as expected now.

**Comment by jenisys** [comment]
Within the step you are still in capture mode. Therefore, you do not see what you are typing/doing. You should disable this mode before you enter the debugger. Workaround: Disable capture-mode on command-line before you want to enter the debugger.

**Comment by ea2809** [comment]
I don't remember where, but you can do the following:
```python
import sys, pdb; pdb.Pdb(stdout=sys.__stdout__).set_trace()
```
