### ISSUE TITLE
Step Data starting with meaningful space

### ISSUE THREAD

**Issue by martingbrown** [behave/behave#803]
I'm writing a test scenario with a step that requires a table of data. However the test is sensitive to whether there is a space at the start of a value or not. So " frog" needs to be treated differently to "frog". This doesn't work because behave strips whitespace at the start and end. So in this case the two frog strings end up the same:

|Column|
| frog|
|frog|

I appreciate that I can lay this out with quotes added and then strip the quotes off in my step code like this:

|Column|
|" frog"|
|"frog"|

However I was wondering if there is any built in way to handle this with behave that wouldn't require the extra step code?

**Comment by jenisys** [comment]
You are using a weird corner case.
The table parse strips the value in each cell because that is the commonly needed behaviour.
Instead of quotes, you could try to use a BACKSLASH, like: `| \ one | => " one"
Note that I have not tried it yet.

**Comment by martingbrown** [comment]
I got it working with the quotes by stripping them off again. I was just wondering if I'd missed some way of doing it. I guess not.
