### ISSUE TITLE
about the steps dictory and enviroment.py path

### ISSUE THREAD

**Issue by liujfsunshine** [behave/behave#804]
I have some problems to confirm:
1: The features/ directory must needs a steps/ subdirectory?Can I change it to another name?【ps:when I change the name,if I run the program,  I will get an error such as :can't find the steps path】
2:could I design a directory structure like this:
+-- steps/*.py
+-- features/*.feature
3:enviroment.py file must under the features subdirectory?

I look forward to your reply，thank you very much!

**Comment by jenisys** [comment]
Could you elaborate why you need to change the name ?

HINT: 
`behave` has naming conventions and "steps" is the naming of the steps directory.
Look at the staging mechanism if that is any help for your use case.

SEE ALSO:
* https://behave.readthedocs.io/en/latest/new_and_noteworthy_v1.2.5.html#test-stages

**Comment by jenisys** [comment]
No reaction => CLOSE IT
