### ISSUE TITLE
Boolean Expressions with Active Tags

### ISSUE THREAD

**Issue by bschwyn** [behave/behave#806]
I would like to make active tags with more complicated logic, something like:

`use.with_((category1=A or category1=B or (category1=C and category2=D)) and category3=E)`

or 

`not.with_(cateogry1=A or category1=B)`

**Comment by bschwyn** [comment]
What I am doing right now is I made a special tag called "expression", and when I come across a tag like 
`not.with_expression=(cateogry1=A or category1=B)`
then I invoke a parser which parses and evaluates the 'sub-tags' and the overall truth value of the tag.

**Comment by jenisys** [comment]
Necessary steps / tasks to be solved to accomplish this:

* Gherkin parse needs a more generic definition of tags (currently a tag is basically a word)
* CANDIDATE: For boolean expression logic could be the new tag-expressions (see extension in behave or the core implementation in cucumber-tag-expressions)
* Similar problems need to be solved like for active-tag-expressions

When can I expect your pull-request ?

SIDE NOTES:
* This will get complicated (and complicated for the reader to understand)
* This will probably make your feature files *less readable* / *unreadable* if I look at your examples above
* Do you really want to do this ?!?

**Comment by jenisys** [comment]
@bschwyn 
By the way, you are aware that you can use multiple active-tags for a Scenario (and therefore get part of the boolean logic for free).

SEE ALSO:
* [features/step.async_steps.feature](https://github.com/behave/behave/blob/master/features/step.async_steps.feature#L33)
