### ISSUE TITLE
scenario.name is empty in before_scenario hook

### ISSUE THREAD

**Issue by MichaelBaarzIngka** [behave/behave#807]
Hey,

I'm using now behave 1.2.6 where scenario.name is empty. In some version (I dont remember before) it has always worked.

def before_scenario(context, scenario):
    raise OSError(str(scenario.name))

--> return nothing, same with after_scenario hook.

**Comment by jenisys** [comment]
I am not quite sure what your are complaining about:

* The scenario.name is empty if you have not provided a name/title for the scenario
* The scenario.name is non-empty if you have provided a name/title for the scenario

Provide a concise description what the problem is that you have.

**Comment by MichaelBaarzIngka** [comment]
No. I provide a scenario name in the gherkin file. But in behave in the version I mentioned it does not get delivered as described. E.g. in the logs which are printed in console the names are there. I use python 3.8.1
________________________________
Von: jenisys <notifications@github.com>
Gesendet: Donnerstag, Januar 30, 2020 11:37 PM
An: behave/behave
Cc: Michael Baarz (External - Capgemini Sverige AB); Author
Betreff: Re: [behave/behave] scenario.name is empty in before_scenario hook (#807)


I am not quite sure what your are complaining about:

  *   The scenario.name is empty if you have not provided a name/title for the scenario
  *   The scenario.name is non-empty if you have provided a name/title for the scenario

Provide a concise description what the problem is that you have.
