### ISSUE TITLE
Anybody in FOSDEM?

### ISSUE THREAD

**Issue by xrg** [behave/behave#809]
Sorry for the off-topic, but apparently there is no other communication.
Is anybody from you around in FOSDEM, should we discuss about a community?

**Comment by jenisys** [comment]
Sorry, I saw it too late.
But I am not at the FOSDEM, maybe Peter Bittner (@bittner).

Otherwise, if if you think you can contribute to behave and its „community“, let me know and we could get something organized.

Ciao,
Jens

**Comment by bittner** [comment]
Not this year, sorry!

I would also be interested in a more lively community.

Meeting in-person is clearly optimal, an open video conference could be a viable alternative.
