### ISSUE TITLE
Unable to run 'behave -n' when the search string contains bracket

### ISSUE THREAD

**Issue by xv-chris-w** [behave/behave#810]
**HOW TO REPRODUCE**
Have a test name that contains brackets: 

> Scenario: This is a test name (1.0)
>     Given A
>     When B
>     Then C

and try run test with the full name which contains the brackets,  behave is unable to identify the test
`behave -n 'This is a test name (1.0)'`.

**WORKAROUND**
We will need to escape the bracket to make it work 
`behave -n 'This is a test name \(1.0\)'`

**EXPECTED**
We should be able to use the bracket in the string without escaping it.

**Comment by jenisys** [comment]
Well, a regular expression need escape-char if you use PARENTHESIS.

SEE ALSO:
* https://practicaltypography.com/parentheses-brackets-and-braces.html

**Comment by xv-chris-w** [comment]
Hi @jenisys,  isn't `--name` and `-n` mean to be doing text string,  didn't expect it is expecting a regex in there.   see [here](https://behave.readthedocs.io/en/latest/behave.html#cmdoption-n)

It would be nicer to have behave escape this from upstream.  I can imagine users may have their test cases contain brackets,  and this could be something unexpected for them.

**Comment by jenisys** [comment]
SEE: [features/runner.select_scenarios_by_name.feature](https://github.com/behave/behave/blob/master/features/runner.select_scenarios_by_name.feature)

**Comment by jenisys** [comment]
Clarification integrated into behave-1.27.dev1
