### ISSUE TITLE
stage environment 

### ISSUE THREAD

**Issue by loutente** [behave/behave#811]
[Related documentation](https://behave.readthedocs.io/en/latest/new_and_noteworthy_v1.2.5.html#test-stages)

When I call behave with my stage the dedicated stage_environment.py is never called

Any idea ?

**Comment by jenisys** [comment]
Which stage name are you using ?
(I assume that you do not use stage_name="stage")

The documented schema is: `features/{stage_name}_environment.py`

```bash
# -- EXAMPLE: stage_name="alice"
# USES: "features/alice_environment.py" and "features/alice_steps/*.py"
$ behave --stage=alice features/
...
```

SEE ALSO:
* [features/runner.use_stage_implementations.feature](https://github.com/behave/behave/blob/master/features/runner.use_stage_implementations.feature)

**Comment by loutente** [comment]
Sorry, after futher investigation it is the Pycharm plugin that break the feature.
