### ISSUE TITLE
Is it possible to define an execution order?

### ISSUE THREAD

**Issue by Facon** [behave/behave#812]
I would like to know, how would I make behave have execution order?

I'm in context of testing a black box remote application that you can communicate through json. It's interesting for example, to send a ping to remote equipment before executing anything else.

How can I do it?

Thank you.

**Comment by xrg** [comment]
Tests have to be independant. This is a fundamental concept in testing and Gherkin.
However, I have been also thinking about creating some kind of "flows", dependencies between scenarios. This would be an extension of the Gherkin language and needs some scrutiny before it can be drafted.

**Comment by jenisys** [comment]
Use @files (AT-files) and/or file-locations, if you need a specific order.

But for your use case, I would use fixtures/fixture-tags.
The fixture checks that the remote equipment is accessible (in the before-hook/setup-part) before the scenario/feature is executed. If it fails the scenario/feature is skipped/fails.

SEE ALSO:
* [features/runner.feature_listfile.feature](https://github.com/behave/behave/blob/master/features/runner.feature_listfile.feature)
* [features/fixture.feature](https://github.com/behave/behave/blob/master/features/fixture.feature)
