### ISSUE TITLE
"U" mode is no longer accepted from Python 3.9

### ISSUE THREAD

**Issue by tirkarthi** [behave/behave#813]
https://github.com/behave/behave/blob/80c1e97acdd3251dc291fbb8d1d02c774d3f6d2d/behave/json_parser.py#L36

https://github.com/python/cpython/pull/16959

**Comment by jenisys** [comment]
@tirkarthi 
Thanks for the information.

**Comment by tirkarthi** [comment]
I will add a PR for this that works on both Python 2 and 3.

**Comment by jenisys** [comment]
Reopen
