### ISSUE TITLE
Provide command to find path of module defining step

### ISSUE THREAD

**Issue by orontee** [behave/behave#814]
This feature would be useful to implement "jump to step definition" in editors. Example in a shell:
```shell
$ behave --find-step "When we implement a test"
features/steps/tutorial.py:3
```

**Comment by orontee** [comment]
Ok, I realize that `behave -f steps.catalog more.features/tutorial.feature:4` outputs the information I was looking for for all steps used in the given feature.

**Comment by jenisys** [comment]
... or the other step-formatters: steps, steps.doc, steps.usage
