### ISSUE TITLE
How to provide an unbuffered formatter ?

### ISSUE THREAD

**Issue by oatssss** [behave/behave#817]
I'm running Python scripts on Jenkins and using [`python -u`](https://docs.python.org/3/using/cmdline.html#cmdoption-u) so everything going to `stdout` is unbuffered and shown immediately in the Jenkins console.

Behave is still buffering its `--format plain|pretty|progress|etc` output though. Is it possible to have this unbuffered?

**Comment by jenisys** [comment]
This point never came up. Having it unbuffered is often a performance penalty.
Many of the formatters have only line buffered mode for a scope. In my experience, this does not cause any problems in Jenkins.

Without looking at it:
Provide your own unbuffered formatter and replace the existing one if needed.

SEE ALSO:
* [features/formatter.user_defined.feature](https://github.com/behave/behave/blob/master/features/formatter.user_defined.feature)
