### ISSUE TITLE
Cannot access properties in behave.ini

### ISSUE THREAD

**Issue by longk15t** [behave/behave#818]
Hello guys, have a good day, I can't access data in `behave.ini` file.

I have a `behave.ini` file which has a userdata property
```
[behave.userdata]
browser = firefox
```
in `environment.py` I print the value of this `browser` property
```
def before_all(context):
    print(context.config.userdata["browser"])
```
When I run command `behave`, I get empty dictionary `{}`
`environment.py` and `behave.ini` are in the same directory. What did I miss ? Thanks in advanced.

**Comment by jenisys** [comment]
Try `behave --verbose ...` and check if "behave.ini" is really detected, like:

```sh
$ behave --verbose features
Loading config defaults from "./tox.ini"
Loading config defaults from "./setup.cfg"
Loading config defaults from "./behave.ini"    <== IMPORTANT-LINE-HERE
Using defaults:
...
Using default path "./features"
Trying base directory: /Users/.../behave/features
...
```

The MARKED-LINE above is missing if "behave.ini" is not detected. For example, if your current working-directory does not contain a "behave.ini" file.

**Comment by jenisys** [comment]
SEE ALSO:
* docs: [new_and_noteworthy_v1.2.5: Userdata](https://behave.readthedocs.io/en/latest/new_and_noteworthy_v1.2.5.html#index-7)
* [features/userdata.feature](https://github.com/behave/behave/blob/master/features/userdata.feature)

**Comment by jenisys** [comment]
Seems to be resolved.
