### ISSUE TITLE
Alternative use of behave (for non-testing purposes)

### ISSUE THREAD

**Issue by athityakumar** [behave/behave#822]
Hey there! 👋 

Thanks a lot for building behave! I was actually trying to use behave for another use-case where we'd like to expose some actions based on Gherkin DSL (easier for people to write and contribute); and just wanted to know if it's possible through the behave API.

Here's my use-case. Let's say there's a flask service endpoint people can input some condition (clause) and get some response back depending on which clause they've specified. In the back-end, we have a huge nested if-else decision-tree that decides the response based on the clause the user has specified.

We're trying to port this huge nested if-else block from a centralized one to behave feature-file with lots of scenarios. That way, it'll be more distributed and easier to be crowd-sourced right? Just wanted to know if user input can somehow be plugged in to go through all different scenarios, get the matching scenario (like getting matching leaf of the decision tree) and take action only for the matching scenario.

```
#! decision_tree.feature

Feature: Deciding based on user input

  Scenario: Scenario_1_1
    Given we have received action_type_1
    When we have received input_1
    Then we take action_1_1

  Scenario: Scenario_1_2
    Given we have received action_type_1
    When we have received input_2
    Then we take action_1_2

  Scenario: Scenario_2_1
    Given we have received action_type_2
    When we have received input_1
    Then we take action_2_1

...
```

And when user gives input through flask service like `action_type=1, input=2`, I'd like to get the precise scenario (`Scenario_1_2`) and get the given-when-then blocks in that scenario. Would this be possible through the behave API?

**Comment by xrg** [comment]
Everything is possible!
But you'd have to write some code to get that done.
Say, you could use the existing behave parser to discover/scan/load all your feature files into Feature/Scenario objects. From there on, is where your custom code should take on. You'd need to either try all Scenarios against your input condition, decide which "wins" by testing to a positive result. Or, better, try to build a *mapping* of common input variables into an "index" of possible scenarios, then test only those.
Behave has the building blocks, you need to rearrange them to fit your goal.

**Comment by athityakumar** [comment]
@xrg - Awesome. Given the use-case, what'd you suggest as the best/easy way to tweak behave? It'd be great if you point to the exact places of code change. Thanks for the swift reply! 😄

**Comment by athityakumar** [comment]
That is, I'm imagining it'll be along the lines of:

```python3
def decide_clause(action_type, input_type):
    feature = read_feature("decision_tree.feature")
    for scenario in feature.scenarios():
        try:
            scenario.call_given_and_when_steps_with(action_type, input_type)
            return(scenario)
        except:
            print("Not this scenario")

correct_scenario = decide_clause(1, 2) # Returns Scenario_1_2
if correct_scenario:
    correct_scenario.call_then_steps() # Executes action_1_2 step
```

Can you please point me to the exact functions that'd be useful to rewrite this pseudocode to actual working code?

**Comment by athityakumar** [comment]
@xrg - I've managed to parse the feature file and get the `Feature`/`Scenario` objects. Can you please let me know how to "execute" the python3 `step` functions written for a single scenario?

```python3
from behave.configuration import Configuration
from behave.parser import parse_feature

text = open('features/bar.feature').read()
print(text)
bar_feature = parse_feature(text, filename='features/steps/bar_step.py')
print(bar_feature)

for scenario in bar_feature.scenarios:    
    print(scenario)
    for step in scenario.steps:
        print(step)
```

**Comment by jenisys** [comment]
@athityakumar 
You are missing some important concepts:
* Runner: executes parsed features (and parses feature files before by using the Gherkin parser)
* Runner Context: Used by steps to store variables (Given steps mostly) and provide them for other steps
* ...

In addition, one step back what you are trying to achieve. What you are trying to achieve sounds much like a "If-this-then-that" (IFTTT) logic often used to control smart-home gadgets. There is a correspondence between IFTTT and Gherkin syntax. I am not quite sure, if using behave how you want to do it, is the best approach, but you better know your problem.

The easiest way to accomplish what you want with `behave`, add tags to the scenarios with action_type_X and input_Y, like:

```Gherkin
...
  @action_type_1 @input_2
  Scenario: Scenario_1_2
    Given we have received action_type_1
    When we have received input_2
    Then we take action_1_2
...
```

This allows you to use the tag expression `@action_type_1 and @input_2` to select Scenarion_1_2 (and no other Scenario should have the some combination of tags for your usecase). The Then-Step should just store the desired action in the Context, like `context.desired_action = "action_1_2"`. After executing the selected scenario in your runner, you just need to retrieve the `context.desired_action` before the Scenario context layer is popped. May be simpler to store the "current desired action" somewhere.

The decision tree that you try to reimplement is easier to solve with a 2-dimensional map (a map with two index parts, the action_type and the input), for example stored in a JSON file.
You read the JSON file and determine what the desired action is.

**Comment by athityakumar** [comment]
@jenisys - Yes, the use-case is pretty much IFTTT and Gherkin DSL seems like a pretty user-friendly method for us. The issue is, these action_types and inputs are not exactly static - so I'm just wondering if we could provide these magic variables into the context directly. I've run into another issue now, and I'll add the current script I've gotten now with Runner and Context.

**Comment by jenisys** [comment]
If the action_types and inputs change, you need to generate the feature file anyway (with tags included). In addition, you may look into the active-tag mechanism. This allows you provide current action_type and input before evaluation and the active-tag mechanism selects the Scenarios (in your case: it should be only one) instead of using a tag-expression.
