### ISSUE TITLE
junit formatter for Zephyr or something equivalent to zephyr-xml-formatter.jar?  

### ISSUE THREAD

**Issue by GMVictor** [behave/behave#831]
I wonder if there's any equivalent to the zephyr-xml-formatter.jar used in java to format XML report files coming from the junit execution.

Currently I'm handling the XML after its creation for updating the xml tags as I need.

**Comment by jenisys** [comment]
The problem with the JUnit XML format is that there is not the one specification but several XML dialects instead and how there are used. But you can easily provide your own formatter (and override the default one in the config-file).

SEE ALSO:
* Behave's JUnit XML schema: https://github.com/behave/behave/tree/master/etc/junit.xml
