### ISSUE TITLE
All my steps involve async calls, how can I avoid using the async decorator on every step?

### ISSUE THREAD

**Issue by vjpr** [behave/behave#833]
```
from behave.api.async_step import async_run_until_complete
@given(...)
@async_run_until_complete
async def foo(context):
  response = await requests.post(...)
```

I want to avoid `async_run_until_complete` decorator on every step...and also to re-use the same event loop.

Is there a way to wrap the execution of a step? Maybe `before_step`?

**Comment by jenisys** [comment]
Well, if your lazy you must also provide an intelligent solution to remain lazy ;-)

I would provide an own python module that provides the given/when/then decorators with wrapped-async-decorators, like:

```python
# -- FILE: features/steps/my_steps.py

from behave_async_decorators import given, when, then
...
```

The advantage is that is solution is easier to understand (more readable) what you are doing.
In addition, if you need the original decorators you can still do that.
