### ISSUE TITLE
Unable to display color output in gitlab CI/CD

### ISSUE THREAD

**Issue by rileydak** [behave/behave#835]
Hi team -

I am working running behave in a gitlab CI/CD pipeline, and the output returns without color. According to gitlabs documentation, ANSI Color Escapes are supported. Any advice how to get color display working in a GitLab CI/CD job output?

Thanks!

**Comment by cbuehler** [comment]
I had the same issue and solved it by running it with `script -c "behave"`.
See also https://gitlab.com/gitlab-org/gitlab-runner/-/issues/1021#note_3346988

**Comment by jenisys** [comment]
behave checks if tty-support is enabled before enabling color mode.

**Comment by darkdragon-001** [comment]
Noticed that our pipelines are no longer failing when behave fails when using `script -c`.  Make sure to add the following flag:
> -e, --return                  return exit code of the child process

**Comment by jenisys** [comment]
If `behave` detects that the output is piped, it disables colored-output and uses monochrome mode for the pretty-formatter (that you are probably using; no other of the builtin formatter has coloring support).

ALTERNATIVES: For report / colored-report generation
* Use the HTML formatter (see: https://pypi.org )
* Use the allure formatter for behave (see: https://pypi.org )

**Comment by jenisys** [comment]
What operating system (Linux, Windows, ...) are you using on your CI/CD ?

**Comment by vergenzt** [comment]
Update: functionality to output color even when output is not to tty is merged @ #591!

(Just noting here since I found this ticket and was disappointed, but then later saw that PR 😄)
