### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by ifalex** [behave/behave#836]
I see last version is dated to 2018. Has been put on hold?

**Comment by amaltson** [comment]
Did you get an answer @ifalex? It hasn't been updated since 2018..

**Comment by ifalex** [comment]
> Did you get an answer @ifalex? It hasn't been updated since 2018..

Seems like no answer. 2 years back

**Comment by luki922** [comment]
> > Did you get an answer @ifalex? It hasn't been updated since 2018..
> 
> Seems like no answer. 2 years back

switch from behave to robot framework browser

**Comment by bittner** [comment]
Related:
- https://github.com/behave/behave/issues/1044
- https://github.com/behave/behave/issues/855
