### ISSUE TITLE
Can we get variable name used in the step definitions 

### ISSUE THREAD

**Issue by smankena** [behave/behave#837]
I know we get values of order_name and order_quantity but can we just get the variable names without the values assigned to them during the test run 
   
 @ff001_tc01
    Scenario Outline: Create Order
        When I make a request with name "<order_name>" and size "<order_quantity>" via API
In the step implementaion
@step(
    r'I make a rack creation request with name "(?P<order_name>.*)" and size "(?P<order_quantity>.*)" via API')
def step_impl(context, order_name, order_quantity):

I wanted the order_name and order_quantity as as just strings not the values passed to them. Can it be acheived

**Comment by jenisys** [comment]
Why would you want to do that ?
"order_name" and "order_quantity" are the parameter names of the step function. You predefined it yourself when you implemented the step function.

**Comment by smankena** [comment]
coming from cucumber in ruby its kinda different so was experimenting few things. I got the answer I wanted after some digging
