### ISSUE TITLE
Remove use of os.path.relpath

### ISSUE THREAD

**Issue by sebastianraizer** [behave/behave#838]
`os.path.relpath` does not work on windows when `os.curdir` is on a different drive than the feature files. ref: https://bugs.python.org/issue7195
This results in an exception:
`ValueError: path is on drive D:, start on drive C:`
Proposed solution: `os.path.relpath` is not really needed so it could be removed:
* for loging purposes, 'filename' variable can be used directly, or `os.path.abspath`. 
* for accessing the files, `os.path.abspath` can be used.

**Comment by jenisys** [comment]
Could you explain why you actually need that ?
I normally execute it where my test / features are.

**Comment by sebastianraizer** [comment]
We are running behave on Jenkins. Jenkins and the 'test framework', including behave and other test tools are installed on the C: drive ('fixed stuff').
The program under test, as well as feature files and step definitions are downloaded on the D: drive ('changing stuff'). We also have a requirement that the program under test is callable from anywhere in the file system, so there should not be any restrictions regarding the drive we run from.
Moreover, when looking at the code, I've noticed that most of the calls to `os.path.relpath` are actually not necessary.

**Comment by denravonska** [comment]
See also, https://github.com/xmlrunner/unittest-xml-reporting/issues/222

**Comment by TopherHenk** [comment]
I have a similar issue where the "test framework" with behave, the feature files, and other tools are installed as python packages (typically onto the C drive) while the user is testing their code which is on D Drive.

**Comment by jenisys** [comment]
Sorry, I will not remove the use of `os.path.relpath` for the simple reason that the test suite w/ feature for behave will no longer work (especially across platforms).

In my opinion, you have such an esoteric use case that I didn't even think of it.
A work-around exists if you use only one drive (by organising your workspace).
I might consider, to provide a solution if this special case is detected, but that is not decided yet.
