### ISSUE TITLE
"Latest" documentation is more findable than "stable" documentation

### ISSUE THREAD

**Issue by BrambleRamble** [behave/behave#841]
My team has been using tags to select test scenarios, and we have had quite a lot of frustration trying to get it to behave as documented.

We've realised that we're using Behave v1.2.6, the stable version, but that the documentation we got from the first results from Googling "behave tags" was the latest version, v1.2.7. We didn't realise this mismatch initially, and assumed the documentation applied to the version we were using, even though the features aren't available in it yet.

Is there a way to make the stable version of the documentation more prominent please, and to make the latest version more receding?

**Comment by jenisys** [comment]
Latest documentation is leading edge (and potentially unreleased), but in sync with current development.
Stable documentation edition is referenced in the README file of the Github repository (under: "More Information" at the end of the file)
and points to the last released version of behave (currently: behave v1.2.6).

Check the "New and Notweworthy" section in the docs which features are available in which version.

**Comment by BrambleRamble** [comment]
@jenisys Yes, that's exactly why the `latest` documentation bubbling to the top is unhelpful..

At least two members of our team have found this `latest` documentation at the top of search results. I've also tried searching with Bing on Edge (forgive me) and have the same issue that the `latest` documentation takes precedence over the `stable` version.

If the `latest` version was more obviously experimental, either from its URL or its appearance, then this would be less of an issue, but as it is, there's a significant risk of Behave users unwittingly landing on documentation that doesn't actually describe the version they're running.

**Comment by bittner** [comment]
Personally, I believe the true solution to the "frustration problem" would be issuing releases of `behave` much more often. The "delta" of the current (stable) release and the content of the `master` branch should always be small.

This is a common pattern, a "known issue", across a lot of issues in this project. @jenisys, I'd really try to get that fixed. I hope we can meet in person one day soon, e.g. at the next best Python or Django conference.

**Comment by BrambleRamble** [comment]
@bittner That is a great point. Although I'd still like the documentation that matches what's released to be the most visible/findable/default, with the changes you describe, unintentionally using the `latest` documentation instead would be much less likely to cause significant misunderstandings.

**Comment by Greblys** [comment]
I think documentation should match latest stable version. Highlighting documentation version in the header or somewhere with high visibility might help as well. If latest changes are documented then there should be a note in which version it is available. NodeJS explicitly forces to pick some specific documentation version https://nodejs.org/en/docs/ and leaves notes in which version specific methods are available. Bootstrap has highly visible header if you are reading documentation which is not up to date - https://getbootstrap.com/docs/3.4/css/, it seems behave has opposite problem where documentation is ahead of the release, so similar header might be beneficial.

**Comment by 0buz** [comment]
It doesn't help that even [cucumber.io](https://cucumber.io/docs/installation/python/) links to latest docs, rather than stable. And given that people commonly go for pip installation (stable), you can see how easily one ends up with this confusion.

**Comment by bittner** [comment]
@jenisys The behavior @0buz refers to is that the "plain" RTD link https://behave.readthedocs.io/ redirects to "latest" rather than "stable". This behavior can be configured on RTD. We have this point to "stable" for [behave-django](https://behave-django.readthedocs.io/), for example.

I would suggest:

1. We configure "stable" as the default version (RTD ➜ Admin ➜ Advanced Settings ➜ Default version).
1. We ensure searching works on RTD, fix it otherwise (as reported in https://github.com/behave/behave/issues/783#issuecomment-740566474).

I would also vote for restoring the Alabaster theme for the docs again. That's more beautiful and nicer to read. Was there a specific reason why you changed that in the past?

**Comment by bittner** [comment]
[behave.readthedocs.io](https://behave.readthedocs.io/) now redirects to "stable".  As always, you can still find all versions, including `latest`, in the version selector of the footer.
