### ISSUE TITLE
Run different example tables in the same Scenario Outline

### ISSUE THREAD

**Issue by lucasmoura** [behave/behave#847]
I was trying to write the following scenario outline, where I need to kind of perform a cartesian product between the first set of example and the second set, since I would repeat all of the services commands for different ubuntu releases. I tried to write something like this:

```
   Scenario Outline:  run cmd in a ubuntu container
        Given a `<release>` machine with
        And I run ` <service>` as non-root
        Then I will see the following on stderr:
            """
            This command must be run as root (try using sudo)
            """
        When I run `cmd <service> ` with sudo
        Then I will see the following on stdout:
            """
            Cannot run cmd on a container
            """

        Examples: ubuntu release
            | release |
            | bionic  |
            | focal   |   
            | trusty  |
            | xenial  |

        Examples: Un-supported services in containers
           | service         |
           | service1       |
           | service2       |
           | service3       |
```

But behave cannot recognize the second examples table. Is doing something like this achievable in behave ?

**Comment by thunguyen19** [comment]
Behave does support multiple example tables. Check this out https://github.com/behave/behave/blob/master/docs/gherkin.rst. However I think you should combine your 2 example tables together since they have different column fields. And you need both `release` and `service` values for your steps in the scenario, i.e: 
```
Examples: ubuntu release
            | release | service  |
            | bionic  | service1 |
            | focal   | service2 |
            | trusty  | service3 |
            | xenial  | service4 |
```
Hope this helps.

**Comment by lucasmoura** [comment]
@thunguyen19 I think I have not expressed my idea properly. The idea is to make a cartesian product between two distinct tables. In my example, if I wanted to create a single table, I would have something like this:

``Examples: ubuntu release
            | release | service  |
            | bionic  | service1 |
            | bionic  | service2 |
            | bionic  | service3 |
            | bionic  | service4 |
            | focal  | service1 |
            | focal  | service2 |
            | focal  | service3 |
            | focal  | service4 |
            | xenial  | service1 |
            | xenial  | service2 |
            | xenial  | service3 |
            | xenial  | service4 |
            | trusty  | service1 |
            | trusty  | service2 |
            | trusty  | service3 |
            | trusty  | service4 |
```

And that is extremely verbose. That why I was considering having two distinct tables and be able to do a cartesian product between them

**Comment by jenisys** [comment]
@lucasmora
What you want to achieve is quite clear.
But `behave` is not very good at mind reading with your two example-tables approach (basically violating your required placeholders needed by the ScenarioOutline as template).

You basically need a table-generator that transform one table with 2 columns (or rows) into the cartesian product.
This functionality is not supported yet (and will require an additional "preprocessor stage" before all Scenarios are generated from the ScenarioOutline template and the Example tables).
The solution that works for you right now: Use a text-template engine, like Jinja2, to generate the feature-file for you.
