### ISSUE TITLE
Ambiguity in context attribute lifecycle documentation

### ISSUE THREAD

**Issue by ncoghlan** [behave/behave#849]
https://behave.readthedocs.io/en/latest/context_attributes.html#user-attributes says "A user can assign (or modify) own attributes to the context object. But these attributes will be removed again from the context object depending where these attributes are defined."

It's clear that if you access an existing attribute and mutate it, then that won't change the scope of the attribute being mutated.

The ambiguity relates to operations like `context.test_system = test_system_a`, where `test_system` is an already existing attribute at a higher level of the context.

Does that operation rebind the existing attribute on the scope where it already exists? Or does it temporarily shadow the attribute in the narrower scope, and then revert it back to its previous value once the feature or scenario is completed?

(The situation where this came up is with "initialise on first use, clean up in after_all" fixtures that want to populate state on the root context for cleanup in after_all but are typically handed a feature or scenario level context when they run)

**Comment by jenisys** [comment]
Behave provides a "layered stack" for Context attributes. When you enter a scope, a layer is pushed onto the stack. When you leave the scope, the layer is popped for the stack.

Scopes are:
* test-run (all: before_all(), after_all()
* feature
* rule
* scenario

Context attributes are assigned to the layer that is currently used (if you do not use woodo and black-magic arts).
Therefore, in your case `context.test_system` is/should be temporarily overridden. When the scope is left and the layer is popped, the change is gone (and the original attribute value reappears).

Proof me wrong ;-)
