### ISSUE TITLE
stage steps: Override reused steps from common/other stage(s) with stage-specific Step

### ISSUE THREAD

**Issue by kimjunte** [behave/behave#853]
With the following file structure:

Given a feature file:
---------
/features
----/steps
--------steps.py
----/A_steps
--------steps.py
----foo.feature
----A_environments.py

Running the following command:

$behave --stage=A

This will run the A_enviroments; the features/steps/steps.py files; the features/A_steps/steps.py and run the test for foo.feature.

HOWEVER:

When feature/steps/steps.py has a step definition called @step(u"bar") and feature/A_steps/steps.py has the same step definition @step(u"bar") THEN an AmbigiousError is raised because the same step definition is given.

Is it possible to add a --override flag that allows any same step defintion given to be overriden with the new one present in feature/A_steps/steps.py?

This will allow a 'common' steps definition within steps/steps but however cater to different stage testing for different configuration. Which will allow code to be reused and not just copied and pasted to each different stage directories.

**Comment by spyoungtech** [comment]
As a hack, you could try to remove the previously defined step from the registry before defining the new step. This works, provided that the file containing the 'common' steps is imported/executed first, meaning the filename needs to, alphabetically, come first.



```python
# override_steps.py
@overrides(u'bar', 'step')  # removes the existing definition and adds this one
def special_step(*args, **kwargs):
    print('Overrides the original step!')
```

Additionally, you can make a decorator for the common steps like `@if_not_defined` which can cover the case where the common steps gets imported after the override steps. This avoids the ambiguous step definition error and if used together with `overrides`, should work regardless of the order of imports.

```python
# common_steps.py
@if_not_defined(u'bar', 'step')  # has no effect if the 'bar' step is already defined
def default_step(*args, **kwargs):
    print('This will only fire if no other step "bar" exists')
```

```python
# override_steps.py
@overrides(u'bar', 'step')
def overriden_step(*args, **kwargs):
    print('override!')
```

An implementation of these two decorators can be made as follows:

```python
def overrides(step_text, step_keyword='step'):
    from behave.runner import the_step_registry
    step_type = step_keyword.lower()
    assert step_type in ('given', 'when', 'then', 'step'), f'Invalid step type: {step_type}'
    step_definitions = the_step_registry.steps[step_type]

    def step_decorator(func):
        deco = the_step_registry.make_decorator(step_type)
        for index, existing in enumerate(step_definitions):
            if existing.match(step_text):
                break
        else:
            print('no existing definition to override!')
            deco = deco(step_text)
            return deco(func)

        print(f'replacing step {existing.describe()} from {existing.location} with {func}')
        step_definitions.pop(index)
        deco = deco(step_text)
        return deco(func)  # apply the decorator normally

    return step_decorator


def if_not_defined(step_text, step_keyword='step'):
    from behave.runner import the_step_registry
    step_type = step_keyword.lower()
    assert step_type in ('given', 'when', 'then', 'step'), f'Invalid step type: {step_type}'
    step_definitions = the_step_registry.steps[step_type]
    def step_decorator(func):
        deco = the_step_registry.make_decorator(step_type)
        for index, existing in enumerate(step_definitions):
            if existing.match(step_text):
                break
        else:
            print(f'{step_text} not yet defined! Adding now!')
            deco = deco(step_text)
            return deco(func)

        print(f'step {existing.describe()} already exists in {existing.location}, doing nothing!')
        return func
    return step_decorator
```

An example output might look like this:

```
$ behave --no-capture features/test.feature
bar not yet defined! Adding now!
replacing step @step('bar') from features/steps/common_steps.py:3 with <function overridden_step at 0x104fbfb80>
Feature: testfeature # features/test.feature:2

  Scenario: myscenario  # features/test.feature:4
    Then bar         # features/steps/override_steps.py:3
    Then bar         # features/steps/override_steps.py:3 0.000s

1 feature passed, 0 failed, 0 skipped
1 scenario passed, 0 failed, 0 skipped
1 step passed, 0 failed, 0 skipped, 0 undefined
Took 0m0.000s
```

It would be nice if `behave` provided such a mechanic natively. 

Inability to reuse code was a main motivation for my project [behave-classy](https://github.com/spyoungtech/behave-classy) which provides a class-based approach to defining step definitions, so steps could be re-used across projects/libraries by subclassing.

Hope this helps @kimjunte

**Comment by kimjunte** [comment]
@spyoungtech - Firstly Thank you for such a fantastic response!

I have been 'hacking' my way through the code and managed to implement the hacky first solution you mentioned:
`
def add_step_definition(self, keyword, step_text, func):
    step_location = Match.make_location(func)
    step_type = keyword.lower()
    step_text = _text(step_text)
    step_definitions = self.steps[step_type]

    for existing in step_definitions.copy():
        if self.same_step_definition(existing, step_text, step_location):
            # -- EXACT-STEP: Same step function is already registered.
            # This may occur when a step module imports another one.
            return
        elif existing.match(step_text): 
            step_definitions.remove(existing)
`

But you are completely right - I didn't consider the order in which the files will be imported.

I'll see if your decorator method works for my case - It seems very promising to me and will also look at your behave-classy solution.

Again, thank you for your time and it has been very helpful :)

**Comment by kimjunte** [comment]
"It would be nice if behave provided such a mechanic natively."

Is this something that behave wants to push? I can make a pull request with my changes if this is a design changes that you guys wish for.

Something like --override as in input argument will allow this project to have this feature and safely still pass this test well you guys discuss the design decision. @jenisys

**Comment by jenisys** [comment]
From my point of view, this a step-module organisation problem.
If you move the common steps into smaller step-module(s), it is easier to reuse them in several stages.
If you have too many stages with different requirements (what common steps are and what not), it will grow complicated.

The `@overrides` approach is more fine granular.
But it also makes it easier to shoot your into your foot (if you override the same steps twice in the same stage).
And you must decide if you only override steps that have the same step.pattern (step-text) or any step that matches the step-text (the second approach was taken above).

EXAMPLE: Use common steps via step-library
```
+-- steplib_foo/*.py       -- Provides for common steps for all stages.
+-- features/
       +-- steps/
       |.        +-- use_steplib_foo.py                 -- Just imports common steps from "steplib_foo.*"
       |.        +-- stage_specific_steps_1.py.    -- For default-stage.
       |.        +-- stage_specific_steps_2.py
       +-- A_steps/
       |.        +-- use_steplib_foo.py                 -- Just imports common steps from "steplib_foo.*"
       |.        +-- stage_specific_steps_1.py.    -- For stage=A
       |.        +-- stage_specific_steps_2.py
```

**Comment by kimjunte** [comment]
@jenisys What an interesting take - I'll have a think about that implementation. That you for getting back :)
