### ISSUE TITLE
Behave test failed but Gitlab CI/CD job succeeded 

### ISSUE THREAD

**Issue by 2Dennis** [behave/behave#854]
Hello, 

I've integrated Behave tests in the GitLab CI/CD pipeline and the tests are running successfully. 

However, when a Behave test fails (AssertionError) it should also fail the CI/CD job in GitLab. 
But the job succeeded successfully. 

`behave features/tests/sample-behave-test.feature
`
```
 When the request sends POST                                           # features/steps/api_testing.py:49
    Then the response status is 200                                       # features/steps/api_testing.py:53
      Traceback (most recent call last):
        File "/usr/local/lib/python3.8/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/usr/local/lib/python3.8/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/api_testing.py", line 55, in step_impl
          assert context.api_client.response.status_code == status
      AssertionError

    And the response json contains $.id                                 # None
    And the response time is less than 1.0 seconds               # None


Failing scenarios:
  features/tests/sample-behave-test.feature:2  Behave test

0 features passed, 1 failed, 0 skipped
0 scenarios passed, 1 failed, 0 skipped
4 steps passed, 1 failed, 4 skipped, 0 undefined
Took 0m0.050s

```

**`Job succeeded`**

Any reason why this job succeeded successfully?

**Comment by jenisys** [comment]
Behave ensures that a not-zero (FAILED) error code is returned when an Exceptions are raised (or an exception is raised).
Therefore, the problem is probably located elsewhere, like:

* CI build scripts ignores exit-code and passes SUCCESS (0).
* behave script was patched (by you or ...)
* ...

**Comment by denravonska** [comment]
If the Gitlab pipes work anything like Azure Devops it only uses the exit code from the last command in the job. Double check that you don't have an additional command after invoking Behave. If you do, capture the Behave return code, do your other things and then exit with the captured code at the end.
