### ISSUE TITLE
behave reports passing features when no features were tested

### ISSUE THREAD

**Issue by artlivongo** [behave/behave#856]
When my test setup fails in environment.py because appium fails to initialize, behave reports 1 feature as passing even though none of the feature files were tested:

```
HOOK-ERROR in before_all: MaxRetryError: HTTPConnectionPool(host='localhost', port=4722): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9169a299a0>: Failed to establish a new connection: [Errno 61] Connection refused'))

ABORTED: By user.
1 feature passed, 0 failed, 0 skipped, 9 untested
0 scenarios passed, 0 failed, 0 skipped, 153 untested
0 steps passed, 0 failed, 0 skipped, 0 undefined, 1162 untested
Took 0m0.000s
```

**Comment by jenisys** [comment]
The features/runner.hook_errors.feature test says otherwise (while raising an exception in the before_all() hook).
I assume the problem is on your side (your environment, your setup, ...).

* Which version of behave are you using?
* What Python version ?
* Which operation system (and version) ?

**Comment by artlivongo** [comment]
@jenisys Here's my setup:
Behave - 1.2.6
Python - 3.7.6
OSX - 10.14.6

**Comment by jenisys** [comment]
Ok, looks good.

Now I need more information, like a simple GIST example or a simplified description of how you setup your project.
But as I already said, the problem should be lurking somewhere in your (workspace) environment.

**Comment by jenisys** [comment]
One simple try would be if you get a different behavior with the current TIP/HEAD of the Git repository.

**Comment by jenisys** [comment]
Closed due to inactivity.
