### ISSUE TITLE
Implementing a step to run a feature file

### ISSUE THREAD

**Issue by leonardopsantos** [behave/behave#857]
I have a series of embedded applications that I use Behave to test, so I have several folders with feature files and step implementations. To test each application, I go into each one of the application folders and run Behave.

I was thinking about how can I create a top-level test file that I could run to test all applications.

I know Gherkin doesn't allow importing a feature file into another feature file, so I can't have a top-level file that imports the other feature files.

I think the obvious answer would be to move the individual feature files for each test to as scenarios in a top-level feature file and control what is tested with tags. That would be doable but is a lot of re-work and I'd rather not deal with all the possible interactions between the different scenarios.

And what if I created this top-level test as a separate Behave test that would go into each individual folder and run Behave? Let's say that I have the following folder structure:

```
samples/
│
└tests/
 │
 ├── BehaveTest1
 │   ├── BehaveTest1.feature
 │   └── steps
 │       └── test_steps.py
 └── BehaveTest2
     ├── BehaveTest2.feature
     └── steps
         └── test_steps.py

```

I know I can run Behave in both folders with

`behave samples/tests/BehaveTest*`

How can I use Behave to automate that?

In the samples folder I could have a feature file like:

```
Feature: Test everything

  Scenario Outline: Test all samples
    Given the test folder is"<test_folder>"
     When we run the test
     Then the test is successful

Examples:
  | test_folder                   |
  | samples/tests/BehaveTest1     |
  | samples/tests/BehaveTest2     |
```

The step implementation would change to the correct folder and load the feature file. I could do that with 

```
@step('the test folder is "test_folder"')
def step_impl(context, test_folder):
    command = ['behave', test_folder]
    subprocess.call(command)
```

I think it's a bit silly to use subprocess to call Behave form within Behave. Is there a way to do that programatically?

Thanks!

**Comment by jenisys** [comment]
From my point of view, you are trying to solve the problem from the wrong side (meaning: You want to solve it in behave).
You need either:

* Build script that performs the test run (build automation/coordination), like [invoke](https://pyinvoke.org) (see: [behave: tasks/test.py](https://github.com/behave/behave/blob/master/tasks/test.py#L61) and using `invoke test.behave`)
* A special test-runner that performs the coordination (currently)

SIDE NOTE:
If you still want to solve in behave: [more.features/run_examples.feature](https://github.com/behave/behave/blob/master/more.features/run_examples.feature)
But this approach hides the cory details during the test run.
