### ISSUE TITLE
How standardize domain language using Behave python BDD Framework

### ISSUE THREAD

**Issue by gaganhattar** [behave/behave#858]
Hi, I wish to use the similar capability in Robot Framework (using Keywords) in Behave to enforce/reuse domain specific language in feature files.
Please help in defining the steps involved.
Thanks

**Comment by jenisys** [comment]
That is an extremely general question.
From my experience, it helps by writing down some features and scenarios.
The "domain specific language" (DSL) normally evolves from trying to express yourself in the scenarios.
Over time, you will see what is good and what is not.

In addition, it helps if you understand what features / functionality is provided by Gherkin to express yourself in behave (or cucumber or any other BDD framework).

If you have already used the Robot framework in the Given/When/Then style, it should not be so different.
Note that I am not an expert in the Robot framework, but I looked several times into it, if it would be useful for me.

**Comment by jenisys** [comment]
That is an extremely general question.
From my experience, it helps by writing down some features and scenarios.
The "domain specific language" (DSL) normally evolves from trying to express yourself in the scenarios.
Over time, you will see what is good and what is not.

In addition, it helps if you understand what features / functionality is provided by Gherkin to express yourself in behave (or cucumber or any other BDD framework).

If you have already used the Robot framework in the Given/When/Then style, it should not be so different.
Note that I am not an expert in the Robot framework, but I looked several times into it, if it would be useful for me.

**Comment by jenisys** [comment]
That is an extremely general question.
From my experience, it helps by writing down some features and scenarios.
The "domain specific language" (DSL) normally evolves from trying to express yourself in the scenarios.
Over time, you will see what is good and what is not.

In addition, it helps if you understand what features / functionality is provided by Gherkin to express yourself in behave (or cucumber or any other BDD framework).

If you have already used the Robot framework in the Given/When/Then style, it should not be so different.
Note that I am not an expert in the Robot framework, but I looked several times into it, if it would be useful for me.

**Comment by jenisys** [comment]
That is an extremely general question.
From my experience, it helps by writing down some features and scenarios.
The "domain specific language" (DSL) normally evolves from trying to express yourself in the scenarios.
Over time, you will see what is good and what is not.

In addition, it helps if you understand what features / functionality is provided by Gherkin to express yourself in behave (or cucumber or any other BDD framework).

If you have already used the Robot framework in the Given/When/Then style, it should not be so different.
Note that I am not an expert in the Robot framework, but I looked several times into it, if it would be useful for me.

**Comment by jenisys** [comment]
That is an extremely general question.
From my experience, it helps by writing down some features and scenarios.
The "domain specific language" (DSL) normally evolves from trying to express yourself in the scenarios.
Over time, you will see what is good and what is not.

In addition, it helps if you understand what features / functionality is provided by Gherkin to express yourself in behave (or cucumber or any other BDD framework).

If you have already used the Robot framework in the Given/When/Then style, it should not be so different.
Note that I am not an expert in the Robot framework, but I looked several times into it, if it would be useful for me.

**Comment by jenisys** [comment]
That is an extremely general question.
From my experience, it helps by writing down some features and scenarios.
The "domain specific language" (DSL) normally evolves from trying to express yourself in the scenarios.
Over time, you will see what is good and what is not.

In addition, it helps if you understand what features / functionality is provided by Gherkin to express yourself in behave (or cucumber or any other BDD framework).

If you have already used the Robot framework in the Given/When/Then style, it should not be so different.
Note that I am not an expert in the Robot framework, but I looked several times into it, if it would be useful for me.

**Comment by gaganhattar** [comment]
Hi jenisys,
In robot Framework we can set the domain specific Keyword libraries that can be reused/inherited by other feature/robot file, this way, the language is standardized. 
For Example: In any feature file: Given the browser shows {page}
In Keyword python Library: @keyword(name=r'the browser shows {page}'
Hence there is no need to implement step definition whenever this generic keyword is used and also the language is standardized whenever this type of case needs to specify.
Thanks

**Comment by jenisys** [comment]
I am not quite sure what your point is.
In behave, you can provide and use step-libraries so that you can use a step-library in several projects (if that was your core point). In addition, steps (step-implementations) are not bound to a specific feature-file.

SEE ALSO:
* [features/step.use_step_library.feature](https://github.com/behave/behave/blob/master/features/step.use_step_library.feature)
* [features/steps/use_steplib_behave4cmd.py](https://github.com/behave/behave/blob/master/features/steps/use_steplib_behave4cmd.py)

**Comment by gaganhattar** [comment]
Cheers, can you share any example for using step registry to expose pre-defined steps (1 time implementation) as:https://behave-webdriver.readthedocs.io/en/stable/steps.html that don't require any stepDefinition implementation while re-use these generic specific steps in any feature file.


https://behave-webdriver.readthedocs.io/en/stable/quickstart.html#importing-the-step-implementations


Thanks,Gagan
    On Wednesday, 26 August 2020, 01:29:29 pm GMT-7, jenisys <notifications@github.com> wrote:  
 
 


That is an extremely general question.
From my experience, it helps by writing down some features and scenarios.
The "domain specific language" (DSL) normally evolves from trying to express yourself in the scenarios.
Over time, you will see what is good and what is not.

In addition, it helps if you understand what features / functionality is provided by Gherkin to express yourself in behave (or cucumber or any other BDD framework).

If you have already used the Robot framework in the Given/When/Then style, it should not be so different.
Note that I am not an expert in the Robot framework, but I looked several times into it, if it would be useful for me.
