### ISSUE TITLE
Question regarding cleanup points

### ISSUE THREAD

**Issue by samapara** [behave/behave#861]
I wanted to know if I can only login once and perform all scenarios execution and at end I close the browser. 
I tired but I came to know that behave clears all the context objects after every scenario, so is there any other way I can achieve this thing? Please help, I really need to achieve this.

Thanks in advance.

**Comment by jenisys** [comment]
The cleanups occur at the level where you entered them.
Meaning, if you add variable to the context while executing a scenario, the variable will be removed at the end of the scenarios and the registered cleanups for this scenario will be executed.

If you enter a variable in the "before_all()" will remain valid until the end of the test-run (but you mean override in the future/scenario).

Same if you enter a variable in the "before_feature()" hook, the variable will be valid until the end of the feature.

SEE ALSO:
* https://behave.readthedocs.io/en/latest/context_attributes.html#user-attributes (lifecycle layer scope)
* https://behave.readthedocs.io/en/latest/new_and_noteworthy_v1.2.6.html?highlight=Cleanups#context-based-cleanups
* https://behave.readthedocs.io/en/latest/fixtures.html?highlight=Cleanups#fixture-cleanup-points
