### ISSUE TITLE
allow an easy add_cleanup() hiding stdout (capturing to throw it away)

### ISSUE THREAD

**Issue by praiskup** [behave/behave#863]
Seems like that at the time of evaluation `cleanup_func` method, the standard output
is not capture as it is done for the normal steps.

**Comment by jenisys** [comment]
Output/Log capture mechanism is currently around the execution of steps.
Cleanup functions are normally executed approx.  at the after-hooks (after_scenario(), after_feature(), after_tag(), etc.).

**Comment by praiskup** [comment]
Work-around is to use something like `with no_output():` before each command
producing stdout with:
```
@contextmanager
def no_output():
    """
    Suppress stdout/stderr when it is not captured by behave
    https://github.com/behave/behave/issues/863
    """
    real_out = sys.stdout, sys.stderr
    sys.stdout = io.StringIO()
    sys.stderr = io.StringIO()
    yield
    sys.stdout, sys.stderr = real_out
```
https://pagure.io/fork/praiskup/copr/copr/c/c4e07c771c89b0b45bdcee4dd20111174b44f558

But it would be nice if I could just use some built-in.

**Comment by jenisys** [comment]
What is your intention?
Show cleanup-errors or hide cleanup-errors.
The latter case can be configured:

```py
# — features/environment.py
from behave.runner import Context
def before_all(ctx):
     # — SILENCE ANY CLEANUP ERRORS (and hide them in summary):
     ctx.on_cleanup_error = Context.ignore_cleanup_error
     ctx.fail_on_cleanup_errors = False  # Hide errors in summary
```
Or use a fixture/fixture-tag to enable your current cleanup-error handling strategy for a feature/scenario, etc. The problem w/ Context.ignore_cleanup_error is currently that you no longer know why a feature/scenario has failed.

**Comment by praiskup** [comment]
> Show cleanup-errors or hide cleanup-errors.
> ctx.on_cleanup_error = Context.ignore_cleanup_error

Sounds interesting, but I don't care about errors that much ... I only care about the
stderr/stdout output which is produced by some subprocess calls in the cleanup hook.
I don't want _that_ output to break the nice colorized behave messages.

**Comment by praiskup** [comment]
IOW, I have to do:
```
def clean_project(context, project):
    """ Clean copr project by copr-cli """
    with no_output():
        rc, out, err = context.cli.run(["delete", project])
    ...

@given(u'a project that builds packages for this system')
def step_impl(context):
    ...
    context.add_cleanup(clean_project, context, name)
    ...
```

If I don't do the `with no_output()`, the command `cli.run()` poisons the
otherwise polished behave terminal window.  In normal step_impl it is
not a problem because the stdout is hidden as long as there's no failure.

**Comment by jenisys** [comment]
You have a rather specialized feature that is hiding output (not really capturing it).
You have your solution. But currently I see no need to provide this functionality within `behave`.
