### ISSUE TITLE
Manipulating step parameters

### ISSUE THREAD

**Issue by trashbat** [behave/behave#866]
My test suite makes fairly heavy use of the .behaverc file, and I'm wondering if there's a way to automatically interpolate strings from the feature file using the values in .behaverc. I'm already doing it manually, but I have to remember to include the same line of code everywhere that I need to do it.

Here's a simplified example, with a single config setting in my .behaverc file (in reality I have about 12):

```dosini
[behave.userdata]
workspace_path=C:/path/to/workspace
```

My feature file could look something like this, I'm actually testing the UI of an IDE:

```gherkin
Feature: Example feature

  Scenario: Check that clicking on the build button produces the expected files
    When I click on the build button
    And I wait 5 minutes for the progress bar to finish
    Then the file "${workspace_path}/build_artefact.ext" should exist
```

The following code does exactly what I need it to do:

```python
from string import Template

from assertpy import assert_that
from behave import *


@then('the file "{filename}" should exist')
def step_impl(context, filename):
    filename = Template(filename).substitute(context.config.userdata)

    assert_that(filename).exists()
```

The problem I have is that it's a large test suite with more than 80 step implementation functions, and almost every time I create a new one I need to include the `Template(...).substitute(...)` line. Is there somewhere that I can hook into in order to manipulate the parameters that are passed to `step_impl()`; perhaps indicating the ones that could contain variables by using a specific naming convention (e.g. parameter name ends with "_template", such as "filename_template" in the above example) or writing a custom step matcher that extends the default?

**Comment by jenisys** [comment]
Use an TypeConverter in your step implementation for the step parameters that:
* matches the ${...} placeholder style
* retrieves the placeholder value from the userdata

Same problem arrives when you directly want to use environment-variable values with the same dollar-style placeholders.

**Comment by jenisys** [comment]
The other solution would be to provide a decorator for the step implementations that acts as preprocessor for the step parameter values.

```python
@step("I use "{filename} ...")
@replace_userdata_placeholders_in_step_params(params=["filename"])
def step_impl(ctx, filename, ...):
    ...
```

**Comment by trashbat** [comment]
Thanks, I'm going to try both of those and see which is a better fit.
