### ISSUE TITLE
Type registration not executed unless step defined in file

### ISSUE THREAD

**Issue by domingezjorge46** [behave/behave#868]
I would like to concentrate all the my specific type parsers registrations in a single file. However, these type registrations are not executed unless there is at least one step defined in the file that defines them - preferably a step that use that registered type. Ideally, I would like to execute all registrations in the `before_all` hook - but this is too late since by then the feature files are already parsed and the parser complains it does not recognize my types.

**Comment by jenisys** [comment]
This statement is not quite correct.
You can import your module(s) with type registrations either in:
* `features/environment.py` (before any steps are imported)
* `features/steps/*.py`

**Comment by domingezjorge46** [comment]
My bad - I did not define the registration method(s) as top-level ones but rather called them from `before_all`.
