### ISSUE TITLE
Documentation: Tags expressions should use `~` operator instead of 'not' for versions <= 1.2.6

### ISSUE THREAD

**Issue by domingezjorge46** [behave/behave#869]
The available documentation gives examples using "not" whereas the real operator is "~" - i.e. instead of `behave ... --tags="not wip"` one should use `behave --tags="~wip"` (I am referring to version 1.2.6).

**Comment by domingezjorge46** [comment]
I guess the documentation relates to version 1.2.7 - see [Cucumber - Migrating from old style tags](https://github.com/cucumber/cucumber/tree/master/tag-expressions#migrating-from-old-style-tags)

**Comment by jenisys** [comment]
Correct, the [LATEST documentation](http://behave.readthedocs.io/en/latest/) is for the bleeding edge development.
It describes/uses the [new tag-expressions](https://behave.readthedocs.io/en/latest/new_and_noteworthy_v1.2.7.html?highlight=tag%20expressions#tag-expressions-v2) (tag expressions v2).

The [STABLE documentation](http://behave.readthedocs.io/en/stable/) reflects to the latest release (behave v1.2.6).

SEE ALSO:
* https://behave.readthedocs.io/en/latest/new_and_noteworthy_v1.2.7.html#tag-expressions-v2
* https://behave.readthedocs.io/en/latest/tag_expressions.html
