### ISSUE TITLE
How to do such a logotype? :)

### ISSUE THREAD

**Issue by JulianVolodia** [behave/behave#870]
Hello Dear @jenisys , appreciate project. Could You tell me how You generate the image from words because I not found any documentation in commits from docs/_static/*.png in this repo.

Thanks, have a great weekend

Cheers! 😊

**Comment by jenisys** [comment]
I basically used [PyTagCloud](https://github.com/jenisys/PyTagCloud) forked from [atizo/PyTagCloud](https://github.com/atizo/PyTagCloud) ;-)

**Comment by JulianVolodia** [comment]
Thanks @jenisys  <3

Have a great day
