### ISSUE TITLE
call reset_runtime()

### ISSUE THREAD

**Issue by berndhahnebach** [behave/behave#871]
I run into the `behave.step_registry.AmbiguousStep` failure

see https://github.com/behave/behave/issues/209, https://github.com/behave/behave/issues/264, https://github.com/behave/behave/issues/549

How do I run `reset_runtime()`

I did a grep on behave source on Debian but there is no `reset_runtime()` 

I have version 1.2.5-2 installed https://packages.debian.org/buster/python3-behave

**Comment by jenisys** [comment]
Why are you using a completely outdated version of behave ?

You should know that the Debian package management is normally extremely conservative.
This means if you develop something on Debian, you need to build your own libs/toolchains/development resources to be somewhat up-to-date.


USE:
```sh
# -- EXAMPLE: With Python3 (with Debian buster you should have Python 3.7 or 3.8)
sudo apt-get install python3-pip
sudo pip3 install -U "behave>=1.2.6"
```

SEE ALSO:
* [behave/__main__.py:13](https://github.com/behave/behave/blob/master/behave/__main__.py#L13)

**Comment by berndhahnebach** [comment]
For the simple reason it is what is included in Buster. Thanks for the hints. I will give it a try and report back.

bernd

**Comment by berndhahnebach** [comment]
import works great, but still I get the error ... 

```
# clean logs to be able to run tests again but on another building model
# https://github.com/behave/behave/issues/871
from behave.runner_util import reset_runtime
reset_runtime()

# run tests
from behave.__main__ import main as behave_main
behave_main(behave_args)
```


```
  File "C:\Users\BHA\AppData\Roaming\FreeCAD\Mod\bimtester\code_bimtester\fcbimtester.py", line 147, in run_intmp_tests
    behave_main(behave_args)
  File "C:\0_BHA_privat\progr\FreeCAD_0.19.xxxxx_Py3Qt5\bin\lib\behave\__main__.py", line 183, in main
    return run_behave(config)
  File "C:\0_BHA_privat\progr\FreeCAD_0.19.xxxxx_Py3Qt5\bin\lib\behave\__main__.py", line 127, in run_behave
    failed = runner.run()
  File "C:\0_BHA_privat\progr\FreeCAD_0.19.xxxxx_Py3Qt5\bin\lib\behave\runner.py", line 804, in run
    return self.run_with_paths()
  File "C:\0_BHA_privat\progr\FreeCAD_0.19.xxxxx_Py3Qt5\bin\lib\behave\runner.py", line 809, in run_with_paths
    self.load_step_definitions()
  File "C:\0_BHA_privat\progr\FreeCAD_0.19.xxxxx_Py3Qt5\bin\lib\behave\runner.py", line 796, in load_step_definitions
    load_step_modules(step_paths)
  File "C:\0_BHA_privat\progr\FreeCAD_0.19.xxxxx_Py3Qt5\bin\lib\behave\runner_util.py", line 412, in load_step_modules
    exec_file(os.path.join(path, name), step_module_globals)
  File "C:\0_BHA_privat\progr\FreeCAD_0.19.xxxxx_Py3Qt5\bin\lib\behave\runner_util.py", line 386, in exec_file
    exec(code, globals_, locals_)
  File "..\..\..\..\Users\BHA\AppData\Local\Temp\tmprkd1z0zu\features\steps\classification.py", line 13, in <module>
    @step(u'The classification {name} must be used')
  File "C:\0_BHA_privat\progr\FreeCAD_0.19.xxxxx_Py3Qt5\bin\lib\behave\step_registry.py", line 92, in wrapper
    self.add_step_definition(step_type, step_text, func)
  File "C:\0_BHA_privat\progr\FreeCAD_0.19.xxxxx_Py3Qt5\bin\lib\behave\step_registry.py", line 58, in add_step_definition
    raise AmbiguousStep(m<class 'behave.step_registry.AmbiguousStep'>: @step('The classification {name} must be used') has already been defined in
  existing step @step('The classification {name} must be used') at ../../../../Users/BHA/AppData/Local/Temp/tmpm5q2vsv7/features/steps/classification.py:13
```

**Comment by jenisys** [comment]
Look at [features/step.duplicated_step.feature](https://github.com/behave/behave/blob/master/features/step.duplicated_step.feature) if that helps you (and run the feature test).

What is weird in your case:
* LAST_ENTRY-2 features\steps\classification.py", line 13
* LAST_ENTRY: Indicates that the step exists already at features/steps/classification.py:13 (SAME-FILE-LOCATION)
* The stack trace has Windows filename/path conventions, but you told me that you are using Debian Buster.
  Are you using "Windows Subsystem for Linux" (WSL) with Debian Buster ? 
  (and reusing the Windows Python installation which would be rather BAD ?!?)

In my example from above, I get the following stack trace:
```bash
#-- DUPLICATED STEPS: features/steps/alice_steps.py: line 3 and line 7
$ behave features/step.duplicated_step.feature:8

  File "/.../behave_master.tip/behave/runner_util.py", line 581, in load_step_modules
    exec_file(os.path.join(path, name), step_module_globals)
  File "/.../behave_master.tip/behave/runner_util.py", line 555, in exec_file
    exec(code, globals_, locals_)
  File "features/steps/alice_steps.py", line 7, in <module>                 <=== PROBLEMATIC DUPLICATING-STEP (second one)
    @given(u'I call Alice')
  File "/.../behave_master.tip/behave/step_registry.py", line 92, in wrapper
    self.add_step_definition(step_type, step_text, func)
  File "/.../behave_master.tip/behave/step_registry.py", line 58, in add_step_definition
    raise AmbiguousStep(message % (new_step, existing_step))
behave.step_registry.AmbiguousStep: @given('I call Alice') has already been defined in
  existing step @given('I call Alice') at features/steps/alice_steps.py:3   <=== PROBLEMATIC-STEP OCCURED HERE FIRST.
```

It is probably best if you:

* Update to the newest version (or the repository HEAD of master branch) and retry if the problem is solved 
* Use the debugger to debug the step-loading mechanism
* Use diagnostic print statements in "behave/step_registry.py::StepRegistry::add_step_definition()" (on file locations of registered steps)

NOTE:
* Your behave version uses other line numbers than mine (but I am currently using the git-repo master branch).
* From my experience with WSL, you should work only inside the WSL filesystem when your are using WSL (and in the Windows-Filesystem when you are using Windows). Weird things seem to happen if you edit/modify a file under Windows/Windows-Application from the WSL Filesystem and vice versa (and try to fix the Unix file permissions for example).

**Comment by berndhahnebach** [comment]
I do not use WSL at all. I just run the same code on Windwos and on Linux depending which machine I am sitting at. But happily I run behave mostly on Linux. I did not know I had the 1.26 version of behave on Windows already. Thus I started testing more deeper on Windows without even upgrade behave on Buster.

Thanks again for all the hints. It will take some time to go through all. 

Might be interesting for you. It is about bimtester. We use behave for testing features (attributes, geometry etc) of building model data. Thus run the test on a modell, afterwards run the same test suite (featrues and steps) on the next model data and so on.

**Comment by jenisys** [comment]
Sounds interesting.

In some way similar to what I do with behave feature tests by using behave4cmd0 steps and test support to test behave itself
(or “behave.example” that does something similar by using sphinx to run behave examples and capture its output and verifies that no error(s) occur => Self-documenting/self-verifying that the examples work and the output represents the current version of behave.)

**Comment by berndhahnebach** [comment]
installed latest behave on windows, https://github.com/behave/behave/commit/3eb88d4517838ae2651ede5d75facdecdf186843 had to install https://github.com/cucumber/tag-expressions-python as well. The  error keeps, no reset seams to be done.

OK will try the other suggestions you made.

May be one mor information. Since I do not would like to copy the feature files to the source code (the step files), because the featrue files change due to test requirement and I do not want to copy the step to the feature files and delete them afterwards I decided to copy all (building model data, step and feature files) in a unique temp directory (unique for each new test run) run behave with this data.

**Comment by berndhahnebach** [comment]
If not a unique directory is used but the same temporary directory every time it works well. Before every run the directory is deleted and recreated. The `AmbiguousStep`  does not raise in this case.

**Comment by jenisys** [comment]
Your analysis hints that you are using the same steps from duplicated unique directories.
Therefore, Ambiguous steps error works as design in my opinion.
The use of step-libraries within your python search path should remedy this problem (without knowing too many details of your use case).
