### ISSUE TITLE
Issue with Behave failure and skip

### ISSUE THREAD

**Issue by subbro** [behave/behave#878]
Hi,
I have one issue. Say i have 5 steps and 3rd step fails, I see that the next two steps are marked as Passed in first run and if it fails again at 3rd step then the next two steps are skipped in 2nd run.
I have the autoretry logic in before_scenario() to run twice

@jenisys please help me on this. Any insights that you could give me

Thanks,

**Comment by jenisys** [comment]
As already stated, analyse what is causing the flaky test and fix it.

**Comment by subbro** [comment]
Let us continue here rather than on #299 please

**Comment by jenisys** [comment]
Why should the retry logic cause this failure.
The retry logic only kicks in when a failure has occurred. Therefore, there is probably a problem in your given steps (and the underlying assumptions). They should be written in such a way that they are idempotent, meaning the do what is necessary but do not cause any problem when they are done multiple times.

**Comment by jenisys** [comment]
In general, you should use the retry logic only on flaky tests. And it is only a temporary work-around until you have fixed the flaky test.

**Comment by subbro** [comment]
Okay , let me intentionally fail few tests and get back to you with my observations.

**Comment by subbro** [comment]
I think the issue is with the allure-behave reporting tool that I am using. Please let me know if you have any insight over that

**Comment by jenisys** [comment]
@subbro Then you should add an issue (bug report) to https://github.com/allure-framework/allure-python
