### ISSUE TITLE
Dynamically load features in other directories

### ISSUE THREAD

**Issue by vincent-lg** [behave/behave#881]
Hi,

Maybe that's already doable at the time (I saw a similar issue and a mention of Behave feature libraries, though I couldn't find any documentation on the topic).

I would like to be able to dynamically specify other feature directories in my `environment.py` file.  Here's my current directory structure:

    src/
        ...
        features/
            *.feature
            steps/
            environment.py
        plugins/
            atom/
                features/
                    *.feature
                ...
            pdf/
                features/
                    *.feature
                ...

In this simple directory hierarchy, I have two plugins, "atom" and "pdf".  They're not always active so I don't want to test their feature no matter what.  Instead I have a general setting in code (say, a Python tuple containing the names of the installed plugins).

In my `src/features/environment.py` file, I would like to add possible features path.  In my case, I would like to add the path of installed plugins and ignored non-installed plugins.

That might sound pretty specific, but I'm sure you can find other use cases for this feature.  Again, there might be a way to do that.  The difficulty, of course, arises from the fact that when `src/features/environment.py` is loaded, the directories of features is probably already set (and cannot be extended).  I could "dynamically" edit a config file, of course, this would just be a bit messy.

Thanks in advance,

Vincent

**Comment by bittner** [comment]
There was, what I think is, [a similar question](https://github.com/behave/behave-django/issues/115) on the `behave-django` issue tracker.

With our test setup [we use "decorators"](https://github.com/behave/behave-django/blob/master/tests/acceptance/features/fixture-loading.feature#L1) in the `.feature` files, and [selectively run](https://github.com/behave/behave-django/blob/master/tox.ini#L28-L29) the related tests using behave's `--tags` option.

So, if "dynamically" is satisfied by "when the test run is started" maybe you could use tags and separate test runs? Would that already meet your needs?

**Comment by jenisys** [comment]
@vincent-lg 
That should already work, but try it out and complain if not.

CONSTRAINTS (from the current Test Runner):
* There is only one location from where to load steps and the environment file
* The first command line parameter (feature-file or feature-directory) is used to discover where the steps-directory is and the "environment.py" file (if any is provided).
* As long as you always use the feature directory or feature-files from your main directory before adding other feature-directories or other feature-files from other directories, you should be fine

EXAMPLE:
```bash
$ behave --dry-run -f progress features/ plugin/atom/features/
...
# -- EXPECTED: 
# The progress-Formatter shows the filenames of all processed feature files.
# Due to dry-run mode, all features are skipped (no need to wait for execution of the tests/scenarios).
#  * Runs all features from the features/ directory.
#  * Runs all features from the plugin/atom/features/ directory, too.
```

**Comment by vincent-lg** [comment]
@jenisys: that's what I did.  In my case, I would have liked behave to be "smart" and only load features of plugins/atom if the plugin was installed (similar to a Django setup).  My workaround at the time is pretty ugly, but I've created a simple Python file that calls behave.main() and calculates at runtime the arguments it should give it.  Not ideal, I know, and there might be better ways to do that, but for the time being, it works, and that's something.

**Comment by jenisys** [comment]
From my point of view, using active-tags is the better choice.
Changing the command-line arguments (or appending to them) is a rather corner-case. Therefore, it is not supported directly.

Behave can not know what you want to achieve. Therefore, there needs to be some code from your side that guides it. That is also the case with the skip-if logic for active-tags. In addition, many test frameworks have such a skip-if support. 

What you are trying to achieve is pretty weird to support inside the tool. I haven't seen it yet in any other test framework. It is far easier to support it outside the tool (in a build-script/build-system or a command-wrapper). That is also the reason why your "hack" works (and was easy/easier to implement).

**Comment by vincent-lg** [comment]
Yes, all that is true.  Besides it turns out I'll have to have greater control of what .feature file to run, as they can "replace" each other in my plugin hierarchy.  So I'll keep on trudging this uncertain road. Thanks for the answers!  Closing this.
