### ISSUE TITLE
get the feature file language setting with a context attribute

### ISSUE THREAD

**Issue by berndhahnebach** [behave/behave#885]
In the feature file it is possible to set the native language by 

`# language: de`

Is it possible to retrieve this setting with the context after each feature in environment module?

Eventually I need this information somehow for each feature in the json report.

**Comment by jenisys** [comment]
* There is a `language` attribute in the `Feature` class that you can use
* Use `ctx.feature` to access the current feature during a test run
* The `language` information is currently not part of the JSON output schema

SEE ALSO:
* [behave docs: api -- Feature.language attribute](https://behave.readthedocs.io/en/latest/api.html?highlight=language#behave.model.Feature.language)
* https://behave.readthedocs.io/en/latest/context_attributes.html
