### ISSUE TITLE
Add logs and steps in python behave html formatter report

### ISSUE THREAD

**Issue by swatantra15081986** [behave/behave#888]
I want to add logs and steps in behave html report which is showing in CLI . How can it add ?

**Comment by bittner** [comment]
_Note: If this request is specific to [HTML formatter](https://github.com/behave-contrib/behave-html-formatter/) it would be more appropriate and efficient to open an issue there._

Related:

- #791
- #819

**Comment by bittner** [comment]
I just merged a contribution by @Korijn that adds an `attach` method to the `context` object. An example might look like:

```python
image = context.browser.get_full_page_screenshot_as_png()
context.attach("image/png", image)
```

Please verify yourself whether this works with `behave-html-formatter` and the latest `behave` off the `master` branch. If it doesn't we might have to adapt the [embedding](https://github.com/behave-contrib/behave-html-formatter/blob/master/behave_html_formatter/html.py#L540-L542) method of the `HTMLFormatter` class.

**Comment by swatantra15081986** [comment]
@bittner : I tried it, but it doesn't work. It is not attaching screenshot in behave-html.

Code in environment.py  :   -

def after_scenario(context, scenario):
    # Take screenshot if scenario fails
    if scenario.status == 'failed':
        image = context.browser.get_full_page_screenshot_as_png()
        context.attach("image/png", image

**Comment by bittner** [comment]
Are you using both `behave` and `behave-html-formatter` off the `master` branch? You can install them like this:

```console
python3 -m pip install -U git+https://github.com/behave/behave#egg=behave
python3 -m pip install -U git+https://github.com/behave-contrib/behave-html-formatter#egg=behave_html_formatter
```

You should be able to verify that you have a recent version installed by successfully attaching a screenshot with the `json` formatter (this feature was merged recently). Then try again with the HTML formatter. If that still doesn't work it would be helpful if you can find out what is the problem.

We could then go from there with a PR on [behave-contrib/behave-html-formatter](https://github.com/behave-contrib/behave-html-formatter). Alternatively, please come up with a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), including all setup steps.

**Comment by swatantra15081986** [comment]
When going with https://github.com/behave-contrib/behave-html-formatter
It's showing to install tox, is it using for behave html formatter ?

**Comment by jenisys** [comment]
@swatantra15081986 
This issue should be worked on in the [behave-html-formatter](https://github.com/behave-contrib/behave-html-formatter) repository. Therefore, open the correct issue there.

NOTE: If we stumble over something that is missing in `behave` to make it work, we can add an associated issue here.

**Comment by swatantra15081986** [comment]
Hi

What is the Ubuntu command of following :

html = behave_html_formatter:HTMLFormatter

**Comment by jenisys** [comment]
That is a formatter-alias that you can use if you have [behave-html-formatter](https://github.com/behave-contrib/behave-html-formatter) installed (same as for: allure-behave formatter; and has nothing to do with Ubuntu):

```bash
# -- SCHEMA in config-file: "name_alias = scoped_class_name" (of the Formatter class)
$ behave -f html -o report.html ...
```

SEE ALSO:

* https://github.com/behave-contrib/behave-html-formatter

**Comment by jigisha9** [comment]
```
 def after_scenario(context, scenario):
    print("AFTER SCENARIO")
    if scenario.status == 'failed':
            image = context.browser.get_full_page_screenshot_as_png()
            context.attach("image/png", "pageImage.png")

```
**AttributeError: 'DriverFactory' object has no attribute 'get_full_page_screenshot_as_png'
AttributeError: 'Context' object has no attribute 'attach'**


if I use context.browser.driver.save_screenshot("pageImage.png") it does takes screenshot, but then getting error on "attach"

How to make it work?

PS: I have already set behave formatter in behave.ini. Above code is in environment.py

**Comment by swatantra15081986** [comment]
Is it fixed ?
