### ISSUE TITLE
Warn or error about incorrectly configured formatter aliases

### ISSUE THREAD

**Issue by bittner** [behave/behave#889]
Currently, when you configure an alias for a formatter, and you configure it wrongly, `behave` doesn't error out (which is okay) but you also get no feedback about what's wrong, i.e. why the formatter alias doesn't work.

## Example

```ini
#-- FILE: behave.ini
[behave.formatters]
html = behave_html_formatter.HTMLFormatter
```
Note the period (`.`), which should really be a colon (`:`).

As a result, the `--format=help` screen shows the alias without a description:
```console
$ behave -f help
Available formatters:
  html           
  json           JSON dump of test run
  json.pretty    JSON dump of test run (human readable)
  ...
```
In addition, we get the typical cryptic error message:
```console
$ behave -f html
usage: behave [options] [ [DIR|FILE|FILE:LINE] ]+
behave: error: format=html is unknown
```

## Suggested Solution

1. The `-f help` screen should list incorrectly configured or unavailable (i.e. currently not importable) formatters separately, e.g.
   ```console
   $ behave -f help
   Available formatters:
     json           JSON dump of test run
     json.pretty    JSON dump of test run (human readable)
     ...

   Unavailable:
     html           could not be loaded (ImportError)
   ```
2. The error message when being executed should be more explict, e.g.
   ```console
   $ behave -f html
   usage: behave [options] [ [DIR|FILE|FILE:LINE] ]+
   behave: error: formatter `html` could not be loaded (ImportError)
   ```

**Comment by bittner** [comment]
This issue is still unsolved.

**Comment by bittner** [comment]
This issue is still unsolved.

**Comment by jenisys** [comment]
Branch `runner_class_part2` of the Git repository contains a solution for this.
As soon as it is merged, this issue will be resolved.

```shell
$ behave -f help
Available formatters:
  allure         ModuleNotFoundError: No module named 'allure_behave.formatter'
  html           ModuleNotFoundError: No module named 'behave_html_formatter'
  json           JSON dump of test run
...
```

Problem cases:

* ModuleNotFoundError: Python package is not installed (or python search path is not setup correctly)
* ClassNotFoundError: Module found, but class does not exist in this module
* InvalidClassError: Class is not a formatter (subclass of: `Formatter`)
* KeyError / LookupError: Formatter alias is unknown

**Comment by jenisys** [comment]
INTEGRATED INTO: behave v1.2.7
