### ISSUE TITLE
Scenario Outline: Support tags containing * wildcards

### ISSUE THREAD

**Issue by tsg9292** [behave/behave#896]
This request is basically an expansion of #678 

I'd like to be able to use tags on the ScenarioOutline that contain a `*`

```
Feature: Run Scenario Outlines with wildcard asterisk in the tags

    @tag*
    Scenario Outline: Test outline with asterisk tag
        ...
```

The above Scenario Outline will end up being processed with an effective tag of just `tag`, not `tag*`. It looks like `Tag.make_name` is filtering out the `*` character from all the tags on the Scenario Outline level.

I understand that I am able to tag the `Examples` table instead of the Scenario Outline to get my desired behavior, but it would be nice if there was more consistency between tags on Scenario Outlines and tags on Scenarios and Features.

**Comment by jenisys** [comment]
Rejected.
Tag-expressions v2 use wildcards `*`. 
Therefore, using wildcards in tags is a bad idea (even in Scenarios).

**Comment by jenisys** [comment]
@tsg9292 
Is there a compelling reason why you want to use asterisk ( `*`) in tags ?

**Comment by tsg9292** [comment]
This is the first I've seen the plans for tag-expressions v2. 
Using an asterisk in a Scenario is currently allowed, therefore the switch to tag-expressions v2 will be a breaking change for our test suite.

We have our own `ActiveTagMatcher` defined that uses fnmatch to match certain tags in a flexible way. **This is why we use asterisk in Scenarios**.

For consistency sake, I'd think you'd want tags on the Scenario and the Scenario Outline level to behave in the same way.

**Comment by jenisys** [comment]
REJECTED:
* The use of `*` (wildcard) is reserved for pattern matching with new tag-expressions v2.
* You where using „Undefined Behavior“ in your implementation of your ActiveTagMatcher
