### ISSUE TITLE
behave with re as the step matcher can't match step 

### ISSUE THREAD

**Issue by sbedi123** [behave/behave#897]
**I have the following BDD given statement in landing.py file**

```py
use_step_matcher("re")

@given(u'that I land on the (page_name) landing page with the correct offer id (?:start network traffic)')
def landing_page(context, page_name):
    ...
```

**Feature file is:**

```gherkin
...
Scenario: DR lil page end2end test starting with utm parameters
   Given that I land on the "google page" landing page with the correct offer id start network traffic
```

**When I try to run it says undefined step**

I am using the step matcher "re" and the text "start network traffic" in my given statement is optional. Why is it failing?

**Comment by jenisys** [comment]
You should use named-parameters with “re” matcher, for example.

SEE ALSO:
* http://behave.github.io/behave.example/step_matcher/re_matcher.html <http://behave.github.io/behave.example/step_matcher/re_matcher.html>

**Comment by sbedi123** [comment]
Jenisys,

**I updated the given statement in my .py file, to be :**

use_step_matcher("re")
@given(u'that I land on the (page_name) landing page with the '
       u'correct offer id "(?P<network_traffic>start network traffic|end network traffic)"')
def landing_page(context, page_name, network_traffic):
    assert isinstance(context.browser, WebDriver)
    context.page = context.get_page(page_name)

**Feature file:**

Scenario : DR lil page end2end test starting with utm parameters
		       Given that I land on the "<google page>" landing page with the correct offer id "start network traffic"

**Getting undefined error:, What am i doing wrong here?**

  Scenario Outline: DR lil page end2end test starting with utm parameters -- @1.1 Pages
    Given that I land on the "Ageless Turmeric DR T2" landing page with the correct offer id "start network traffic" ... undefined in 0.000s

**Comment by sbedi123** [comment]
Hello Jenisys

I updated the given statement in my .py file, to be named parameter (network_traffic) and it can have 2 values namely start network traffic|end network traffic :
use_step_matcher("re")
@given<https://github.com/given>(u'that I land on the (page_name) landing page with the '
u'correct offer id "(?P<network_traffic>start network traffic|end network traffic)"')
def landing_page(context, page_name, network_traffic):
    assert isinstance(context.browser, WebDriver)
    context.page = context.get_page(page_name)
Feature file:
Scenario : DR lil page end2end test starting with utm parameters
Given that I land on the "google page" landing page with the correct offer id "start network traffic"
When I run it Getting undefined error below:, What am I doing wrong here?
Scenario Outline: DR lil page end2end test starting with utm parameters -- @1.1 Pages
Given that I land on the "google page" landing page with the correct offer id "start network traffic" ... undefined in 0.000s
Below are the screenshots of the code and feature file:
[cid:image001.jpg@01D6EFEC.0AEAAB00]
[cid:image002.jpg@01D6EFEC.0AEAAB00]

**Comment by jenisys** [comment]
@sbedi123 
From what I see, you fixed one step-parameter (network_traffic), but have not fixed the other one (`page_name`).
As long as how do not follow the guideline how to use it, why should it work.
After this is fixed, the regular expression must be checked (if there is still an issue).

```python
from behave import given, use_step_matcher
use_step_matcher("re")

@given(u'that I land on the "(?<page_name>.*)" landing page with the correct offer id "(?P<network_traffic>start network traffic|end network traffic)"')
def landing_page(context, page_name, network_traffic):
    assert isinstance(context.browser, WebDriver)   # Hopefully setup before scenario is entered.
    context.page = context.browser.get_page(page_name)
```

BEST PRACTICE:
* Use double-quotes around your placeholders to run into greedy regular-expression problem where the regex matches too much.
* Use the `parse` of `cfparse` matcher instead of the regular-expression matcher unless you know what you are doing.

**Comment by sbedi123** [comment]
Hi Jenisys,

Thanks a lot. That definitely worked.

So now I am able to call the function def landing_page(context, page_name, network_traffic) for the following Given statements

Given that I land on the "Ageless Turmeric DR T2" landing page with the correct offer id "start network traffic"

Given that I land on the "Ageless Turmeric DR T2" landing page with the correct offer id "end network traffic"

My question is if I need the same function to work for following given statement where empty string (no value) is being passed to network traffic, how can I do that?
Given that I land on the "Ageless Turmeric DR T2" landing page with the correct offer id

Will this work

@given(u'that I land on the "(?<page_name>.*)" landing page with the correct offer id "(?P<network_traffic>start network traffic|end network traffic|’’)"')
