### ISSUE TITLE
Purpose of fixture decorator

### ISSUE THREAD

**Issue by auburus** [behave/behave#898]
Hey,

I have been recently using fixtures, and I can't seem to grasp the purpose of the `@fixture` tag in `environment.py` functions, it seems to not do anything?

# Example

```gherkin
# a.feature
Feature:
  @fixture.foo
  @fixture.bar
  Scenario:
    Given something
     When something
     Then something
```

```python
# environment.py
from behave import use_fixture
import fixtures

@fixture
def foo(context):
    yield "something"

# No @fixture here
def bar(context):
    yield "something"

def before_tag(context, tag):
    if tag == "fixture.foo":
        use_fixture(foo, context)
    if tag == "fixture.bar":
        use_fixture(bar, context):
```

Therefore, since the behavior is the same, what is the purpose of the `@fixture` tag?

# Expected behavior (maybe?)
What I would like (and I can submit a PR, but I wanted to discuss it first :) ), is a behavior like this:

```gherkin
# a.feature

Feature:
  @fixture.foo
  @fixture.bar.baz
  Scenario:
    Given something
     When something
     Then something
```
```python
# fixtures.py

from behave import fixture

@fixture
def foo(context):
    pass

@fixture(name="bar.baz")
def fixture_impl(context):
    pass
```
And then, with NO changes in `environment.py`, the fixtures would be autoloaded.
Would that make sense?

Thank you!

**Comment by jenisys** [comment]
Terminology first:

* `fixture-tag` is used in the gherkin file (`*.feature`) that refers to a provided fixture/fixture-function in Python
* `fixture decorator` is used in the Python files to mark the fixture functions (and supports the mapping between `fixture-tag` and fixture/fixture-function).

Therefore, I assume you mean the `fixture decorator` and not the `fixture-tag`.

Currently, the `fixture decorator` is mostly syntactic sugar (as described in the documentation).
A plugin mechanism can be supported later-on (independent how it is implemented). The `fixture decorator` will probably encapsulate the plugin registration mechanism when this is done.

**NOTES**: On plugin mechanism and `mind reading` (global registration and discovery)
* Your suggested approach hints that you want to perform `mind reading`. You do not state how `fixtures.py` is discoverable and its fixtures are registered.
* Plugin mechanisms that want to perform `mind reading`, normally do not scale well.
* In addition, fixture names could often get duplicated if you try to detect everything.
* Therefore, it is normally a good idea that the user selects which plugins (fixtures in this case) should be used and which not.

**Comment by auburus** [comment]
Sorry, yes, I was referring to the fixture decorator, thank you for laying out the proper terminology.

Regarding the points you've made, I completely agree that `mind reading` usually comes with this problems, but I got the impression that behave was already using it a lot (`environment.py` is a file that is automatically read; every file inside the `steps` folder is scanned and every `@given`, `@when` and `@then` are parsed there...), so I thought that adding another "magic file" called `fixtures.py` would follow this philosophy, but I can see other options.

Therefore I have two questions:
- Do you think it would make sense to "autoload" every `@fixture` found in `environment.py` or in `steps`? That way a new file doesn't need to be introduced.
- You are talking about plugins, do you mean implementing as a different python package, like `behave-fixtures`?

Thanks!

**Comment by jenisys** [comment]
The current implementation is the minimal needed functionality to support fixtures.

Auto-discovery/auto-registration of fixtures in `environment.py` file or any `step*.py` files would be an intended improvement in the future. In addition, auto-discovery of fixtures from modules that are imported in these files would also be nice and intended. Such a mechanism provides the "control-point" that allows the user has to state what should be used (which is along the lines with environment and step loading).

Plugins was mentioned because you normally use such a mechanism to register resources. Fixtures was mentioned as one kind of such plugins. If we provide such a mechanism in `behave` it will be contained as part of `behave` because it is a core functionality then. But until then it is possible to provide such a mechanism in another python package and you trigger it the functionality in the `before_all()` hook.

```py
# -- FILE: features/environment.py
from behave_better_fixtures import discover_fixtures
def before_all(ctx):
   fixtures_map = discover_fixtures()   # Perform magic: Browse globals for fixtures, browse imported modules ...
   ctx.fixture_registry = fixtures_map
```
