### ISSUE TITLE
Add support for features/steps discovery using config parameters/CLI options

### ISSUE THREAD

**Issue by lktslionel** [behave/behave#900]
###### AS
A user
###### I WANT TO
Use `behave.ini` or `behave` CLI options as a way to specify where `step` and `feature` paths are located
###### SO THAT
I can be flexible in organizing my steps/features. Especially since `behave` reads the step implementations from step files in the steps directory **only**.

<br>

#### USAGE

We can use the following parameters to specify those paths:

| behave.ini | behave CLI options | Examples |
|-----------|--------------------|-----------|
| `feature_paths=`| `--feature-paths` | `/path/to/featdir1:/path/to/featdir2` |
| `step_paths=`| `--step-paths` | `/path/to/stepdir1:/path/to/stepdir2:/path/to/stepdir3` | 

> We can use the column sign `:` to separate the paths.

**behave** should be able to discover all steps and features.

<br>

#### ACCEPTANCE CRITERIAS

- [ ] Given no feature paths, It should use the default path from the default layout folder `features`
- [ ] Given no step paths, It should use the default path from the default layout folder `features/steps`
- [ ] Given a set of paths for the features, It should find those features
- [ ] Given a set of paths for the steps, It should find those steps and the related features

<br>

#### IMPLEMENTATION
Nothing yet

<br>

#### REFERENCES

* [Tips - Importing behave python steps from subdirectories](https://qc-analytics.com/2019/10/31/importing-behave-python-steps-from-subdirectories/)
* [Example 1: An example of `behave` usage with a well-defined directory structure](https://www.testaddict.space/understanding-behaves-feature-files-and-step-implementations/)
* [Example 2: etup python’s behave library to read steps from subfolders](https://aditamasblog.wordpress.com/2018/07/18/setup-pythons-behave-library-to-read-steps-from-subfolders/)

**Comment by jenisys** [comment]
There seems to be some misunderstanding how certain things work with `behave`.

* feature search path: This is not needed (and completely unclear why this is needed). 
  Use the path to the features as command line args.
  Use at-list-files, like `@my_features.txt` if you want to provide a list of feature file paths and simplify to reuse it.

* step search path: This is not desired and leads to unnecessary complexity.
  You can place your steps where ever you want (see: step-libraries).
  You only need to provide a step file that imports your steps from somewhere else in your steps directory as glue code.
   In the future, step directories will be available at multiple levels of the directory structure where feature files are.

**Comment by lktslionel** [comment]
Thank you a lot for these great explanations.
I have also found an example of a step-library https://github.com/ggozad/behaving.
Thanks again
