### ISSUE TITLE
Provide a way to add custom "before feature" and "after feature" code for individual features

### ISSUE THREAD

**Issue by shanebishop** [behave/behave#901]
behave already has `before_feature()` and `after_feature()` functions so setup and teardown code can be provided for all features. This code is shared by all features.

It would be useful to provide a way to specify custom "before feature" and "after feature" code for individual features. This is useful if, for example, a specific feature needs its own setup that is unique to it.

Presumably the custom "before feature" code would run after the "shared" `before_feature()` function, and the custom "after feature" code would run before the shared `after_feature()` function.

**Comment by jrazgunas** [comment]
Can't this already be achieved with the before_tag capabilities?

**Comment by shanebishop** [comment]
I haven't heard of before_tag capabilities, but you are right, this can be achieved using tags. See [here](https://stackoverflow.com/q/66015535/8593689) for how.

I will close this issue now.
