### ISSUE TITLE
XRAY problem w/ behave example: "Error assembling issue data: project is required" with Cubumber report formatter

### ISSUE THREAD

**Issue by leonardopsantos** [behave/behave#908]
Hi Everybody! I'm following [Testing using Behave in Python](https://docs.getxray.app/display/XRAY/Testing+using+Behave+in+Python) to get the results of my Behave tests into Jira Xray, but I'm getting 

```
{"error":"Error assembling issue data: project is required"}
```

This seems a problem with the Jira Xray REST API than a Behave one, but as I'm using Behave to run the tests I decided to ask here to see if anyone has a suggestion.

This is related to issue #267.

**Comment by jenisys** [comment]
Mmh, I think this is an XRAY related problem and not a `behave` problem (as you have already stated).
