### ISSUE TITLE
How to create a bash script to execute non-headless chromedriver python-behave

### ISSUE THREAD

**Issue by bhadmus** [behave/behave#910]
I wrote an automated test suite in Python, Selenium, and Behave. I am trying to execute my script with a bash file. The challenge here is that I want to create two separate scripts. One will run headless mode (build my docker file and run it headless in docker) while the other script will execute a non-headless one locally on my system> I was able to create the first one easily.

This is what I have done to my webconfig.py file.

    from selenium import webdriver
    from selenium.webdriver.chrome.options import Options
    
    
    headless = True
    
    
    class Driver:
        def __init__(self, driver):
            self.driver = driver
            if driver == "chrome":
                if headless:
                    chrome_options = Options()
                    chrome_options.add_argument("--headless")
                    chrome_options.add_argument("--no-sandbox")
                    chrome_options.add_argument("--disable-gpu")
                    chrome_options.add_argument("--start-maximized")
                    chrome_options.add_argument("--window-size=1920,1200")
                    chrome_options.add_argument("--disable-dev-shm-usage")
    
                    self.driver = webdriver.Chrome(chrome_options=chrome_options)
                else:
                    self.driver = webdriver.Chrome()
            elif driver == "firefox":
                self.driver = webdriver.Firefox()
            else:
                print(f"{driver} is not defined.")

I am yet to write the Firefox implementation but I felt with this, I should be able to create a bash script where I can specify that `headless=False` and it should execute a visual regression locally. How can I achieve this?

**Comment by jenisys** [comment]
Mmh, the main point here seems to be somewhat unrelated to `behave`.
In addition, it is not completely clear to me what you are trying to achieve and what the problem is (or where you see it).

**Comment by bhadmus** [comment]
@jenisys This is what I am trying to achieve:
I want to create two shell scripts that I can use to execute my codes locally 

One should be able to run it in headless mode while the other should execute it in non-headless mode.

**Comment by jenisys** [comment]
Make a concrete example what you are trying to achieve in the shell scripts, like:

```bash
#!/bin/bash
# VARIANT 1: Run in headless mode
behave -D headless=true $*
```

```bash
#!/bin/bash
# VARIANT 2: Run in normal mode (no-headless)
behave $*
# SAME AS: behave -D headless=false $* 
#    if headless=false is the default.
```

NOTE:
By using userdata to allow the user to hand in parameters on the command-line (or "behave.ini" config-file) that can be evaluated within behave, normally in "features/environment.py" file.

**Comment by bhadmus** [comment]
```
#! /usr/bin/env bash
# headless mode through the docker set up
docker build . -t docker_mode; docker run docker_mode
```
```
#! /usr/bin/env bash
# non-headless mode through docker
headless 1= 0 #I specified this in a `.env` file to make headless false
docker build . -t docker_mode; docker run docker_mode
```

I will try the environment.py approach and revert back

**Comment by bhadmus** [comment]
I didn't use the environment approach. I found a work around by using `export headless=0; behave` in the non-headless bash script and it worked.

The caveat to this method is that I have to use `os.getenv('headless')` which refers to the value set in my .env file.
