### ISSUE TITLE
Behave hooks should be declarative wrappers

### ISSUE THREAD

**Issue by rittneje** [behave/behave#911]
Currently we can register hooks in environment.py via before_X and after_X functions. However, this approach is incompatible with the declarative style of programming, such as context managers. Instead, the hook should be a function that is responsible for running the step/scenario/feature/whatever.

For example
```python
# environment.py

def run_step(context, step):
    # do before_step items here
    try:
        step.run(context)
    finally:
        # do after_step items here
```

**Comment by jenisys** [comment]
I think not.

The before/after hooks are extension points where a user/creator of a test suite can plug in additional things.
But there is a lot more in the background that the user should not change and be allowed to break (for example: leaving out the line `step.run(context` and hiding exceptions from the test runner).

In addition, you do not seem to be aware of **behave fixtures** which already allow you to provide code as context manager.
This covers everything except steps (meaning: You can use fixtures in steps / `before_step` hook by using `use_fixture(...)` but the cleanup-point is at the end of the scenario and not in the `after_step` hook.
Therefore, what you are asking for is for most cases already provided.

SEE ALSO:
* [docs: New and Noteworthy -- Fixturres](https://behave.readthedocs.io/en/latest/new_and_noteworthy_v1.2.6.html#fixtures)

**Comment by rittneje** [comment]
From what I can tell, fixtures are only run at a scenario level, so they are less flexible than hooks (which can be run at a step, scenario, or test suite level). Also, they do not have access to the result of the scenario. So they don't meet our needs.

It seems very unlikely that someone would neglect to call `step.run(context)` and not notice. But even then I think it would be simple enough for the framework to say something like "if !step.was run, raise exception".

**Comment by jenisys** [comment]
Fixtures are run at the level they are injected and not only at the scenario level. The exception of the rule is the cleanup-point for steps. That was mentioned above.

The main point of fixtures is setup/cleanup.
But if you need to access the Scenario result, use the `context.scenario` attribute (available if it is executed in a scenario).
