### ISSUE TITLE
Missing "Rule" keyword from Gherkin

### ISSUE THREAD

**Issue by Wecros** [behave/behave#916]
Hello,

I have written a few feature files using Gherkin reference only to find that there is no support for the [`Rule` keyword](https://cucumber.io/docs/gherkin/reference/#rule). Do you plan to support the feature in the future? What do you recommend to use instead? I imagine splitting the "rules" into several feature files will work similarly.

Thanks!

**Comment by Wecros** [comment]
It looks like the `Rule` keyword is [present](https://behave.readthedocs.io/en/stable/tutorial.html) after all, just deeper in the documentation than I expected. The parser is failing due to a different kind of error, I will close this issue once I find out what is it causing to fail.

**Comment by jenisys** [comment]
The Rule keyword is supported for over a year. Currently you need to use the tip of the Github repository or one of the v1.2.7dev tags on the Github repository to use it.

SEE ALSO
* [behave: examples/gherkin_v6](https://github.com/behave/behave/tree/master/examples/gherkin_v6)
* [docs.latest: new_and_noteworthy_v1.2.7.html](https://behave.readthedocs.io/en/latest/new_and_noteworthy_v1.2.7.html?highlight=Rule#support-gherkin-v6-grammar)

**Comment by Wecros** [comment]
Alright, thanks for the tip. The version I had installed was from `pip` where the newest version is only 1.2.6. Installing the `v1.2.7.dev1` version from git solved the issue for me. 

Thank you for helping me out and sorry for the trouble!

**Comment by bittner** [comment]
@jenisys This issue would be one more reason to push a new release to PyPI. Any priority on that?
