### ISSUE TITLE
run behave with using PyPy interpretator

### ISSUE THREAD

**Issue by Alexander-Tkachev** [behave/behave#918]
Hi. I want that when I run my tests through the terminal command "behave" everything works not through the Python interpreter, but through the PyPy that I installed in my Windows 10. How can I do this?

**Comment by adityakumar1990** [comment]
Use wrapper script

**Comment by jenisys** [comment]
Just install behave with the pip of your pypy interpreter. The installed behave script can be directly be used if it is in your search path.

**Comment by Alexander-Tkachev** [comment]
> Just install behave with the pip of your pypy interpreter. The installed behave script can be directly be used if it is in your search path.

Can a pypy also use a pip? And how can I find out that the launched behave (registered in the Windows OS path) works precisely through the pypy, and not through the python interpreter?

**Comment by jenisys** [comment]
You use „behave“ with the Python interpreter that you install it: Either the standard one (Windows in your case) or pypy. You should not mix them, that will only get you into trouble.
