### ISSUE TITLE
Some guidance on cross browser automation

### ISSUE THREAD

**Issue by dsm23** [behave/behave#919]
So I understand from https://behave.readthedocs.io/en/stable/fixtures.html#realistic-example that I can use the tags to control which browsers run and currently if I use only one browser at a time everything passes and looks good. What I don't understand is how to make sure the tests pass in every browser. The behaviour that I currently seem to have is that the browsers race each other and the ones that lose don't even cleanup

**Comment by bittner** [comment]
Do you run the different browsers in parallel with a single test run on the same machine?

I guess, the "Variant 1" and "Variant 2" in the code samples suggest that you have either one or the other set up. Or you run your test suite with a (command line) parameter, which chooses one of your preset configurations.

The latter would be my suggestion for running the tests in a CI/CD pipeline. You would thus separate the problem domains into dedicated build jobs, which make it easy to spot (when a job fails) for which browser issues were introduced.

Does that make sense?

**Comment by jenisys** [comment]
If you want to run one or more feature files with **all browsers**, you need to provide a for-loop that loops over each browser variant. That is basically a build script problem:
* Use your build script to loop over all browser (or provides multiple behave runs with ``-D browser=xxx`` (user-data))
* Use a behave feature file as build script (use behave to run behave)
 
In the second approach you provide a feature file with ScenarioOutline over all browser that runs other features files with ``-D browser=xxx`` (user-data) on the command line.

EXAMPLES: For the second approach (use behave to run behave)
* [behave: more.features/run_examples.feature](https://github.com/behave/behave/blob/master/more.features/run_examples.feature)
* [behave: more.features/formatter.json.validate_output.feature](https://github.com/behave/behave/blob/master/more.features/formatter.json.validate_output.feature)
