### ISSUE TITLE
Features organized into directories

### ISSUE THREAD

**Issue by symygy** [behave/behave#926]
I would like to ask about possibility to organize feature files into directories. For now I have:
tests/features/A1.feature
tests/features/A2.feature
tests/features/B1.feature
tests/features/B2.feature

What I want to do:
tests/features/A/1.feature
tests/features/A/2.feature
tests/features/B/1.feature
tests/features/B/2.feature

It would definitely help to organize features if I have many of them.

**Comment by jenisys** [comment]
Read the docs or behave's feature files on directory layout.
You can do both. And try it out to verify it.
