### ISSUE TITLE
behave_html_formatter:HTMLFormatter UTF-8 issues

### ISSUE THREAD

**Issue by y4rk4s** [behave/behave#935]
Hi!

There are some issues with utf-8 character writing
OS: Win10
Python: 3.8
Key: HU
Behave version: 0.98 ( with older version also reproducible )

Command:
behave --tags=@smoke test_app/ --color --no-capture --no-skipped -f behave_html_formatter:HTMLFormatter

Special characters:
éáűőúöüóí

**Case 1:**
Formatter cannot handle propery characters above, on output only � appears

**Case 2:**
On a special chase stream contains character: "→" write to file causing exception, check details bellow
HTML output does not created

`File "c:\program files (x86)\python38-32\lib\site-packages\behave_html_formatter\html.py", line 592, in close
    self.stream.write(ET_tostring(self.html, pretty_print=True))
  File "c:\program files (x86)\python38-32\lib\encodings\cp1250.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]

Exception UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 47003: character maps to <undefined>
Traceback (most recent call last):`

**Comment by bittner** [comment]
Please use triple-backticks (` ``` `) to wrap code snippets and console output. This makes it easier to understand and analyze your problem.

**Comment by bittner** [comment]
The exception seems to be thrown by the html-formatter, not `behave` itself.

Can you please report the issue on [the formatter's issue tracker](https://github.com/behave-contrib/behave-html-formatter/issues)? Thank you for your understanding.
