### ISSUE TITLE
Behave hangs after completion

### ISSUE THREAD

**Issue by lawnmowerlatte** [behave/behave#938]
We run behave in our CI pipeline in Jenkins and I've observed behave getting stuck at the end of a test run. I have a timeout of 30m to catch runaway tests, so what I see is the ending summary, followed by an interrupt some time later.

```
[2021-07-15T11:28:55.485Z] 1 feature passed, 0 failed, 0 skipped
[2021-07-15T11:28:55.485Z] 5 scenarios passed, 0 failed, 0 skipped
[2021-07-15T11:28:55.485Z] 107 steps passed, 0 failed, 0 skipped, 0 undefined
[2021-07-15T11:28:55.485Z] Took 3m52.690s
[2021-07-15T11:53:27.367Z] Sending interrupt signal to process
[2021-07-15T11:53:33.526Z] make: *** [Makefile:41: behave] Terminated
[2021-07-15T11:53:33.537Z] script returned exit code 2
```

Is there anything I can do to investigate where or why it is getting stuck? It sounds somewhat similar to issue #830, but we run behave on Ubuntu.

**Comment by jenisys** [comment]
The fault location should be in your code (and not in `behave`).
I assume you have one or more thread(s) running or a future(s) that still waits for its result (like: multiprocessing).
AFAIK, these are some cases why the Python process does not end.

HOW TO EXPLORE:
* Create your own copy of behave main() function that you can instrument
* Place print() statement to detect how far you are coming in the main() function
* Dump threads stack traces
* Explore where the teardown of your resources is not working or missing
* ...

HOW TO FIX:
* EXAMPLE: In `after_all()` hook, ensure that all precious resources are released, all threads are joined, ...
* Use cleanups to ensure that the important resources are released

**Comment by jenisys** [comment]
No reaction, close it
