### ISSUE TITLE
Is it possible to run "Given" and "When" steps for each row in examples table before running the "Then" step?

### ISSUE THREAD

**Issue by AndrewC19** [behave/behave#942]
Hi,

I'm experimenting with using behave to gather data from an epidemiological model and I have the following scenario outline:

```cucumber
Scenario Outline: Single vaccine
    Vaccines should reduce the cumulative number of infections and some are better than others.

    Given vaccine <vaccine_name> is available
    When the simulation is finished
    Then the cumulative number of infections should be less than when vaccine <other_vaccine_name> is available
    Examples:
      | vaccine_name | other_vaccine_name |
      | A            |  None              |
      | B            |  A                 |
      | C            |  B                 |
```
In my steps file, the `Given` step calls code which adds `<vaccine_name>` to the model. The `When` step then runs the model and collects the results in a csv. The `Then` step then does the comparison to check that `<vaccine_name>` yields less infections than `<other_vaccine_name>`.

My issue is that I would like to run the model for each <vaccine_name> (`Given` and `When` steps) before I do the `Then` step. This will give me a single csv file which contains all of the desired data which will then allow me to use a specific statistical technique for the `Then` step. 

Is this possible or do I have to repeat the Given, When, and Then steps for each example?

Thanks!

**Comment by jenisys** [comment]
In your case, it probably makes more sense to support that multiple vaccine names are used in the first column, like:

```gherkin
Given I simulate that the vaccines „A, B, C“ become available in this order
When I use the vaccine <vaccine_name>
Then … # like before

Examples: # like before
  | vaccine_name | other_vaccine_name |
  …
```

In this case, the Given step is the work horse that processes the list of vaccines (as comma seperated list; use a type-converter to convert it into a list of vaccine-names) and performs the simulation. The Given step should memorize the results and check if it has already performed the computation/simulation with the specified list. Therefore, you only pay the price once while processing the first row. For the second and following rows it checks if it is the same list and performs a lookup the result.

RELATED: Type-converter example for parsing a list of T as placeholder in a step
* behave.example docs: [Cardinality one or more (many)](https://behave.github.io/behave.example/datatype/cardinality_one_or_more.html) 

HINTS:
* Type parsing as placeholder params makes only sense if you have a small number (less than 5..10) and short names
* If this not the case use a Given step with a data table instead (and convert the table into a list of names in the step)

**Comment by AndrewC19** [comment]
Thanks @jenisys, this is really helpful. 

We ended up using a table in the Given step to list the different vaccines and then used the When step to ensure all vaccine runs had been executed and the results combined into a single dataframe.
