### ISSUE TITLE
execute_steps() in multiple threads

### ISSUE THREAD

**Issue by SpangleLabs** [behave/behave#950]
I've been trying to write some tests which run multiple steps in parallel, however it seems execute_steps() is very much not thread safe. 
It looks like Context.table, text, and feature all end up being reset between threads.
I tried to see if I could make copies of the Context somehow, but had no luck with that.

Do you know if there's any way to achieve this?

**Comment by jenisys** [comment]
A parallel test runner should have the following characteristics:

* Scenario(s) are run in parallel, not steps
* Each thread should use an own test runner and therefore own Context object
* Shared resources that are used in step implementations must somehow be protected
* You need a „master test runner“ that dispatches the „work items“ to the subrunners, on in each thread.
  This test runner needs to collect the results of the subrunners and present it to the user (Formatter).

NOTES:
* From your description above you seem to share the Context object between multiple threads.

**Comment by joshcoales** [comment]
Yes, I'm not wanting a parallel test runner, so much as a test scenario that does steps in parallel.

An example test case:
- Set some configuration in a system
- Launch 10 threads and wait for them to complete:
  - Creating an account each
  - Doing some other account actions
- Check system configuration

The idea is that it is testing for race conditions and performance in the system under test.

And meanwhile, we have some tests like this in behave already:
- Set some configuration in a system
- Creating an account each
- Doing some other account actions
- Check system configuration

So re-using steps would be nice

Which are checking the standard functionality, but we're just wanting to add some parallelism to those tests to check they're thread safe and performant

**Comment by jenisys** [comment]
This is a much easier to achieve if:

* you provide your own test runner for this rather special purpose
* Start multiple behave test runners in parallel, for example each in its own process/shell

**HINT:**
If you only have steps that you like to reuse, you have probably done something suboptimal.
In general, my steps use other test support / test infrastructure functions and classes.
This often simplifies how you write step implementations.
In addition, you can use this test support / test infrastructure also with other case (like another test framework or a specific test automation case, etc.). And you can write tests for the test support / test infrastructure functions/classes.
