### ISSUE TITLE
Getting `HOOK-ERROR in after_step: AssertionError` if `context.execute_steps` used in any step of Behave Scenario

### ISSUE THREAD

**Issue by sbedi123** [behave/behave#952]
I am getting following erroe when I use context.execute_steps

Captured stdout:
HOOK-ERROR in after_step: AssertionError:

Please let me know how i can resolve the above issue. The example here i call context.execute_steps is:

def verify_pixel_events(context):
    for row in context.table:
        if row['pixel_name'] == 'Taboola':
            context.execute_steps('''
                 then I verify taboola pageview event
                 and I verify taboola purchase event
            ''')
        elif row['pixel_name'] == 'Reddit':
            context.execute_steps('''
                then I verify reddit pagevisit event
            ''')

**Comment by sbedi123** [comment]
Here is my scenario:


Scenario Outline: Opt-in end2end test starting with a HasOffers link
    	Given that I follow a HasOffers link to the "<page_name>" landing page 
        Then I should see email input is pre-populated
        When I enter the unique email with spaces
        Then I am redirected to the Bonus page
    	And I am redirected to the correct sales lander
        And I verify pixel tracking events
        |pixel_name|
        |Taboola|
  	|Reddit|
        
        Examples: Opt-in Pages
        |page_name| 
        |10 Foods That Fight Visceral Fat|

**Comment by sbedi123** [comment]
Please guide me how to resolve this. This is blocker for me and I have no idea how to resolve this. Basically using a data table and calling multiple steps based on the value of index table

**Comment by sbedi123** [comment]
There was an issue in my code which is resolved

**Comment by jenisys** [comment]
AFAIK, if you run behave with option `—verbose`, you will get the stack trace that will point you to the failing step in `context.execute_steps()`.
