### ISSUE TITLE
use_2to3 being deprecated causing install failures

### ISSUE THREAD

**Issue by krisgesling** [behave/behave#955]
Hi there, 

I'm starting to see pip install failures in Github Actions due to the use of `use_2to3` in `setup.py`. Setuptools deprecated use of `use_2to3` from v58 (see [changelog](https://setuptools.readthedocs.io/en/latest/history.html#v58-0-0)).

So an alternative approach will be needed, or dropping support for Python 2. Figured this is a call for the maintainers hence an issue rather than a PR.

Thanks for a great package though :)

**Comment by bittner** [comment]
@jenisys I would suggest to issue a (1.3.0)  release "as is" now and drop Python 2 support afterwards, issuing another release (say, 2.0.0).

If any backward-compatibility  is still needed work could continue off the 1.3.0 version in a separate branch. That should hence be a safe strategy that allows us to move forward.

Any opinion on this?

**Comment by krisgesling** [comment]
I should also note that cucumber-tag-expressions suffers the same issue. I also opened a ticket there:
https://github.com/cucumber/common/issues/1736

So you probably want to wait until that is fixed and released.

**Comment by jenisys** [comment]
MERGED INTO: behave-1.2.7.dev2

**Comment by jenisys** [comment]
HINT: cucumber-tag-expressions v4.0.1 (soon to be published) contains the fix for the related issue in the `tag-expressions` package (see above: cucumber/common#1736 and pull-request cucumber/common#1742).
