### ISSUE TITLE
Replace dashes with underscores to comply with setuptools v54.1.0

### ISSUE THREAD

**Issue by arrooney** [behave/behave#958]
Support for dashes is being removed from setuptools: https://github.com/pypa/setuptools/commit/a2e9ae4cb

https://github.com/behave/behave/blob/34ec5097f33c9b1620714d8dd95e75901559668b/setup.cfg#L14

**Comment by jenisys** [comment]
FIXED IN: behave v1.2.7 (after: v1.2.7.dev3)
