### ISSUE TITLE
get_full_page_screenshot_as_png nor attach working using behave html formatter.

### ISSUE THREAD

**Issue by jigisha9** [behave/behave#959]
@bittner @jenisys 

```
      def after_scenario(context, scenario):
    print("AFTER SCENARIO")
    if scenario.status == 'failed':
            image = context.browser.get_full_page_screenshot_as_png()
            context.attach("image/png", "pageImage.png")
```

**_AttributeError: 'DriverFactory' object has no attribute 'get_full_page_screenshot_as_png'_**
**_AttributeError: 'Context' object has no attribute 'attach'_**

How to make it work?

PS: I have already set behave formatter in behave.ini. Above code is in environment.py

**versions:**
behave 1.2.6 
behave-html-formatter  0.9.8

**Comment by jenisys** [comment]
Which behave version are you using?

**Comment by jigisha9** [comment]
@jenisys 

behave 1.2.6 
behave-html-formatter  0.9.8

**Comment by jenisys** [comment]
The `Context.attach()` method was added 2020-12-14.
It is not part of `behave v1.2.6.
Currently, you must use the current tip of the repository to use it.

**Comment by jigisha9** [comment]
@jenisys  I have referred below doc. and try to install 1.2.7.dev2 but seems this tag is not available yet.  is there any way i can get it? 

https://buildmedia.readthedocs.org/media/pdf/behave/latest/behave.pdf

pip install git+https://github.com/behave/behave@1.2.7.dev2

**Comment by jenisys** [comment]
The last line is nearly correct (first character of tag is missing; tag: v1.2.7.dev2 )

````sh
pip install ***@***.***
```

**Comment by jigisha9** [comment]
@jenisys 

still error remains : `object has no attribute 'get_full_page_screenshot_as_png'`

![image](https://user-images.githubusercontent.com/7517067/134021812-e84d42ea-bbea-4124-b1b2-a00c3eb1cb5b.png)

![image](https://user-images.githubusercontent.com/7517067/134024873-7e79a1af-95ba-4de7-80c7-389a86cb7860.png)

**Comment by jenisys** [comment]
Yeah, but that is neither a behave problem nor a problem of the HTML formatter.

That is the `Browser` (driver) class that you are using for `context.browser`. Search where the Browser object is assigned to `context.browser = …`, for example in the `before_all()` hook in the environment.

Maybe you are not using the Firefox webdriver but another one that is lacking this functionality (like Chrome) ?!

SEE ALSO:
* Selenium webdriver (for Firefox): https://www.selenium.dev/selenium/docs/api/py/webdriver_firefox/selenium.webdriver.firefox.webdriver.html?highlight=screenshot#selenium.webdriver.firefox.webdriver.WebDriver.get_full_page_screenshot_as_png

**Comment by jigisha9** [comment]
@jenisys 

We are using Chrome driver.so using below it pass thru'.
`context.browser.driver.save_screenshot("pageImage.png")`

![image](https://user-images.githubusercontent.com/7517067/134032474-b5248db0-6f0c-4656-9371-8d9c4321bcb0.png)

Issue is: now we do see screenshot link, on click it it does not visualize image.  i checked on other browsers as well. but same results.

Should it be ".png" file or something else? how we can visualize it?

**Comment by jenisys** [comment]
The PNG image file is probably not stored in the correct directory, I assume (but the current working directory). Check the generated HTML pages w/ the link to the screenshot (or try to open that URL link). But I assume you must use the same directory where your HTML page(s) are located.

**Comment by jigisha9** [comment]
screenshot saved at project directory directly so not to define path or directory. but don't know where context.attach is reading from?

when tried to open screenshot link it does not have http link to open in separate tab. so i can only click it. 

1. Tried with `context.browser.driver.save_screenshot("pageImage.png")` ==> as image is saved directly under project directory.
2. Tried with absolute path : full path - "c:/....." ==> still image is not visualize


below is source code of html:

<html>
<body>


<a onclick="Collapsible_toggle('embed_2')">Screenshot</a>
--
  | <img id="embed_2" style="display: none" src="data:image/png;base64,pageImage.png"/>


</body>
</html>

**Comment by jigisha9** [comment]
@jenisys  @bittner 

had to use `self.driver.get_screenshot_as_base64()` to make png image visible in html report.

**Comment by jigisha9** [comment]
Thanks a lot @jenisys for your help.

**Comment by anqon** [comment]
@jenisys  is it already possible in json formatter (PrettyCucumberJSONFormatter) ? I have: nHOOK-ERROR in after_step: KeyError: 'embeddings'"

def after_step(context, step):
    if step.status == "failed":
        screenshot = context.driver.get_screenshot_as_base64()
        context.attach("image/png", screenshot)

_(appium + behave 1.2.7.dev2)_

**Comment by jenisys** [comment]
@anqon 
Needs to be addressed in [Cucumber-Behave-Package](https://github.com/BluThaitanium/Cucumber-Behave-Package) (by its maintainer).
If you compare its code with [JsonFormatter.embedding()](https://github.com/behave/behave/blob/main/behave/formatter/json.py#L170), it should be clear what is the problem in `PrettyCucumberJSONFormatter.embedding()` function implementation.

SEE ALSO:
* https://github.com/BluThaitanium/Cucumber-Behave-Package/blob/main/behave_cucumber_formatter/__init__.py#L147
* https://github.com/behave/behave/blob/main/behave/formatter/json.py#L170
