### ISSUE TITLE
Execute precondition only once before running behave tests

### ISSUE THREAD

**Issue by mglowinski93** [behave/behave#965]
I would like to run background `preconditions` only once before running a bunch of tests (defined in scenario outlines).

Let's say I've `feature file` like this:

    Background:
	    Given Fan is powered

	#Test to check fan speed
	@TEST_FAN-1 @SuperFan
	Scenario Outline: Checking fan speed
		Given fan is not running
		When send speed command with <speed>
		Then fan is running with <speed>

		Examples:
			| speed |          
			| 5     |
			| 50    |
			| 100   |

I've defined `Given Fan is powered` as below:

    @given("Fan is powered")
    def step_impl(context):
        assert conetxt.fan.is_powered

This precondition is executed before every test defined in [scenario outline][1].
Is there a way to run it only once, before running first tests from scenario outlines?

PS. Moving this check to `before_all` method will not be a solution, since I do not expect to execute this check for other feature files.

  [1]: https://behave.readthedocs.io/en/stable/gherkin.html#scenario-outlines

**Comment by lawnmowerlatte** [comment]
This might be a fit for fixtures instead.

**Comment by mglowinski93** [comment]
Yes, this is how I solved it at this point.
I was just wondering if there was a way with `given`.

**Comment by rittneje** [comment]
@mglowinski93 One possibility is to add a context attribute in `before_all` to keep track of whether the step in question has executed before or not. This will still show the step in the logs but subsequent attempts will be no-ops.

```python
def before_all(context):
    context.precondition_cache = set()

...

@given("fan is powered")
def step_impl(context):
    if "fan is powered" not in context.precondition_cache:
        # power up the fan
        context.precondition_cache.add("fan is powered")
```

**Comment by mglowinski93** [comment]
oh, that is quite nice idea, thanks for a tip:)
