### ISSUE TITLE
[Feature] Improve CI to facilitate maintenance

### ISSUE THREAD

**Issue by blaisep** [behave/behave#969]
(@jenisys another placeholder issue)

[Link to the "hackathon fork"](https://github.com/controlpl4n3/behave/discussions/1) so we can work without disturbing the upstream.

Goals: 
- reduce the overhead of reviewing PRs and merging.
- automate linting and unit testing with pre-push hooks and Dockerfiles to improve the quality of PRs
-  ....

### Edit: adding @bittner for visibility

**Comment by jenisys** [comment]
Sorry, for the late reply.

Could you elaborate why you think this is an improvement?

NOTE:
In general, you need to describe a new feature in more detail (and discuss it).
Therefore, a Gherkin snippet would only be a part in an `enhancement` issue (or: `new feature` request).

**Comment by jenisys** [comment]
@blaisep 
HINT: 
* Enabled github-actions as CI since approx. 2 weeks.
* Remove Travis CI (was: outdated and no longer working)

**Comment by jenisys** [comment]
ALREADY DONE (since a few weeks).
