### ISSUE TITLE
can not capture stderr message via context.stderr_capture

### ISSUE THREAD

**Issue by smone123** [behave/behave#974]
stdout could be captured via context.stdout_capture.

**Comment by jenisys** [comment]
Explain what you are exactly trying to do.

HINTS:
output capture (stdout, stderr, logging) are handled by the test runner (via command-line args) and not by calling `context.stdout_capture` (if you intended/used this).

**Comment by jenisys** [comment]
CLOSED: Due to inactivity. Was probably not important enough.
