### ISSUE TITLE
exception of a failed test is not catched if context.execute_steps is used

### ISSUE THREAD

**Issue by berndhahnebach** [behave/behave#981]
if `context.execute_steps()` is used the exception is not catched ... the first three steps do not use `context.execute_steps()`. They work fine. The fourth and fifth step uses `context.execute_steps()` fails, but the exception is not caught. 

![screen](https://user-images.githubusercontent.com/6129869/145679084-0f449dba-5d85-422f-a14e-11f25027f4de.jpg)

feature file:
```gherkin
# language: en

Feature: Base setup

In order to use translation
As any interested developer
We implement some failed tests


Scenario: Some failed tests

 * This is the first test which will fail
 * Further test without success
 * Here we have another not passed test
 * Again a test, which is not good, and exception is raised
 * This test is not ok either, but exception is not catched

```

step file one:
```python
from behave import step


@step('This is the first test which will fail')
def step_impl(context):
    assert_schema()


@step('Further test without success')
def step_impl(context):
    assert True == False, "Test fails."


def assert_schema():
    assert True == False, "Test fails."

```

Step file two:
```python
from behave import step
import behaveproblem.features.steps.steps_a as steps_a


@step('Here we have another not passed test')
def step_impl(context):
    steps_a.assert_schema()


@step('Again a test, which is not good, and exception is raised')
def step_impl(context):
    context.execute_steps(f'* Further test without success')


@step('This test is not ok either, but exception is not catched')
def step_impl(context):
    context.execute_steps(f'* This is the first test which will fail')

```

find attached the structure to reproduce this ... 

[behaveproblem.zip](https://github.com/behave/behave/files/7697135/behaveproblem.zip)
[report.json.txt](https://github.com/behave/behave/files/7697139/report.json.txt)
[report.html.txt](https://github.com/behave/behave/files/7697140/report.html.txt)

code to run it

```python
import os
from os.path import join
localpath = join("C:", os.sep, "Users", "BHA", "Desktop", "mybehavetest") 

import sys
sys.path.append(localpath)

features_path = join(localpath, "behaveproblem", "features", "some_test.feature")
report_json = join(localpath, "report.json")

import json
args = [features_path, "--no-capture", "--format", "json.pretty", "--outfile", report_json]
print(json.dumps(args, indent=4))

from behave.__main__ import main as behave_main
behave_main(args)

```

**Comment by berndhahnebach** [comment]
feature file:
```
# language: en

Feature: Base setup

In order to use translation
As any interested developer
We implement some failed tests


Scenario: Some failed tests

 * This is the first test which will fail
 * Further test without success
 * Here we have another not passed test
 * Again a test, which is not good, and exception is raised
 * This test is not ok either, but exception is not catched

```

step file one
```
from behave import step


@step('This is the first test which will fail')
def step_impl(context):
    assert_schema()


@step('Further test without success')
def step_impl(context):
    assert True == False, "Test fails."


def assert_schema():
    assert True == False, "Test fails."

```

Step file two
```
from behave import step
import behaveproblem.features.steps.steps_a as steps_a


@step('Here we have another not passed test')
def step_impl(context):
    steps_a.assert_schema()


@step('Again a test, which is not good, and exception is raised')
def step_impl(context):
    context.execute_steps(f'* Further test without success')


@step('This test is not ok either, but exception is not catched')
def step_impl(context):
    context.execute_steps(f'* This is the first test which will fail')



```

**Comment by jenisys** [comment]
I cannot reproduce the problem that you have:

* All steps fail, even the ones executed via `context.execute_steps()`
* Even your own HTML based report indicates this with your stack traces after each step

```bash
(.venv_py39) bash-5.1$ behave -f plain features/
Feature: Base setup

  Scenario: Some failed tests
    * This is the first test which will fail ... failed in 0.000s
Assertion Failed: Test fails.
    * Further test without success ... failed in 0.000s
Assertion Failed: Test fails.
    * Here we have another not passed test ... failed in 0.000s
Assertion Failed: Test fails.
    * Again a test, which is not good, and exception is raised ... failed in 0.001s
Assertion Failed: FAILED SUB-STEP: * Further test without success
Substep info: Assertion Failed: Test fails.
Traceback (of failed substep):
  File "/Users/.../behaveproblem_issue981/.venv_py39/lib/python3.9/site-packages/behave/model.py", line 1329, in run
    match.run(runner.context)
  File "/Users/.../behaveproblem_issue981/.venv_py39/lib/python3.9/site-packages/behave/matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "features/steps/steps_a.py", line 11, in step_impl
    assert True == False, "Test fails."

    * This test is not ok either, but exception is not catched ... failed in 0.000s
Assertion Failed: FAILED SUB-STEP: * This is the first test which will fail
Substep info: Assertion Failed: Test fails.
Traceback (of failed substep):
  File "/Users/.../behaveproblem_issue981/.venv_py39/lib/python3.9/site-packages/behave/model.py", line 1329, in run
    match.run(runner.context)
  File "/Users/.../behaveproblem_issue981/.venv_py39/lib/python3.9/site-packages/behave/matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "features/steps/steps_a.py", line 6, in step_impl
    assert_schema()
  File "features/steps/steps_a.py", line 15, in assert_schema
    assert True == False, "Test fails."

Failing scenarios:
  features/some_test.feature:10  Some failed tests

0 features passed, 1 failed, 0 skipped
0 scenarios passed, 1 failed, 0 skipped
0 steps passed, 5 failed, 0 skipped, 0 undefined
```

HINTS:
* I do not have your HTML report generator. Therefore, I used the plain simple stuff: The "plain" formatter
* I need to fix the "features/steps/steps_b.py" import for "steps_a"

```python
# -- FILE: features/steps/steps_b.py
from behave import step
# OLD: import behaveproblem.features.steps.steps_a as steps_a
# REASON: The "__init__.py" files on multiple directory levels are missing to make that statement above work.
import steps_a
...
```

SEE ALSO:

* [behave/runner.py: Context.execute_steps](https://github.com/behave/behave/blob/master/behave/runner.py#L413)
* RELATED ISSUE: #96 -- Assertion messages are more verbose if `Context.execute_steps()` are used to improve diagnostics

**Comment by berndhahnebach** [comment]
may be my description was bad. You are correct, the exception is caught. The question should be. Is it possible to omitt the traceback for the steps which use context.execute_steps() like at the first three steps.

**Comment by berndhahnebach** [comment]
are you interested in the html formatter?

**Comment by jenisys** [comment]
QUESTION: `Is it possible to omit the traceback for the steps which use context.execute_steps() ?`

Currently not, as you can see from the referenced implementation of `behave.runner:Context.execute_steps()`.
A configuration point needs to be introduced to be able to configured the desired behaviour (with tracebacks or without tracebacks). But even without tracebacks this would mean at least two lines in my opinion: The assertion message (string from AssertionError) and the diagnostics in which dubstep the assertion failed.
In addition, it may be useful to switch on exception-tracebacks if the `--verbose` option is used.

QUESTION 2: `Are you interested in the html report generator?`

In principle, yes.
Just to explore if it is useful for me.
It should have the functionality of a normal python package: must be installable.

There is another [HTML formatter](https://github.com/behave-contrib/behave-html-formatter) in the [behave-contrib](https://github.com/behave-contrib/) Github area.
This project is coached by @bittner and with the effort of a few other contributors.

If your HTML reporter is useful (and it is feasible for you), there are a number of potential next steps:

* Add your HTML reporter project under the [behave-contrib](https://github.com/behave-contrib/) Github area 
  (if you have not published it somewhere else and do not want to do that)
* One may think of combining both projects (the HTML formatter and the HTML report generator as post-processor)

In both cases, it will be easier for other `behave` users to find the functionality.

SEE ALSO:

* https://github.com/behave-contrib/behave-html-formatter

**Comment by berndhahnebach** [comment]
Since the questions are answered perfectly well and there is a issue for the real problem the issue can be closed. 

I will leave some comments on your answers later on today.

**Comment by berndhahnebach** [comment]
Question 1:
thanks for bringing light in the problem I had. I have understood what my problem was. See https://github.com/behave/behave/issues/983#issuecomment-991959810

**Comment by berndhahnebach** [comment]
Question 2:
see https://github.com/IfcOpenShell/IfcOpenShell/blob/4e9a5f246f2260ad6a9c1c6ffa46230a0f8b5914/src/ifcbimtester/bimtester/reports.py but I patched it to run with the simplified files I provided in first post.

**Comment by berndhahnebach** [comment]
`python
# licence see https://github.com/IfcOpenShell/IfcOpenShell/tree/4e9a5f246f2260ad6a9c1c6ffa46230a0f8b5914/src/ifcbimtester 

import datetime
import json
import os
import pystache
import sys


class ReportGenerator:
    def __init__(self):
        try:
            # PyInstaller creates a temp folder and stores path in _MEIPASS
            self.base_path = sys._MEIPASS
        except Exception:
            self.base_path = os.path.dirname(os.path.realpath(__file__))

    def generate(self, report_json, output_file):
        print("# Generating HTML reports.")

        report = json.loads(open(report_json).read())
        for feature in report:
            self.generate_feature_report(feature, output_file)

    def generate_feature_report(self, feature, output_file):
        # file_name = os.path.basename(feature["location"]).split(":")[0]
        data = {
            # "file_name": file_name,
            "time": datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "name": feature["name"],
            "description": feature.get("description", ""),
            "is_success": feature["status"] == "passed",
            "scenarios": [],
        }

        if "elements" not in feature:
            if "status" in feature and feature["status"] == "skipped":
                print("Feature was skipped. No html report will be created.")
            else:
                print("For a unknown reason no html report well be created.")
            # happens if the feature file does not consist of any valid Scenario
            return

        for scenario in feature["elements"]:
            scenario_data = self.process_scenario(scenario, feature)
            if scenario_data:
                data["scenarios"].append(scenario_data)

        data["total_passes"] = sum([s["total_passes"] for s in data["scenarios"]])
        data["total_steps"] = sum([s["total_steps"] for s in data["scenarios"]])
        try:
            data["pass_rate"] = round((data["total_passes"] / data["total_steps"]) * 100)
        except ZeroDivisionError:
            data["pass_rate"] = 0

        data.update(self.get_template_strings())

        with open(output_file, "w", encoding="utf8") as out:
            with open(
                os.path.join(self.base_path, "template.html"), encoding="utf8"
            ) as template:
                out.write(pystache.render(template.read(), data))

    def process_scenario(self, scenario, feature):
        if len(scenario["steps"]) == 0:
            print("Scenario '{}' in feature '{}' has no steps.".format(scenario["name"], feature["name"]))
            return

        steps = []
        total_duration = 0

        for step in scenario["steps"]:
            step_data = self.process_step(step)
            total_duration += step_data["time_raw"]
            steps.append(step_data)

        total_passes = len([s for s in steps if s["is_success"] is True])
        total_steps = len(steps)
        pass_rate = round((total_passes / total_steps) * 100)

        return {
            "name": scenario["name"],
            # on behave < 1.2.6 there is no 'status' thus report fails
            "is_success": scenario["status"] == "passed",
            "time": round(total_duration, 2),
            "steps": steps,
            "total_passes": total_passes,
            "total_steps": total_steps,
            "pass_rate": pass_rate,
        }

    def process_step(self, step):
        name = step["name"]
        if "match" in step and "arguments" in step["match"]:
            for a in step["match"]["arguments"]:
                name = name.replace(a["value"], "<b>" + a["value"] + "</b>")
        if "result" not in step:
            step["result"] = {}
            step["result"]["status"] = "skipped"
            step["result"]["duration"] = 0
            step["result"]["error_message"] = "This requirement has been skipped due to a previous failing step."
        elif step["result"]["status"] == "undefined":
            step["result"] = {}
            step["result"]["status"] = "undefined"
            step["result"]["duration"] = 0
            step["result"]["error_message"] = "This requirement has not yet been specified."
        data = {
            "name": name,
            "time_raw": step["result"]["duration"],
            "time": round(step["result"]["duration"], 2),
            "is_success": step["result"]["status"] == "passed",
            "is_unspecified": step["result"]["status"] == "undefined",
            "is_skipped": step["result"]["status"] == "skipped",
            "error_message": None if step["result"]["status"] == "passed" else step["result"]["error_message"],
        }

        # Remove the first "Assertion Failed" message
        if isinstance(data["error_message"], list) and data["error_message"]:
            data["error_message"].pop(0)
        return data

    def get_template_strings(self):
        return {
            "_lang": "en",
            "_success": "Success",
            "_failure": "Failure",
            "_tests_passed": "Tests passed",
            "_duration": "Duration",
            "_auditing": "OpenBIM auditing is a feature of",
            "_and": "and",
        }

`

**Comment by berndhahnebach** [comment]
part of some real report from BIMTester from IfcOpenShell

![screen](https://user-images.githubusercontent.com/6129869/145728402-4b4b88ff-0aa5-432c-b259-5b5de0b2079f.png)

**Comment by jenisys** [comment]
Thanks for the info.
I will have a look at it.
