### ISSUE TITLE
While running multiple scenario outline one browser is only working 

### ISSUE THREAD

**Issue by VI-SA-P** [behave/behave#982]
```gherkin
Feature: eVitalyst Login

  @Regression
  Scenario Outline: eVitalyst Login
    Given Browser is opened
    And usrer is on eVitalyst  login page
    When user enter <username> and <password> for eVitalyst
    And click on evitalyst login
    Then user is navigated to login page

    Examples: 
      | username  | password |
      | SuperUser |       11 |
      | SuperUser |       11 |

  @Regression
  Scenario Outline: second login
    Given select eVitalist roles <role>
    And select eVitalyst clients <client>
    And select eVitalyst organization <organization>
    And select eVitalyst warehouse <warehouse>
    Then click on submit in user credential selection

    Examples: 
      | role      | client      | organization | warehouse            |
      | ABC ADMIN | ABC COMPANY | DUBAI        | DXB OFFICE Warehouse |
      | ABC ADMIN | ABC COMPANY | DUBAI        | DXB OFFICE Warehouse |
```

**Comment by xrg** [comment]
See [behave_manners](https://github.com/xrg/behave_manners) . It's handling browser resources implicitly, might shave a ton of boilerplate off your side. (hint: designed and heavily tested against "parallel" branch of behave)

**Comment by jenisys** [comment]
I agree with @xrg .

The problem / fault location is probably in your step implementation or the helper functions you use to open the browser.
A "use-or-create" functionality to open the browser is probably implemented.
MAYBE: Ensure that the browser is closed/exited at the end of the scenario (will probably have a performance impact on the other tests).

HINTS:
* Your problem description (in Gherkin) is unnecessarily complex

MAYBE BETTER EXAMPLE: 
```gherkin
Scenario Outline: eVitalyst Login
    Given I use the web page "https://example.org/"
    And I login as user "<username>" with password "<password>"
    Then user is navigated to login page

    Examples: 
      | username  | password |
      | SuperUser |       11 |
      | SuperUser |       11 |
```

REASON:
* Shows the intention (without too much noise), easier to understand what is important
* Avoids too many technical details
* Exact steps procedure may change (brittle; then you need to adapt/change your acceptance tests which is bad).
  That can be hidden in your step implementations (which are easier to change w/ respect to your other internal functionality).

**Comment by jenisys** [comment]
CLOSED: Due to inactivity (reason: Probably a user problem).
