### ISSUE TITLE
Who to contact for security issues

### ISSUE THREAD

**Issue by JamieSlome** [behave/behave#993]
Hey there!

I belong to an open source security research community, and a member (@srikanthprathi) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by jenisys** [comment]
Security policy was created.

**Comment by jenisys** [comment]
I created a security policy with the relevant information.

SEE: https://github.com/behave/behave/blob/master/.github/SECURITY.md

Sincerely,
Jens Engel

**Comment by JamieSlome** [comment]
@jenisys - appreciate the swift response! ⚡ You should receive an e-mail shortly. Otherwise, you can view the report directly here:

https://huntr.dev/bounties/485a8268-99f5-4d19-9481-f596b6249947/

It is private and only accessible to maintainers with repository write permissions. Let me know if you have any questions.
