### ISSUE TITLE
setup.py: use_2to3 breaks install with 'setuptools >= 58.0'

### ISSUE THREAD

**Issue by jonringer** [behave/behave#994]
behave is no longer supported for platform which consume packages as sdists (most package repositories).

Related: https://github.com/jenisys/parse_type/issues/17

**Comment by jenisys** [comment]
AFFECTED PLATFORMS:
* Linux

HOW TO REPEAT:
```bash
$ pip install -U setuptools
$ pip install --no-binary :all: --force-reinstall behave
...
Complete output (1 lines):
  error in behave setup command: use_2to3 is invalid.
```

WORK-AROUND UNTIL FIXED:
```bash
$ pip install 'setuptools<58.0'
$ pip install --no-binary :all: --force-reinstall behave
...
Successfully installed behave-x.x.x ...
```

**Comment by jenisys** [comment]
* ALREADY FIXED
* NEXT RELEASE PENDING (next release on https://pypi.org/ will fix it)

RELATED ISSUE:

* #955
